### ISSUE TITLE
Create repository xtext-vscode

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext#1068]
The Xtext repository has been split up into several repositories. One of the main reasons is to keep projects for different IDEs (Eclipse,IDEA,Web) apart from each other.

With availabilty of the Language Server Protocol Microsoft's Visual Studio Code has become a target with which Xtext integrates. It is worth to have first-class support from the Xtext framework for this tool.

Primary goal of such a repository should be to provide VS Code extensions for languages by Xtext itself (like Xtext Grammar or for the common example projects), and framework extensions to produce these extensions. There are currently two examples available which both show how such extensions are implemented:
- https://github.com/cdietrich/xtext-languageserver-example
- https://github.com/TypeFox/languageserver-example

Both implementations have several things in common, and for further languages this can be abstracted further. As a first use case a generator fragment for the Xtext code generator could be provided, which produces the VS Code extension code for a given grammar.

As a first contribution to the Xtext VS Code codebase there is such a generator fragment available in the following repository:
- https://github.com/itemis/xtext-generator-vscode

With availabilty of the proposed xtext-vscode repository we want to contribute this project to the Xtext project within Xtext's namespace.

**Comment by svenefftinge** [comment]
-1 The goal is to get rid of the platform specific extensions not to add more.
It is planned to add a small! generator fragment that creates a basic vscode extension, and include that in the generator module.

**Comment by spoenemann** [comment]
@kthoms The generators for web and IDEA are included in `org.eclipse.xtext.xtext.generator` in xtext-core, so we should do the same for the VS Code generator. Feel free to open a PR there.

The big advantage of the Language Server Protocol is that we need only very little code on the VS Code side to integrate an Xtext language, so an extra integration project for that platform should not be necessary.

Any other opinion? Otherwise I would close this.

**Comment by kthoms** [comment]
Makes sense. I'll open another issue for that soon.
