### ISSUE TITLE
The OOMPH setup should be usable without providing the personal Bugzilla password

### ISSUE THREAD

**Issue by meysholdt** [eclipse/xtext#1070]
Currently, the filed for the password is mandatory.

Also, what's the best way to handle passwords securely in OOMPH? Is there something more secure than properties and plain text widgets?

**Comment by kthoms** [comment]
The bugzillla password field is masked. Why do you feel insecure?

<img width="840" alt="screenshot 30" src="https://cloud.githubusercontent.com/assets/265597/17602470/0b886e62-600d-11e6-8497-7cfd855d115a.png">

Further, when developing on Xtext you should be aware of open bugs, and this includes the 700+ open in Bugzilla.

I think it is not possible to mark the Bugzilla password field optional.
<img width="336" alt="screenshot 31" src="https://cloud.githubusercontent.com/assets/265597/17602637/cdb8cc70-600d-11e6-9cb7-a42b9baf102f.png">

We could move Mylyn features, Bugzilla and Github queries to another project, e.g. "Xtext Issues", which you could select as an optional project. If not selected, you won't get bothered by entering passwords. Would this be appropriate?

**Comment by dhuebner** [comment]
@kthoms I would also prefer to include the reporting stuff to a separate project. "Xtext issues" sounds good.

**Comment by kthoms** [comment]
@meysholdt Do you also agree? I would start working on that when I get a "go".

**Comment by dhuebner** [comment]
@kthoms He agreed. Please also move all the related tasks (like p2) into this project.

**Comment by meysholdt** [comment]
agreed

**Comment by kthoms** [comment]
https://github.com/eclipse/xtext-eclipse/pull/48

Xtext Issues project has different streams which lets you select a subset of issues, or all.
![screenshot 33](https://cloud.githubusercontent.com/assets/265597/17626376/5b6c089e-60ad-11e6-809d-d659d432cd39.png)

Without selecting "Xtext Issues" there are no variables for Bugzilla / GitHub credentials.
![screenshot 32](https://cloud.githubusercontent.com/assets/265597/17626404/7b2e984a-60ad-11e6-88ab-e70f0dd859ab.png)

When selecting "Xtext Issues" there are additional variables.
![screenshot 35](https://cloud.githubusercontent.com/assets/265597/17626470/a887ec10-60ad-11e6-8ae1-38989a4eb78d.png)

Mylyn feature installation is bound to the "Xtext Issues" project.
![screenshot 36](https://cloud.githubusercontent.com/assets/265597/17626504/c5c40822-60ad-11e6-9606-613e026cdd68.png)

**Comment by kthoms** [comment]
@meysholdt Please close. I can't.
