### ISSUE TITLE
Splitted repositories do not contain release tags

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext#1071]
During the split release tags got lost. It is important to have these tags to be able to compare sources against a certain release, which is important to track changes for bugs that were reported for a past release.

The release tags https://github.com/eclipse/xtext/tags should be available for the other repos when appropriate. I think the release tags should be sufficient, old milestones could be ignored.

**Comment by kthoms** [comment]
[tagging-scripts.zip](https://github.com/eclipse/xtext/files/489108/tagging-scripts.zip)

Contains scripts that have to be executed in the respective repo. The scripts create the release tags, but do not upload them. The tags have to be pushed afterwards.

I listed the commit tags of the orginal repo and left out milestone and other non-release tags. With these dates I queried the repositories to list the last commit before the original tag date (including the tag time). The listed commit hashes are the result.

**Comment by spoenemann** [comment]
Thanks! I pushed the tags, but omitted those that do not contain any meaningful history for the respective repositories (xtend from v2.4, maven from v2.5, idea and web from v2.9).

**Comment by spoenemann** [comment]
> I queried the repositories to list the last commit before the original tag date

With such a flat list branches are not considered, which could lead to incorrect selection of commits. @kthoms could you check whether this is a problem, and reopen if so?

**Comment by kthoms** [comment]
Looks good!
