### ISSUE TITLE
Book on Xtext

### ISSUE THREAD

**Issue by packtpartner** [eclipse/xtext#1073]
Packt has published a new book in August '[Implementing Domain-Specific Languages with Xtext and Xtend](https://www.packtpub.com/application-development/implementing-domain-specific-languages-xtext-and-xtend-second-edition)'
It is the second edition to ['Implementing Domain-Specific Languages with Xtext and Xtend'](https://www.packtpub.com/application-development/implementing-domain-specific-languages-xtext-and-xtend) addition of these books to the community section of https://eclipse.org/Xtext/ would prove to be beneficial for the Xtext and Xtend community. 

Let me know your thoughts on this.

**Comment by svenefftinge** [comment]
please don't miss-use our issue tracker for marketing purposes.

**Comment by packtpartner** [comment]
@svenefftinge Thanks for your reply
