### ISSUE TITLE
[reposplit] devtools got lost

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext#1074]
The repository contained a folder `/devtools` which is not available in any of the splitted repositories.

**Comment by kthoms** [comment]
Maybe the devtools could be placed in xtext-extras?

I see the problem that the workflows GenerateXtext.mwe2 (from o.e.x.bootstrap) and GenerateAllLanguages.mwe2 (from o.e.x.language-generator) is affects sources in multiple git repos now. I think it can be assumed that the repos are located in the same folder and have a fixed name, since they are usually set up with Oomph.

Moving to xtext-extras would imply that xtext-extras has some implicit dependencies which it currently does not have, e.g. generating code to the idea projects and thus a dependency on xtext-idea.

The other option is either to place the devtools in the umbrella project, i.e. this repo, or create a new repo for dev- & releng tools, e.g. "xtext-tools".

**Comment by spoenemann** [comment]
I don't think we need GenerateAllLanguages. Regarding GenerateXtext, @sailingKieler has started some work to restore a bootstrap process in xtext-core, see eclipse/xtext-core#125
