### ISSUE TITLE
NullPointerException when adding a empty directory to an IDEA module

### ISSUE THREAD

**Issue by EricSalemi** [eclipse/xtext#1075]
A bit of context first.

I'm developing a language and an application using that language with the following tools:

IDEA 2016.2.4
Xtext IDEA plugin 2.10
Gradle 3.0

The language is called "flax".
The application is called "cactus".
I encountered this issue while trying to provide a library in the flax jar.

Minimal steps to reproduce:

1) Create an XText project with the IDEA wizard
```
Name: org.septentrio.sandbox.flax.Flax
Extension: flax
Project name: flax
Project location: .../flax
```
2) Modify the language to include at least one cross-reference
```
grammar com.septentrio.sandbox.flax.Flax with org.eclipse.xtext.common.Terminals
generate flax "http://www.septentrio.com/sandbox/flax/Flax"
Model:
  classes+=Class*;
Class:
  'class' name=ID ('extends' parent=[Class])?;
```
3) Modify the `flax.parent/flax.idea/build.gradle` to use IDEA version '162.2032.8'
4) Execute the `runIdea` Gradle task
5) In the newly launched IDEA, create a new empty project (this is cactus...)
6) Create a new module and the Flax facet
7) In the source folder of the module create a new `lib.flax` file
```
class A extends B
```
8) As expected B is flagged as an undefined symbol
9) Create an empty folder and add it to the module dependency
10) `NullPointerException` is repeatedly thrown by XText

I believe this issue prevents me from providing a custom library together with my language. I have tried other methods such as packaging an extra library file in a JAR and adding that JAR to the dependencies of the cactus module but the same exception would be thrown.

Is there a way to provide a custom library when developing XText languages in IDEA?

**Comment by spoenemann** [comment]
Should be solved in the xtext-idea repository.
