### ISSUE TITLE
"Found a bug?" on Xtend and Xtext websites still links to Bugzilla

### ISSUE THREAD

**Issue by abelhegedus** [eclipse/xtext#1077]
Based on https://github.com/eclipse/xtext/blob/master/CONTRIBUTING.md#report-an-issue Github should be used for issues.
However both https://eclipse.org/xtend/community.html and https://www.eclipse.org/Xtext/community.html link to Bugzilla with "Found a bug?".

**Comment by meysholdt** [comment]
sounds like a bug. All links should point to Github.

**Comment by kthoms** [comment]
fixed via 433fbc1c6a77e0ded668f4ca3447eee1358fd2cb
It is not online yet, we will do this when releasing 2.11.
