### ISSUE TITLE
Maven publishing validation fails

### ISSUE THREAD

**Issue by spoenemann** [eclipse/xtext#1080]
- All generated `pom.xml` must have a project name and description (at least inferred from parent).
- Signature file `.asc` does not exist for org.eclipse.xtext.maven.parent `pom.xml`.

**Comment by cdietrich** [comment]
@spoenemann is there something left here?

**Comment by dhuebner** [comment]
@cdietrich We would like to keep it open, so we can verify the changes during beta2

**Comment by spoenemann** [comment]
Fixed.
