### ISSUE TITLE
Fix cbi tests before release

### ISSUE THREAD

**Issue by dhuebner** [eclipse/xtext#1083]
All the '--' entries must be fixed before we can contribute to the Oxigen common repository

- [x] Feature license
- [x] Provider name xtext.ui.feature
- [x] pack200

https://hudson.eclipse.org/xtext/view/Common/job/simrel-reports/

**Comment by dhuebner** [comment]
pack200 support - will probably be not available for 2.11

**Comment by LorenzoBettini** [comment]
do you need help in setting this in the tycho build?

**Comment by spoenemann** [comment]
It shouldn't be done in the Tycho build, but in the [Gradle publishing build](https://github.com/TypeFox/publishing). We'll have a look at that soon.

**Comment by cdietrich** [comment]
Job is green now
