### ISSUE TITLE
Create Umbrella Repository

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext#1084]
The main Xtext repository contains some releng projects. Further, we need a composite build in order to be able to resolve cross-repo dependencies. The old main repository seems not to be the right place, since it is quite huge and it is not possible to make a shallow clone with Oomph/JGit at this moment. 

Therefore Releng stuff and maybe more (docs etc.) should be collected in a new umbrella repository. A name has not been decided yet.

This issue is for the decision of the repository's name and the actual creation. Further actions to populate it should be handled in a separate issue.

See https://github.com/eclipse/xtext-eclipse/pull/118 for more details.

**Comment by svenefftinge** [comment]
I was about asking the webmaster for a repo called 'xtext-umbrella'. 
Any objections?

**Comment by kthoms** [comment]
Not from my side, I'm fine with any decided name.

**Comment by svenefftinge** [comment]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=507722

**Comment by kthoms** [comment]
https://github.com/eclipse/xtext-umbrella
