### ISSUE TITLE
[gradle] Project import changes order of build commands

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext#1088]
When importing Xtext project with Buildship, the resulting `.project` files exchange the order of the build commands. The Xtext builder is added after the Java builder, but it must be before.

![screenshot 119](https://cloud.githubusercontent.com/assets/265597/20759739/14a2054a-b71e-11e6-9d20-0304b6635393.png)

The current setting `java-compiler-settings.gradle` files adds the xtextBuilder with
```
buildCommand 'org.eclipse.xtext.ui.shared.xtextBuilder'
```
This will append the command, so the order is wrong.

The build command can be added in front with
```
buildCommands.add(0,new org.gradle.plugins.ide.eclipse.model.BuildCommand('org.eclipse.xtext.ui.shared.xtextBuilder'))
```

The order is now that the xtextBuilder is before javabuilder, which can be verified by console output by adding
```
println(project.name+": "+project.buildCommands.collect{bc->bc.name})
```
This will result in the output:
```
org.eclipse.xtext: [org.eclipse.xtext.ui.shared.xtextBuilder, org.eclipse.jdt.core.javabuilder]
org.eclipse.xtext.ide: [org.eclipse.xtext.ui.shared.xtextBuilder, org.eclipse.jdt.core.javabuilder]
org.eclipse.xtext.ide.tests: [org.eclipse.xtext.ui.shared.xtextBuilder, org.eclipse.jdt.core.javabuilder]
org.eclipse.xtext.testing: [org.eclipse.xtext.ui.shared.xtextBuilder, org.eclipse.jdt.core.javabuilder]
org.eclipse.xtext.testlanguages: [org.eclipse.xtext.ui.shared.xtextBuilder, org.eclipse.jdt.core.javabuilder]
org.eclipse.xtext.testlanguages.ide: [org.eclipse.xtext.ui.shared.xtextBuilder, org.eclipse.jdt.core.javabuilder]
org.eclipse.xtext.tests: [org.eclipse.xtext.ui.shared.xtextBuilder, org.eclipse.jdt.core.javabuilder]
org.eclipse.xtext.util: [org.eclipse.xtext.ui.shared.xtextBuilder, org.eclipse.jdt.core.javabuilder]
org.eclipse.xtext.xtext.generator: [org.eclipse.xtext.ui.shared.xtextBuilder, org.eclipse.jdt.core.javabuilder]
org.eclipse.xtext.xtext.wizard: [org.eclipse.xtext.ui.shared.xtextBuilder, org.eclipse.jdt.core.javabuilder]

CONFIGURE SUCCESSFUL
```

The same problem exists when calling `gradle eclipse` from command-line:
![screenshot 126](https://cloud.githubusercontent.com/assets/265597/20760145/651cb550-b71f-11e6-90d5-3bd14af012a1.png)

**Comment by oehme** [comment]
I checked out xtext-core, made the change you showed above and imported it. Works for me.

**Comment by oehme** [comment]
Just talked with @cdietrich: You currently have to use the `keep` option when you import. The next milestone will remove this dialog and do the right thing in all cases.

What's happening here is that JDT adds the Java builder when we add the Java nature. This happens before all other builders are added. So by the time Buildship tries to add the Xtext builder, the Java builder is already the first one.

The next milestone will completely replace the list of builders, no matter what other plugins like JDT did before.

**Comment by kthoms** [comment]
Of course I used `overwrite` option since I expected from `keep` that project descriptors are not changed since they are kept as is and I only see effects when the descriptos are overridden.

Which way of adding the build command will be the correct one? The existing or with explicit placement of the build command at index 0?

**Comment by oehme** [comment]
> Of course I used overwrite option since I expected from keep that project descriptors are not changed since they are kept as is and I only see effects when the descriptos are overridden.

That's why we're removing the dialog in the next version and always replace the configuration with what's in the Gradle model.

> Which way of adding the build command will be the correct one? The existing or with explicit placement of the build command at index 0?

The one at index 0, because you want Xtext to come first.

**Comment by kthoms** [comment]
> The one at index 0, because you want Xtext to come first.

OK, I will prepare the necessary changes.

**Comment by kthoms** [comment]
@oehme Please review

**Comment by kthoms** [comment]
@cdietrich reviewed the changes, so the Xtext code is prepared.

We have to keep this issue open until we use the next Buildship milestone, which should preserve the .project files on import. If that is the case then we can close the issue.

**Comment by cdietrich** [comment]
seems no longer to be an issue with the recent buildship versions
