### ISSUE TITLE
[doc] Contribution Guide: SSH key necessary

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext#1092]
To be able to clone the Git repo with Oomph it is necessary to have a SSH key registered in the Oomph profile. This should be mentioned in the contribution guide. 

Here is a forum post reporting the issue: https://www.eclipse.org/forums/index.php?t=rview&goto=1750269#msg_1750269

**Comment by dhuebner** [comment]
> SSH key necessary

This is not true. You can use HTTP + user + password or even read-only anonymous clone. It depends on user selection.


![bildschirmfoto 2016-12-19 um 13 22 57](https://cloud.githubusercontent.com/assets/454322/21312824/add16e0c-c5ee-11e6-804a-a408362ba6e5.png)

**Comment by kthoms** [comment]
You are right. But there is chance that the user selects the first option. Then we should be clear about that.

**Comment by EricSalemi** [comment]
@dhuebner git is selected by default for all project when using the oomph installer so a newbie like me would always bump into the cryptic egit error which tells that an authentication error has occured (no mention of SSH whatsoever). Another solution would be to modify the default XText repository retrieval method to be "HTTPS anonymous" and I assume you guys have complete control over that.

**Comment by dhuebner** [comment]
@EricSalemi We need to copy&paste the Oomph documentation which describes what the options are. There is a lot of other tricky parts in oomph which than have to be documented in Xtext as well.
My concerns with this ticked is:  
1. "SSH key necessary" - is wrong wording and it simply not true.
2. If we describe how to create and setup SSH, we should first describe that there are three possibilities to setup the git repository.

Better would be have a link to the public Oomph documentation which describes this aspect, so we do not need to maintain this part in our Xtext documentation.

**Comment by cdietrich** [comment]
Fixed
