### ISSUE TITLE
[doc] Xtend documentation code samples broken on eclipse.org website

### ISSUE THREAD

**Issue by px-djozis** [eclipse/xtext#1098]
As per title, eclipse.org formats the code samples in the documentation very strangely currently.

A picture tells a thousand words - here's a screenshot:
![image](https://cloud.githubusercontent.com/assets/25015875/22081437/90b28aee-dd91-11e6-8b32-625b2523ec88.png)

From this URL: https://eclipse.org/xtend/documentation/203_xtend_expressions.html#switch-expression
Chrome version: 55.0.2883.87 m

**Comment by cdietrich** [comment]
Should be already fixed with https://github.com/eclipse/xtext/pull/1096

**Comment by dhuebner** [comment]
We should apply the fix to the maintenance branch to fix the website.

**Comment by cdietrich** [comment]
@dhuebner can you elaborate how the website works? is it directly running from jekyll? i thought the website is copy & oaste the generated html pages?

**Comment by cdietrich** [comment]
@dhuebner do you care or should i?

**Comment by dhuebner** [comment]
@cdietrich Yes.
The website is build from the maintenance branch. I will cherry pick your fix from master.

**Comment by dhuebner** [comment]
Fixed now. Thanks for reporting @px-djozis

**Comment by px-djozis** [comment]
Thanks! Looks great again now.
