### ISSUE TITLE
Cannot locate JRE definition: "J2SE-1.8". Launch aborted.

### ISSUE THREAD

**Issue by vihanga-liyanage** [eclipse/xtext#1100]
Hi, I tried to complete the [15 Minutes Tutorial](http://www.eclipse.org/Xtext/documentation/102_domainmodelwalkthrough.html) but this error keeps coming when I tried to run the application after generating the artifacts. Please help!

![capture](https://cloud.githubusercontent.com/assets/9441136/22962950/2e5a2280-f376-11e6-81dc-794fb67a3480.JPG)

**Comment by cdietrich** [comment]
this is a issue in the generator/wizard
https://github.com/eclipse/xtext-core/issues/273

solutions:
- if you use debug -> debug configurations .... -> debug it should be autorepaired
- you unide `.resources` in the explorer or open the .launch file on file system and replace J2SE-1.8 with JavaSE-1.8

**Comment by vihanga-liyanage** [comment]
OMG! Thanks a lot! This gave me a headache for days.

**Comment by cdietrich** [comment]
yes it is unfortunate that this slipped into the release.
=> hope for a soon released Xtext 2.11.1
