### ISSUE TITLE
Tag branch for v2.11.0 is not available

### ISSUE THREAD

**Issue by vgirishkumar** [eclipse/xtext#1104]
once the release is done, tagging is usually done for ex v2.8.4. but even after the release of 2.11.0, i am not able see the tag v2.11.0 available.

Could anybody do the same

**Comment by cdietrich** [comment]
hi, are you sure you look at the right place

e.g. https://github.com/eclipse/xtext-core/releases/tag/v2.11.0

**Comment by vgirishkumar** [comment]
Thanks you, I was looking at https://github.com/eclipse/xtext/
