### ISSUE TITLE
Oxygen - Xtext 2.12 contribution

### ISSUE THREAD

**Issue by dhuebner** [eclipse/xtext#1111]
Things to do:

- [x] Prepare a stable 2.12 build
- [x] Wait for fix https://bugs.eclipse.org/bugs/show_bug.cgi?id=515647
- [x] Wait for fix https://bugs.eclipse.org/bugs/show_bug.cgi?id=515646
- [x] Add stable build to the common eclipse repository
- [x] Notify other projects (cross-project mailing list) about the change

**Comment by dhuebner** [comment]
Viatra updated the version range:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=515646#c8

**Comment by LorenzoBettini** [comment]
@dhuebner https://bugs.eclipse.org/bugs/show_bug.cgi?id=515647 is fixed as well

**Comment by dhuebner** [comment]
All artifacts are published.

**Comment by dhuebner** [comment]
cross-project notified:  https://dev.eclipse.org/mhonarc/lists/cross-project-issues-dev/msg14418.html
