### ISSUE TITLE
Xtext Upgrade related issue

### ISSUE THREAD

**Issue by chetanladdha** [eclipse/xtext#1115]
Hi,

We are migrating from Xtext 2.8.2 to 2.11.0. As per Xtext release notes and documentation, Xtext is having backward compatibility for the Generator. 

We have similar to below mwe2 file in our module, but same is not working with latest Xtext 2.11. 
It's giving error saying 

> couldn't resolve referenec to JvmType 'Generator'. 
We also found that we don't have org.eclipse.xtext.generator.Generator.* inside 2.11. Do we require to do anything else to make this work in Xtext 2.11 ?

`    component = Generator {                  
pathRtProject = runtimeProject         
pathUiProject = "${runtimeProject}.ui"         
pathTestProject = "${runtimeProject}.tests"         projectNameRt = projectName         projectNameUi = "${projectName}.ui"         language = {         forcedResourceSet = resourceSet             uri = grammarURI             fileExtensions = file.extensions              // Java API to access grammar elements (required by several other fragments)             fragment = grammarAccess.GrammarAccessFragment {}               // Serializer 2.0             fragment = serializer.SerializerFragment {}                          // the serialization component (1.0)             // fragment = parseTreeConstructor.ParseTreeConstructorFragment {}              // a custom ResourceFactory for use with EMF             fragment = resourceFactory.ResourceFactoryFragment {                 fileExtensions = file.extensions             }              // The antlr parser generator fragment.             fragment = parser.antlr.XtextAntlrGeneratorFragment {             //  options = {             //      backtrack = true             //  }             }              // java-based API for validation             fragment = validation.JavaValidatorFragment {                 composedCheck = "org.eclipse.xtext.validation.ImportUriValidator"                 composedCheck = "org.eclipse.xtext.validation.NamesAreUniqueValidator"             }              // scoping and exporting API             // fragment = scoping.ImportURIScopingFragment {}             // fragment = exporting.SimpleNamesFragment {}              // scoping and exporting API             fragment = scoping.ImportNamespacesScopingFragment {}             fragment = exporting.QualifiedNamesFragment {}             fragment = builder.BuilderIntegrationFragment {}              // generator API             fragment = generator.GeneratorFragment {                 generateMwe = true                 generateJavaMain = true             }              // formatter API             fragment = formatting.FormatterFragment {}              // labeling API             fragment = labeling.LabelProviderFragment {}              // outline API             fragment = outline.OutlineTreeProviderFragment {}             fragment = outline.QuickOutlineFragment {}              // quickfix API             fragment = quickfix.QuickfixProviderFragment {}              // content assist API             fragment = contentAssist.JavaBasedContentAssistFragment {}              // generates a more lightweight Antlr parser and lexer tailored for content assist             fragment = parser.antlr.XtextAntlrUiGeneratorFragment {}              // generates junit test support classes into Generator#pathTestProject             fragment = junit.Junit4Fragment {}              // project wizard (optional)             // fragment = projectWizard.SimpleProjectWizardFragment {             //      generatorProjectName = "${projectName}"             //      modelFileExtension = file.extensions             // }              // provides the necessary bindings for java types integration             fragment = types.TypesGeneratorFragment {}              // generates the required bindings only if the grammar inherits from Xbase             fragment = xbase.XbaseGeneratorFragment {}              // provides a preference page for template proposals             fragment = templates.CodetemplatesGeneratorFragment {}              // rename refactoring             fragment = refactoring.RefactorElementNameFragment {}              // provides a compare view             fragment = compare.CompareFragment {                  fileExtensions = file.extensions             }          }     }`

**Comment by kthoms** [comment]
Make sure that you have plugin org.eclipse.xtext.generator on your classpath.

**Comment by chetanladdha** [comment]
Thanks ...I was using org.eclipse.xtext.xtext.generator only.

**Comment by kthoms** [comment]
The org.eclipse.xtext.xtext.generator plugin contains the new Xtend based generator. Make sure you upgrade your workflow and project structure to 2.9+ level. The old generator is deprecated and we don't fix issues there anymore.
