### ISSUE TITLE
Oddities with comments in DSLs

### ISSUE THREAD

**Issue by BeckmaR** [eclipse/xtext#1118]
Hey, I am currently trying to build a formatter (API 1) for a DSL written with Xtext, and I stumbled over a weird edge case.

When trying to format the following example code:
```
class ABC {
    /* Comment 1 */
    def method1() {
    }
    /* Comment 2 */
    def method2() {
    }
}
```
No matter what I do, the first comment always gets pushed to the left:
```
class ABC {
/* Comment 1 */
    def method1() {
    }
    /* Comment 2 */
    def method2() {
    }
}
```
The funny thing is, the same happens when editing by hand in the respective editor (and even in the Xtend editor). Given the following code, with the pipe symbolizing the caret:
```
class ABC { |//comment

}
```
pressing return gives:
```
class ABC { 
//comment
}
```
while the regular Java editor does:
```
class ABC { 
    //comment
}
```
is there some kind of auto formatting hardcoded into all Xtext editors or something like that?

**Comment by cdietrich** [comment]
similar as https://bugs.eclipse.org/bugs/show_bug.cgi?id=405184

**Comment by cdietrich** [comment]
this problem can be no longer reproduced in 2.19 => fixed
