### ISSUE TITLE
Return type example from documentation does not work

### ISSUE THREAD

**Issue by hyphz** [eclipse/xtext#1119]
The documentation suggests adding a return type to a rule as `returns ecore::EInt`.

However entering this produces the error *Couldn't resolve reference to AbstractMetamodelDeclaration 'ecore'.*

**Comment by kthoms** [comment]
The documentation quotes the terminal rule from `org.eclipse.xtext.common.Terminals`. To use the ecore namespace the ecore metamodel has to be imported, like in `Terminals` (you can navigate to there).

In your case add
```
import "http://www.eclipse.org/emf/2002/Ecore" as ecore
```

**Comment by cdietrich** [comment]
fixed with 64f0b5c0a4fc326788630a47dc28b292c553ef1c
