### ISSUE TITLE
Task marker parsing error in Xtext-based languages

### ISSUE THREAD

**Issue by ChristianBurghard** [eclipse/xtext#1124]
If a TODO marker is written in a multiline comment without linebreaks in any Xtext-based language including Xtend, the task description wrongly includes the trailing delimiter. 
For example, the line
`/* TODO: something */`
will result in an Xtext Task marker with the following description:

> TODO: something */

This problem has also been referenced in comment nr. 13 of this rather old bug report:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=380449

**Comment by cdietrich** [comment]
@ChristianBurghard which xtext version do you use?

**Comment by ChristianBurghard** [comment]
@cdietrich 2.11.0 if I read it correctly

**Comment by cdietrich** [comment]
i can no longer reproduce with xtext 2.12

**Comment by ChristianBurghard** [comment]
Yes, this seems to have been fixed in the meantime. Thanks for checking, though.
