### ISSUE TITLE
Problems with documentation

### ISSUE THREAD

**Issue by kdrozd** [eclipse/xtext#1138]
I see few problems with Text documentation (website).

1. Not updated (info about new things from r2.13)
2. Some pages are missing (like https://www.eclipse.org/Xtext/documentation/307_special_languages.html is missing in menu)
3. Information about LSP services.
4. So many branches for website....

How can help?

**Comment by cdietrich** [comment]
@kdrozd please give a proper description

**Comment by cdietrich** [comment]
Documentation not written is not there. If nobody documents ....

About the missing table of contents I have no idea why it is like it is. See https://github.com/eclipse/xtext/issues/1095 as well

**Comment by kdrozd** [comment]
I know about that... believe me that I would like to change this.... but I'm still learning Xtext. 

So far I can contribute by testing.

#1095 is about missing documentation to example languages not exactly to Xtext it self.

**Comment by cdietrich** [comment]
Yes but is shows what 307 was commented out from the table of contents

**Comment by cdietrich** [comment]
Created 

https://github.com/eclipse/xtext/issues/1139
https://github.com/eclipse/xtext/issues/1140
https://github.com/eclipse/xtext/issues/1141

**Comment by kdrozd** [comment]
Correct, but why? It should be updated like the part for whitespace-aware languages not hidden.

**Comment by cdietrich** [comment]
I have no idea

**Comment by cdietrich** [comment]
@szarnekow do you have any idea why the WS Language documentation was removed from the toc?

**Comment by szarnekow** [comment]
@cdietrich No, unfortunately I don't recall why it was removed. Maybe @spoenemann  remembers why it was removed in https://github.com/eclipse/xtext/commit/ef128efb0ed1d0ae7c936f8460399100598f3eb4#diff-af0d507e03f4e6d8e1e0f12f4f5793c8 ?

**Comment by spoenemann** [comment]
I think we wanted to make to make the TOC more concise. Feel free to put it back if you like.

**Comment by cdietrich** [comment]
restored ws languages docs. since i created separate issues for other missing stuff => close
