### ISSUE TITLE
Document LSP

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#1141]

**Comment by hristo-vrigazov** [comment]
I am looking forward to this one

**Comment by psuzzi** [comment]
As per discussion with @cdietrich, this issue is about documenting the Xtext implementation of LSP. Currently, the main source of information is some examples and blog post. Any reference to them would be useful to fix this issue.

**Comment by miklossy** [comment]
> ...there doesn't seem to be any clear documentation that I've been able to find about what Xtext IDE features are supported via LSP, so it's difficult to tell what kind of feature parity to expect between the native Eclipse IDE plugin and an LSP IDE and where the gaps might be. There is not even an LSP section on the Xtext documentation website....

See also https://www.eclipse.org/forums/index.php/t/1106716/

**Comment by miklossy** [comment]
The [LSP Support](https://www.eclipse.org/Xtext/documentation/340_lsp_support.html) section has been added to the Xtext documentation.

Fixed in 2.25
