### ISSUE TITLE
[doc] Contribution Guide: 2 factor authorisation on GitHub is not supported 

### ISSUE THREAD

**Issue by brodo** [eclipse/xtext#1144]
Hi,
the installer will not work properly if you do have two factor authorisation enabled on GitHub:

![two-factor](https://user-images.githubusercontent.com/377911/32690889-de4bdcc2-c6fe-11e7-80c4-b5b16cce34fb.png)

See [this](https://bugs.eclipse.org/bugs/show_bug.cgi?id=426144) bug in Egit.

**Comment by kthoms** [comment]
Seems that we can't do anything about it except for mentioning this in the contributor guide. Could you extend the documentation, please?
