### ISSUE TITLE
Installer: Installer rejects correct username/password combination

### ISSUE THREAD

**Issue by brodo** [eclipse/xtext#1145]
In the installer, under "Eclipse user ID/Password for Bugzilla/Hudson." when I click on "Authenticate" I get an Invalid password error even when using the correct password. The setup process still works though.

![eclipse authorisation](https://user-images.githubusercontent.com/377911/32690938-fdec51aa-c6ff-11e7-8fc1-f705a829b299.png)

**Comment by kthoms** [comment]
I am sure that this worked before. Might be an issue for Oomph.

**Comment by cdietrich** [comment]
1,3/4 year of inactivity. will close
