### ISSUE TITLE
[Java9] Add Automatic-Module-Name to all projects

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext#1152]
It is strongly recommended to add the `Automatic-Module-Name` manifest header for Java 9 compatibility. We have to add it for all projects.
Note that with the latest JDT there is a quickfix for that.

**Comment by kthoms** [comment]
See also https://dev.eclipse.org/mhonarc/lists/cross-project-issues-dev/msg14888.html

**Comment by szarnekow** [comment]
This will need careful testing. Xtext relies heavily on reflection and as long as it is part of the unnamed module, it depends on all other modules. As soon as it has a name, it depends only on other *named* modules thus it cannot see stuff from unnamed modules.

**Comment by kthoms** [comment]
How could we test this? How reliable are the existing tests to recognize failures?

**Comment by cdietrich** [comment]
since we run nothing agains j9
and xtext gradle shit does not work with j9
the only thing is to create example xtext projects, switch them to j9
and test that.

this requires my and florians changes to be gone through first

**Comment by kthoms** [comment]
If I see it correct we have refactored all occurances now.
