### ISSUE TITLE
Duplicate @Named ids in AbstractMultiLineCommentProvider

### ISSUE THREAD

**Issue by enikao** [eclipse/xtext#1153]
Xtext version: 2.12

The ids for both
org.eclipse.xtext.documentation.impl.AbstractMultiLineCommentProvider.RULE
and
org.eclipse.xtext.documentation.impl.AbstractMultiLineCommentProvider.WS_RULE
are the same:
"org.eclipse.xtext.ui.editor.hover.MultiLineDocumentationProvider.ruleName"

This way, we cannot change the names of both ML_COMMENT and WS default terminals.

**Comment by cdietrich** [comment]
Fixed in 2.14
