### ISSUE TITLE
Project Templates for Xtext Languages

### ISSUE THREAD

**Issue by ArneDeutsch** [eclipse/xtext#1154]
It would be nice if an Xtext user could easaly create a wizard for a language such that users of his language can create new projects using pre-defined project templates. This generated wizard should support:

- Selection of one out of many templates
-- Each template should at least have a name and a desription
- Configuration of the template
-- Each template should be able to define a UI to enable the user to customize the generated project
- Generation of artifacts
-- Each template should define what kind of files to generate for the new project and the generated files

The new wizard could be added as a fragment next to the existing SimpleProjectWizardFragment2.
The generated source should make it as simple as possible for the user to define new project templates.

The wizard would be defined in mwe2 file like this:
```
fragment = ui.projectWizard.TemplateProjectWizardFragment {
	generate = true
}
```

I've implemented this feature and created the following pull requests:
- https://github.com/eclipse/xtext-core/pull/593
- https://github.com/eclipse/xtext-eclipse/pull/497

**Comment by ArneDeutsch** [comment]
Screens vom Beispiel:

![wizard](https://user-images.githubusercontent.com/30502733/34045027-a91d50a8-e1a7-11e7-8ff9-77c18cb1db52.png)
![wizard2](https://user-images.githubusercontent.com/30502733/34045033-abb5aa40-e1a7-11e7-8830-3149def2e34c.png)

**Comment by ArneDeutsch** [comment]
Definition des Templates:

```
class MyDslProjectTemplateProvider implements IProjectTemplateProvider {
	override getProjectTemplates() {
		#[new HelloWorldProject]
	}
}

@ProjectTemplate(label="Hello World", icon="project_template.png", description="<p><b>Hello World</b></p>
<p>This is a parameterized hello world for org.xtext.example.mydsl.MyDsl. You can set a parameter to modify the content in the generated file
and a parameter to set the package the file is created in.</p>")
final class HelloWorldProject {
	var advanced = check("Advanced", false, "Check to enabled advanced configuration")
	var name = combo("Name", #["Xtext", "World", "Foo", "Bar"], "The name to say 'Hello' to")
	var path = text("Package", "mydsl", "The package path to place the files in")

	override protected updateVariables() {
		name.enabled = advanced.value
		path.enabled = advanced.value
		if (!advanced.value) {
			name.value = "Xtext"
			path.value = "mydsl"
		}
	}

	override protected validate() {
		if (path.value.matches('[a-z][a-z0-9_]*(/[a-z][a-z0-9_]*)*'))
			null
		else
			new Status(ERROR, "Wizard", "'" + path + "' is not a valid package name")
	}

	override generateFiles(IProjectFileGenerator generator) {
		generator.generate('''src/«path»/Model.mydsl''',
			'''
				/*
				 * This is an example model
				 */
				Hello «name»!
			''')
	}
}
```

**Comment by szarnekow** [comment]
I can imagine that project templates are something, that should be possible to contribute without changing the language itself. Assuming you'd want to have templates for different Xtext languages, I doubt that we would want to alter the language itself.
Did you consider adding an extension point for that purpose?

**Comment by kthoms** [comment]
The project templates are language specific, and I think it is valid to ship them with the language itself. I don't think that there is a high need to customize them by users of the language. Also template proposals and the simple project wizard are usually bound to the language implementation. Granted, templates could be added and edited by users, but normally they are just shipped and users rarely define their own afterwards.
Thus I would be fine with a language bound definition of templates.

**Comment by ArneDeutsch** [comment]
An extension point would be doable for sure. But I would agree that the templates would be most usable for the language designer to ship some examples to the new user to examplify how to use the language. In projects and project kickoffs I can imagine to use them to quickly show some fast project setup. I would propose to stick with the static approch for now and only add more flexibility in case users actually ask for it.

**Comment by ArneDeutsch** [comment]
Extension point is now added as well as i18n support for the project templates.

**Comment by ArneDeutsch** [comment]
Support for multiple projects per template is now also implemented. Infrastructure for that (including project dependencies, libraries ...) is reused to a large degree. Hence it should be not to hard to adapt Xtext and Xtext example projects to new wizard.

**Comment by ArneDeutsch** [comment]
@kthoms reviewed this interactivly with me. Following issues were detected:
- Missing comments in generated code
- "TextFileContributor" is a class of genereal interest and should be moved to "util" package
- The Template wizard should use IGrammarAccess.getName instead of generating an instance with hard coded grammar name constant
- Some classes are generated but noch used ... they should not be generated any more (implementation artifacts)
- The page variables in the wizard need to be "protected" such that a subclass can sucessfully override "addPages"
- In addtition to "getProjectInfo" the wizard should support a protected "createProjectInfo" to ease the work for an subclass
- Genertion of project.messages seems to be buggy ... check the implementation
- "build.properties" need to have an entry for "icons" folder .... fragment needs to be adapted
- Stream needs to be closed when reading temporary files in "TemplateProjectWizardFragment" (and guava has nice "ByteStreams.toByteArray" which will simplify implementation)
- A concept for grouping variables should be investigated ... probably some ideas how to make widgets more flixible in general
- An small info icon at a variable with additional description would be nice

**Comment by kthoms** [comment]
Great new feature! Good job, Arne!
