### ISSUE TITLE
Reduce build warnings

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext#1155]
During the builds several warning messages are produced, e.g.
- javadoc: broken links, invalid tags
- compile: use of deprecated API, unsafe/unchecked operations

Code shall be cleaned up to produce less warnings.

**Comment by ArneDeutsch** [comment]
I've gone through all projects and checked the warnings. Most warnings are there to preserve backwards compatibility for one reason or the other. Seems there are nearly no low hanging fruits left (if any).

I would propose to close this general ticket and instead create specific ones in case we want to get rid of specific usages of deprecated code or similar.

**Comment by kthoms** [comment]
I'm fine with creating more specific issues when needed again. Also allows us to tag this one with a milestone now.
