### ISSUE TITLE
Update Copyright Headers

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext#1160]
The copyright headers should be updated. Eclipse Copyright Header guidelines are here:
https://www.eclipse.org/projects/handbook/#ip-copyright-headers

- The copyright date should reflect the last commit year. We have to take the repository split into account. As a first approach we should only update files that changed after the split. I guess 2016-AUG-01 is a good cutoff date.
- Some copyright headers contain errors in the text. For example, I found occurances like
  - `under the terms of the Eclipse def License v1.0`
  - `under the terms of the Eclipse License v1.0`
- The headers should contain the SPDX-License-Identifier
- The term 'All rights reserved' is not necessary. It could be left as is or we could remove it. Newer files should not contain it anymore.

**Comment by cdietrich** [comment]
@kthoms anything left?

**Comment by kthoms** [comment]
Feature descriptors in umbrella are missing. Will provide a PR.

**Comment by kthoms** [comment]
I think we are done for the first round. We may add SPDX-License-Identifier and do more harmonizing later with a seperate issue.

**Comment by kthoms** [comment]
Some files in xtend-gen folders have been changed manually with the changes. The copyright date is derived from the Xtend sources, so some files are changing on recompilation.

**Comment by cdietrich** [comment]
as discussed last week the state in the source file should be deciding
