### ISSUE TITLE
[J9] how can we make sure ASM6 will be installed when installing on oxygen

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#1161]

**Comment by cdietrich** [comment]
is it possible we need to change

`<import plugin="org.objectweb.asm" version="5.0.1" match="compatible"/>`
to
` <import plugin="org.objectweb.asm" version="5.0.1" match="greaterOrEqual"/>`

**Comment by cdietrich** [comment]
or do we have to increase the version there. but what happens with luna and co then?

**Comment by cdietrich** [comment]
or should users install http://download.eclipse.org/tools/orbit/downloads/drops2/S20171130170529/repository or something like that manually

**Comment by szarnekow** [comment]
Isn't it possible to use asm 6.0.1 on Luna, too?

**Comment by cdietrich** [comment]
yes but how to make sure it can be installed / found?

**Comment by cdietrich** [comment]
and how shall we ship asm 6 to luna. we would have to add it to our update site correct?

**Comment by cdietrich** [comment]
so mabye we should simply ship it as we do with antlr and log4j?
https://github.com/eclipse/xtext-umbrella/blob/master/releng/org.eclipse.xtext.runtime.feature/feature.xml

**Comment by szarnekow** [comment]
Yes, that sounds about right to me.

**Comment by cdietrich** [comment]
while testing this with luna i wonder if somebody ever tried to install a recent xtext with luna

**Comment by cdietrich** [comment]
Fixed in 2.14
