### ISSUE TITLE
ASM6 Paperwork?

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#1162]
@svenefftinge @szarnekow do we need to do paperwork for usage of
ASM6?

if yes which?

**Comment by svenefftinge** [comment]
Yes, someone needs to request approval to use it, by creating a CQ. It will then end up in our IP-Log, that we have to get approval before any minor or major release.
Such CQs can be created through the portal.

Here is the one I create just now for ASM 6.0: 
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=15427

**Comment by cdietrich** [comment]
@svenefftinge where can i find the "create" button for such requests. we need one for gradle wrapper 4.4 as well i think

**Comment by cdietrich** [comment]
created https://dev.eclipse.org/ipzilla/show_bug.cgi?id=15428

**Comment by cdietrich** [comment]
gradle is done as well
