### ISSUE TITLE
Xtext Documentation - Link to 'state machine example' is broken.

### ISSUE THREAD

**Issue by miklossy** [eclipse/xtext#1163]
The link to the 'state machine example' on the web page https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html is broken.

**Comment by cdietrich** [comment]
@kthoms  this is related to your change.

**Comment by cdietrich** [comment]
```
xtext[website-published]$ grep -ril "org.eclipse.xtext.xtext.ui.examples" .
./xtext-website/documentation/308_emf_integration.md
./xtext-website/documentation/310_eclipse_support.md
./xtext-website/documentation/303_runtime_concepts.md
```

**Comment by miklossy** [comment]
I think this issue can be considered as solved (since the pull request has already been merged) and can be closed.

**Comment by kthoms** [comment]
Thx for the reminder.
