### ISSUE TITLE
Idea: use git modules or analuge to pull all modules into this repository

### ISSUE THREAD

**Issue by paulvi** [eclipse/xtext#1167]
It is possible use git modules or analogue to pull all modules into this repository

GitHub can display git modules

**Comment by cdietrich** [comment]
if so https://github.com/eclipse/xtext-umbrella/ would be a potential place as well

**Comment by kthoms** [comment]
But if we'd introduce modules I would prefer to have them in the main Git repo, i.e. here.

**Comment by kthoms** [comment]
Question would be how to keep them automatically up-to-date. Git modules are a nightmare.

**Comment by paulvi** [comment]
Quick search about gitmodule alternatives:

- https://stackoverflow.com/questions/6500524/git-subtree-or-gitslave-as-alternatives-to-git-submodules
- https://www.atlassian.com/blog/git/alternatives-to-git-submodule-git-subtree

**Comment by kthoms** [comment]
We won't take any action here in the near future. IDEA support is deprecated and will be removed soon.

**Comment by cdietrich** [comment]
This an idea not about idea

**Comment by cdietrich** [comment]
will close this. repo merged discussed on https://github.com/eclipse/xtext/issues/2135
