### ISSUE TITLE
Move deprecated classes to 'deprecated' source folders

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext#1171]
In `org.eclipse.xtext.ui` there is an additional source folder `/deprecated`in which some of the deprecated classes are collected. This makes it easier to decide on source level which classes are deprecated. 
We should follow this pattern and move sources to such folders.

**Comment by cdietrich** [comment]
@kthoms anything left?

**Comment by kthoms** [comment]
No, all fine
