### ISSUE TITLE
Set "discouraged access" to warning on all projects

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#1175]
Set "discouraged access" to warning on all projects

@kthoms @szarnekow what do you think?

**Comment by kthoms** [comment]
With x-internals in place for Xtext, we only get those warnings on internal API from external bundles, right? And thus the places where we should be friends of or refactor.
Problem is that there will be a long transition until we finally get rid of these warnings, or actively suppress them again.

**Comment by cdietrich** [comment]
well yes but doing 🙈 wont solve anything

**Comment by kthoms** [comment]
We might not be able to refactor all that stuff without breaking changes. If we really want to get rid off these, we might need a major release.

**Comment by cdietrich** [comment]
the first step is to become xfriends to these parts in platform.
so that we at least get notified on breaking changes

**Comment by cdietrich** [comment]
this is done now
