### ISSUE TITLE
Decide on move to EPL-2.0

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#1176]
https://www.eclipse.org/legal/epl-2.0/faq.php

**Comment by kthoms** [comment]
I think this would also require a major release.

**Comment by kthoms** [comment]
+1 BTW

**Comment by cdietrich** [comment]
@kthoms why do you think so? how will platform and jdt deal with this?

**Comment by kthoms** [comment]
That's worth a question on cross-platform.

**Comment by kthoms** [comment]
According to Wayne a major version upgrade is not required, see 
https://dev.eclipse.org/mhonarc/lists/cross-project-issues-dev/msg15353.html

**Comment by JanKoehnlein** [comment]
Having roughly browsed the FAQ, it looks OK from my side, especially as it does apparently _not_ require the consent of everybody who ever contributed. It also looks like the EF requires us to go that way.

We should inform users and other contributors beforehand using the mailing list and the forum. I am not exactly sure how this is going to hurt existing customers with strict corporate policies, and we should at least give them the possibility to speak up.

**Comment by cdietrich** [comment]
@waynebeaton is this a must now? when did this change?

**Comment by waynebeaton** [comment]
It's been in the FAQ since day one. I believe that there was a board resolution as well.

https://www.eclipse.org/legal/epl-2.0/faq.php#h.60mjudroo8e5

Please make this happen in advance of your next release.

**Comment by svenefftinge** [comment]
I've updated EPL-1.0 reference to EPL-2.0 and also added a Contribute.md

 - https://github.com/eclipse/xtext-core/pull/1378
 - https://github.com/eclipse/xtext-lib/pull/297
 - https://github.com/eclipse/xtext-extras/pull/566
 - https://github.com/eclipse/xtext-eclipse/pull/1334
 - https://github.com/eclipse/xtext-web/pull/219
 - https://github.com/eclipse/xtext-maven/pull/120
 - https://github.com/eclipse/xtext-xtend/pull/1004
 - https://github.com/eclipse/xtext-umbrella/pull/199

**Comment by cdietrich** [comment]
Things to look at

    complete headers
    LICENSE / license.html / epl*html
    about.html / about.properties
    ..... to be checked
    maven metadata / poms (also in gradle)
    feature.xml / feature.properties / license feature in target

https://www.eclipse.org/legal/guidetolegaldoc2.php
https://www.eclipse.org/projects/handbook/#ip-copyright-headers

**Comment by svenefftinge** [comment]
I have updated https://github.com/eclipse/xtext-lib/pull/297. Please check.
Once good-to-merge I'll update the others.

**Comment by svenefftinge** [comment]
I've updated the others

**Comment by cdietrich** [comment]
Fixed in 2.21.

thx @szarnekow @svenefftinge
