### ISSUE TITLE
Documentation on migrating an existing Xtext project to maven

### ISSUE THREAD

**Issue by sigiesec** [eclipse/xtext#1183]
I found https://github.com/xtext/maven-xtext-example and the accompanying explanation on https://www.eclipse.org/Xtext/documentation/350_continuous_integration.html, but they seem to be out of sync. The document mentions a my.mavenized.herolanguage.releng project, which does not exist anymore in https://github.com/xtext/maven-xtext-example. 

Background: I am trying to migrate an existing Xtext 2.13 project (https://github.com/btc-ag/service-idl/tree/initial-import) to maven, but I don't really know where to start.

**Comment by cdietrich** [comment]
Hi the easiest way is to select maven as build system on the second page of the wizard

**Comment by sigiesec** [comment]
I somehow managed to transfer the example from the maven-xtext-example, but I am not getting some errors during the language generation such as `XtextLinkingDiagnostic: null:39 Couldn't resolve reference to JvmType 'Generator'.`

https://travis-ci.org/sigiesec/service-idl/builds/361552152#L2056

**Comment by sigiesec** [comment]
39 looks like a line number here, but I don't know which file this refers to. "null" looks like this could be the file name, but it does not appear to be set. Is this some intermediate file that I don't see in my repo?

**Comment by cdietrich** [comment]
Do you use the old or new workflow

**Comment by sigiesec** [comment]
Probably the old. I see now. Generator has been deprecated in favor of XtextGenerator.

**Comment by cdietrich** [comment]
yes => you should have a look on that the wizard creates. otherwise you may have to add additional stuff to the maven dependency list in the execute task

**Comment by sigiesec** [comment]
Hm, my hope was that I could first get some CI build running with the current/old workflow, and then migrate it to the new workflow, but it does not seem to be that easy :(

I resolved the missing dependency (you were correct about that) and I now have a state with the old workflow that fails with
```
org.eclipse.xtext.resource.FileNotFoundOnClasspathException: Couldn't find resource on classpath. URI was 'classpath:/resource/com.btc.cab.servicecomm.prodigd/com/btc/cab/servicecomm/prodigd/Idl.xtext'
	at org.eclipse.xtext.resource.ClassloaderClasspathUriResolver.findResourceOnClasspath(ClassloaderClasspathUriResolver.java:61)
	at org.eclipse.xtext.resource.ClassloaderClasspathUriResolver.resolve(ClassloaderClasspathUriResolver.java:46)
	... 53 more
```
https://travis-ci.org/sigiesec/service-idl/builds/361577240#L2423

Maybe that is not too far from working!?

I also tried to create a new project from scratch using the wizard, and integrated only the DSL definition for now, which is under https://github.com/sigiesec/service-idl/tree/initial-generation-new-workflow

This seems to work to some extent on travis-ci: https://travis-ci.org/sigiesec/service-idl/builds/361619347

It fails during the ui tests, but this is probably only a secondary problem.

However, the generated directory structure looks very strange to me, and I cannot really use them from Eclipse now. Almost all files are in the *.parent project, and on the other projects I get a warning `build.properties does not exist`.

**Comment by cdietrich** [comment]
obviously the workflow does not fit. i dont have the time to analysze this myself this week.
you may be able to do some time traveling on the maven example. or on others e.g.
https://github.com/cdietrich/xtext-maven-example/tree/78982f3d73303a32a7ef74b5dd2fa6162717a771
https://github.com/cdietrich/xtext-maven-example/blob/78982f3d73303a32a7ef74b5dd2fa6162717a771/org.xtext.example.mydsl/src/org/xtext/example/mydsl/GenerateMyDsl.mwe2#L10
https://github.com/cdietrich/xtext-maven-example/blob/78982f3d73303a32a7ef74b5dd2fa6162717a771/org.xtext.example.mydsl/pom.xml

old projects often where build using the fornax mwe maven plugin.

**Comment by sigiesec** [comment]
Ok, thanks for your hints! I managed to get it working in another try (https://github.com/sigiesec/service-idl/tree/initial-generation-new-workflow-2), with a newly generated Xtext project. I will try to transfer the existing sources to this new project structure.

**Comment by sigiesec** [comment]
Ok, I think I now managed to migrate all sources to the newly generated structure, such that everything builds with maven on travis-ci. I am closing this issue.

Thanks for your suggestions!

**Comment by cdietrich** [comment]
the wrong parent projectin the docs should still be fixed

**Comment by cdietrich** [comment]
@arnedeutsch could you have a look?

**Comment by sigiesec** [comment]
Yes, that's true, lost the original question I raised a bit, sorry ;)

**Comment by ArneDeutsch** [comment]
I will have a look about the documentation.

**Comment by ArneDeutsch** [comment]
I propose to close this ticket.

**Comment by cdietrich** [comment]
no your pr is still in @kthoms inbox

**Comment by cdietrich** [comment]
PRs are merged. thus this is fixed
