### ISSUE TITLE
[J10] Narrow ASM version to [6.1.1,6.2.0)

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#1190]
we should decide how we deal with version ranges in asm

- `[6.1.1, 7.0.0)`
- `6.1.1`
- `[6.1.1,6.1.2)`

cc @szarnekow @holgerschill

**Comment by szarnekow** [comment]
I'm in favor of [6.1.1,6.1.2) to hopefully avoid accidental breakage but also benefit from micro updates.

**Comment by cdietrich** [comment]
that would be

```
[6.1.1,6.2)
```
correct?

**Comment by szarnekow** [comment]
True.

**Comment by cdietrich** [comment]
Fixed in 2.14
