### ISSUE TITLE
Multiline string

### ISSUE THREAD

**Issue by pstoeckle** [eclipse/xtext#1193]
I'm trying to model a YAML-like DSL in Xtext. In this DSL, I need some Multiline String as in YAML.

```yaml
description: |
  	Line 1
    line 2
    ...
```
My first try was this:

```xtext
terminal BEGIN:
	'synthetic:BEGIN'; // increase indentation
terminal END:
	'synthetic:END'; // decrease indentation
terminal MULTI_LINE_STRING:
	"|"
	BEGIN ANY_OTHER END;
```

and my second try was 
```xtext
terminal MULTI_LINE_STRING:
	"|"
	BEGIN
	((!('\n'))+ '\n')+
	END;
```
but both of them did not succeed. Is there any way to do this in Xtext?
I've tried this alternative as well.

```xtext
terminal MULTI_LINE_STRING:
	"|"
	BEGIN ->END
```

When I triggered the "Generate Xtext Artifacts" process, I got this error: 

```bash
3492 [main] INFO  nerator.ecore.EMFGeneratorFragment2  - Generating EMF model code
3523 [main] INFO  clipse.emf.mwe.utils.GenModelHelper  - Registered GenModel 'http://...' from 'platform:/resource/.../model/generated/....genmodel'
error(201): ../.../src-gen/.../parser/antlr/lexer/Internal..Lexer.g:236:71: The following alternatives can never be matched: 1
error(3):  cannot find tokens file ../.../src-gen/.../parser/antlr/internal/Internal...Lexer.tokens
error(201): ../....idea/src-gen/.../idea/parser/antlr/internal/PsiInternal....g:4521:71: The following alternatives can never be matched: 1
```

**Comment by kthoms** [comment]
The Xtend language needs also to support ML strings. Get some inspiration from there:
https://github.com/eclipse/xtext-xtend/tree/master/org.eclipse.xtend.core/src/org/eclipse/xtend/core

Also you can use [ANTLWorks](http://www.antlr3.org/works/) to understand better why it fails to produce a valid lexer.

**Comment by cdietrich** [comment]
this looks like a bug in the idea parser generator. unfortunately we do no longer support it
