### ISSUE TITLE
Maintain Website / GDPR / Rules / etc

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#1194]
things to evaluate

- can we port our jekyll themes to the new eclipse quicksilver (did not find any template/doc yet)
- do we fullfill the header footer whatever stuff the eclipse fqn wants to have
- do we need tagmanager and analytics
- do we need embedded twitter
- do we need embedded vimeo (xtend)
- can we avoid 3rd party cookies (twitter/vimeo)
- can we avoid 1st party cookies (eclipse)
- do we need this inform user on cookies thingy
- can the fork me on github thing done without pulling third party stuff directly

If we are not compliant at May 23nd then websites will be shut down by the fdn

**Comment by cdietrich** [comment]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=534384

**Comment by szarnekow** [comment]
See PR #1196

**Comment by cdietrich** [comment]
we now have a better version of the websites live and will see what the audit by the foundation will give

**Comment by kthoms** [comment]
[GDPR Audit results](https://docs.google.com/spreadsheets/d/1ZICnSgT1H6fAlbLITsHbSTK6gNzP0TuP_l72h48ofD0/edit?usp=sharing) for Xtext & Xtend websites are available. Compliance is approved.

<img width="1421" alt="screenshot 93" src="https://user-images.githubusercontent.com/265597/40033953-0d596cd6-57fb-11e8-87f3-25992c441676.png">
