### ISSUE TITLE
Xtext update site must contain JUnit 5.1 bundles

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext#1199]
Sample DSL with JUnit 5 configured will fail in the build when the update site does not contain JUnit 5 libs.

http://download.eclipse.org/modeling/tmf/xtext/updates/nightly

**Comment by kthoms** [comment]
see https://github.com/eclipse/xtext-core/issues/732

**Comment by dhuebner** [comment]
@kthoms The concrete usecase is not clear to me, could you elaborate?   However, polluting the Xtext update site with bundles required by a wizard output doesn't seem to be right.

**Comment by cdietrich** [comment]
they are not needed by the wizard but by the projects created by the wizard.

**Comment by dhuebner** [comment]
@cdietrich Than Wizard should create a proper target platform and add additional repository entry for the Junit 5 stuff.

**Comment by cdietrich** [comment]
so you dont want to consume it from the xtextupdate sire but directly from orbit.
but i am note sure if karsten is referring to an explicit or implicit target platform.

**Comment by dhuebner** [comment]
@cdietrich  There no need to have Junit 5 installed in the developer eclipse in order to run Xtext Wizard, right? At least I hope so... Hence, the only relevant part is the target platform generated by the wizard. It reference the Xtext update site, the eclipse update site and should reference orbit update site for Junit 5 if needed.

**Comment by cdietrich** [comment]
Bl the need is at runtime and I think the user should care about his target himself but I am not sure what karstens exact problem is

**Comment by cdietrich** [comment]
And I am not sure if we should do a bigger rework now or after the release

**Comment by kthoms** [comment]
@dhuebner is right: The use case is that the projects created need JU5 libs for the build, and they need to be contained in the TP. I thought that adding them directly to the category.xml of the repository would be the right way, since the same already happens for JU4 and ASM:
https://github.com/eclipse/xtext-umbrella/blob/4f0c27947f9c6d81ba2b0b88286ba6aaaeb8f390/releng/org.eclipse.xtext.sdk.p2-repository/category.xml

It will be cleaner then to have these deps explicitly in the target def created by the wizard. I will create a separate issue for that in xtext-core.
