### ISSUE TITLE
Plug-ins validation shows detected problems

### ISSUE THREAD

**Issue by DennisRoeck** [eclipse/xtext#1203]
Unused plug-in can be removed from target platform
![javax xml bind](https://user-images.githubusercontent.com/39051193/39817341-302c3a9c-539e-11e8-92f3-3c6f055180fc.jpg)

**Comment by cdietrich** [comment]
Looks like https://bugs.eclipse.org/bugs/show_bug.cgi?id=511117

**Comment by cdietrich** [comment]
for me it looks like we cannot do anything about that

**Comment by cdietrich** [comment]
still are waiting for progress on the bugzillas
