### ISSUE TITLE
generateP2Build task produces old 'helios' name

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext#1220]
The gradle task produces this target name:
```<target name="org.eclipse.xtext.helios.target" sequenceNumber="0">```
The `helios` part should rather reflect the repo's name, e.g. `core`.

To reproduce:
Execute `./gradlew generateP2Build -PuseJenkinsSnapshots=true` on xtext-core, check change in `releng/releng-target/xtext-core.target.target`

**Comment by cdietrich** [comment]
https://github.com/TypeFox/gradle-plugins/blob/e471361fca80ff975401e798f0de175224ef08fe/gradle-p2gen/src/main/java/io/typefox/gradle/p2gen/P2GenPlugin.xtend#L320
