### ISSUE TITLE
Nightly Deploy does not work

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#1221]
https://ci.eclipse.org/xtext/job/common-deploy/10487/console

it does not find 2.15 drops

**Comment by cdietrich** [comment]
cc @kthoms

**Comment by cdietrich** [comment]
is it possible there is a mkdir missing or something like that?
`     [java] /jobs/genie.xtext/common-deploy/workspace/build-result/promoter.ant:272: /home/data/httpd/download.eclipse.org/modeling/tmf/xtext/downloads/drops/2.15.0 does not exist.`

**Comment by kthoms** [comment]
Will care for it tomorrow

**Comment by kthoms** [comment]
Working now with the bugfix branch, but job _xtext-snapshots_ has to change the URL for the _publishing_ repo once the fix was merged.

**Comment by cdietrich** [comment]
What do you mean by that ?

**Comment by kthoms** [comment]
The promoter.ant file comes from the _publishing_ repo. I forked that, extended the script and created a PR.
The job now uses the bugfix branch from the fork, this has to be reverted once merged.

**Comment by kthoms** [comment]
Change was accepted and job configuration reverted. Fixed now.
