### ISSUE TITLE
Detect local Jenkins environment

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext#1224]
The build jobs are tightly coupled to use the Jenkins on http://services.typefox.io/open-source/jenkins for upstream repositories and target platform resolution. When the jobs are configured on another Jenkins, the build should pick up that environment. The default can stay as it is to use services.typefox.io, e.g. when running a local build. But jobs running on JIPP https://ci.eclipse.org/xtext should use the URLs from that server.

The built-in variable JENKINS_URL should be evaluated therefore.

This will become more important when running builds on the upcoming Eclipse build infrastructure on Cloudbees Jenkins Enterprise.

**Comment by cdietrich** [comment]
this is a placeholder for: the build behaves as we want

cc  @pngowda

**Comment by kthoms** [comment]
The screenshots show that different values for JENKINS_URL are passed in the build when running on different Jenkins instances:

<img width="1229" alt="screenshot 20" src="https://user-images.githubusercontent.com/265597/45518273-36209700-b7b1-11e8-9e51-9f2771d3e697.png">
<img width="1152" alt="screenshot 21" src="https://user-images.githubusercontent.com/265597/45518274-36b92d80-b7b1-11e8-8a5a-0a18b622d840.png">

**Comment by kthoms** [comment]
Passing JENKINS_URL variable in all Gradle/Maven invocations in all Jenkinsfile files

**Comment by kthoms** [comment]
Fixed in 2.16
