### ISSUE TITLE
MWE is not deployed to Sonatype OSS

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#1226]
thx to @kthoms the nightly is now deployed to the update site, but it is not deployed to sonatype oss snapshots. @dhuebner can you help out? which job should deploy the stuff to sonatype

**Comment by dhuebner** [comment]
@cdietrich There is no Job for that. There was no need to produce nightly maven artifacts and I don't see a reason why we should start with that. Are there a lot of changes in MWE? 

Normally I deployed an RC or Release from my local machine by calling `mvn deploy`

**Comment by cdietrich** [comment]
i dont get that
- we consume mwe from maven all over the place
- older snapshots are there https://oss.sonatype.org/content/repositories/snapshots/org/eclipse/emf/org.eclipse.emf.mwe2.lib/
- older releases are on maven central http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.eclipse.emf%22%20AND%20a%3A%22org.eclipse.emf.mwe2.lib%22

**Comment by cdietrich** [comment]
when we are going to modernize xtext for java 11, newer guava, newer asm, newer guice etc then we might want to test this with snapshots as well

**Comment by cdietrich** [comment]
cc @kthoms

**Comment by cdietrich** [comment]
https://github.com/eclipse/mwe/blob/master/Jenkinsfile calls deploy

**Comment by kthoms** [comment]
For EMF there is the following settings file on the build server `/opt/public/hipp/homes/genie.emf/.m2/settings-deploy-ossrh.xml`, see https://bugs.eclipse.org/bugs/show_bug.cgi?id=533616

The 'Xtext-Way' is using the promotion scripts. Whether a release or snapshot is published depends on the version number. We could start with copying the xtext-snapshots job for mwe2, this should enable deployment of the CI builds. For a release, MWE would have to follow the same procedure as Xtext.

**Comment by cdietrich** [comment]
Something similar is inside the log. Thus the question what does wrong

**Comment by cdietrich** [comment]
build calls
mvn -f git-repo/maven/org.eclipse.emf.mwe2.parent/pom.xml -s /opt/public/hipp/homes/genie.xtext/.m2/settings-deploy-ossrh.xml -DBUILD_TYPE=N -Dsign=true -DBUILD_ALIAS= -Dsign.skip=false -DtestFailureIgnore=true -Dmaven.repo.local=/home/hudson/genie.xtext/.jenkins/jobs/mwe2/workspace/.repository clean install

=> @kthoms is is possible jenkinsfile not used?

**Comment by cdietrich** [comment]
ping @kthoms

**Comment by cdietrich** [comment]
ping @dhuebner

**Comment by kthoms** [comment]
I have prepared a job for the deployment: https://ci.eclipse.org/xtext/job/mwe2-snapshots

It uses the publishing plugins like Xtext, but fails at the moment:
```
Caused by: org.gradle.api.publish.maven.InvalidMavenPublicationException: Invalid publication 'orgeclipseemfmwecore': supplied groupId does not match POM file (cannot edit groupId directly in the POM file).
	at org.gradle.api.publish.maven.internal.publisher.ValidatingMavenPublisher$MavenFieldValidator.failure(ValidatingMavenPublisher.java:163)
	at org.gradle.api.publish.maven.internal.publisher.ValidatingMavenPublisher$MavenFieldValidator.matches(ValidatingMavenPublisher.java:156)
	at org.gradle.api.publish.maven.internal.publisher.ValidatingMavenPublisher.validateIdentity(ValidatingMavenPublisher.java:54)
	at org.gradle.api.publish.maven.internal.publisher.ValidatingMavenPublisher.publish(ValidatingMavenPublisher.java:44)
	at org.gradle.api.publish.maven.tasks.PublishToMavenRepository$1.publish(PublishToMavenRepository.java:85)
	at org.gradle.api.publish.internal.PublishOperation.run(PublishOperation.java:36)
```

Will continue to investigate soon.

**Comment by cdietrich** [comment]
=> i wonder if we really should go this way instead of using the old one

**Comment by cdietrich** [comment]
we should simply try to call deploy on the original job and see whats happening

**Comment by kthoms** [comment]
Blocked by https://bugs.eclipse.org/bugs/show_bug.cgi?id=538361

**Comment by kthoms** [comment]
Has been fixed with moving the MWE build to EMF's JIPP.

https://ci.eclipse.org/emf/job/mwe2/
