### ISSUE TITLE
Build against Platform 2018-09

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#1228]
we should have builds against Post Photon in Eclipse and Xtend
+ an option for oomph as soon as possible

**Comment by cdietrich** [comment]
@kthoms are there now update sites available?

**Comment by kthoms** [comment]
Yes, there is http://download.eclipse.org/eclipse/updates/4.9-I-builds

**Comment by cdietrich** [comment]
todo: update codemining (and ui.testing) to build against "latest"
todo: update oomph

**Comment by cdietrich** [comment]
@kthoms i really need your help with that.
since we have tons of failing tests with 4.9
i'd really appreciate it to have a local target platform to debug and analyse this
see
https://github.com/eclipse/xtext-eclipse/issues/739
https://github.com/eclipse/xtext-eclipse/issues/733

**Comment by cdietrich** [comment]
Fixed in 2.15
