### ISSUE TITLE
Couldn't resolve reference to JvmIdentifiableElement 'junitVersion'

### ISSUE THREAD

**Issue by alxbrd** [eclipse/xtext#1229]
I downloaded Eclipse Photon and used the new XText wizard to generate a new DSL with Junit 5.

OS: Centos 7.5
Java: 1.8.0_152

Eclipse Version:

Eclipse DSL Tools

Version: Photon Release Candidate 3 (4.8.0RC3)
Build id: 20180607-0625

Xtext version:

Xtend SDK
Version: 2.14.0.v20180523-0937

The DSL has been generated without error, however, I am seeing the following error in the mwe2 file:

> Description	Resource	Path	Location	Type
> Couldn't resolve reference to JvmIdentifiableElement 'junitVersion'.	GenerateMyDsl.mwe2	/org.xtext.example.mydsl/src/org/xtext/example/mydsl	line: 43 /org.xtext.example.mydsl/src/org/xtext/example/mydsl/GenerateMyDsl.mwe2	MWE2 Problem

Is there a workaround for this issue or did I do something wrong? I cannot see any instructions about this anywhere.

**Comment by cdietrich** [comment]
do you use maven, gradle or plugin project?
can you post a screenshot of the classpath container of the project?
which org.eclipse.xtext.xtext.generator version does it contain?
if you search for the type JUnitFragment, which results are found?
does it help if you close and reopen the mwe editor?

**Comment by alxbrd** [comment]
1. I use Maven.

2. Classpath for the project containing the mwe2 file

```
<?xml version="1.0" encoding="UTF-8"?>
<classpath>
	<classpathentry kind="src" path="src"/>
	<classpathentry kind="src" path="src-gen"/>
	<classpathentry kind="src" path="xtend-gen"/>
	<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-1.8"/>
	<classpathentry kind="con" path="org.eclipse.pde.core.requiredPlugins"/>
	<classpathentry kind="output" path="target/classes"/>
</classpath>
```
![image](https://user-images.githubusercontent.com/1203413/41738776-e5b952e2-758a-11e8-8a7c-9f397d21ba81.png)

3. Nothing found when searching for that type.

4. I tried that, including several other things, including different versions of Eclipse.

**Comment by alxbrd** [comment]
I am trying to generate a working example DSL so that I can upgrade an existing DSL built with XText 2.12. I was hoping to see in the new project what changes I need to make to my old project.

**Comment by cdietrich** [comment]
your plugin dependencies are xtext 2.12 so it looks like you use it in your target platform.
the junit version selection make so sense this way => using the wizard to create projects with target 2.12 is not a supported usecase => you need to remove the junit version selection

**Comment by cdietrich** [comment]
per se you do not need to change anything besides update the target and regenerate.
you can then opt in for other stuff if you like to

**Comment by alxbrd** [comment]
I see what I have done wrong. I also loaded my old project in Photon and forgot that I loaded the old target file for it. Thanks for your help. You can close the issue.
