### ISSUE TITLE
Update to 2018-12 JDT/Platform

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#1232]

**Comment by cdietrich** [comment]
see https://github.com/eclipse/xtext/issues/1231

**Comment by cdietrich** [comment]
@ArneDeutsch could be something for you

**Comment by cdietrich** [comment]
the new jdt version has big memory degredation w.g. when used via xtend gradle plugin that need to be investigated first. https://github.com/xtext/xtext-gradle-plugin/issues/120

**Comment by cdietrich** [comment]
wont be it worth now since no J11 support yet

**Comment by szarnekow** [comment]
Wouldn't it make sense nevertheless to find potential regressions?

**Comment by cdietrich** [comment]
well we have "ui" tests in eclipse and xtend
that i ran manually against 2018-12 once or twice a week.
our current process is to use that one as "regression" detector

**Comment by cdietrich** [comment]
Fixed in Xtext/Xtend 2.17 as part of the Java 11 Update
