### ISSUE TITLE
Maven execution problem with latest EMF version

### ISSUE THREAD

**Issue by Guite** [eclipse/xtext#1233]
Strictly this is an EMF issue, but I thought I let you know because it breaks Xtext based builds.

The `org.eclipse.emf.codegen.ecore` bundle is obsolete at Maven central: last version is 2.12.0, like shown at http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22org.eclipse.emf.codegen.ecore%22

The latest version from Photon is 2.14.0 though. And EMF extended the genmodel which leads to this problem:

```
[ERROR] Failed to execute goal org.eclipse.xtext:xtext-maven-plugin:2.14.0:generate (default) on project my.cool.dsl: Execution default of goal org.eclipse.xtext:xtext-maven-plugin:2.14.0:generate failed: org.eclipse.emf.ecore.xmi.FeatureNotFoundException: Feature 'eclipsePlatformVersion' not found. (archive:file:/.../jenkins/.m2/repository/p2/osgi/bundle/org.eclipse.emf.codegen.ecore/2.14.0.v20180418-0836/org.eclipse.emf.codegen.ecore-2.14.0.v20180418-0836.jar!/model/GenModel.genmodel, 11, 50) -> [Help 1]
```

Any advice what to do? Downgrade EMF again?

**Comment by kthoms** [comment]
I'm working on the deployment of EMF artifacts to Maven Central at the moment. Soon 2.13 & 2.14 will be available.

**Comment by cdietrich** [comment]
@Guite yes it currently does not work to mix a new tycho based emf dependency with our old maven based one. i had hoped that the publishing of a newer emf to maven central would be done by now but unfortunately it is not.

**Comment by cdietrich** [comment]
@Guite could you provide a small example project with your usecase that we can use to test with

**Comment by antoine-morvan** [comment]
Hi, 

If I may, the issue can be reproduced when generating Java code from XCore within a tycho project. This fork can be used https://github.com/antoine-morvan/xcore-maven-example when use with ```mvn clean compile```.

Note: fixing it would require updating the versions in the POM file.

Best.

**Comment by cdietrich** [comment]
[pom.xml.txt](https://github.com/eclipse/xtext/files/2181348/pom.xml.txt)

updated pom there are two problems right now

-  bad ranges for antlr,=> too new version is used
- there is a validation in xcore 2.14 that does not work standalone. contacted @merks  via forum to find out more about that validation

**Comment by kthoms** [comment]
@Guite We have now EMF artifacts for EMF 2.14 in a staging repository on Maven Central. Would be great if you could try to use those artifacts and provide feedback if they are as expected. 
- Are dependencies correct? 
- Are sources and javadocs working?
- Do you miss artifacts?

Please use this repository: https://oss.sonatype.org/content/repositories/orgeclipseemf-1055

**Comment by Guite** [comment]
Sorry I can not test very soon due to holiday vacation.

**Comment by cdietrich** [comment]
if you want to test:

 with emf 2.14 (https://oss.sonatype.org/content/repositories/orgeclipseemf-1055 - be aware of https://bugs.eclipse.org/bugs/show_bug.cgi?id=536883)
 with emf 2.13 (https://oss.sonatype.org/content/repositories/orgeclipseemf-1056/)

**Comment by Guite** [comment]
@kthoms @cdietrich I can do a test this week. Can you point me to how to use a specific repository in Maven?

**Comment by cdietrich** [comment]
you can simply set 

```
	<pluginRepositories>
		<pluginRepository>
.....
```

and

``  <repositories>
    <repository>`
....
```

**Comment by Guite** [comment]
In my local test build it correctly fetched the new version, but failed because of https://bugs.eclipse.org/bugs/show_bug.cgi?id=536883

**Comment by Guite** [comment]
Which is the current recommendation? Downgrade to emf 2.13?

**Comment by cdietrich** [comment]
there is no recommendation. karsten is on holiday and the emf fix will be not available before 2.15 version of emf in september.

=> i dont have anything to offer. of course you could use 2.14 and turn off validation but i am not sure if that's what you are hoping for

**Comment by Guite** [comment]
Thanks @cdietrich for your quick response. I will try using 2.12 again to get Jenkins build working again for the meantime.

**Comment by Guite** [comment]
Just remembered that a workaround would require downgrading Xtext instead.

**Comment by cdietrich** [comment]
it would be sufficient to downgrade emf only

**Comment by holgerschill** [comment]
Current status is that we tried working with EMF 2.15 that got deployed to a SNAPSHOT repo on sonatype (https://oss.sonatype.org/content/repositories/orgeclipseemf-1058/). It worked and we don't see the problem anymore. Stay tuned for the upcoming EMF release. Xtext binds currently to EMF 2.12 where the problem does not exist.

**Comment by cdietrich** [comment]
we will publish emf 2.15 once it is out

**Comment by kthoms** [comment]
> Is there any "stable" repo where we can find all the temporary releases while waiting for a push on Maven Central ?

Nope. Staging repos are cleaned up by Maven Central OSSRH from time to time. We have to stage a new repo then. Fortunately this will have an end soon. I'll produce a new staged repo now.

**Comment by kthoms** [comment]
Finally EMF 2.15 is released and its artifacts are deployed on Maven Central, e.g.
https://search.maven.org/artifact/org.eclipse.emf/org.eclipse.emf.ecore/2.15.0/jar
