### ISSUE TITLE
Xtext Syntax Graph is required

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#1244]
If you want to install Xtext SDK you are forced to install GEF/Draw2d cause of the Graph view.
We should consider to move the graph and its source plugin to a separate feature and include that feature as optional into the current feature.

@szarnekow @kthoms what do you think

**Comment by kthoms** [comment]
I'm in favor of the optional feature. It will be useful to have this installed when Draw2D is available, but not be forced to.

**Comment by szarnekow** [comment]
I think so, too.

**Comment by cdietrich** [comment]
Fixed in 2.15
