### ISSUE TITLE
Adapt Website Deploy Jobs to Git/Gerrit Move

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#1246]
https://ci.eclipse.org/xtext/job/website-deploy/

deploys to "git" but foundation moved everything to "gerrit"
=> job maybe needs to be adapted to push to there

https://git.eclipse.org/r/#/admin/projects/www.eclipse.org/Xtext 
https://git.eclipse.org/r/#/admin/projects/www.eclipse.org/xtend

**Comment by kthoms** [comment]
There is indeed need for action here.

https://ci.eclipse.org/xtext/job/website-deploy/468/console

```
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)

nothing to commit, working directory clean
remote: error: insufficient permission for adding an object to repository database ./objects        
remote: fatal: failed to write object        
error: unpack failed: unpack-objects abnormal exit
To /gitroot/www.eclipse.org/xtend.git/
 ! [remote rejected] master -> master (unpacker error)
error: failed to push some refs to '/gitroot/www.eclipse.org/xtend.git/'
```

**Comment by cdietrich** [comment]
blocked by https://bugs.eclipse.org/bugs/show_bug.cgi?id=537204

**Comment by cdietrich** [comment]
pushing works now. but some changes do seem to work e.g. on community.html

**Comment by kthoms** [comment]
Last change adds a Jenkinsfile and does the publishing work. It checks out the latest change, regenerates the docs and uploads them by pushing to the website repos using SSH.

Job configured to use the `website-published` branch.
