### ISSUE TITLE
Introduce BOM for Xtext 3rd Party Dependencies

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#1249]
to be able to have dedicate versions for all (transitive) 3rd party dependencies it would be nice to have support for a maven bom in xtext.

- we need to be able to consume the bom from maven and gradle
- https://github.com/spring-gradle-plugins/dependency-management-plugin

**Comment by LorenzoBettini** [comment]
This is related to https://github.com/eclipse/xtext-maven/issues/35 isn't it?

**Comment by cdietrich** [comment]
yes but is is more general as should target "EVERYTHING"

**Comment by cdietrich** [comment]
@LorenzoBettini do you have some knowledge on boms vs maven plugins (and optional transitive deps)
for me it looks like it does not work as i expect

**Comment by LorenzoBettini** [comment]
@cdietrich it is somehow explained in https://github.com/eclipse/xtext-maven/issues/35
what is your doubt?

**Comment by cdietrich** [comment]
it does not work to remove the version here

```<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-surefire-plugin</artifactId>
					<version>2.21.0</version>
					<dependencies>
						<dependency>
							<groupId>org.junit.platform</groupId>
							<artifactId>junit-platform-surefire-provider</artifactId>
							<version>1.2.0</version>
						</dependency>
						<dependency>
							<groupId>org.junit.jupiter</groupId>
							<artifactId>junit-jupiter-engine</artifactId>
						</dependency>
					</dependencies>
				</plugin>
```

although its in the bom

```
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.eclipse.xtext</groupId>
				<artifactId>xtext-dev.bom</artifactId>
				<version>${xtextVersion}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>
```

from

http://services.typefox.io/open-source/jenkins/job/xtext-lib/job/sz_bom/lastSuccessfulBuild/artifact/build/maven-repository/

**Comment by LorenzoBettini** [comment]
and I guess junit is in the xtext-dev.bom?

in any case, as far as I know, dependencyManagement and scope import is for compile/test dependencies, that is, for the classpath of the project, not for dependencies of single plugins, which do not end in the classpath of the project...

dependencies of single plugins should come with their version I guess, but plugins can be configured once and for all in pluginManagement in the parent pom

**Comment by cdietrich** [comment]
so you say we still have to manage versions at 20 places

**Comment by LorenzoBettini** [comment]
you mean for plugin configurations? in that case you should use properties in the parent pom for versions.
At least that was my understanding: boms are for classpath dependencies not for plugins' own dependencies. (but I might be wrong).

Version numbers should be properties in a parent pom. The parent pom can also have dependencyManagement section (and in that case the "import" is not required) and act as a bom, or you have a separate pom acting as bom (which can reuse properties for version numbers from the parent pom).

Versions should be managed only in one single place and always through properties.

I'm afraid I can start working on that only in Semptember...

**Comment by cdietrich** [comment]
yes an that is too late for 2.15.
i think we will need 10 interations for that anyway.

**Comment by cdietrich** [comment]
TODO: seriously test
TODO: get rid of xtend and p2gen in xbase.lib seriously
TODO: use newer gradle everywhere
TODO: decide which gradle version to use (am not sure which version should be used with which xtext-gradle-plugin version

**Comment by cdietrich** [comment]
bom crap does not work for the buildscript itself
this then will break the xtext-gradle-plugin 
https://github.com/ArneDeutsch/xtext-gradle-example

**Comment by cdietrich** [comment]
@oehme @spoenemann do you know a possibility to work with Maven BOMs for the buildscript (=xtext gradle plugin) itself?

**Comment by svenefftinge** [comment]
Dropping gradle support for the BOM stuff?

**Comment by cdietrich** [comment]
no that would be general gradle support.
the alternative would be no to use bom but 
use giant cascades of dependencies and transitives excludes everywhere.
unfortunately in platform there are ranges of death everywhere but they dont hold true
=> to be able to have exact control of what we use we would have to take this approach
https://github.com/eclipse/xtext-extras/blob/2fd2d323629d2397bbf650c2fbf3e804c6e14f11/org.eclipse.xtext.builder.standalone/build.gradle#L8
and apply it to all platform (and emf and mwe) dependencies

**Comment by oehme** [comment]
Why would the `buildscript` block need a BOM? The xtext-gradle plugin only depends on xbase-lib (because it's written in Xtend), nothing else. You could get rid of that by writing it in Java if that's a problem.

All the actual runtime dependencies of Xtext are put into a dedicated `Configuration`, not `buildscript.classpath`.

**Comment by cdietrich** [comment]
cause the xtend/xtext gradle plugin uses the stuff. it at least downloads wrong versions of platform plugins

**Comment by cdietrich** [comment]
```
runtime - Runtime dependencies for source set 'main' (deprecated, use 'runtimeOnly ' instead).
\--- org.xtext:xtext-gradle-plugin:1.0.21
     +--- com.google.guava:guava:18.0
     +--- org.eclipse.xtend:org.eclipse.xtend.lib:2.9.0
     |    +--- org.eclipse.xtext:org.eclipse.xtext.xbase.lib:2.9.0
     |    |    \--- com.google.guava:guava:[10.0.1,14.0.1] -> 18.0
     |    \--- org.eclipse.xtend:org.eclipse.xtend.lib.macro:2.9.0
     |         +--- org.eclipse.xtext:org.eclipse.xtext.xbase.lib:2.9.0 (*)
     |         \--- com.google.guava:guava:[10.0.1,14.0.1] -> 18.0
     +--- org.eclipse.core:org.eclipse.core.runtime:3.7.0
     |    +--- org.eclipse.osgi:org.eclipse.osgi:3.7.1
     |    +--- org.eclipse.equinox:org.eclipse.equinox.common:3.6.0
     |    +--- org.eclipse.core:org.eclipse.core.jobs:3.5.100
     |    |    \--- org.eclipse.equinox:org.eclipse.equinox.common:3.6.0
     |    +--- org.eclipse.equinox:org.eclipse.equinox.registry:3.5.101
     |    |    \--- org.eclipse.equinox:org.eclipse.equinox.common:3.6.0
     |    +--- org.eclipse.equinox:org.eclipse.equinox.preferences:3.4.1
     |    |    \--- org.eclipse.equinox:org.eclipse.equinox.common:3.6.0
     |    +--- org.eclipse.core:org.eclipse.core.contenttype:3.4.100
     |    |    +--- org.eclipse.equinox:org.eclipse.equinox.preferences:3.4.1 (*)
     |    |    +--- org.eclipse.equinox:org.eclipse.equinox.registry:3.5.101 (*)
     |    |    \--- org.eclipse.equinox:org.eclipse.equinox.common:3.6.0
     |    \--- org.eclipse.equinox:org.eclipse.equinox.app:1.3.100
     \--- org.xtext:xtext-gradle-protocol:1.0.21
          \--- com.google.guava:guava:18.0
```

**Comment by oehme** [comment]
The `org.eclipse.core:org.eclipse.core.runtime` dependency is only used to generate property files. It has nothing to do with running Xtext.

**Comment by cdietrich** [comment]
yes but the problem is the platform dependencies: the signature errors. we want to avoid that. and we need 100% control on that. it even behaves differently with different gradle versions see https://github.com/xtext/xtext-gradle-plugin/issues/121
thats another issue where we need help and dont get any

**Comment by oehme** [comment]
Again, the dependencies you showed above have nothing to do with running Xtext. They are not visible when running the generator.

**Comment by cdietrich** [comment]
yes but if for some reason the platform people do something wrong again it will explode again.
the client of the plugin dont care if it is related to xtext or not.

**Comment by oehme** [comment]
The dependencies you showed above are not visible to the Generator. Therefor they can't cause the signature error you were seeing. That's unless Java's signing mechanism is broken and ignores classloader boundaries, which sounds very unlikely to me.

**Comment by cdietrich** [comment]
hmmmm but why is then the workaround for the signature problem not working at https://github.com/xtext/xtext-gradle-plugin/issues/121

**Comment by oehme** [comment]
This is because the Xtext Plugin currently uses a [detached configuration](https://github.com/xtext/xtext-gradle-plugin/blob/master/xtext-gradle-plugin/src/main/java/org/xtext/gradle/XtextBuilderPlugin.xtend#L87), which isn't part of `configurations.all {}` and so won't be captured by any dependency management plugins/rules. This should be rather easy to change, i.e. converting it to use a normal named Configuration instead. The same is true for the [Xtend plugin](https://github.com/xtext/xtext-gradle-plugin/blob/master/xtext-gradle-plugin/src/main/java/org/xtext/gradle/XtendLanguageBasePlugin.xtend#L70).

**Comment by cdietrich** [comment]
if i understand it correct the spring dependency plugin to handle the bom would be affected by this flaw too correct?

**Comment by oehme** [comment]
That's correct.

**Comment by oehme** [comment]
The main reason to make it detached was to hide it from users and ensure we have 100% control over it. But that's backfiring now it seems, as you want to control it in a different way.

**Comment by cdietrich** [comment]
well it looks like my 5% gradle knowedge is way to few to understand what is happening.

**Comment by cdietrich** [comment]
cc @ArneDeutsch

**Comment by oehme** [comment]
I'm sorry, but I have trouble following you. 

It's really as simple as changing the plugin so it uses a named Configuration (let's call it `xtextTooling`) instead of a detached Configuration. Then any dependency management plugins the users uses will be applied to it as well.

Also if you create a BOM for Xtext, we should import that BOM by default in the Xtext plugin to further reduce boilerplate.

**Comment by cdietrich** [comment]
the problem is: i have 5% knowledge of gradle internals. so i dont know what "changing the plugin so it uses a named Configuration" implies. there is a `getByName` that is the one i should call at the current place i guess. but where do i call `configurations.create('myConfiguration')`

**Comment by oehme** [comment]
I'm sure @ArneDeutsch would be happy to help out, he made many other improvements to the plugin lately.

**Comment by cdietrich** [comment]
@oehme i have another question:
to be able to use a non detached config the plugin and its dependencies (but maybe not all?) need to be added to the new config. 

```
Caused by: java.lang.IllegalStateException: No org.xtext.gradle.protocol.IncrementalXtextBuilderFactory found on the classpath
        at org.xtext.gradle.tasks.internal.IncrementalXtextBuilderProvider.createBuilder(IncrementalXtextBuilderProvider.java:87)
        at org.xtext.gradle.tasks.internal.IncrementalXtextBuilderProvider.getBuilder(IncrementalXtextBuilderProvider.java:37)
        at org.xtext.gradle.tasks.XtextGenerate.initializeBuilder(XtextGenerate.java:381)
        at org.xtext.gradle.tasks.XtextGenerate.generate(XtextGenerate.java:164)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:50)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:124)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:113)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:95)

```
=> i could do something like

```
val xtextBuilder =  project.dependencies.externalModule('''org.xtext:xtext-gradle-builder:«PLUGIN_VERSION»''')
				val xtextTooling = project.configurations.getByName("xxxx")
				xtextTooling.dependencies += xtextBuilder
				xtext.makeXtextCompatible(xtextTooling)
```
but that would then again draw the unwanted dependcies correct? e.g. `runtime "org.eclipse.jdt:org.eclipse.jdt.core:3.10.0"`

**Comment by cdietrich** [comment]
@oehme if i change the code then models on classpath are not found. does this need explicit configuration or did i destroy something?

**Comment by cdietrich** [comment]
gradle plugin: https://github.com/xtext/xtext-gradle-plugin/tree/cd_exp
test case: https://github.com/cdietrich/xcore-gradle-example/tree/cd_fixSeShit
(works only sometimes, the first time .....)

**Comment by cdietrich** [comment]
=> the main question is: how can i copy over all dependencies from the plugin to my new config so that stuff like Preferences and xbase.lib as fallback can be found

**Comment by cdietrich** [comment]
@oehme no matter what i try i dont get this running without detatched config

- either xtext version cannot be determined
- or the gralde plugin and api cannot be found
- or the eclipse preferences test does not work
- or the xcore example does not work cause it cannot load model files from "classpath"

**Comment by oehme** [comment]
You don't copy over anything, it has exactly one dependency - the builder. The dependencies of the plugin itself have nothing to do with that.

The test failures I saw were because you created one global configuration, but still try to add dependencies to it for every task. This fails on the second task because once resolved you can't add dependencies to a Configuration again. 

If we want to keep the plugin working exactly as it did before, you'll need to create one named Configuration for every request, e.g. appending the sourceSet name (`xtextToolingMain`, `xtextToolingTest`, ...). That should preserve all the features we had while also enabling these Configurations to be managed by the BOM.

**Comment by cdietrich** [comment]
sorry but i am not faimilar with lifecycle of the gradle. so where would i move the create to?

**Comment by oehme** [comment]
Exactly where the detached configuration was before.

**Comment by cdietrich** [comment]
but i still dont get where the sourcesets come into place.

**Comment by oehme** [comment]
Simply add it as [an argument](https://github.com/xtext/xtext-gradle-plugin/blob/86fdc39d884cdbbb5563bc6725350733f955734f/xtext-gradle-plugin/src/main/java/org/xtext/gradle/XtextBuilderPlugin.xtend#L60).

**Comment by cdietrich** [comment]
moved to 2.16 cause we want to test this more intense

**Comment by cdietrich** [comment]
@LorenzoBettini @szarnekow and i are currently working on this. do you have some time to help us understanding this.

what we have found out that we have to tell all the client projects that consume xtext to make use of our bom as well. having the dependencyManagement inside the pom of e.g. xtext.core and xbase.testing is not sufficient. is this correct or do i overlook something

**Comment by cdietrich** [comment]
what really makes my stomach hurt is that using the bom forces all client to adopt their maven and gradle builds and consume the bom => this is no dropin replacement. do i overlook something?

**Comment by LorenzoBettini** [comment]
@cdietrich exactly: the idea is that a client should "import" the bom in his own dependencyManagement section, just like you do in xtext.core and xbase.testing, and then just declaring a dependency without version will pick the version pinned in the bom.

In order to make this even more automatic, an xtext "parent" could be provided as well. The parent could have the bom as its parent (I guess that's what's happening in spring boot, IIRC) or import it in its own dependencyManagement section. Then the client should only have the xtext parent as his parent, and just declare the dependencies (again without version).
The parent could also preconfigure many plugins (in the pluginManagement section). who's using the xtext parent would have all the plugins configured, and just name them (without version, but possibly with additional configurations that would be merged) in the plugins section.

Does that answer your question? Is there already a PR I can pick up and play with?

**Comment by LorenzoBettini** [comment]
The parent and the bom, once introduced, would then bring to automatic updates, but, as you said, at least once they have to be used by clients... that's unavoidable. Indeed, parents and boms should be introduced very early (if not at the beginning) of a project.

Of course, this would not (or shoud not ;) break anything: parent and bom is just an additional convenience, but everyone is free to keep using the poms they already have.

At least, from the xtext side, parent and bom would pin versions (and common plugins configurations) and increase consistency (in the xtext codebase)

**Comment by LorenzoBettini** [comment]
If I understand your second question: clients are not forced... it's just a new additional convenience that we could provide

**Comment by cdietrich** [comment]
there is

http://services.typefox.io/open-source/jenkins/job/xtext-umbrella/job/bom_issue1249/lastSuccessfulBuild/artifact/build/p2-repository/
(xtext version of our branch to be installed in eclipse)
and 
https://projects.itemis.de/nexus/content/groups/xtext-bom/
(proxy that aggregates all the maven repos of all the bom_issue1249 repos in branches)

adding this to a newly created maven project parent
```


	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.eclipse.xtext</groupId>
				<artifactId>xtext-dev.bom</artifactId>
				<version>2.16.0-SNAPSHOT</version>
				<scope>import</scope>
				<type>pom</type>
			</dependency>
		</dependencies>
	</dependencyManagement>

```

and this to a gradle one

```
...
	dependencies {
		classpath 'org.xtext:xtext-gradle-plugin:2.0.2'
		classpath "io.spring.gradle:dependency-management-plugin:1.0.6.RELEASE"
	}
}

subprojects {
	ext.xtextVersion = '2.16.0-SNAPSHOT'
	repositories {
		jcenter()
		maven {
			url 'https://projects.itemis.de/nexus/content/groups/xtext-bom'
		}
	}
	
	apply plugin: 'java'
	apply plugin: "io.spring.dependency-management"
	dependencyManagement {
		imports {
			mavenBom "org.eclipse.xtext:xtext-dev.bom:${xtextVersion}"
		}
	}
...
```

looks good at a first glance

**Comment by cdietrich** [comment]
the problem is that if the client does not use the bom,
then "wrong" = newest dependencies are pulled

```
dietrich@dietrich-zbook:~/Downloads/BOM/ws/org.xtext.example.mydsl1.parent$ find . -name "*core.runtime*jar"
./.g/caches/modules-2/files-2.1/org.eclipse.core/org.eclipse.core.runtime/3.7.0/6658c235056134f7e86295e751129508802d71f2/org.eclipse.core.runtime-3.7.0.jar
./.g/caches/modules-2/files-2.1/org.eclipse.platform/org.eclipse.core.runtime/3.15.0/3f305cc3cae2c81233760f312ad4d9c9994e86a7/org.eclipse.core.runtime-3.15.0.jar
```


```dietrich@dietrich-zbook:~/Downloads/BOM/ws/org.xtext.example.mydsl.parent$ find . -name "*core.runtime*jar"
./.m2/org/eclipse/platform/org.eclipse.core.runtime/3.15.0/org.eclipse.core.runtime-3.15.0.jar
./.m2/org/eclipse/platform/org.eclipse.core.runtime/3.13.0/org.eclipse.core.runtime-3.13.0.ja
```

=> users are forced to use the bom to get correct versions

**Comment by LorenzoBettini** [comment]
That's right: if they want to have the correct versions they must use the bom, that's nothing we can do about I'm afraid ;)

Alternatively, as it is standard with Maven deps, one can specify his own version and exclude other artifacts accordingly, without using the bom.

**Comment by cdietrich** [comment]
@LorenzoBettini  will update the p2 repo so that the wizard will create in incl on the bom in gradle and maven

**Comment by cdietrich** [comment]
wizard creates projects with bom usage now.
=> after updating you can create new project
=> need to replace sonatype.oss with https://projects.itemis.de/nexus/content/groups/xtext-bom
happy testing

**Comment by cdietrich** [comment]
TODO: after the release: rebase again and adopt to version changes on master (e.g. lsp4j)

**Comment by cdietrich** [comment]
for grade: reevaluate https://docs.gradle.org/5.0/userguide/upgrading_version_4.html#rel5.0:bom_import

**Comment by cdietrich** [comment]
@oehme i have seen that gradle itself is starting to support boms. but this seems the implementation is still very bugy. e.g. there is no dependency management section created in generated maven poms.
can you tell how the plans are? is it planned to have full support? https://github.com/cdietrich/gradle-broken-bom-maven-dependencymanagement

**Comment by oehme** [comment]
Please open an issue on our Github repo, so our dependency management team can let you know about their plans.

**Comment by cdietrich** [comment]
https://github.com/gradle/gradle/issues/8105

**Comment by cdietrich** [comment]
looks like we would need to switch from gradle-maven to gradle maven-publish plugin

**Comment by szarnekow** [comment]
Done
