### ISSUE TITLE
https://www.eclipse.org/xtend/ leads to Xtext website

### ISSUE THREAD

**Issue by OLibutzki** [eclipse/xtext#1251]
Hi everyone,

looks like the Xtend website is not reachable as the requests to https://www.eclipse.org/xtend and http://xtend-lang.org/ are redirected to the Xtext website.

Kind regards
Oliver

**Comment by cdietrich** [comment]
looks related to https://github.com/eclipse/xtext/issues/1246

**Comment by cdietrich** [comment]
Fixed the broken Jenkins file and Job Configuration. cc @kthoms
