### ISSUE TITLE
Fix 'typo' in Xtext 15 minutes extended tutorial

### ISSUE THREAD

**Issue by psuzzi** [eclipse/xtext#1253]
There is a typo error in the Xtext 15 minutes tutorial extended (https://www.eclipse.org/Xtext/documentation/103_domainmodelnextsteps.html#tutorial-unit-tests) the line `val model = parser.parse(` should be replaced by `val model = parseHelper.parse(` .

**Comment by cdietrich** [comment]
Fixed with 8efb15d6c66d9c0d8fe526d40b35ed2c86b175a5
