### ISSUE TITLE
Completion doesn't work consistently in web editor

### ISSUE THREAD

**Issue by mvmn** [eclipse/xtext#1262]
h3. Steps to reproduce
Given a simple grammar like
```
grammar x.mvmn.tmpxtextproj.TemporaryXtextProject with org.eclipse.xtext.common.Terminals

generate temporaryXtextProject "http://www.mvmn.x/tmpxtextproj/TemporaryXtextProject"

Model:
	greetings+=Greeting*;

Greeting:
	'$' name=('a' | 'b' | 'c') | '@' name=('x' | 'y' | 'z');
```
Generate web editor (which uses Ace editor by default) and try invoking code completion for inputs "\@" and "\$" (one character input in both cases - don't include quotes).

h3. Expected result
- Completion for input \@ returns options  x, y and z
- Completion for input \$ returns options a, b and c.

h3. Actual result
- Completion for input \@ returns options \@, x, y and z
- Completion for input \$ returns nothing

h3. Issue details
Server responses for /xtest-service/assist in both cases are practically the same:
```
{
    "stateId": "-7ffffffa",
    "entries": [
        {
            "prefix": "",
            "proposal": "x",
            "textReplacements": [],
            "editPositions": [],
            "kind": "KEYWORD"
        },
        {
            "prefix": "",
            "proposal": "y",
            "textReplacements": [],
            "editPositions": [],
            "kind": "KEYWORD"
        },
        {
            "prefix": "",
            "proposal": "z",
            "textReplacements": [],
            "editPositions": [],
            "kind": "KEYWORD"
        },
        {
            "prefix": "@",
            "proposal": "@",
            "textReplacements": [],
            "editPositions": [],
            "kind": "KEYWORD"
        }
    ]
}
```

```
{
    "stateId": "-7ffffff8",
    "entries": [
        {
            "prefix": "",
            "proposal": "a",
            "textReplacements": [],
            "editPositions": [],
            "kind": "KEYWORD"
        },
        {
            "prefix": "",
            "proposal": "b",
            "textReplacements": [],
            "editPositions": [],
            "kind": "KEYWORD"
        },
        {
            "prefix": "",
            "proposal": "c",
            "textReplacements": [],
            "editPositions": [],
            "kind": "KEYWORD"
        },
        {
            "prefix": "$",
            "proposal": "$",
            "textReplacements": [],
            "editPositions": [],
            "kind": "KEYWORD"
        }
    ]
}
```

Debugging shows that this behaviour is the case because \$ is considered to be pre-existing prefix, and completions are filtered using that prefix. For \@ this is not the case though.

Further debugging reveals that this is happening due to Ace editor function for retrieving preceding identifier, which uses hardcoded regexp `/[a-zA-Z_0-9\$\-\u00A2-\uFFFF]/` that includes \$ but does not include \@.
Here is the corresponding code from /webjars/ace/1.2.3/src/ext-language_tools.js
```
var ID_REGEX = /[a-zA-Z_0-9\$\-\u00A2-\uFFFF]/;

exports.retrievePrecedingIdentifier = function(text, pos, regex) {
    regex = regex || ID_REGEX;
    var buf = [];
    for (var i = pos-1; i >= 0; i--) {
        if (regex.test(text[i]))
            buf.push(text[i]);
        else
            break;
    }
    return buf.reverse().join("");
};
```

! Note: adding space after \@ or \$ produces expected result. 
It is not clear though why serverside code returns different completions for just \@ or \$ and for the same input plus extra space.

**Comment by cdietrich** [comment]
issues for web should be filed at https://github.com/eclipse/xtext-web/issues

**Comment by mvmn** [comment]
Moved issue to corresponding project.
