### ISSUE TITLE
Prepare minimal Release Notes for Xtext and Xtend

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#1265]

**Comment by cdietrich** [comment]
ideas

Xtend Gradle Plugin / Java Source Lang
https://scans.gradle.com/s/mk2bzgqye22ga/timeline?taskFilter=:generateXtext
https://scans.gradle.com/s/wtlgbtgrqjhj4/timeline?taskFilter=:generateXtext

Task creation performance

Support Semantic Highlighting with LSP

?????

**Comment by cdietrich** [comment]
solution for the signature exception problem

**Comment by ArneDeutsch** [comment]
Erwähnunenswert erscheinen mir folgende Tickets:
- https://github.com/eclipse/xtext-eclipse/issues/433
- https://github.com/eclipse/xtext-eclipse/issues/677
- https://github.com/eclipse/xtext-xtend/issues/508
- https://github.com/eclipse/xtext-xtend/issues/536
- https://github.com/eclipse/xtext-core/issues/829

Ansonsten würde ich schreiben, dass wir und auf Stabilität, Performance und Eclipse 2018-09 Integration konzentriert haben.

**Comment by cdietrich** [comment]
this is basically done. akos will provide something on lsp semantic highlighting on monday

**Comment by cdietrich** [comment]
done
