### ISSUE TITLE
[Buildship] Commit changed classpath files

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#1274]
after the update to gradle 4.9 all `.classpath` files have changed.
- investigate if changes are ok
- commit the changed files

**Comment by cdietrich** [comment]
@kthoms anything left?

**Comment by kthoms** [comment]
idea is missing, since it wasn't imported by Oomph. Will add this ASAP.

**Comment by cdietrich** [comment]
We should talk again about abandoning idea. It’s not imported by oomph by intention

**Comment by kthoms** [comment]
Know that for sure.

**Comment by kthoms** [comment]
Done.
