### ISSUE TITLE
Create stable Orbit single composite for 2018-09

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#1277]
we should have something similar to http://download.eclipse.org/modeling/tmf/xtext/updates/orbit/compositeContent.xml e.g. http://download.eclipse.org/modeling/tmf/xtext/updates/orbit/2018-09/compositeContent.xml that allows us to "change" to a stable orbit repo to be used in wizard even after an xtext release without creating a new xtext release just for that

e.g. pointing to http://download.eclipse.org/tools/orbit/I-builds/I20180823201637/repository/,
then to the S repo once available, and the R repo when that is available

**Comment by cdietrich** [comment]
https://github.com/xtext/xtext-p2-orbit

**Comment by kthoms** [comment]
Created a job that updates the content of  http://download.eclipse.org/modeling/tmf/xtext/updates/orbit from the given git repo content

https://ci.eclipse.org/xtext/job/xtext-orbit-composite/
