### ISSUE TITLE
Find sustainable for orbit in wizard vs package orbit to our update site problem

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#1279]
(1) keep the interim solution (alias at xtext side - http://download.eclipse.org/modeling/tmf/xtext/updates/orbit/2018-09/)
(2) package all our orbit dependencies to our update site
(3) ask orbit for a stable and predictable repo uri (similar to platform)
(4) open for other ideas

**Comment by kthoms** [comment]
The http://download.eclipse.org/tools/orbit/downloads/latest-R could be an option that does not need updating always the wizard.
It was outdated, but actually should be maintained by the Orbit project (see [Bug#540706](https://bugs.eclipse.org/bugs/show_bug.cgi?id=540706)).

**Comment by cdietrich** [comment]
We don’t want latest. We want to have a sim rel specific

**Comment by szarnekow** [comment]
My impression is that (1) works pretty well atm. What do you think?

**Comment by kthoms** [comment]
I think we can live with (1). Just wanted to give this alternative for discussion.

So can we close this discussion issue?

**Comment by cdietrich** [comment]
i wonder if we should not at least try to talk to orbit about this issue.

**Comment by cdietrich** [comment]
https://www.eclipse.org/lists/orbit-dev/msg05037.html

**Comment by cdietrich** [comment]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=544186

**Comment by cdietrich** [comment]
TODO: test with https://download.eclipse.org/tools/orbit/downloads/2019-06/
(e.g. by letting our composite delegate there)
and see if it works

**Comment by cdietrich** [comment]
included orbit alias into our composites

**Comment by cdietrich** [comment]
negative: builds fail suddenly
positive: builds fail early
neutral: we have to adopt anyway

**Comment by cdietrich** [comment]
Fixed in 2.19
