### ISSUE TITLE
Update to EMF 2.15 (or later)

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#1282]
- update maven and gradle builds (see integ tests too)
- update manifests
- maybe update wizard
- test

**Comment by cdietrich** [comment]
moved to 2.17 since this depends on BOM will move to 2.17

**Comment by cdietrich** [comment]
Moved to 2.19

**Comment by cdietrich** [comment]
it looks like ed has already published emf 2.18 to maven central

**Comment by cdietrich** [comment]
Meanwhile Ed has published 2.19

**Comment by tivervac** [comment]
@cdietrich Do you have any specific concerns with EMF > 2.14 and Oxygen, or do you just have no idea if they still work together? We can test it on our side but we'll need a little bit of time

**Comment by cdietrich** [comment]
I want to make sure it works with old emf too if somebody picks Oxygens emf version (don’t know how you handle that(

**Comment by tivervac** [comment]
I'll raise the issue internally and get back to you

**Comment by cdietrich** [comment]
@tivervac any news?

**Comment by tivervac** [comment]
We had a release last week so this was delayed, but I'm working on it now.

**Comment by miklossy** [comment]
Please consider that the Xtext-Examples (e.g [Domainmodel.genmodel](https://github.com/eclipse/xtext-eclipse/blob/master/org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel/model/generated/Domainmodel.genmodel#L6)) specifies `runtimeVersion="2.12"` I think that would also worth updating.

@cdietrich Or will it be automatically updated when regenerated?

**Comment by cdietrich** [comment]
yes and no and this is one point to investigate

- if there is no version in workflow the default, aka the one on classpath will be used, 
- so in gradle / maven the one in the bom will be used
- in pure eclipse the one installed in eclipse will be used.
so this will be a problem if we dont install a newer emf than the one from oxygen on oxygen (or we have to use the non existing maven version 2.13 from oxygen which is no advancement from current 2.12)

**Comment by cdietrich** [comment]
=> options would be

- use newer runtime version in bom and eclipse (and workflows/genmodels)
- user newer version in bom but old version in workflows explicetly and keep older version in manifests/eclipse

**Comment by tivervac** [comment]
We've tried the following:
In `Eclipse 4.7.3` on `CentOS 6.10 (final)` we added the update site <http://download.eclipse.org/modeling/emf/emf/builds/release/2.19> and manually installed/updated EMF. We now have the `EMF Common 2.16.0.v20190625-1131` and `EMF Ecore 2.19.0.v20190822-1451`.

Everything still seems to work.

**Comment by cdietrich** [comment]
=> the assumption is that using a "newer" emf version of oxygen should work fine.
TBD:
- use runtimeVersion from oxygen
- use newer runtimeVersion and adapt manifests to require newer in eclipse (+ adapt affected target platforms)

**Comment by cdietrich** [comment]
unfortunately the runtime version from oxygen is still outdated regarding `@override` and  `StringBuffer` & co

**Comment by miklossy** [comment]
What does it exactly mean?

**Comment by cdietrich** [comment]
if does not generated override annotation and uses old stingbuffer

**Comment by cdietrich** [comment]
=> i wonder if we should use a newer emf (runtime) even in minimal target is oxygen

**Comment by miklossy** [comment]
Oh, ok, I understand.

**Comment by cdietrich** [comment]
move to 2.21

**Comment by cdietrich** [comment]
Meanwhile EMF 2.20 is on maven central

**Comment by szarnekow** [comment]
Great job @cdietrich! With these branches in my working copy, I do only have EObject from 2.20 in my JDT index.
Remaining: Remove the outdated "## Maven Tycho Hints" from the documentation.

**Comment by cdietrich** [comment]
which hints do you mean? can you please rebase and build all branches?

**Comment by szarnekow** [comment]
> updating the table

Yes, exactly. The table in xtext-website/documentation/350_continuous_integration.md is unnecessarily confusing given that we build against emf 2.20

> rebase
Will do

**Comment by cdietrich** [comment]
@szarnekow i wonder if we should mention the current instead of any old emf version in the table. what do you think?

**Comment by cdietrich** [comment]
i also wonder if i should sequash the commits. i did create separate ones to ease review

**Comment by miklossy** [comment]
I think in such huge change it is better to keep the commits separate.

**Comment by szarnekow** [comment]
> @szarnekow i wonder if we should mention the current instead of any old emf version in the table. what do you think?
> 
> (replace the 2.17s with the emf version of that release)

Yes, that sounds good.

**Comment by cdietrich** [comment]
@szarnekow i updated the PR. please check

**Comment by cdietrich** [comment]
lets see if there are any leftovers

**Comment by cdietrich** [comment]
@ArneDeutsch is going to fix broken xtext-maven-plugin tests. were not discovered due broken test result reporting on jenkins

**Comment by cdietrich** [comment]
no more regressions reported so far. so will close for now. if you find new problems please report a new issue
