### ISSUE TITLE
Release and Update to MWE 2.10.0

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#1283]
- TODO build and test against snapshots
- for the xtext builds
- for maven, tycho, gradle hello world projects, mwe example
- update wizard + ranges in xtext (e.g. core and extras)
- do the release
- update to the release version

also: consider bumping mwe versions in manifests

**Comment by cdietrich** [comment]
TODO remove jcenter workaround

**Comment by kthoms** [comment]
Workaround was removed. Closing.
