### ISSUE TITLE
Adapt api diff job for 2.16

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#1286]
https://ci.eclipse.org/xtext/view/Xtext-Xtend/job/xtext-xtend-api-diff/

**Comment by kthoms** [comment]
Prepared the job, but we need the real date for the right URL of the zipped repo.
Will do this after the release.

**Comment by kthoms** [comment]
Fixed in https://ci.eclipse.org/xtext/job/xtext-xtend-api-diff/1706/
