### ISSUE TITLE
Website bug on mobile phones

### ISSUE THREAD

**Issue by audinue** [eclipse/xtext#1293]
![screenshot_2018-09-05-02-33-47-642](https://user-images.githubusercontent.com/1407800/45053511-b8a2ab80-b079-11e8-8273-c62e64df8c0b.png)

I'm unable to tap the menu on the top right corner.
Could you please make that fork flag a smaller button or move the menu somewhere else?
It's quiet annoying to have to switch to desktop site every time I visit the website.
Thank you in advance. :smile:

**Comment by cdietrich** [comment]
PRs are welcome

**Comment by audinue** [comment]
Do you know where the website source code is?

**Comment by cdietrich** [comment]
Have a look at the website-published branch

**Comment by cdietrich** [comment]
@audinue i slightly adjusted your fix. can you please retest. (on safari on ios you might have to clear cache)
