### ISSUE TITLE
Xbase cannot resolve '+'?

### ISSUE THREAD

**Issue by dr-hx** [eclipse/xtext#1295]
I am developing a DSL based on Xbase. When testing my DSL, I found binary operators, such as +, -, *, /, >, <, etc., cannot be resolved. To determine the cause of this problem, I used the example DSL provided in the Xtext document (in Section "Five simple steps to your JVM language") and got the same problem.

I just copied the example grammar from the document, as follows:
grammar org.example.domainmodel.Domainmodel with
                                      org.eclipse.xtext.xbase.Xbase

generate domainmodel "http://www.example.org/domainmodel/Domainmodel"

Domainmodel:
    importSection=XImportSection?
    elements+=AbstractElement*;

AbstractElement:
    PackageDeclaration | Entity;

PackageDeclaration:
    'package' name=QualifiedName '{'
        elements+=AbstractElement*
    '}';

Entity:
    'entity' name=ValidID ('extends' superType=JvmTypeReference)? '{'
        features+=Feature*
    '}';

Feature:
    Property | Operation;

Property:
    name=ValidID ':' type=JvmTypeReference;

Operation:
    'op' name=ValidID 
        '('(params+=FullJvmFormalParameter 
        (',' params+=FullJvmFormalParameter)*)?')'
        ':' type=JvmTypeReference 
    body=XBlockExpression;

In the model inferrer, I also copied the sample code, as follows:
def dispatch void infer(Domainmodel element, IJvmDeclaredTypeAcceptor acceptor, boolean isPreIndexingPhase) {
		val itr = element.eAllContents;
		while(itr.hasNext) {
			val EObject o = itr.next;
			if(o instanceof Entity) (o as Entity).infer(acceptor, isPreIndexingPhase);
		}
	}
	
	@Inject extension IQualifiedNameProvider
  
  def dispatch void infer(Entity element, 
                IJvmDeclaredTypeAcceptor acceptor, 
                boolean isPrelinkingPhase) {
    acceptor.accept(element.toClass( element.fullyQualifiedName )) [
      documentation = element.documentation
      if (element.superType !== null)
        superTypes += element.superType.cloneWithProxies
      for (feature : element.features) {
        switch feature {
          org.example.domainmodel.domainmodel.Property : {
            members += feature.toField(feature.name, feature.type)
            members += feature.toGetter(feature.name, feature.type)
            members += feature.toSetter(feature.name, feature.type)
          }
          
          Operation : {
            members += feature.toMethod(feature.name, feature.type) [
              documentation = feature.documentation
              for (p : feature.params) {
                parameters += p.toParameter(p.name, p.parameterType)
              }
              body = feature.body
            ]
          }
        }
      }
    ]
  }

Then in the generated text editor, I got the problem as follows:
<img width="417" alt="image" src="https://user-images.githubusercontent.com/43060921/45206558-db220800-b2b7-11e8-8b29-407d918b4dd3.png">

**Comment by cdietrich** [comment]
how does your project and classpath settings look like?

**Comment by dr-hx** [comment]
You answer reminds me to check the classpath. I added org.eclipse.xtext.builder to the list of required plug-ins and solved the problem. Thanks for your reply.

**Comment by cdietrich** [comment]
adding xbase/xtend lib should have been sufficient
