### ISSUE TITLE
security exception attempting to compile using xtend

### ISSUE THREAD

**Issue by mcacker** [eclipse/xtext#1301]
I can't compile my project, which has successfully been compiling for a long time, due to the xtext/xtend security exception below.  Does anyone know why?  Has the public repo been changed?  I'm using version 2.8.3

[INFO] Downloaded: https://oss.sonatype.org/content/repositories/snapshots/org/eclipse/xtext/org.eclipse.xtext.xbase/maven-metadata.xml (567 B at 3.4 KB/sec)
[WARNING] Error injecting: org.eclipse.xtend.maven.XtendCompile
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, java.lang.SecurityException: class "org.eclipse.core.runtime.OperationCanceledException"'s signer information does not match signer information of other classes in the same package
  at org.eclipse.xtend.maven.XtendCompile.<init>(Unknown Source)
  while locating org.eclipse.xtend.maven.XtendCompile

**Comment by cdietrich** [comment]
See and comment at 
https://github.com/eclipse/xtext/issues/1231

**Comment by mcacker** [comment]
thank you very very much.  guess I should have looked around a bit more first.

Compile works now, but based upon other comments checking that it actually works.
