### ISSUE TITLE
.classpath changes by Buildship on Eclipse 2018-09

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext#1303]
After refreshing Gradle projects with Eclipse 2018-09 and current Buildship & Gradle version, `classpath` files are changed again on all projects. The classpath now uses separate output folders for regular and test sources and writes additional attributes `gradle_scope` and `gradle_used_by_scope` to `classpathentry` entries.

<img width="983" alt="screenshot 39" src="https://user-images.githubusercontent.com/265597/45793476-a12b0b80-bc92-11e8-8a92-933100246eb4.png">

**Comment by cdietrich** [comment]
looks like a dupe of https://github.com/eclipse/xtext/issues/1274

**Comment by kthoms** [comment]
Right. Will update the commit message to point to the other.
