### ISSUE TITLE
[oomph] Timeout accessing Oomph integration repository

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext#1304]
I just executed the Oomph Setup for latest Eclipse 2018-09 and Xtext projects and got this popup:

![screenshot 42](https://user-images.githubusercontent.com/265597/45864698-21c53700-bd7b-11e8-9c07-a16d1988e518.png)

Trying to list the repository location with the p2 director from command-line runs into timeout.
https://hudson.eclipse.org/oomph/job/integration/lastSuccessfulBuild/artifact/updates/

The setup can be executed further (but maybe only because I have a cached version of that repo?), but pauses for a while until the timeout occurs.

**Comment by szarnekow** [comment]
Is there anything that we can do about this?

**Comment by kthoms** [comment]
I assume it will be more an Oomph topic than Xtext

**Comment by cdietrich** [comment]
since we cannot do anything on Xtext side i will close this issue
