### ISSUE TITLE
Remove version pinning workaround from bootstrap-setup.gradle

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext#1305]
With upgrade to Xtext 2.15 (#1272) the workaround for pinning platform artifact versions becomes obsolete. Therefore the workaround should be removed.

See https://github.com/eclipse/xtext-core/pull/879#issuecomment-424247477

**Comment by cdietrich** [comment]
@kthoms is this fixed now?

**Comment by cdietrich** [comment]
i assume this fixed. feel free to reopen if necessary @kthoms
