### ISSUE TITLE
Provide Jenkinsfiles for Eclipse CJE CBI

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext#1309]
A new Jenkins infrastructure for Eclipse CBI based on Cloudbees Jenkins Enterprise (CJE) has been provided as of [bug#537284](https://bugs.eclipse.org/bugs/show_bug.cgi?id=537284). Xtext should provide Jenkinsfiles for the build on this infrastructure. It makes slightly different tool assumptions than the TF infra, so it may be realized by seperate Jenkinsfiles first. If possible, they should be put into one for all infras.

**Comment by kthoms** [comment]
xtext-core raises a test failure:
```
org.eclipse.xtext.xtext.generator.KeywordHelperTest.testToAntlrTokenIdentifier
org.junit.ComparisonFailure: expected:<[/EOF, [EOF, model, ÄÖÜäöüß]]> but was:<[/EOF, [???????, EOF, model]]>
```

**Comment by kthoms** [comment]
Test failure can be solved by specifying encoding for the Test task in `java-compiler-settings.gradle:

```
tasks.withType(Test) {
	systemProperty 'file.encoding', 'ISO-8859-1'
}
```

**Comment by cdietrich** [comment]
Please search the GitHub issue history why we didn't do that 1-2 years ago when we had similar problems before and if we set some encoding outside then

**Comment by kthoms** [comment]
Something special in mind? I did not find something. Does not necessarily mean something, searching GH issue is horrible.

**Comment by cdietrich** [comment]
I really want to understand what happens here: what is the default encoding on the machine. what does the test do on a windows machine cc @ArneDeutsch

**Comment by cdietrich** [comment]
@kthoms do you please have a link to the build?

**Comment by kthoms** [comment]
https://jenkins.eclipse.org/xtext/view/issue1309/ lists all builds related to this issue
more specifically the issue was seen in xtext-core and xtext-extras

**Comment by cdietrich** [comment]
@kthoms is there anything left open?

**Comment by kthoms** [comment]
I think we can close this for now. Jobs are running on CJE. If something is wrong there this should be raised in separate issues.
