### ISSUE TITLE
[gradle] Use ISO-8859-1 encoding in Test task

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext#1310]
On CJE JIPP tests may [fail with encoding issues](https://github.com/eclipse/xtext/issues/1309#issuecomment-426130079) during test execution when the encoding is not explicitly specified. On current [JIPP](https://ci.eclipse.org/xtext) the server instance has an encoding set in its environment:
```
echo $LANG
> en_US.UTF-8
```

On [CJE JIPP](https://jenkins.eclipse.org/xtext/job/kth-experimental/1/console), running in a Kubernetes Pod, the same command yields empty output.

The problem can be resolved by explicit setting encoding for the Test task in `java-compiler-settings.gradle`:

```
tasks.withType(Test) {
	systemProperty 'file.encoding', 'ISO-8859-1'
}
```

**Comment by cdietrich** [comment]
I am not sure if we want that. I tried this a year or two ago and it was rejected. I at least want to have a second opinion by @szarnekow

**Comment by kthoms** [comment]
The other way would be to ensure that the system encoding is properly set. We could do this for build machines, but we don't have control over 3rd party machines that want to run the build. So there is likely a problem there.
But I appreciate more feedback on this, I'm not an expert regarding encoding.
Maybe @oehme could also provide feedback.

**Comment by cdietrich** [comment]
I wonder if the tests should run independently from system encoding

**Comment by kthoms** [comment]
May have to initialize encoding themselves if that's important?

**Comment by cdietrich** [comment]
no what i mean: i am not sure if the intension of the tests it to run independent of the actual platform encoding and if this hold not true for a reason to investigate on the new eclipse ci whilst it work on mac, windows, my linuxes, typefox ci, old eclipse ci
=> what is so special about the new eclipse ci

**Comment by kthoms** [comment]
> => what is so special about the new eclipse ci

The environment var LANG is not set on these machines. That's the difference. I don't think that tests should rely on the fact, so it is better to set an encoding for test execution.

**Comment by cdietrich** [comment]
Let’s see what @szarnekow thinks

**Comment by kthoms** [comment]
Spoke with @szarnekow . We'll try to set the encoding in the affected tests instead.

**Comment by kthoms** [comment]
We'll try to fix all related test cases to ensure to work with the required encoding instead. Closing.
