### ISSUE TITLE
Fix tests relying on ISO-8859-1 encoding

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext#1311]
Some tests are relying on the fact that they are executed in an environment with ISO-8859-1 or UTF-8 encoding. They fail when they are executed on machines without explicit environment set, or when they are executed in an environment with US-ASCII. 

#1310 suggested to ensure that Gradle Test task execution happens with ISO encoding, but we decided to try to fix the few test cases instead.

Known cases are KeywordHelperTest from xtext-core and XbaseIntegrationTest from xtext-extras.

**Comment by kthoms** [comment]
Can be closed. It seems that only 2 test cases were affected.

**Comment by kthoms** [comment]
Also affected: [`InitialIndentationWithCommentsTest`](https://jenkins.eclipse.org/xtext/view/issue1309/job/xtext-xtend/job/kth_issue1309_cbi/23/)

**Comment by cdietrich** [comment]
@kthoms what is the state of this issue?

**Comment by kthoms** [comment]
The merged PRs should do the trick.
