### ISSUE TITLE
[Releng] Remove P2Gen plugin from gradle builds

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#1315]
we currently use the p2gen plugin to generate maven tycho builds for our gradle project.
the generates dont fit our needs. thus we should remove the usages of the plugin
from lib, core, extras, ????

**Comment by cdietrich** [comment]
cc @kthoms @pngowda

**Comment by kthoms** [comment]
When the plugin is removed the releng POMs should be refactored also: Dependencies should use `${project.version}` instead duplicating the versions. Same for platform configuration.

**Comment by cdietrich** [comment]
i dont know if this will work with the publishing plugin

**Comment by kthoms** [comment]
Ah right, could be that my mentioned change is not possible due to that.
