### ISSUE TITLE
Eclipse account required when contributing?

### ISSUE THREAD

**Issue by ckulla** [eclipse/xtext#1317]
In https://github.com/eclipse/xtext/blob/master/CONTRIBUTING.md#contribute-via-fork it is mentioned that all you need is a GitHub account in order to contribute. But in "4. Sign off your commits using the same email address you are using for your Eclipse account." it is mentioned that an Eclipse account is required.

Do I need an Eclipse account when creating a pull request via a fork?

**Comment by cdietrich** [comment]
hi, es you need an eclipse account and signoff the commits + sign a contributor assignment at eclipse https://www.eclipse.org/legal/ECA.php
