### ISSUE TITLE
Run Xtext builds in Docker on CBI

### ISSUE THREAD

**Issue by meysholdt** [eclipse/xtext#1323]
On CBI, the Xtext builds should run in a Docker container. This ensures the build environment is decoupled from infrastructure changes.

On http://services.typefox.io/open-source/jenkins/, we have Xtext builds running inside docker containers for ~2.5. years now and can recommend to do so.

To make it easier to create the Dockerfiles for CBI I'm happy to share the one we have been using. See below.

Remarks:
* On CBI, the base image should not be `jenkins`, but `ubuntu` or `alpine`
* The extra APT source was needed to fetch an old GTK version. Hopefully that's not needed anymore.
* `xvfb` is easier to set up than Xvnc since it doesn't need to have a generated password.
* maybe the node stuff isn't needed. 
```
FROM jenkinsci/jenkins

USER root

# Xvn on ubuntu:
# http://blog.dahanne.net/2011/07/18/run-ui-tests-on-a-headless-jenkins-hudson-continuous-integration-server-running-ubuntu/

# see https://github.com/nodesource/distributions#debinstall
RUN curl -sL https://deb.nodesource.com/setup_8.x | bash -

# hack to get packages from 'oldstable' debain-release to get older version of gtk to be more compatible with SWT during UI tests
RUN echo "deb http://deb.debian.org/debian jessie main"         >> /etc/apt/sources.list && \
    echo "deb http://deb.debian.org/debian jessie-updates main" >> /etc/apt/sources.list

# RUN apt-get remove -y gtk-update-icon-cache && apt -y autoremove
RUN apt-get update && apt-get -y --allow-downgrades install \
	libgtk-3-0=3.14.5-1+deb8u1 libgtk-3-common=3.14.5-1+deb8u1 \
#	libgtk-3-bin=3.14.5-1+deb8u1
	vnc4server xvfb vim fluxbox \
	openjdk-8-source \
	nodejs \
	make \
	g++

RUN npm install -g yarn

USER jenkins
```

**Comment by kthoms** [comment]
Related CBI issue: https://bugs.eclipse.org/bugs/show_bug.cgi?id=540236

**Comment by cdietrich** [comment]
@kthoms anything left?

**Comment by kthoms** [comment]
This task is done.
