### ISSUE TITLE
Redirecting for target file does not work

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#1326]
+ echo Redirecting target platforms in releng/org.eclipse.xtext.releng/target-platforms/developer-mars.target to master

=> it picks master instead of the branch. is there something missing @kthoms ?

**Comment by cdietrich** [comment]
script does 
`branchname=${1:-master}`
but who passes the arg?
is this a jenkins config issue?
why does the code care about the branchname for redirect at all.
why dont we let adjustPipelines do that and just care about the base url?

**Comment by cdietrich** [comment]
cc @szarnekow 

did your approach to just replace the prefix/JenkinsUrl and not the branch work?

**Comment by kthoms** [comment]
Might be that the Jenkinsfile should not replace the branch and leave this to adjustPipelines for the moment. The important part is to switch the Jenkins URL depending on the environment.
adjustPipelines is not superfluous yet, but it shall become.
I propose to change the Jenkinsfile to only replace the Jenkins URL in the targets until we have a working upstream detection.

**Comment by kthoms** [comment]
Or we introduce a boolean parameter that uses the BRANCH_NAME environment variable. So by default the branch names are not touched, but if desired it is taken from the current branch.

**Comment by cdietrich** [comment]
as discussed: in a first step replace prefix/jenkins url only

**Comment by szarnekow** [comment]
> as discussed: in a first step replace prefix/jenkins url only

Done in umbrella, eclipse and xtend

**Comment by kthoms** [comment]
I think this can be closed then, or shall we leave it open until we have a complete branch detection?

**Comment by szarnekow** [comment]
That was my understanding of 'in a first step'
