### ISSUE TITLE
Add new committers to maven/gradle

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#1330]
@kittaakos @miklossy if you like you can add yourself to

```
./xtext-web/gradle/developers.gradle
./xtext-maven/org.eclipse.xtext.maven.parent/pom.xml
./xtext-core/gradle/developers.gradle
./xtext-idea/gradle/developers.gradle
./xtext-extras/gradle/developers.gradle
./xtext-xtend/releng/org.eclipse.xtend.maven.parent/pom.xml
./xtext-xtend/gradle/developers.gradle
./xtext-lib/gradle/developers.gradle
``` 
please open PRs to do so

**Comment by miklossy** [comment]
I updated the developers sections as requested.
@kittaakos please also do so.

**Comment by cdietrich** [comment]
@kittaakos would still be nice if you could find the time.
if you dont want to feel free to close this issue

**Comment by kittaakos** [comment]
Sorry for the so long delay. I will add myself to `xtext-core` as part of one of my PRs and reference this issue.

I am closing this now.
