### ISSUE TITLE
Provide N&N link for 2018-12

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext#1331]
- create initial release notes
- provide link to
https://bugs.eclipse.org/bugs/show_bug.cgi?id=541240

**Comment by cdietrich** [comment]
i have already created the initial release notes for xtext and xtend on the website-master branch.
am not sure what the foundation requires here (wiki, website, .....)

**Comment by kthoms** [comment]
website link
https://www.eclipse.org/Xtext/releasenotes.html#/releasenotes/2018/09/04/version-2-15-0

can we already provide the link? It includes the release date and won't exist before publishing. Or can we provide already a state with a TODO comment? Not sure if I like that. I think if we could provide the link already and mention in the bug that it won't be valid until release day could be OK, let's see what they respond then.

**Comment by cdietrich** [comment]
the main problem is that i dont want the release notes on the official Xtext website before the release since publishing the release notes is defacto publishing the release

**Comment by kthoms** [comment]
I think it should be the final HTML link for release notes. Other projects already publish notes before their actual release, this is different.

**Comment by cdietrich** [comment]
well our release notes page has a stable link: http://www.eclipse.org/Xtext/releasenotes.html

**Comment by cdietrich** [comment]
even the new one is predictable since we have a release date already

**Comment by cdietrich** [comment]
so for 2.15 http://www.eclipse.org/Xtext/releasenotes.html#/releasenotes/2018/09/04/version-2-15-0
should get
http://www.eclipse.org/Xtext/releasenotes.html#/releasenotes/2018/12/04/version-2-16-0

**Comment by kthoms** [comment]
Reported the latter link. It already works and just shows the common release notes.
