### ISSUE TITLE
Assisted injection does not work

### ISSUE THREAD

**Issue by tsjfd** [eclipse/xtext#1332]
I want to pass parameters to a constructor of a custom class with guice by following the first answer on [https://stackoverflow.com/questions/9237996/pass-parameter-to-constructor-with-guice](https://stackoverflow.com/questions/9237996/pass-parameter-to-constructor-with-guice).

I adapt the MyDsl sample project but as soon as I get the injector via `val injector = new MyDslStandaloneSetup().createInjectorAndDoEMFRegistration` I get the following error

```
Exception in thread "main" com.google.inject.ConfigurationException: Guice configuration errors:

1) No implementation for org.eclipse.xtext.resource.IResourceFactory was bound.
  while locating org.eclipse.xtext.resource.IResourceFactory

1 error
	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1004)
	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:961)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1013)
	at org.xtext.example.mydsl.MyDslStandaloneSetupGenerated.register(MyDslStandaloneSetupGenerated.java:36)
	at org.xtext.example.mydsl.MyDslStandaloneSetupGenerated.createInjectorAndDoEMFRegistration(MyDslStandaloneSetupGenerated.java:24)
	at org.xtext.example.mydsl.main.main(main.java:9)

```

**Comment by cdietrich** [comment]
can you give some more details?

usually xtext generated the following (MyDslRuntimeModule inherits indirectly from DefaultRuntimeModule

```
	public Class<? extends IResourceFactory> bindIResourceFactory() {
		return XtextResourceFactory.class;
	}
```
=> how das your module hierarchy look like?

**Comment by cdietrich** [comment]
and i wonder what **exactly** you customized

**Comment by tsjfd** [comment]
I just have a class where I need access to a dependency injected class (e.g. scope provider), so I must also instantiate this class via dependency injection. The problem is that I want to create the class with a parametrized constructor (-> assisted injection).

For a minimal example I have added the following files to the MyDsl project and add the Google guice assisted inject package to Eclipse.

`Foo.xtend`
```
package org.xtext.example.mydsl.scoping

import com.google.inject.Inject
import com.google.inject.assistedinject.Assisted

class Foo implements FooInterface {
	package String bar

	@Inject new(@Assisted String bar) {
		this.bar = bar
	}

	// return the final name
	override String getFooName() {
		return this.bar
	}
}
```

`FooFactory`
```
package org.xtext.example.mydsl.scoping

interface FooFactory {
	def Foo create(String bar)
}
```

`FooInterface`
```
package org.xtext.example.mydsl.scoping

interface FooInterface {
	def String getFooName()
}
```

`main.xtend`
```
package org.xtext.example.mydsl

class main {
	def static void main(String[] args) {
		val injector = new MyDslStandaloneSetup().createInjectorAndDoEMFRegistration
	}
}
```

added the following snippet to `MyDslRuntimeModule`
```
	override void configure(Binder binder) {
		binder.install(new FactoryModuleBuilder().implement(FooInterface, Foo).build(FooFactory))
	}
```

**Comment by cdietrich** [comment]
do you think

```
override void configure(Binder binder) {
                // skip what the super impl does
		binder.install(new FactoryModuleBuilder().implement(FooInterface, Foo).build(FooFactory))
	}
```

is a good idea?

**Comment by tsjfd** [comment]
Yep, copy & paste error. The MyDsl example works now but I still get a `ComputationException` from guice on my real world project. I can't figure out the reason so that I solve my problem in a different way.
