### ISSUE TITLE
Umbrella repository should be downloaded from current Jenkins

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext#1348]
The "xtext-release" job downloads the aggregated p2 repo of xtext-umbrella hardcoded from the TypeFox server. The URL should evaluate JENKINS_URL.

https://ci.eclipse.org/xtext/view/Xtext-release/job/xtext-release/33/consoleFull

```
:downloadXtextP2Repository
Download http://services.typefox.io/open-source/jenkins/job/xtext-umbrella/job/milestone_2.16.0.M3/lastStableBuild/artifact/build/org.eclipse.xtext.sdk.p2-repository-2.16.0.M3.zip
```

**Comment by cdietrich** [comment]
@kthoms is there anything open for this issue left?

**Comment by kthoms** [comment]
This was already resolved
