### ISSUE TITLE
"unnecessary private modifier" quickfix removes comments

### ISSUE THREAD

**Issue by fabtagon** [eclipse/xtext#1360]
The following code ...
```xtend
package foo

class CommentEaterTest {
       // someComment
       private String fooBar
}
```

... brings up a warning by Eclipse: "The private modifier is unnecessary on field fooBar". Quickfix removes the 'private' modifier, as desired, but also the comment:

```xtend
package foo

class CommentEaterTest {
       String fooBar
}
```

Expected behaviour: the comment is kept

**Comment by cdietrich** [comment]
Duplicates https://github.com/eclipse/xtext-xtend/issues/415
