### ISSUE TITLE
Oomph: Prepare support for 2019-03 Host and Target

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#1365]

**Comment by cdietrich** [comment]
@kthoms provided https://github.com/eclipse/xtext-eclipse/pull/931 to fix the 4.10-i-builds.
wonder when https://git.eclipse.org/c/oomph/org.eclipse.oomph.git/commit/?id=68f67b9193558fcca9e4629aa1fe6a67cb719f7e is available so that we can use that for 2019-03 / 4.11-ibuilds

**Comment by cdietrich** [comment]
@kthoms is there anything left to have 2019-03 in dev eclipse as well?

**Comment by kthoms** [comment]
I don't think so.

**Comment by cdietrich** [comment]
ok then this is done now
