### ISSUE TITLE
Error 'mismatched input '..' expecting ')'' and 'mismatched input '.' expecting ';''

### ISSUE THREAD

**Issue by SharkJ** [eclipse/xtext#1366]
Hi,
I'm converting an antlr4 grammar to Xtext. I get the error `mismatched input '..' expecting ')'` at two instances which I have mentioned below: -

![errorxetxt](https://user-images.githubusercontent.com/23653853/49710685-045c8680-fc61-11e8-902c-aaebb9399a26.png)

Could you please tell me how I should correct these errors? AFAIK, the syntaxes are correct.

**Comment by cdietrich** [comment]
.. is only allowed in terminal rules

**Comment by SharkJ** [comment]
Thank you! Could you kindly explain about ~ and . symbols?

**Comment by cdietrich** [comment]
please have a look at the docs. the terminal grammar and others.
xtext has lexer/terminal rules and parser rules :(
