### ISSUE TITLE
Description of Xtend IDE feature is incomplete

### ISSUE THREAD

**Issue by mark-christiaens** [eclipse/xtext#1371]
![image](https://user-images.githubusercontent.com/813926/50080833-4bacbf00-01ed-11e9-9381-8646b8aa8496.png)

* The place holder for the "Build id" is incorrect.  
* The copyright statement looks out of date.

**Comment by cdietrich** [comment]
am not sure where is is coming from. we use the eclipse license feature. am not sure if they have a newer one for EPL v 1.0

**Comment by cdietrich** [comment]
Fixed in 2.17
