### ISSUE TITLE
2.16 wizard does not generate idea project

### ISSUE THREAD

**Issue by DanySK** [eclipse/xtext#1374]
This is probably more a question than a bug report, I searched the changelogs and I found no trace of a change in the project structure, so I'm asking here.

Generating a project with previous versions of Xtext automatically created generic IDE support as well as an `idea`, Gradle-managed sub-project which generated the IntelliJ Idea plugin.

Now, executing the wizard with these options with Xtext 2.16.0:
![image](https://user-images.githubusercontent.com/1991673/50895130-79a8ac00-1405-11e9-885e-725e04e3f515.png)

generates these projects:
![image](https://user-images.githubusercontent.com/1991673/50895173-a1980f80-1405-11e9-8262-4aac3bae42d6.png)

The `idea` project does not appear anymore. Is this behaviour expected? Did the IntelliJ plugin generation support get dropped?

**Comment by cdietrich** [comment]
Xtext Idea is currently not maintained. contributor are wanted for 2 years now but nobody really showed interest. you might have a look at lsp support in idea

**Comment by cdietrich** [comment]
codebase is here: https://github.com/eclipse/xtext-idea

**Comment by DanySK** [comment]
Thanks for the clarification
