### ISSUE TITLE
Document BOM

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#1385]
Document BOM for Xtext / Xtend and Gradle (Native vs Spring Deps) vs Maven

https://www.eclipse.org/forums/index.php/t/1097108/

**Comment by kthoms** [comment]
=> External blog post

**Comment by stephan-herrmann** [comment]
> => External blog post

Are you saying an external blog post _exists_? If so, where?

**Comment by cdietrich** [comment]
https://blogs.itemis.com/en/xtext-2-17-the-java-11-release
