### ISSUE TITLE
Nightly site content not up-to-date

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext#1395]
The nightly site http://download.eclipse.org/modeling/tmf/xtext/updates/composite/latest/head does not contain the latest artifacts. Current content for example:

```
org.eclipse.xtext.ui=2.17.0.v20190205-2144
org.eclipse.xtend.ide=2.17.0.v20190204-1259
```

I would expect more recent versions here,

**Comment by cdietrich** [comment]
you know the shitty ci infrastructure?

https://ci.eclipse.org/xtext/job/xtext-umbrella/job/master/ ran last at 6th
https://ci.eclipse.org/xtext/job/xtext-xtend/job/master/ was yellow on 5th and 6th
=> works as expected

**Comment by szarnekow** [comment]
I'm inclined to close this one as `works for me`

**Comment by kthoms** [comment]
Looks like
