### ISSUE TITLE
Follow up Guava 27.1 update in orbit

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#1398]
https://www.eclipse.org/lists/orbit-dev/msg05047.html

**Comment by cdietrich** [comment]
am not sure if this already effects 2019-03 but 2019-06 for sure if guava is updated

**Comment by cdietrich** [comment]
topic seems hot again
things to consider:
- actual fixes
- support for range or new version only (if the latter how to deal with older target platforms cc @tivervac  @lievenlemiengre)
- do we need to update guice too?

**Comment by cdietrich** [comment]
https://download.eclipse.org/tools/orbit/downloads/drops/I20190517220210/

**Comment by tivervac** [comment]
Having two different versions on different target platforms is indeed quite annoying for us, I have no solution.

**Comment by cdietrich** [comment]
the question is:
what if we use 27.1 only and add it to oxygen. what will explode

**Comment by cdietrich** [comment]
```
com.google.guava:guava:16.0.1 
 27.1-jreconflict resolution
com.google.inject:guice:3.0 
 4.0selected by rule
org.eclipse.xtext:org.eclipse.xtext.util:2.18.0-SNAPSHOT
org.eclipse.xtext:org.eclipse.xtext:2.18.0-SNAPSHOT
org.eclipse.xtext:org.eclipse.xtext.common.types:2.18.0-SNAPSHOT
org.eclipse.xtext:org.eclipse.xtext.xbase:2.18.0-SNAPSHOT
org.eclipse.xtend:org.eclipse.xtend.core:2.18.0-SNAPSHOT
:org.xtext.example.mydsl2.ide xtendToolingMain
org.eclipse.xtext:org.eclipse.xtext:2.18.0-SNAPSHOT

```

=> guice seems to be a problem too

**Comment by cdietrich** [comment]
Moved to 2.19
