### ISSUE TITLE
Setup Target platforms for 2019-03 / 2019-06

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#1412]
For Xtext-Eclipse and Xtext-Xtend
- latest should point to 2019-06
- r201903 should be created

- Wizard should point to 2019-06

- Create and use Orbit 2019-06 and use it in wizard and TP (latest)

**Comment by cdietrich** [comment]
will prepare a first set of pr for orbit and 2019 03 and update the latest as soon as the new update sites are available

**Comment by cdietrich** [comment]
Tasks Left: Adapt OOmpf @kthoms could you please have a look?

**Comment by kthoms** [comment]
PR updated & merged
