### ISSUE TITLE
Get rid of Typefox Jenkins as Default Upstream and Bootstrap

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#1424]

**Comment by cdietrich** [comment]
open: lsp4j see https://github.com/eclipse/xtext-core/issues/975

**Comment by kthoms** [comment]
As default https://ci.eclipse.org/xtext is now used, except for upstream lsp4j.

**Comment by kthoms** [comment]
@cdietrich Is there anything left for bootstrapping?

**Comment by cdietrich** [comment]
can grep only after everything is merged

**Comment by cdietrich** [comment]
created a lsp4j job on ci.eclipse.org/xtext to bypass the tf lsp4j/certificate problem and the non availability of a snapshot build on ci.eclipse.org/lsp4j

**Comment by cdietrich** [comment]
Fixed in 2.18
