### ISSUE TITLE
[enhancement] Provide find references search page with number of matches 

### ISSUE THREAD

**Issue by ElenMouner** [eclipse/xtext#1425]
Similar to text search, I think "Find References" search page should shows number of matches as shown in attached photo 
<img width="350" alt="findref" src="https://user-images.githubusercontent.com/9890195/55257086-818b2600-5267-11e9-9769-7b3fc8ab98a5.PNG">

**Comment by cdietrich** [comment]
https://www.eclipse.org/forums/index.php/t/1098255/

**Comment by ElenMouner** [comment]
Also, It would be helpful to show first match by default

**Comment by cdietrich** [comment]
what do you mean by 

> show first match by default

**Comment by ElenMouner** [comment]
every time I use find References, all results is collapsed and I have to navigate through results.
In text search, First match will be shown by default in text search
<img width="334" alt="findrefdefault" src="https://user-images.githubusercontent.com/9890195/55257560-f14de080-5268-11e9-960b-bc9161a4d40b.PNG">

**Comment by cdietrich** [comment]
you mean the tree will be expanded and the first match be selected?

![Bildschirmfoto vom 2019-03-29 20-59-15](https://user-images.githubusercontent.com/238736/55259303-9797e700-5265-11e9-84aa-99cf15073912.png)

**Comment by ElenMouner** [comment]
Exactly

**Comment by riederm** [comment]
i've provided a pullrequest for this issue https://github.com/eclipse/xtext-eclipse/pull/1165

- it adds a suffix to the status-label on top indicating the number of matches
- it auto-selects the first hit (first child of the first item)

![image](https://user-images.githubusercontent.com/3087112/63195346-a5160800-c072-11e9-9392-d52d319e4c59.png)

**Comment by cdietrich** [comment]
this will be part of Xtext 2.20 thx to @riederm
