### ISSUE TITLE
Build failures due to slack send failures

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext#1429]
On CJE buids are sporadically failing on the slackSend command:

```
[Pipeline] slackSend
Slack Send Pipeline step running, values are - baseUrl: https://itemis.slack.com/services/hooks/jenkins-ci/, teamDomain: <empty>, channel: xtext-builds, color: #FF0000, botUser: true, tokenCredentialId: 89564295-c53a-431e-883e-ee1c1af9ee3a
ERROR: Could not parse response from slack, potentially because of invalid configuration (botUser: true and baseUrl set), response: ok
```

The build should be successful even when slackSend fails.

**Comment by kthoms** [comment]
Build jobs are finished successfully even when this "error" happens. Since the message is sent to Slack although we receive this error we don't have a problem here.

**Comment by cdietrich** [comment]
@kthoms as discussed. maybe we should simply close this
as the workaround is in place now everywhere

**Comment by kthoms** [comment]
Yes, that's why I closed it ;)
