### ISSUE TITLE
createTempFile uses no suffix

### ISSUE THREAD

**Issue by rheydenr** [eclipse/xtext#1432]
This method in org.eclipse.xtext.junit4.TemporaryFolder
`	public File createTempFile(String prefix, String suffix) throws IOException {
		return File.createTempFile(prefix, prefix, getRoot());
	}
`

should rather be

`	public File createTempFile(String prefix, String suffix) throws IOException {
		return File.createTempFile(prefix, suffix, getRoot());
	}
`

**Comment by cdietrich** [comment]
org.eclipse.xtext.xbase.testing.TemporaryFolder.createTempFile(String, String) is affected too

**Comment by cdietrich** [comment]
see also https://github.com/eclipse/xtext/issues/1072

**Comment by kthoms** [comment]
@rheydenr The mentioned signatures are identical. Copy/paste error?

**Comment by cdietrich** [comment]
The are not
Prefix prefix 
Is not äprefix suffix

**Comment by MarcMil** [comment]
@kthoms The signatures are identical; the implementation is not.
The implementation's method call's second parameter is different.

**Comment by cdietrich** [comment]
Fixed in 2.19
