### ISSUE TITLE
ASM 7.0 is no longer in Orbit

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#1440]
ASM 7.0 is no longer in Orbit

https://download.eclipse.org/tools/orbit/downloads/drops/S20190501151401/

https://dev.eclipse.org/ipzilla/show_bug.cgi?id=19630

**Comment by cdietrich** [comment]
@ArneDeutsch i miss a change for the bom in lib

**Comment by ArneDeutsch** [comment]
Updated to ASM 7.1.
