### ISSUE TITLE
CBI builds old branches/PRs over and over again

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#1442]
CBI builds old branches/PRs over and over again and thus creates unneccessary load on the machines. @kthoms is here something wrong in the config
i still have no clue what causes the triggering of the builds?
maybe a new commit on master?

https://jenkins.eclipse.org/xtext/job/xtext-core/view/change-requests/job/PR-199/

**Comment by cdietrich** [comment]
![Bildschirmfoto vom 2019-05-03 17-36-24](https://user-images.githubusercontent.com/238736/57148519-0a96ff00-6dca-11e9-8492-a66efd3a053d.png)

**Comment by cdietrich** [comment]
seems to be caused because PRs are build "upon" master and not on the baseline

**Comment by szarnekow** [comment]
> seems to be caused because PRs are build "upon" master and not on the baseline

This is the correct behavior, isn't it?

**Comment by cdietrich** [comment]
yes and no.
the problem is: jenkins (cbi) is too weak for that.
this blocks the server for a half a day for the may open pr we have

**Comment by kthoms** [comment]
We changed the strategy for option "Discover pull requests from forks"
- from: "Merging the pull request with the current target branch revision"
- to: "The current pull request revision"

This should avoid that PRs are built upon master changes.

![screenshot 86](https://user-images.githubusercontent.com/265597/57226835-2b509600-7010-11e9-9b26-fd7bcee4abd0.png)
