### ISSUE TITLE
GWT library support

### ISSUE THREAD

**Issue by mbudnick** [eclipse/xtext#1444]
We use a small xbase-based DSL in our GWT application client and need therefor org.eclipse.xtext.xbase.lib.gwt.
What are the possibilities in the future for our application if there is no org.eclipse.xtext.xbase.lib.gwt anymore? Can I build it for my own?

The relevant part our DSL is

	Model:
		uses+=UseDomainobject*
		variables+=XVariableDeclaration*
		term=(JavaTerm | SqlTerm)
	;
	JavaTerm:
		type=JavaFctType name=ID ':' expression=XExpression
	;
	// Xbase Customization
	@Override
	XLiteral returns xbase::XExpression:
		XBooleanLiteral |
		XNumberLiteral |
		XNullLiteral |
		XStringLiteral |
		XTypeLiteral
	;

We generate our GWT application: From a model we reassemble the DSL sourcecode, generate javacode and write this into the source of the GWT application as assignment for a variable.
So our model use only an simple DSL expression and can use nevertheless complex statements like if etc. frome Xbase.

**Comment by cdietrich** [comment]
the xbase gwt support has not been dropped yet. but actually you are the first one that publicly voiced interest. the support for gwt with gradle plugins got worse and we have noone that keeps sure that what we build makes sense. therefore any help to keep it alive would be welcome

**Comment by mbudnick** [comment]
We use maven for the builds.

**Comment by cdietrich** [comment]
xbase-lib, core, extras, web and parts of xtend are built with gradle right no so we rely on having reasonable support there.
buts its not only about build. its also about making sure changes to xbase lib are properly reflected in gwt is currently done by nobody cause there is nobody that volunteers to do so or cares

**Comment by cdietrich** [comment]
see also https://github.com/eclipse/xtext-lib/issues/131

**Comment by cdietrich** [comment]
with the fix of eclipse/xtext-lib#131 we will keep gwt (for now)
