### ISSUE TITLE
[J11] I'd like to have the option to build all modules against/with java 11 regularly

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#1450]
[J11] I'd like to have the option to build all modules against/with java 11 regularly
eclipse and xtend should be build with tp latest

**Comment by cdietrich** [comment]
i assume we need an image with java 11 and java 8 installed  and need to set the `JAVA_HOME` var somehow

**Comment by Hejado** [comment]
After eclipse/xtext-umbrella#150 is done, we could use those images and maybe find a good way to adjust the podTemplate for a second job without much duplication.

**Comment by cdietrich** [comment]
move to 2.22

**Comment by cdietrich** [comment]
see also https://github.com/eclipse/xtext/issues/1717

**Comment by cdietrich** [comment]
move to 2.23

**Comment by cdietrich** [comment]
move to 2.24

**Comment by cdietrich** [comment]
TODO
tigger once a week:
- java 11 build in xtext-lib with trigger downstream
- java 8 build in xtext-lib with trigger downstream (to unrol changes by java 11 build)

**Comment by cdietrich** [comment]
move to 2.26

**Comment by NicoPrediger** [comment]
Unassigning myself due to priorities. Re-assign if priorities change...

**Comment by cdietrich** [comment]
move to 2.27

**Comment by cdietrich** [comment]
moved once more

**Comment by cdietrich** [comment]
close wont fix
