### ISSUE TITLE
Need to run tests on Windows

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#1455]
It would be nice to have the possibility to run all master builds with tests on windows.

**Comment by miklossy** [comment]
See also https://bugs.eclipse.org/bugs/show_bug.cgi?id=417686

**Comment by miklossy** [comment]
See also @kthoms suggestion https://github.com/eclipse/xtext-core/issues/1108#issuecomment-479900993

**Comment by ArneDeutsch** [comment]
I have build all 8 reporsitories on windows successful. No failing tests any more.

**Comment by cdietrich** [comment]
@ArneDeutsch @Hejado so you see no change to have a windows ci?

**Comment by ArneDeutsch** [comment]
Ah, wasn't aware that this was the intention of the ticket. I guess a windows CI is possible and with the fixed tests it might be green. But I have absolute no clue how to setup such an instance.

**Comment by cdietrich** [comment]
move to 2.22

**Comment by cdietrich** [comment]
move to 2.24

**Comment by LorenzoBettini** [comment]
I'm closing this because in GitHub Actions we now also build on Windows.
