### ISSUE TITLE
Problems generating code from Xcore models with Tycho/Buildship

### ISSUE THREAD

**Issue by melaasar** [eclipse/xtext#1456]
I am trying to find a target platform with a consistent set of dependencies to use for building xcore + xtext projects using Tycho or Builldship. The part that I am having the most difficulty with is generating code from Xcore models. Every platform release I have tried (from 2018-09 to 2019-03) gives some error due to some mismatched dependencies. If I don't use versions from a given release, but instead use custom maven GAVs, I found combinations of versions that are consistent, for example:

    dependencies {
	compile "org.eclipse.xtext:org.eclipse.xtext.xbase:2.16.0"
	compile 'org.eclipse.emf:org.eclipse.emf.ecore.xcore.lib:1.3.0'
	xtextLanguages "org.eclipse.xtext:org.eclipse.xtext.ecore:2.16.0"
	xtextLanguages "org.eclipse.emf:org.eclipse.emf.mwe2.runtime:2.9.0.201605261059"
	xtextLanguages 'org.eclipse.emf:org.eclipse.emf.ecore.xcore:1.3.1'
	xtextLanguages 'org.eclipse.emf:org.eclipse.emf.ecore.xcore.lib:1.3.0'
	xtextLanguages 'org.eclipse.emf:org.eclipse.emf.codegen:2.11.0'
	xtextLanguages 'org.eclipse.emf:org.eclipse.emf.codegen.ecore:2.11.0'
	xtextLanguages 'org.eclipse.emf:org.eclipse.emf.codegen.ecore.xtext:1.2.0'
    }

So what is the best way to address this? Do I assemble an adhoc target platform based on those versions that seem to work together? or will there be a release in the near future that is self-consistent?

**Comment by cdietrich** [comment]
hi, if nobody is working on making it consistent (or gives somebody else an incentive to do so)
i have doubts this will happen soon. https://github.com/eclipse/xtext/issues/1282
newer versions are not on maven yet.
there are some working combinations out there https://github.com/itemis/itemis-blog/tree/xcore_gradle_upgrade_xtext_neu
but i dont know if that will help you with your problem

**Comment by melaasar** [comment]
This example uses Maven dependencies directly, which works for me using the versions in my first comment. However, what I am trying to do is build the DSL with Tycho or Buildship, which uses a target platform (in Buildship's case, the target platform gets mavenized locally first). The reason I want to build this way is that I want to build an Eclipse updatesite for my DSL to work natively in Eclipse, in addition to a language server to work with LSP editors. The LS is doable only using maven dependencies, but the updatesite requires Tycho or Buildship, which produce Eclipse artifacts.

**Comment by kthoms** [comment]
The mentioned artifact versions are all available on p2 update sites, and building with Tycho won't be a problem. Consistent update sites are always the Eclipse Simultaneous Release sites, for 2019-03 it is http://download.eclipse.org/releases/2019-03.
There is everything in there what you need - Eclipse Platform, EMF, MWE, Xtext, Xcore.

**Comment by cdietrich** [comment]
we plan to bump the emf version with #1282 thus i will close this here
