### ISSUE TITLE
Oomph: Consider using Buildship 3.x

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#1459]
Oomph: Consider using Buildship 3.x
Maybe we need to increase the minimal host eclipse version for that

**Comment by cdietrich** [comment]
@kthoms https://download.eclipse.org/buildship/updates/e47/releases/2.x/ does not contain buildship 3.x
but it is installed. so it looks like it is picked not from the buildship update site but from the eclipse update site.

http://download.eclipse.org/buildship/updates/e411/releases/3.x
might need eclipse 4.11

@kthoms do you think we should use the latter for the 4.11, 4.12 and 4.13 targlet?

**Comment by kthoms** [comment]
Shall I try install 3.x on Eclipse 4.7?

**Comment by cdietrich** [comment]
testing this with the targlet should be sufficient

**Comment by kthoms** [comment]
Buildship 3.1 installs from the mentioned update site on Oxygen.3a without problems. So I will update the Buildship URL in the setup.

**Comment by cdietrich** [comment]
fixed in 2.19
