### ISSUE TITLE
[CBI] Configure job timeouts

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext#1463]
On JIRO we observed that some jobs may hang forever and block agents for the build jobs in the job queue. In order to cancel hanging jobs automatically we should configure timeouts for them. Timeouts are configured in the [options section](https://jenkins.io/doc/book/pipeline/syntax/#options).

Further it is useful to configure the timestamps option.

**Comment by kthoms** [comment]
With preparation for JIRO job timeouts have been configured for the jobs (eclipse/xtext#1463). While building the 2.18 release the xtext-extras build was aborted after 45 minutes in the longrunning tests stage. So the 45 minutes are unfortunately not enough as a useful timeout for this job.

The value should be changed to 60 for xtext-extras.

**Comment by cdietrich** [comment]
Moved to 2.19

**Comment by Hejado** [comment]
In addition to the timeout, we should add timestamps to logging as well. Okay to do this in this issue?

**Comment by cdietrich** [comment]
yes

**Comment by cdietrich** [comment]
@kthoms @Hejado is there anything left

**Comment by Hejado** [comment]
@cdietrich I don't think we missed something, so this should be done. Timeout periods should be big enough, if not - we can always adjust on the fly on the branch.
