### ISSUE TITLE
[Jenkins] Use declarative JUnit step

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext#1465]
JUnit result archivation is currently configured via JUnitResultArchiver in declarative pipelines:

```
step([$class: 'JUnitResultArchiver', testResults: '**/build/test-results/test/*.xml'])
```

This should be changed to declarative style provided by the JUnit plugin:

```
   junit '**/build/test-results/test/*.xml'
```

Also move the result archivation to the post process stage.

Affects all CBI.Jenkinsfile and Jenkinsfile files.

**Comment by cdietrich** [comment]
moved to 2.19

**Comment by cdietrich** [comment]
@kthoms anything left?

**Comment by cdietrich** [comment]
@kthoms anything left?

**Comment by kthoms** [comment]
Yes, xtext-eclipse and xtext-xtend still need to be changed. Will do this today.

**Comment by kthoms** [comment]
The last Jenkinsfile is now changed. Finally closing this issue.
