### ISSUE TITLE
[CBI] Add JIRO as known environment qualifier for build notification message

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext#1467]
In CBI.Jenkinsfile the new staging environment "ci-staging.eclipse.org" should be detected to append the qualifier "JIRO" to Slack notifications.

**Comment by cdietrich** [comment]
still some branches/builds where this is missing

**Comment by cdietrich** [comment]
moved to 2.19

**Comment by cdietrich** [comment]
fixed
