### ISSUE TITLE
[CBI] Migrate xtext-snapshots job to JIRO

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext#1471]
The job [xtext-snapshots](https://ci-staging.eclipse.org/xtext/job/releng/job/xtext-snapshots/) needs adjustments to run on JIRO. This may require work on the publishing plugin.

```
:signXtextCoreJars
Sign build/artifacts/org.eclipse.xtext-2.18.0-SNAPSHOT.jar
    2494147 bytes uploaded, 2696137 bytes downloaded (2.887942 s)
Sign build/artifacts/org.eclipse.xtext.ide-2.18.0-SNAPSHOT.jar
    496455 bytes uploaded, 533506 bytes downloaded (1.438424 s)
Sign build/artifacts/org.eclipse.xtext.util-2.18.0-SNAPSHOT.jar
    279356 bytes uploaded, 305810 bytes downloaded (1.304776 s)
Sign build/artifacts/org.eclipse.xtext.testing-2.18.0-SNAPSHOT.jar
    175301 bytes uploaded, 191643 bytes downloaded (1.269550 s)
Sign build/artifacts/org.eclipse.xtext.xtext.ide-2.18.0-SNAPSHOT.jar
    114756 bytes uploaded, 122153 bytes downloaded (1.163338 s)
Sign build/artifacts/org.eclipse.xtext.xtext.generator-2.18.0-SNAPSHOT.jar
    946553 bytes uploaded, 997279 bytes downloaded (1.686139 s)
Sign build/artifacts/org.eclipse.xtext.xtext.wizard-2.18.0-SNAPSHOT.jar
    221402 bytes uploaded, 233376 bytes downloaded (1.284811 s)
Sign build/artifacts/org.eclipse.xtext-2.18.0-SNAPSHOT-sources.jar
    1645273 bytes uploaded, 1782562 bytes downloaded (2.292317 s)
Sign build/artifacts/org.eclipse.xtext.ide-2.18.0-SNAPSHOT-sources.jar
    609374 bytes uploaded, 657010 bytes downloaded (1.592984 s)
Sign build/artifacts/org.eclipse.xtext.util-2.18.0-SNAPSHOT-sources.jar
    147628 bytes uploaded, 164984 bytes downloaded (1.293865 s)
Sign build/artifacts/org.eclipse.xtext.testing-2.18.0-SNAPSHOT-sources.jar
    148612 bytes uploaded, 162950 bytes downloaded (1.263169 s)
Sign build/artifacts/org.eclipse.xtext.xtext.ide-2.18.0-SNAPSHOT-sources.jar
    88973 bytes uploaded, 95699 bytes downloaded (1.259374 s)
Sign build/artifacts/org.eclipse.xtext.xtext.generator-2.18.0-SNAPSHOT-sources.jar
    1154065 bytes uploaded, 1205804 bytes downloaded (1.969389 s)
Sign build/artifacts/org.eclipse.xtext.xtext.wizard-2.18.0-SNAPSHOT-sources.jar
    212211 bytes uploaded, 227562 bytes downloaded (1.289680 s)
:copyOrgeclipsextextPom
:generatePomFileForOrgeclipsextextPublication SKIPPED
:signArchivesXtextCore FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':signArchivesXtextCore'.
> Cannot perform signing task ':signArchivesXtextCore' because it has no configured signatory
```

Full log:
[log.txt](https://github.com/eclipse/xtext/files/3222526/log.txt)

**Comment by kthoms** [comment]
In the job configuration 2 files are referenced in $HOME. They won't exist on JIRO there:
```
-Posspub.userMavenSettings=$HOME/.m2/settings-deploy.xml
-Psigning.secretKeyRingFile=$HOME/.gnupg/secring.gpg
```

**Comment by kthoms** [comment]
settings.xml might be configured via volume mount as we do it in the main jobs. This would likely require that `xtext-snapshots` has to be converted to a pipeline job, since the freesytle job does not allow us to configure the pod.

Second issue is GPG signing. On JIPP we have secring.gpg, which we likely don't have on JIRO yet. We should ask EclipseFdn staff for support here.
https://wiki.eclipse.org/IT_Infrastructure_Doc#What_about_GPG_signing.3F

**Comment by kthoms** [comment]
Opened [Bug#548657](https://bugs.eclipse.org/bugs/show_bug.cgi?id=548657)

**Comment by kthoms** [comment]
Xtext JIRO is prepared
https://wiki.eclipse.org/Jenkins#How_can_artifacts_be_deployed_to_OSSRH_.2F_Maven_Central.3F

**Comment by kthoms** [comment]
Running the Publish plugin within jnlp container does not work (see https://github.com/xtext/publishing/issues/8).
Instead we can run it in the xtext-buildenv container. But there we need `gpg` to perform the steps mentioned in the Wiki.
=> New Docker image version required with gpg installed.

**Comment by kthoms** [comment]
```
gpg: fatal: can't create directory `/home/default/.gnupg': Permission denied
```
=> https://docs.openshift.com/container-platform/3.9/creating_images/guidelines.html#use-uid
```
RUN chgrp -R 0 /some/directory && \
    chmod -R g=u /some/directory
```

**Comment by kthoms** [comment]
With image `docker.io/smoht/xtext-buildenv:0.9` the `gpg` is available and the process can be executed further.

```
21:45:12  + gpg --batch --import ****
21:45:12  gpg: directory `/home/default/.gnupg' created
21:45:12  gpg: new configuration file `/home/default/.gnupg/gpg.conf' created
21:45:12  gpg: WARNING: options in `/home/default/.gnupg/gpg.conf' are not yet active during this run
21:45:12  gpg: keyring `/home/default/.gnupg/secring.gpg' created
21:45:12  gpg: keyring `/home/default/.gnupg/pubring.gpg' created
21:45:12  gpg: key 084853F7: secret key imported
21:45:12  gpg: /home/default/.gnupg/trustdb.gpg: trustdb created
21:45:12  gpg: key 084853F7: public key "Eclipse Xtext Project <xtext-dev@eclipse.org>" imported
21:45:12  gpg: Total number processed: 1
21:45:12  gpg:               imported: 1  (RSA: 1)
21:45:12  gpg:       secret keys read: 1
21:45:12  gpg:   secret keys imported: 1
21:45:12  ++ gpg --list-keys --with-colons
21:45:12  ++ awk -F: '/fpr:/ {print $10}'
21:45:12  ++ sort -u
```

**Comment by kthoms** [comment]
Problem does not disappear
```
22:03:30  Execution failed for task ':signArchivesXtextCore'.
22:03:30  > Cannot perform signing task ':signArchivesXtextCore' because it has no configured signatory
```

Maybe we have to follow more stricter the documented process and remove this part from the publishing plugin?

**Comment by cdietrich** [comment]
the code signs the archive. if we want to change that we have to sign everywhere along the process with unknown side effects. 
where does this error message come from?
do you have a complete stacktrace?

**Comment by kthoms** [comment]
https://docs.gradle.org/current/userguide/signing_plugin.html

**Comment by cdietrich** [comment]
i assume there is no key id passed or something like that

**Comment by cdietrich** [comment]
did you test that on ci with the newer gradle?

**Comment by cdietrich** [comment]
i also miss the logs from the PublishingPlugin in the log

**Comment by kthoms** [comment]
Stack trace is here
https://ci-staging.eclipse.org/xtext/job/releng/job/build-artifacts-for-release/23/console

>did you test that on ci with the newer gradle?

the job already uses Gradle 5.4.1

>i assume there is no key id passed or something like that

I assume sthg similar. The public key Id might be different on the new credentials file. I tried to use the one that I saw on importing (it was different to the one on JIPP), but this did not help.

**Comment by cdietrich** [comment]
no i mean the job on ci. does that work with 5.4.1 if you changed that today

**Comment by kthoms** [comment]
I'll trigger the xtext-snapshots build, let's see.

**Comment by cdietrich** [comment]
=> can you run the job with info or debug

**Comment by kthoms** [comment]
On JIPP it looks fine
https://ci.eclipse.org/xtext/job/xtext-snapshots/1116/console

I will enable debug log with the next iteration (currently no executors left and another try already pending)

**Comment by cdietrich** [comment]
maybe we should gradle a hello world gradle project and call the sighning there
to separate the generate problem from the publishing plugin

**Comment by cdietrich** [comment]
it would also help to have debug on ci so that we can compare

**Comment by kthoms** [comment]
Debug log
[log.txt](https://github.com/eclipse/xtext/files/3347335/log.txt)

**Comment by cdietrich** [comment]
i wonder in the information should come from maven settings that are not there

**Comment by kthoms** [comment]
Output from the PublishingPlugin indicates at least that property `signing.keyId` was passed in

```
		if (hasProperty(SIGNING_KEY_ID)) {
			logger.info('''«infoPrefix»: using global property «SIGNING_KEY_ID»''')
```
=>
```
[INFO] [org.gradle.api.Project] OSSPUB: using global property osspub.version
[INFO] [org.gradle.api.Project] OSSPUB: using global property osspub.userMavenSettings
[INFO] [org.gradle.api.Project] OSSPUB: using global property signing.secretKeyRingFile
[INFO] [org.gradle.api.Project] OSSPUB: using global property signing.keyId
```
Used keyId `D1AE0CFD` as got from `gpg -K`
```
22:50:27  + gpg -K
...
22:50:27  ssb   4096R/D1AE0CFD 2016-03-01
```

**Comment by cdietrich** [comment]
ci says

```
01:38:37.811 [INFO] [org.gradle.api.Project] Maven Settings: including user file /opt/public/hipp/homes/genie.xtext/.m2/settings-deploy.xml
01:38:37.856 [INFO] [org.gradle.api.Project] Maven Settings: including security file /opt/public/hipp/homes/genie.xtext/.m2/settings-security.xml
01:38:37.864 [INFO] [org.gradle.api.Project] Maven Settings: found 3 server entries
01:38:37.874 [INFO] [org.gradle.api.Project] Maven Settings: using encrypted server entry for ossrh repository
01:38:37.875 [INFO] [org.gradle.api.Project] Maven Settings: using encrypted server entry for pgp signing
```

ci-staging says
```[2019-07-01T21:10:04.018Z] 21:10:02.975 [INFO] [org.gradle.api.Project] Maven Settings: including user file /home/jenkins/.m2/settings.xml
[2019-07-01T21:10:04.018Z] 21:10:02.975 [INFO] [org.gradle.api.Project] Maven Settings: including global file /usr/share/maven/conf/settings.xml
[2019-07-01T21:10:04.018Z] 21:10:03.054 [INFO] [org.gradle.api.Project] Maven Settings: found 0 server entries
```

**Comment by cdietrich** [comment]
@fredg02 do you know why there is no `settings-security.xml` on CBI

**Comment by cdietrich** [comment]
or do we have to do this: https://docs.gradle.org/current/userguide/signing_plugin.html#sec:using_gpg_agent

**Comment by fredg02** [comment]
> @fredg02 do you know why there is no `settings-security.xml` on CBI

See my comment here: https://bugs.eclipse.org/bugs/show_bug.cgi?id=548867#c2

**Comment by kthoms** [comment]
With the new instructions in the Wiki
   https://wiki.eclipse.org/Jenkins#Custom_container_on_Jiro_2

we finally got our first GPG signing and upload to OSSRH.

Besides the `settings-security.xml` we mounted also the wrong `settings.xml`. Previously we mounted 
```
  - name: settings-xml
    configMap: 
      name: m2-dir
      items:
      - key: settings.xml
        path: settings.xml
```
but it must be
```
  - name: settings-xml
    secret:
      secretName: m2-secret-dir
      items:
      - key: settings.xml
        path: settings.xml
```

These files must be passed to the publishing plugin.

Also, the file `/home/default/.gnupg/secring.gpg` (created by `gpg --batch --import "${KEYRING}"`) has to be passed.

The working scenario is now:
```
          ./gradlew \
            --refresh-dependencies \
            -PJENKINS_URL=$JENKINS_URL \
            -Posspub.userMavenSettings=/home/jenkins/.m2/settings.xml \
            -Posspub.mavenSecurityFile=/home/jenkins/.m2/settings-security.xml \
            -Posspub.version=$XTEXT_VERSION \
            -Posspub.signJars=$ORG_GRADLE_PROJECT_OSSPUB_SIGN_JARS
            -Posspub.packJars=$ORG_GRADLE_PROJECT_OSSPUB_PACK_JARS
            -Psigning.secretKeyRingFile=/home/default/.gnupg/secring.gpg \
            -Psigning.keyId=D1AE0CFD \
            clean publishMavenXtext publishEclipseXtext
```

Next steps:
- Jar signing
- Publish to Eclipse project storage

**Comment by kthoms** [comment]
The new job produces a file `build-artifacts-for-release.zip, but this zip should contain the build id (N<TIMESTAMP>) as name.

![screenshot 130](https://user-images.githubusercontent.com/265597/60575705-52131a80-9d7c-11e9-97b2-67fc7b5e95f0.png)
![screenshot 131](https://user-images.githubusercontent.com/265597/60575717-58a19200-9d7c-11e9-9f4f-b440796eb979.png)

**Comment by kthoms** [comment]
Target drop location is
```
<DOWNLOAD_AREA>/downloads/drops/<VERSION>/<BUILD_ID>
```

The properties can be read from `build-result/promote.properties`and `build-result/publisher.properties`
```
BUILD_ID=build-result/promote.properties#build.id
    [N|S|R]YYYYMMDDHHMM
DOWNLOAD_AREA=build-result/publisher.properties#downloads.area
    /home/data/httpd/download.eclipse.org/modeling/tmf/xtext/
VERSION=build-result/publisher.properties#version
    2.19.0
```

**Comment by kthoms** [comment]
The target location for the nightly update site location is
`/home/data/httpd/download.eclipse.org/modeling/tmf/xtext/updates/nightly`
Its content can be replaced.

The content can be unzipped from the uploaded zipped repository.

**Comment by kthoms** [comment]
Note: The `zip` command does not exist in the `jnlp` container. On the other side, ssh commands on projects-storage are not possible with the `xtext-buildenv` container.

**Comment by kthoms** [comment]
Renamed the job to [`sign-and-deploy`](https://ci-staging.eclipse.org/xtext/job/releng/job/sign-and-deploy)

The first deployment of the p2 repo zip and unpacking to the nightly p2 location is now functional.

With the current [build#73](https://ci-staging.eclipse.org/xtext/job/releng/job/sign-and-deploy/73/console) the OSSRH upload does not work. This used to be working already before. When this is working again we should be fine to deploy snapshots now.

**Comment by cdietrich** [comment]
problem might be that we redeploy the same stuff over and over again with no changes / rebuilds on the masters

**Comment by kthoms** [comment]
Might be, let's observe that. When uploading is done then the job is ready to replace the old `xtext-snapshots` job.

**Comment by kthoms** [comment]
The `sign-and-deploy` job uploads stuff to OSSRH. This becomes visible when enabling info output with `gradlew -info`, see https://ci-staging.eclipse.org/xtext/job/releng/job/sign-and-deploy/77/consoleFull

```
15:00:25  Publishing to repository 'ossrh' (https://oss.sonatype.org/content/repositories/snapshots/)
15:00:25  Deploying to https://oss.sonatype.org/content/repositories/snapshots/
15:00:25  Downloading: org/eclipse/xtext/org.eclipse.xtext/2.19.0-SNAPSHOT/maven-metadata.xml from repository remote at https://oss.sonatype.org/content/repositories/snapshots/
15:00:25  Uploading: org/eclipse/xtext/org.eclipse.xtext/2.19.0-SNAPSHOT/org.eclipse.xtext-2.19.0-20190704.130024-53.pom to repository remote at https://oss.sonatype.org/content/repositories/snapshots/
15:00:25  Uploading: org/eclipse/xtext/org.eclipse.xtext/2.19.0-SNAPSHOT/org.eclipse.xtext-2.19.0-20190704.130024-53.jar to repository remote at https://oss.sonatype.org/content/repositories/snapshots/
15:00:28  Uploading: org/eclipse/xtext/org.eclipse.xtext/2.19.0-SNAPSHOT/org.eclipse.xtext-2.19.0-20190704.130024-53-sources.jar to repository remote at https://oss.sonatype.org/content/repositories/snapshots/
15:00:29  Uploading: org/eclipse/xtext/org.eclipse.xtext/2.19.0-SNAPSHOT/org.eclipse.xtext-2.19.0-20190704.130024-53-javadoc.jar to repository remote at https://oss.sonatype.org/content/repositories/snapshots/
15:00:39  Uploading: org/eclipse/xtext/org.eclipse.xtext/2.19.0-SNAPSHOT/org.eclipse.xtext-2.19.0-20190704.130024-53.jar.asc to repository remote at https://oss.sonatype.org/content/repositories/snapshots/
15:00:39  Uploading: org/eclipse/xtext/org.eclipse.xtext/2.19.0-SNAPSHOT/org.eclipse.xtext-2.19.0-20190704.130024-53-sources.jar.asc to repository remote at https://oss.sonatype.org/content/repositories/snapshots/
15:00:46  Uploading: org/eclipse/xtext/org.eclipse.xtext/2.19.0-SNAPSHOT/org.eclipse.xtext-2.19.0-20190704.130024-53-javadoc.jar.asc to repository remote at https://oss.sonatype.org/content/repositories/snapshots/
15:00:46  Uploading: org/eclipse/xtext/org.eclipse.xtext/2.19.0-SNAPSHOT/org.eclipse.xtext-2.19.0-20190704.130024-53.pom.asc to repository remote at https://oss.sonatype.org/content/repositories/snapshots/
15:00:47  Downloading: org/eclipse/xtext/org.eclipse.xtext/maven-metadata.xml from repository remote at https://oss.sonatype.org/content/repositories/snapshots/
15:00:47  Uploading: org/eclipse/xtext/org.eclipse.xtext/2.19.0-SNAPSHOT/maven-metadata.xml to repository remote at https://oss.sonatype.org/content/repositories/snapshots/
15:00:48  Uploading: org/eclipse/xtext/org.eclipse.xtext/maven-metadata.xml to repository remote at https://oss.sonatype.org/content/repositories/snapshots/
15:00:49  :publishOrgeclipsextextPublicationToOssrhRepository (Thread[Daemon worker,5,main]) completed. Took 25.913 secs.
```

**Comment by kthoms** [comment]
Pipeline merged to xtext-umbrella/master and job configured to use master.
