### ISSUE TITLE
[releng] Change target file name for p2 repository for stable/release builds

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext#1472]
The publishing plugin packages the p2 repository in the `zipXtextP2Repository` step to a zip with pattern [`tmf-xtext-Update-<BUILDTYPE><TIMESTAMP>.zip`](https://ci.eclipse.org/xtext/job/xtext-release/ws/build-result/downloads/).
For build type "S" and "R" the zip should contain the release name (e.g. `tmf-xtext-Update-2.18.0.M3.zip`)

**Comment by kthoms** [comment]
The related code is in `EclipsePublishing.xtend`, line 175ff.

```val zipP2RepoTask = tasks.create('''zip«repoName»P2Repository''', Zip)```

**Comment by cdietrich** [comment]
@kthoms would that solve  https://bugs.eclipse.org/bugs/show_bug.cgi?id=522525

**Comment by kthoms** [comment]
Yes, this should solve that.

**Comment by kthoms** [comment]
https://www.eclipse.org/modeling/tmf/downloads/

2.18.0.M3 has been named properly. Older milestones have still `S<BUILD_ID>`.

![screenshot 97](https://user-images.githubusercontent.com/265597/58465575-49557600-8138-11e9-98a8-2ea030b7d602.png)

**Comment by trancexpress** [comment]
I tried downloading the M3 build from this link:

https://www.eclipse.org/downloads/download.php?file=/modeling/tmf/xtext/downloads/drops/2.18.0/S201905280716/tmf-xtext-Update-S201905280716.zip

> Eclipse downloads - file unavailable
> 
> The selected file is invalid, or it is no longer available for download.
> 
> This happens when the file is part of a nightly or development build. If so, please return to the project's home page and download a newer version. 

Also tried to navigate to the 28.05.2019 build from here:

https://www.eclipse.org/downloads/download.php?file=/modeling/tmf/xtext/downloads/drops/

The mirrors I've automatically been assigned to don't have any contents for this build, see e.g.:

http://eclipse.mirror.garr.it/eclipse/modeling/tmf/xtext/downloads/drops/2.18.0/S201905280716/

I have been able to download from the official M3 link though:

https://www.eclipse.org/downloads/download.php?file=/modeling/tmf/xtext/downloads/drops/2.18.0/S201905280716/tmf-xtext-Update-2.18.0.M3.zip

Not sure if the above is expected, in particular @cdietrich pinged me about the xtext 2.18 M3 build with a non-working link:

http://www.eclipse.org/modeling/download.php?file=/modeling/tmf/xtext/downloads/drops/2.18.0/S201905280716/tmf-xtext-Update-S201905280716.zip

**Comment by cdietrich** [comment]
@kthoms when do the file names change? i copied the name from here. https://www.eclipse.org/modeling/tmf/downloads/
