### ISSUE TITLE
Merges Website-Published -> Website Master

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#1476]
@kthoms usually we do Merges Website-Published -> Website Master
now we have a cbi jenkinsfile on published.
is there any harm merging that to website-master?

**Comment by kthoms** [comment]
No, this does not harm. On ci.eclipse.org we use Jenkinsfile, on ci-staging we use CBI.Jenkinsfile. The JIPP job has been removed. The new job is on ci-staging: [website-deploy](https://ci-staging.eclipse.org/xtext/job/releng/job/website-deploy/)
