### ISSUE TITLE
Xtext Nightly update site is broken

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#1478]
```
ERROR: org.eclipse.equinox.p2.director code=10053 Cannot complete the install because one or more required items could not be found.
  at org.eclipse.oomph.targlets.internal.core.TargletContainer.forceUpdate(TargletContainer.java:806)
  at org.eclipse.oomph.setup.targlets.impl.TargletTaskImpl$4.run(TargletTaskImpl.java:1167)
  at org.eclipse.oomph.util.pde.TargetPlatformUtil.runWithTargetPlatformService(TargetPlatformUtil.java:120)
  at org.eclipse.oomph.setup.targlets.impl.TargletTaskImpl.perform(TargletTaskImpl.java:1033)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3824)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.access$1(SetupTaskPerformer.java:3767)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil$1.run(SetupTaskPerformer.java:5125)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2295)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2322)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil.performNeededSetupTasks(SetupTaskPerformer.java:5119)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil.access$0(SetupTaskPerformer.java:5117)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:3758)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:3733)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:3626)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$9.run(ProgressPage.java:575)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$11$1.run(ProgressPage.java:701)
  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
  ERROR: org.eclipse.equinox.p2.director code=0 Software being installed: artificial_root 1.0.0.v1559206377001
  ERROR: org.eclipse.equinox.p2.director code=0 Missing requirement: artificial_root 1.0.0.v1559206377001 requires 'org.eclipse.equinox.p2.iu; org.eclipse.xtext.xbase.lib.feature.group 2.14.0' but it could not be found

```

??????????

**Comment by cdietrich** [comment]
have no idea which update site the feature was pulled from before

**Comment by cdietrich** [comment]
No repository found at http://download.eclipse.org/modeling/tmf/xtext/updates/nightly/head.
=> @kthoms is our nightly update site broken?

**Comment by cdietrich** [comment]
i wonder how this can happen. do we delete stuff and then decide not to redeploy cause we think it is already deployed?

```

publish.build.stage.2:
     [echo] Used launcher: /opt/public/common/buckminster-4.3/plugins/org.eclipse.equinox.launcher_1.3.0.v20130327-1440.jar
     [java] Picked up JAVA_TOOL_OPTIONS: -Xmx2G -Djava.io.tmpdir=/tmp/genie.xtext
     [java] Buildfile: /jobs/genie.xtext/common-deploy/workspace/build-result/promoter.ant
     [java] 
     [java] -check.property.file.location:
     [java] 
     [java] -load.properties.as.is:
     [java] 
     [java] -load.properties.with.prefix:
     [java] 
     [java] -load.properties:
     [java] 
     [java] publish.build.from.framework:
     [java] 
     [java] publish:
     [java] 
     [java] echo-status:
     [java]      [echo] Build N201905291758 already promoted, nothing to do...
     [java] BUILD SUCCESSFUL
     [java] 
     [java] BUILD SUCCESSFUL
     [java] Total time: 0 seconds
```

**Comment by cdietrich** [comment]
or is this done by https://ci.eclipse.org/xtext/job/xtext-snapshots
?

**Comment by cdietrich** [comment]
https://ci.eclipse.org/xtext/job/common-deploy/11384/console

**Comment by cdietrich** [comment]
still have no idea who delete the dir and how to recreate it

**Comment by cdietrich** [comment]
zips are bad too
https://www.eclipse.org/modeling/tmf/downloads/

**Comment by cdietrich** [comment]
Sebastian reverted the change to publishing so the nightly is deployed again

**Comment by cdietrich** [comment]
@kthoms @Hejado how shall we proceed.
are you working on a fix for xtext/publishing

**Comment by Hejado** [comment]
Didn't we already find/fix the issue for this on monday, @kthoms ?

**Comment by Hejado** [comment]
Not sure, if I'm missing something...

**Comment by kthoms** [comment]
We have a fix and it is available on the branch. We should merge that when we have the time to repair it for the case that something breaks. I think we should do this on tuesday. I don't have time today/tomorrow.

**Comment by cdietrich** [comment]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=548397

**Comment by cdietrich** [comment]
@kthoms still does not work. try to revert your changes again

**Comment by cdietrich** [comment]
the xtext-snapshots has also bogus messages in the log

```
Pack build-result/p2.repository/plugins/org.eclipse.xtext.ui.codetemplates.ui_2.19.0.v20190618-0537.jar

Could not read error output of: command '/opt/public/common/java/oracle/jdk1.8.0_192_x64/jre/bin/pack200'.
java.io.IOException: Stream Closed
	at java.io.FileOutputStream.writeBytes(Native Method)
	at java.io.FileOutputStream.write(FileOutputStream.java:326)
	at org.gradle.process.internal.streams.ExecOutputHandleRunner.run(ExecOutputHandleRunner.java:55)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by cdietrich** [comment]
deploy did not work cause it thinks its already deployed
this crap needs to be more stable

**Comment by cdietrich** [comment]
```
[java] echo-status:
     [java]      [echo] Build N201906180629 already promoted, nothing to do...
     [java] BUILD SUCCESSFUL
```

**Comment by cdietrich** [comment]
@kthoms

 [ERROR] Failed to resolve target definition /home/travis/build/itemis/xtext-reference-projects/greetings-tycho/2.19.0/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target: Failed to load p2 metadata repository from location https://download.eclipse.org/modeling/tmf/xtext/updates/nightly/: Unable to read repository at https://download.eclipse.org/modeling/tmf/xtext/updates/nightly. Artifact not found: https://download.eclipse.org/modeling/tmf/xtext/updates/nightly/head/content.xml.xz. -> [Help 1]

=> the update site is deleted again

**Comment by kthoms** [comment]
Will check today

**Comment by kthoms** [comment]
Download folder contains "workspace.zip"
![screenshot 132](https://user-images.githubusercontent.com/265597/60575492-ee88ed00-9d7b-11e9-808a-9aeb53edb28b.png)

The zip file should be N<TIMESTAMP>.zip
![screenshot 131](https://user-images.githubusercontent.com/265597/60575501-f183dd80-9d7b-11e9-9c5d-47087bf819bd.png)

**Comment by cdietrich** [comment]
still an issue

**Comment by cdietrich** [comment]
log contains

```
 Additional action for task ':zipXtextP2Repository': was implemented by the Java lambda 'io.typefox.publishing.EclipsePublishing$$Lambda$159/568787640'. Using Java lambdas is not supported, use an (anonymous) inner class instead.
```
this might be the issue

**Comment by kthoms** [comment]
We changed recently the Xtext/Xtend version in `publishing/buildSrc/build.gradle`. Has this something to do with that?

**Comment by kthoms** [comment]
Note: The issue might be resolved with the new deployment job on ci-staging.

**Comment by cdietrich** [comment]
i converted the lamdas to classes. lets see what happens

**Comment by cdietrich** [comment]
yes but the code is broken

```
task viech(type: Zip) {
	//archiveFileName = "my-distribution.zip"
    destinationDirectory = file("$buildDir/dist")
    from "lele"
    archiveFileName = provider {
    	"demo.zip"
    }
}
```

is needed with newer gradle

**Comment by cdietrich** [comment]
also the gradle api still seems 4.8

**Comment by kthoms** [comment]
First successful deployment with new job [sign-and-deploy](https://ci-staging.eclipse.org/xtext/job/releng/job/sign-and-deploy/):
```
director -l -r http://download.eclipse.org/modeling/tmf/xtext/updates/composite/latest/
201906242045.Default=1.0.0.8h3-cKYB3-_kE7Ag7QAY3AgMU
201906242045.mwe2lang=1.0.0.67U3cLSXLr7E7Ag7UEME7MQ
a.jre.javase=10.0.0
a.jre.javase=10.0.0
a.jre.javase=11.0.0
a.jre.javase=11.0.0
com.google.guava=27.1.0.v20190517-1946
com.google.guava=27.1.0.v20190517-1946
com.google.guava.source=27.1.0.v20190517-1946
com.google.guava.source=27.1.0.v20190517-1946
```

**Comment by cdietrich** [comment]
=> you use the workspace zip name and rename back?
i have pushed a fixed version for the broken api

**Comment by kthoms** [comment]
No, I ignore the zip that the publishing plugin creates and zip it with a shell command.

**Comment by kthoms** [comment]
=> the plugin still creates a zip with wrong name

**Comment by kthoms** [comment]
https://ci-staging.eclipse.org/xtext/job/releng/job/sign-and-deploy/lastSuccessfulBuild/artifact/build-result/downloads/

**Comment by cdietrich** [comment]
should the nightly deploy job be deactivated too?

**Comment by kthoms** [comment]
`nightly-deploy` it triggers the `common-deploy` and `simrel-tests` job nightly with the result from `xtext-snapshots`.

The new job combines that all together. It runs nightly for the `master` branch, builds the repository for upload and deploys it to the nightly site. It is also already prepared to do the same for milestone/release builds.

I have disabled `nightly-deploy` now.

**Comment by kthoms** [comment]
https://download.eclipse.org/modeling/tmf/xtext/updates/nightly/
contains the latest build result from the [sign-and-deploy](https://ci-staging.eclipse.org/xtext/job/releng/job/sign-and-deploy/) job.
This job is triggered nightly for branch master.

I consider this fixed now.
