### ISSUE TITLE
[releng] Delete org/eclipse/[xtext|xtend] from local repository

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext#1481]
This is a regression error that was introduced when the build steps were externalized into shell scripts. Before, the local repository was cleaned up for the paths `.m2/repository/org/eclipse/xtext` and `.m2/repository/org/eclipse/xtend`. This got removed, since it was not clear why these subpaths got cleaned up.

This step is actually important, since Maven will not overwrite release artifacts when they are already available in the local repository, which might get into there from previous builds. When the build for a milestone/release branch is retriggered (which might be necessary), these artifacts are not overwritten. They are collected in the Maven build step when building a p2 repository from Gradle results.

This means, for all builds that combine Gradle and Maven, the `.m2/repository` path must be cleaned up before running Maven.

**Comment by Hejado** [comment]
The clean up was actually only missing in core and extras. PRs are open.

**Comment by cdietrich** [comment]
fixed in 2.19. thx @Hejado

**Comment by kthoms** [comment]
CBI.Jenkinsfile in xtext-extras needs to be changed, maybe others. I'll check that.

**Comment by kthoms** [comment]
My mistake: For CBI we do not need to do this. Rather than that the local repository should go to /home/jenkins/.m2/repository there. This would be another issue.

**Comment by cdietrich** [comment]
is /home/jenkins/.m2/repository reused/shared or new foreach build

**Comment by Hejado** [comment]
No. Nothing is reused, so it should ultimately not matter, where to save the local repository. (At least not for Jenkins reasons)
