### ISSUE TITLE
Update Xtext Icon on the About Eclipse IDE Page

### ISSUE THREAD

**Issue by miklossy** [eclipse/xtext#1486]
Currently, the Xtext project is represented by a Modelling Icon on the `About Eclipse IDE` Page.
![screenshot](https://user-images.githubusercontent.com/20393472/59174987-f0cca280-8b53-11e9-8468-3bbdc5611ad5.png)

I suggest to use a more project specific symbol here (similar to the Eclipse GEF project icon).
CC: @hejado

**Comment by miklossy** [comment]
**Hint:** 
Currently the `modeling32.png` is used. The file is located under:
Xtext: https://github.com/eclipse/xtext-core/blob/master/org.eclipse.xtext/modeling32.png
Xtend: https://github.com/eclipse/xtext-xtend/blob/master/org.eclipse.xtend.ide/modeling32.png

The file is referenced from the `about.ini` files:
Xtext: https://github.com/eclipse/xtext-core/blob/master/org.eclipse.xtext/about.ini#L14
Xtend: https://github.com/eclipse/xtext-xtend/blob/master/org.eclipse.xtend.ide/about.ini#L11

**Comment by miklossy** [comment]
See also [Eclipse Feature Branding](https://ekkescorner.wordpress.com/2010/06/13/brand-your-feature-and-be-part-of-about-eclipse/)

**Comment by miklossy** [comment]
@cdietrich Should the [xtext-core/org.eclipse.xtext/build.gradle](https://github.com/eclipse/xtext-core/blob/master/org.eclipse.xtext/build.gradle#L29) file also be updated to include the `xtext32.png` file?

**Comment by cdietrich** [comment]
yes

**Comment by miklossy** [comment]
I created the PR https://github.com/eclipse/xtext-core/pull/1247 to include the `xtext32.png` file into the `build.gradle` file.

**Comment by miklossy** [comment]
Please consider that after clicking on the `Eclipse Xtext` symbol, there are two features listed. The icon should be upadted on all the 3 places.
![screencast](https://user-images.githubusercontent.com/20393472/65683318-41adcb80-e05d-11e9-970f-9fc6b2e759d8.gif)

**Comment by cdietrich** [comment]
Have no idea how branding works 
Did not find docs

**Comment by miklossy** [comment]
@cdietrich Have you also studied this one? https://github.com/eclipse/xtext/issues/1486#issuecomment-501302271

**Comment by cdietrich** [comment]
Does that mean the name in the feature is useless ?

**Comment by cdietrich** [comment]
Of course all other features miss the branding plugin
But I eG don’t know if the branding plugin needs to be part of the features

**Comment by cdietrich** [comment]
@miklossy updating from the latest nightly zip (update site may take a bit of time) it looks good

**Comment by miklossy** [comment]
Could you please attach a screenshot?

**Comment by cdietrich** [comment]
![Bildschirmfoto vom 2019-09-26 14-11-19](https://user-images.githubusercontent.com/238736/65686966-93f3ea00-e067-11e9-8591-613506cd2635.png)

**Comment by miklossy** [comment]
Looks really good. I will also test it as soon as the update site is available. I will leave the ticket open till that.

**Comment by cdietrich** [comment]
@miklossy it looks like the image names in feature.xml are not needed.
i also cannot find them in the dtd
=> we should remove them

**Comment by miklossy** [comment]
I analysed the [Eclipse GEF code base](https://github.com/eclipse/gef) and there I also did not find the image names in the `feature.xml` files. So I also think that can be removed. I created the corresponding PR.

**Comment by miklossy** [comment]
I have just updated from the latest update site and can confirm that the icons are shown properly:
![screenshot](https://user-images.githubusercontent.com/20393472/65693892-4d0cf100-e075-11e9-9238-4fe8309b24fa.png)
@cdietrich should I remove the `modeling32.png` files that are not needed any more?

**Comment by cdietrich** [comment]
i dont know if they are needed anywhere else. if you remove them also remove them from build.properties and build.gradle

**Comment by cdietrich** [comment]
e.g. i dont know what the wizards do

**Comment by miklossy** [comment]
Till now I did not see the `modeling32.png` image on the Xtext/Xtend wizard pages. But I will double check that.

**Comment by miklossy** [comment]
@cdietrich Indeed I found some places in the wizard where the `modeling32.png` is referenced:
https://github.com/eclipse/xtext-core/blob/master/org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/IdeProjectDescriptor.xtend#L247
https://github.com/eclipse/xtext-core/blob/master/org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/IdeProjectDescriptor.xtend#L340

**Comment by cdietrich** [comment]
the question is: is the icon acutally created by the wizard

**Comment by miklossy** [comment]
The `modeling32.png` file occurs in the newly created Xtext projects only when the option `Build Language Server` is selected. In that cases no `modeling32.png` file is created, it occurs only in the `exclusion` section of the `pom.xml` / `build.gradle` files.

So I think it is safe to remove the `modeling32.png` file and its occurrences from the `pom.xml` / `build.gradle` files created by the wizard.

@kthoms @ArneDeutsch What do you think about this?

**Comment by cdietrich** [comment]
i assume it was never created (might need testing with a version old version before the repo split e.g. 2.9.1 or so.

**Comment by cdietrich** [comment]
it might even be that this was some bad c&p from "somewhere"

**Comment by miklossy** [comment]
I have just checked with `Xtext 2.9.1` and there no `modeling32.png` file is created by the wizard. So it should be save to remove it.

**Comment by miklossy** [comment]
Fixed in 2.20

**Comment by Bananeweizen** [comment]
Is it intended to have a white background instead of a transparent one? The Xtext icon now looks out of place in my SDK, compared to the other ones.
![grafik](https://user-images.githubusercontent.com/406876/66703710-92881a00-ed15-11e9-98a4-027d1ee70697.png)

**Comment by cdietrich** [comment]
In doubt nothing is intended

**Comment by cdietrich** [comment]
did some convertion with
`convert -fuzz 2%  xtend32.png -transparent white transparent.png`
lets see how this works out

**Comment by miklossy** [comment]
I will also test it as soon as the PRs are merged and give feedback.

**Comment by cdietrich** [comment]
@Bananeweizen @miklossy  please update and retest
here is how it looks on my machine
![Bildschirmfoto_2019-10-13_09-31-27](https://user-images.githubusercontent.com/238736/66712387-4c29ce00-ed9c-11e9-818f-d0a18fa28c48.png)

**Comment by miklossy** [comment]
I have just verified and it also looks fine on my machine:
![image](https://user-images.githubusercontent.com/20393472/66712430-c35f6200-ed9c-11e9-8436-0c13bdd8d9c9.png)

**Comment by cdietrich** [comment]
Fixed
