### ISSUE TITLE
Update to Gradle Wrapper 5.5

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#1489]
We should update to Gradle Wrapper 5.5 once its out.
https://github.com/eclipse/xtext/blob/master/dev-doc/GradleWrapperVersionBump.md

**Comment by cdietrich** [comment]
[ ] CQ https://dev.eclipse.org/ipzilla/show_bug.cgi?id=20314
[ ] Builds
[ ] Wizard
[ ] Ref Projects

**Comment by kthoms** [comment]
Anything left?

**Comment by cdietrich** [comment]
Fixed in 2.19
