### ISSUE TITLE
Migrate xtext-xtend-api-diff to JIRO

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext#1501]
The job `xtext-xtend-api-diff` is not working on the JIRO build server.

The first problem is that the job makes use of the jar `/shared/modeling/tmf/xtext/japicmp-ext.jar`. This must have been deployed a while ago. 

Is this a variant of the [japicmp](https://siom79.github.io/japicmp/) tool? If so, what has been extended (indicated by `-ext` suffix)?

**Comment by cdietrich** [comment]
can you provide me with the jar.
maybe ext means "not-base"

**Comment by cdietrich** [comment]
i also found this https://github.com/dhuebner/xtext-apidiff
which has an ant file creating the -ext jar

**Comment by cdietrich** [comment]
maybe we should setup an new project and a gradle based build that creates the custom uber jar

**Comment by cdietrich** [comment]
pushed wip
to
https://github.com/xtext/xtext-apidiff/tree/cd_gradle

moderinizing might be more work, a lot changed

**Comment by cdietrich** [comment]
we might also have a look at complete solutions like https://github.com/melix/japicmp-gradle-plugin

**Comment by cdietrich** [comment]
@kthoms added a bash script to my branch that basically should do "everything"

**Comment by cdietrich** [comment]
https://ci-staging.eclipse.org/xtext/job/releng/job/xtext-xtend-api-diff-2/

**Comment by cdietrich** [comment]
TODO: merge PR
TODO: rename job / delete old one

**Comment by cdietrich** [comment]
will close for now. if there is a possibility for the html publisher we will adapt the job
