### ISSUE TITLE
Drop old milestone releases

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#1502]
Should we drop old  milestone releases e.g 2.17.Mx 2.18.Mx from eclipse downloads
https://download.eclipse.org/oomph/archive/eclipse/modeling/tmf/xtext/downloads/drops/2.18.0/index.html ?
/edit note: typo

**Comment by cdietrich** [comment]
cc @kthoms  @Hejado

**Comment by szarnekow** [comment]
Yes, I think we should.

**Comment by cdietrich** [comment]
any news @kthoms @Hejado

**Comment by cdietrich** [comment]
move to 2.22

**Comment by Hejado** [comment]
Just to be safe (again):

I will now remove/delete **all** of the following milestones update-sites:

/home/data/httpd/download.eclipse.org/modeling/tmf/xtext/updates/milestones/S201907120222
/home/data/httpd/download.eclipse.org/modeling/tmf/xtext/updates/milestones/S201908050915
/home/data/httpd/download.eclipse.org/modeling/tmf/xtext/updates/milestones/S201908260548
/home/data/httpd/download.eclipse.org/modeling/tmf/xtext/updates/milestones/S201910140836
/home/data/httpd/download.eclipse.org/modeling/tmf/xtext/updates/milestones/S201911042013
/home/data/httpd/download.eclipse.org/modeling/tmf/xtext/updates/milestones/S201911251623
/home/data/httpd/download.eclipse.org/modeling/tmf/xtext/updates/milestones/head/S201610201537
/home/data/httpd/download.eclipse.org/modeling/tmf/xtext/updates/milestones/head/S201610211140
/home/data/httpd/download.eclipse.org/modeling/tmf/xtext/updates/milestones/head/S201612190841
/home/data/httpd/download.eclipse.org/modeling/tmf/xtext/updates/milestones/head/S201612190948
/home/data/httpd/download.eclipse.org/modeling/tmf/xtext/updates/milestones/head/S201701180206
/home/data/httpd/download.eclipse.org/modeling/tmf/xtext/updates/milestones/head/S201701270250
/home/data/httpd/download.eclipse.org/modeling/tmf/xtext/updates/milestones/head/S201704271113
/home/data/httpd/download.eclipse.org/modeling/tmf/xtext/updates/milestones/head/S201709191305
/home/data/httpd/download.eclipse.org/modeling/tmf/xtext/updates/milestones/head/S201710131050
/home/data/httpd/download.eclipse.org/modeling/tmf/xtext/updates/milestones/head/S201804242303
/home/data/httpd/download.eclipse.org/modeling/tmf/xtext/updates/milestones/head/S201810150206
/home/data/httpd/download.eclipse.org/modeling/tmf/xtext/updates/milestones/head/S201811260210
/home/data/httpd/download.eclipse.org/modeling/tmf/xtext/updates/milestones/head/S201901151856
/home/data/httpd/download.eclipse.org/modeling/tmf/xtext/updates/milestones/head/S201902051759
/home/data/httpd/download.eclipse.org/modeling/tmf/xtext/updates/milestones/head/S201902261756
/home/data/httpd/download.eclipse.org/modeling/tmf/xtext/updates/milestones/head/S201904151903
/home/data/httpd/download.eclipse.org/modeling/tmf/xtext/updates/milestones/head/S201905061516
/home/data/httpd/download.eclipse.org/modeling/tmf/xtext/updates/milestones/head/S201905280716

In Addition to that, I will remove/delete **all** of the following milestone drop locations:

/home/data/httpd/download.eclipse.org/modeling/tmf/xtext/downloads/drops/2.17.0/S201901151856
/home/data/httpd/download.eclipse.org/modeling/tmf/xtext/downloads/drops/2.17.0/S201902051759
/home/data/httpd/download.eclipse.org/modeling/tmf/xtext/downloads/drops/2.17.0/S201902261756
/home/data/httpd/download.eclipse.org/modeling/tmf/xtext/downloads/drops/2.18.0/S201904151903
/home/data/httpd/download.eclipse.org/modeling/tmf/xtext/downloads/drops/2.18.0/S201905061516
/home/data/httpd/download.eclipse.org/modeling/tmf/xtext/downloads/drops/2.18.0/S201905280716
/home/data/httpd/download.eclipse.org/modeling/tmf/xtext/downloads/drops/2.19.0/S201907120222
/home/data/httpd/download.eclipse.org/modeling/tmf/xtext/downloads/drops/2.19.0/S201908050915
/home/data/httpd/download.eclipse.org/modeling/tmf/xtext/downloads/drops/2.19.0/S201908260548
/home/data/httpd/download.eclipse.org/modeling/tmf/xtext/downloads/drops/2.20.0/S201910140836
/home/data/httpd/download.eclipse.org/modeling/tmf/xtext/downloads/drops/2.20.0/S201911042013
/home/data/httpd/download.eclipse.org/modeling/tmf/xtext/downloads/drops/2.20.0/S201911251623

The following milestone sites/drops belong to the current release - I will keep them for now:

/home/data/httpd/download.eclipse.org/modeling/tmf/xtext/updates/milestones/S202001131426
/home/data/httpd/download.eclipse.org/modeling/tmf/xtext/updates/milestones/S202002031045
/home/data/httpd/download.eclipse.org/modeling/tmf/xtext/updates/milestones/S202002241333
/home/data/httpd/download.eclipse.org/modeling/tmf/xtext/downloads/drops/2.21.0/S202001131426
/home/data/httpd/download.eclipse.org/modeling/tmf/xtext/downloads/drops/2.21.0/S202002031045
/home/data/httpd/download.eclipse.org/modeling/tmf/xtext/downloads/drops/2.21.0/S202002241333

If this is correct, confirm please and I will start deleting.

**Comment by cdietrich** [comment]
:+1:

**Comment by cdietrich** [comment]
@kthoms should we keep m3? should we add the release to the milestones site?

**Comment by Hejado** [comment]
2.21.0.M[1-3] are not part of the "delete" list for now.

I will continue to delete the listed milestones after the release process. I will not get an agent anyway...

I don't want to manually delete milestones after every release, so I propose two options:

1) Jenkins deletes X.Y.Z.M[1-3] after every release
2) Jenkins deletes X.Y-1.Z.M[1-3] after every release

WDYT?

**Comment by kthoms** [comment]
I would opt for option 2. If someone is using the milestone update site, they would be surprised if it is suddenly empty after a release. It does not harm to keep the latest milestones for 3 months.

**Comment by Hejado** [comment]
Another way of looking at this: Jenkins removes existing milestones when deploying the next M1. Then all consumers have the whole quiet period to make the switch and the milestone-composite would never be empty.

**Comment by Hejado** [comment]
I removed above mentioned update-sites in this job:
https://ci.eclipse.org/xtext/job/releng/job/manual-one-off-commands/3/consoleFull

updates/milestones shrinked from 1.3G to 187M.

This left /updates/milestones/maintenance and /updates/milestones/head empty, I removed those in https://ci.eclipse.org/xtext/job/releng/job/manual-one-off-commands/4/consoleFull

Also, I removed above mentioned milestones from the drop location here: https://ci.eclipse.org/xtext/job/releng/job/manual-one-off-commands/5/console

downloads/drops shrinked from 3.7G to 3.1G

**Comment by Hejado** [comment]
All milestones belonging to the current/last release (2.21) are still available.

As mentioned, I'm in favor of clearing old milestones on the M1 release build. Should we discuss this here or close 1502 and create a new issue?

**Comment by cdietrich** [comment]
no we can discuss this here. yes on m1 old milestones should be dropped. @kthoms what do you think?

**Comment by cdietrich** [comment]
ping @kthoms @Hejado

**Comment by kthoms** [comment]
OK, let's do that.

**Comment by cdietrich** [comment]
move to 2.24

**Comment by Hejado** [comment]
Necessary changes are now merged into the Jenkinsfile. Will test next week

**Comment by Hejado** [comment]
Test was successful.
