### ISSUE TITLE
umbrella-master should be built daily on ci-staging

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#1503]
umbrella-master should be built daily on ci-staging
(ideally before the nightly)

**Comment by Hejado** [comment]
Adding the trigger is trivial. Maybe we could let umbrella-master trigger the nightly deploy in this case? This would make sure they run in the right order without overlapping due to agent shortage.

**Comment by kthoms** [comment]
The deploy job should run just once a day. We should not trigger it with each build of umbrella.

**Comment by Hejado** [comment]
Ok, good point

**Comment by cdietrich** [comment]
@Hejado could you please have a look at this issue?

**Comment by Hejado** [comment]
Yes...

Turns out, the Jenkinsfile already defines a cron trigger, but it does not differentiate between branches.

Also, it does not work at all, so ...  :-)

Will investigate

**Comment by Hejado** [comment]
I don't know, why the cron trigger is ignored on JIRO - cannot reproduce this. Locally, the trigger is configured correctly and everything is working fine.

My guess is, that the GitHub SCM Plugin overrides triggers completely, while adding its own trigger:

![Bildschirmfoto von 2019-07-29 11-37-09](https://user-images.githubusercontent.com/4725345/62038066-556fb980-b1f5-11e9-8ef4-49e15b5274b8.png)

**Comment by Hejado** [comment]
The trigger was indeed overridden, but not by the Github SCM plugin, but by us:

```groovy
[...]
script {
  properties([
    [$class: 'GithubProjectProperty', displayName: '', projectUrlStr: 'https://github.com/eclipse/xtext-core/'],
    [$class: 'RebuildSettings', autoRebuild: false, rebuildDisabled: false],
    pipelineTriggers([githubPush()])
[...]
```
Moving the githubPush() trigger to the trigger section fixes the problem.

This makes me wonder, how many other declarative settings we might find in our pipelines that are overridden by an outdated scripted counter part...

**Comment by Hejado** [comment]
Done.

**Comment by cdietrich** [comment]
nice. thx @Hejado
