### ISSUE TITLE
Remove / Disable Jobs on TF Jenkins

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#1506]
The following Jobs can be removed / disabled on TF Jenkins

- xtext-lib
- xtext-core
- xtext-extras
- xtext-maven
- xtext-eclipse
- xtext-xtend
- xtext-web
- xtext-idea
- xtext-umbrella

The following jobs should be kept
- MWE

**Comment by meysholdt** [comment]
ok, I'm glad the Eclipse infrastructure caught up. I'll disable them, in case somebody downloads still from the TF Jenkins and delete them later.

**Comment by cdietrich** [comment]
ok. but i have doubts anybody will try to download, since the jobs are red for a while now

**Comment by cdietrich** [comment]
ping

**Comment by dhuebner** [comment]
@meysholdt
I will look into it

**Comment by dhuebner** [comment]
@meysholdt 
What about this guys here? 

xtend-bootstrap
xtext-eclipse-params 
xtext-jflex

**Comment by cdietrich** [comment]
xtext-jflex might still be in use if somebody changes something at the fragment.
the xtext-eclipse-params is my personal job an no longer needed.

the xtend-bootstrap: you can remove it, but it would be nice if you provide a copy of the job config in case we need to recreate it on eclipse server

**Comment by dhuebner** [comment]
@cdietrich Here is a copy of xtend-bootstrap config.xml: 
[config.txt](https://github.com/eclipse/xtext/files/3440808/config.txt)

**Comment by cdietrich** [comment]
thx @dhuebner
