### ISSUE TITLE
Provide lsp4j build on Xtext JIRO instance

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext#1507]
Xtext needs to be able to build against the latest snapshots from LSP4J. Unfortunately the job [lsp4j-snapshots](https://ci.eclipse.org/lsp4j/job/lsp4j-snapshots/) seems disfunctional (has not been run since 8 months). That's why Xtext provided its own lsp4j build on JIPP.

For the upcoming migration to JIRO we therefore need an LSP4J build on JIRO, too. It is sufficient to build master only.

All references to https://ci.eclipse.org/xtext/job/lsp4j/job/master have to be changed to the new URL. This affects `upstream-repositories.gradle`, `pom.xml` files across all repos.

**Comment by cdietrich** [comment]
see https://github.com/eclipse/lsp4j/issues/331 too

**Comment by cdietrich** [comment]
maybe we can also use sonatype and filter

```
https://docs.gradle.org/current/userguide/declaring_repositories.html
```

**Comment by cdietrich** [comment]
without tests jobs seems to run. but i still dont have any idea why the job works in a local container but not on k8s.

**Comment by cdietrich** [comment]
@kthoms @Hejado i will provide a pr that will consume lsp4j snapshots from sonatype.

**Comment by cdietrich** [comment]
TODO: 
- remove the https://ci-staging.eclipse.org/xtext/job/lsp4J job
- rename https://ci-staging.eclipse.org/xtext/job/lsp4j-master/ to https://ci-staging.eclipse.org/xtext/job/lsp4j
- adapt the gradle files and poms to use Jenkins_URLs analogous to other places

**Comment by Hejado** [comment]
:heavy_check_mark: removed old job
:heavy_check_mark: renamed new job
:heavy_check_mark: opened 5 PRs

**Comment by Hejado** [comment]
Can we close this or did I miss something?

**Comment by cdietrich** [comment]
We will see
