### ISSUE TITLE
[Jenkins] Trigger downstream builds

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext#1508]
Instead of having upstream triggers, which AFAIK can't be made conditional, pipelines could invoke downstream jobs. For multibranch pipelines a downstream pipeline should be triggered when a branch with the same name exists.

This could be handy for typical situations where a branch with the same name is created across multiple repositories.

The following command retrieves HTTP status code 200 if a job exists:
```curl -s -L -o /dev/null -I -w '%{http_code}' JOB_URL```

This has been prototyped for xtext-lib here:
https://ci-staging.eclipse.org/xtext/job/xtext-lib/job/kth_issue1384_downstream/7/console

```
[Pipeline] sh
23:44:39  + curl -L -s -o /dev/null -I -w '%{http_code}' https://ci-staging.eclipse.org/xtext//job/xtext-core/job/kth_issue1384_downstream
[Pipeline] build (Building xtext-core » kth_issue1384_downstream)
23:44:44  Scheduling project: xtext-core » kth_issue1384_downstream
```

**Comment by kthoms** [comment]
@Hejado @cdietrich WDYT? Shall we enable downstream triggers? Except for master, of course. Maybe guarded by parameter (default on or off)?

**Comment by cdietrich** [comment]
i am not sure if this will lead to duplicate and triple builds if i commit something to
core, extras and web for example. will web then be built 3 times?

**Comment by kthoms** [comment]
Yes, it would trigger another build. Good point.
We could maybe use the same logic to detect an upstream branch build running and abort the downstream before it does something. Does this makes sense?

**Comment by Hejado** [comment]
Not really. A build has to run (read: have an active executor) to be able to cancel/abort other builds. A build cannot cancel other builds while waiting in the queue.

**Comment by kthoms** [comment]
How about this scenario:
- xtext-lib is pushed and gets an executor
- xtext-core is pushed and gets an executor
- xtext-extras is pushed, gets no executor and is queued
- xtext-lib finishes and triggers build 2 of xtext-core, which gets no executor and is enqueued after xtext-extras
- xtext-core build 1 finishes and triggers xtext-extras. Does it trigger build 2, or is build 1 taken?

**Comment by kthoms** [comment]
As discussed with @Hejado we should guard the downstream trigger with a job parameter `TRIGGER_DOWNSTREAM_JOBS`. The default should consider the branch, i.e. for milestone/release branches default to true, while for all other cases false. 
For the case that someone wants to trigger downstream builds for a certain branch, a rebuild should be scheduled with explicit setting to true. Ideally, the job propagates the param value to downstream builds.

**Comment by kthoms** [comment]
This would also make the modifications to add upstream triggers by the `release-prepare-branches` job obsolete.

**Comment by kthoms** [comment]
Current state looks promising:

- xtext-lib does not trigger xtext-core by default: https://ci-staging.eclipse.org/xtext/job/xtext-lib/job/kt_issue1508_downstream/3/console
![screenshot 139](https://user-images.githubusercontent.com/265597/60952299-4f27a500-a2fb-11e9-8603-047fec583522.png)

- when xtext-lib runs with flag TRIGGER_DOWNSTREAM_BUILD set, then it triggers downstream build of xtext-core
![screenshot 140](https://user-images.githubusercontent.com/265597/60952380-71212780-a2fb-11e9-9c4e-a8a4ec5673e6.png)

![screenshot 138](https://user-images.githubusercontent.com/265597/60952119-ee986800-a2fa-11e9-9b78-9cce42701902.png)

- the TRIGGER_DOWNSTREAM_BUILD value is propagated to xtext-core, so this build will trigger downstream build to xtext-extras and propagate the flag further down the job chain.

![screenshot 137](https://user-images.githubusercontent.com/265597/60952122-f0622b80-a2fa-11e9-84aa-37cd509e45bd.png)

**Comment by kthoms** [comment]
The changes for downstream triggers is not needed for leaf projects, i.e.
- xtext-maven
- xtext-web
- xtext-umbrella

**Comment by Hejado** [comment]
> 
    xtext-lib is pushed and gets an executor
    xtext-core is pushed and gets an executor
    xtext-extras is pushed, gets no executor and is queued
    xtext-lib finishes and triggers build 2 of xtext-core, which gets no executor and is enqueued after xtext-extras
    xtext-core build 1 finishes and triggers xtext-extras. Does it trigger build 2, or is build 1 taken?

Every trigger triggers a new build. Running builds do not count.

**Comment by kthoms** [comment]
Created branch `2.19.0.M1` in [xtext-build-tools](https://github.com/itemis/xtext-build-tools/tree/2.19.0.M1). Updates to Jenkinsfiles are removed there, as we do not need to add upstream triggers anymore.
Job [release-prepare-branches](https://ci-staging.eclipse.org/xtext/job/releng/job/release-prepare-branches) is configured to use this branch for the M1 build.

**Comment by kthoms** [comment]
Unfortunately this caused a regression:
https://ci-staging.eclipse.org/xtext/job/xtext-lib/job/master/75/console
```
Error when executing success post condition:
groovy.lang.MissingPropertyException: No such property: TRIGGER_DOWNSTREAM_BUILD for class: groovy.lang.Binding
	at groovy.lang.Binding.getVariable(Binding.java:63)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onGetProperty(SandboxInterceptor.java:270)
```

I wonder why this did not happen on the change branches. This needs a quick fix on master.

**Comment by kthoms** [comment]
Looks good now. Tested with creation of "release" `2.19.0.Beta`. Jobs are triggering downstream for that release branch, while not doing this on master.
