### ISSUE TITLE
Replace trigger-nightly-build-against-latest-target with actual triggers in those jobs

### ISSUE THREAD

**Issue by Hejado** [eclipse/xtext#1513]
We should replace the trigger-nightly-build-against-latest-target job with actual triggers in the jobs this job triggers. :blush: 

This makes it much easier to understand what's happening without looking into 7 different build logs.

**Comment by cdietrich** [comment]
:+1:

**Comment by Hejado** [comment]
Problem: xtext-eclipse & xtext-xtend currently use 'oxygen' as default parameter value, while the trigger jobs want to use 'latest'. I assume we don't want to change that.

Possible solution: https://plugins.jenkins.io/parameterized-scheduler
This might give us the means to add a cron trigger with non-default parameters.

Will evaluate locally, because it looks like the plugin is not installed on JIRO and I don't want to ask for untested plugins.

**Comment by Hejado** [comment]
Looks like this works as expected.

![Bildschirmfoto von 2019-07-29 14-59-52](https://user-images.githubusercontent.com/4725345/62050744-2d428380-b212-11e9-80b2-f2b7d7a4dcf3.png)
![Bildschirmfoto von 2019-07-29 15-04-06](https://user-images.githubusercontent.com/4725345/62050746-2ddb1a00-b212-11e9-8765-c2af3fa69304.png)

I think, we could use this plugin for replacing trigger-nightly-build-against-latest-target, and also for other stuff like a nightly build with Java 11 for example.

@cdietrich  @kthoms WDYT?

**Comment by Hejado** [comment]
I opened a bug for the installation of this plugin: https://bugs.eclipse.org/bugs/show_bug.cgi?id=549633

**Comment by Hejado** [comment]
Plugin is installed.
I've been playing around with this plugin in the meantime:
```groovy
pipeline {
  agent any

  parameters {
    choice(name: 'target_platform', choices: ['oxygen', 'photon', 'r201812', 'r201809', 'r201903', 'r201906', 'latest'], description: 'Which Target Platform should be used?')
  }

  triggers {
    parameterizedCron(env.BRANCH_NAME == 'master' ? '''
      0 H/5 * * * %target_platform=latest
      0 H/2 * * * %target_platform=photon
    ''' : '')
  }

  stages {
    stage('Checkout') {
      steps {
        echo "${target_platform}"
        script { currentBuild.description = "${target_platform}" }
      }
    }
  }
}
```

This would configure the trigger only for the master branch, yet new branches would fail for the first run anyway, because parameterizedCron() needs parameters to exist and they don't exist until after the first run.

**Comment by Hejado** [comment]
> new branches would fail for the first run anyway

Nevermind, nothing fails, everything works... Will push branches shortly.

**Comment by cdietrich** [comment]
@Hejado can you disable the old job?

**Comment by Hejado** [comment]
> @Hejado can you disable/remove the old job?

Already done.

Old trigger job is now deactivated and moved into archive:
https://ci.eclipse.org/xtext/job/archived/job/trigger-nightly-build-against-latest-target/

Triggered jobs now trigger themselves:
https://ci.eclipse.org/xtext/job/xtext-eclipse/job/master/
https://ci.eclipse.org/xtext/job/xtext-xtend/job/master/
