### ISSUE TITLE
Some Slack Notifications dont get sent on JIRO

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#1515]
https://ci-staging.eclipse.org/xtext/job/xtext-eclipse/job/cd_platform_bump/3/console
there was no notification for that build. is there still something wrong with the CBI.Jenkinsfile?

**Comment by Hejado** [comment]
The slack notification step is located in the post/changed block. It only gets executed when the current build result differs from the last one. Build #3 did not qualify, #4 did notify though.

**Comment by cdietrich** [comment]
yes but i wonder if we should notify with "still failing" in this case. @szarnekow what do you think?

**Comment by szarnekow** [comment]
If possible, I’d prefer a notification for all broken builds and when a build turns green again. Also for the first build of newly created branches.

**Comment by Hejado** [comment]
Entirely possible! Would we define 'unstable' as failing/broken in this case? (I would.)

**Comment by szarnekow** [comment]
> Entirely possible! Would we define 'unstable' as failing/broken in this case? (I would.)

Exactly.

**Comment by Hejado** [comment]
To clarify: We basically always want a notification, except for "still-green" builds?

**Comment by cdietrich** [comment]
Exactly

**Comment by Hejado** [comment]
Will open PRs as soon as at least one pipeline clears (all PRs will have the same code anyway).

I moved the slack notification from the `changed` post stage to the `cleanup` post stage, because it will
 
> the steps in this post condition after every other post condition has been evaluated, regardless of the Pipeline or stage’s status.

(https://jenkins.io/doc/book/pipeline/syntax/#post-conditions)

**Comment by cdietrich** [comment]
https://ci-staging.eclipse.org/xtext/job/xtext-umbrella/job/master/49/ was reported as still failing

@szarnekow @Hejado do we want to distinguish "still failing" and "failing"

**Comment by szarnekow** [comment]
Good question. Is it possible to have failing (n times)?

**Comment by Hejado** [comment]
Oh, I see it now. Kind of obvious :see_no_evil: 

I'll fix that.

> Is it possible to have failing (n times)?

Not unless we can address the `previousbuild` property of the `currentbuild.previousbuild` property. And the `previousbuild` property of that one, and... so on. :blush: 

> do we want to distinguish "still failing" and "failing"

Maybe use "failing" as a base, with an optional "first time failing"?

**Comment by Hejado** [comment]
Maybe like this:

```        if (lastResult == 'NONE') {
          curResult = "NEW: ${curResult}"
        } else if (curResult == 'SUCCESS' && lastResult == 'SUCCESS') {
          sendNotification = false
        } else if (curResult == 'SUCCESS' && lastResult != 'SUCCESS') {
          curResult = 'FIXED'
        } else if (curResult == 'UNSTABLE' && lastResult == 'SUCCESS') {
          curResult = 'FIRST TIME UNSTABLE'
          color = '#FFFF00'
        } else if (curResult == 'FAILURE' && lastResult == 'SUCCESS') {
          curResult = 'FIRST TIME FAILING'
          color = '#FF0000'
        } else if (curResult == 'UNSTABLE') {
          curResult = 'UNSTABLE'
          color = '#FFFF00'
        } else { // FAILURE, ABORTED, NOT_BUILD
          curResult = 'FAILING'
          color = '#FF0000'
        }```

or - simplier - like this:
```        if (lastResult == 'NONE') {
          curResult = "NEW: ${curResult}"
        } else if (curResult == 'SUCCESS' && lastResult == 'SUCCESS') {
          sendNotification = false
        } else {
          curResult = "${lastResult} => ${curResult}"
        }```
