### ISSUE TITLE
[Releng] This plug-in does not export all of its packages

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#1518]
we currently have a lot of warnings with message "This plug-in does not export all of its packages" all over our xtext workspace. how shall we deal with that

- change severity
- export all packages eclipse complains about as `x-internal`

what about the affect wizard and fragments for new projects

**Comment by cdietrich** [comment]
@szarnekow  @kthoms what do you think?

**Comment by cdietrich** [comment]
created https://bugs.eclipse.org/bugs/show_bug.cgi?id=549329 for better quickfixes on PDE side

**Comment by miklossy** [comment]
I have just tried out the `Add missing packages` quickfix and it enters the `x-internal:=true` directive for all packages having `internal` in their name.

**Comment by cdietrich** [comment]
hmm of course we dont stick to that pattern at many places

**Comment by szarnekow** [comment]
I'm in favor of exporting the packages as x-internal, independently from their name.

**Comment by miklossy** [comment]
See also https://bugs.eclipse.org/bugs/show_bug.cgi?id=544977

> So exporting all packages and declaring internal packages "x-internal" seems dangerous and counterintuitive to me. I vote for the problem severity being changed back from warning to ignore.

**Comment by miklossy** [comment]
For the `New Xtext Project` and for the `Xtext Examples` I would prefer to export all packages that are not exported yet as `x-internal`, for the Xtext Development Environment I would prefer change the severity of the issue to ignore. The severity of the issue can be configured under:
![screenshot](https://user-images.githubusercontent.com/20393472/65938773-3b846a00-e424-11e9-9e60-9e377ceab68f.png)

**Comment by szarnekow** [comment]
I'm still at 
> exporting the packages as x-internal, independently from their name.

Having a custom setting for our projects does not make too much sense to me.

**Comment by cdietrich** [comment]
there are still other places e.g. in extras where this is not done.
@szarnekow do you still have the prs for these somewhere in the queue

**Comment by szarnekow** [comment]
I don't have any warnings left in my WS. Let's see.

**Comment by cdietrich** [comment]
looks better now. 
but there is some complaints about missing build.properties files now
am not sure if we can "steal" them from arnes branch

**Comment by szarnekow** [comment]
Fixed

**Comment by szarnekow** [comment]
Reopened per @cdietrich comment

**Comment by cdietrich** [comment]
@szarnekow is this done now with the build.properties fixes?

**Comment by cdietrich** [comment]
ping @szarnekow

**Comment by szarnekow** [comment]
Yes
