### ISSUE TITLE
Move xtext-build-tools to xtext org

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#1522]
Move xtext-build-tools to xtext org
- there are usages from https://github.com/itemis/xtext-build-tools
- there might even be usages from https://github.com/pngowda/xtext-build-tools

cc @pngowda

**Comment by cdietrich** [comment]
also consolidate branches for releases and checkversions

**Comment by cdietrich** [comment]
@kthoms @Hejado could have a look at this

**Comment by cdietrich** [comment]
ping

**Comment by cdietrich** [comment]
ping @kthoms @Hejado

**Comment by cdietrich** [comment]
@kthoms @Hejado any news on this issue?

**Comment by cdietrich** [comment]
ping

**Comment by cdietrich** [comment]
move to 2.21

**Comment by kthoms** [comment]
I'm planning to get rid of this and move the job to xtext-umbrella/releng

**Comment by cdietrich** [comment]
would be ok if we can manage to sort the files in an way that it is clear which of the 20 groovy files belongs to where

**Comment by cdietrich** [comment]
ping @kthoms  @Hejado

**Comment by cdietrich** [comment]
move to 2.22

ping @kthoms @Hejado

**Comment by cdietrich** [comment]
move to 2.24
ping @kthoms @Hejado

**Comment by cdietrich** [comment]
move to 2.25
ping @kthoms @NicoPrediger

**Comment by cdietrich** [comment]
@kthoms @NicoPrediger this is the task i was talking about today.
which route should we go:

- simply move to xtext org and update references (can we somehow find out where this is used in non checked in jobs e.g.  checkversions
- move to umbrella along with https://github.com/eclipse/xtext/issues/1875

**Comment by cdietrich** [comment]
move to 2.26

**Comment by kthoms** [comment]
Moved release-prepare-branches job to umbrella via https://github.com/eclipse/xtext-umbrella/pull/252

**Comment by kthoms** [comment]
Affected jobs:
- https://ci.eclipse.org/xtext/job/releng/job/check-versions/

**Comment by kthoms** [comment]
The jobs and functions we needed are now in xtext-umbrella. The xtext-build-tools repo can be archived. This has to be done by itemis. @NicoPrediger could you do this?

From Xtext we can assume this as finished.

**Comment by cdietrich** [comment]
@kthoms can you adapt the comment in releng/jenkins/release-prepare-branches/Jenkinsfile

**Comment by kthoms** [comment]
> @kthoms can you adapt the comment in releng/jenkins/release-prepare-branches/Jenkinsfile

Trivial change; directly pushed to master
