### ISSUE TITLE
Remove obsolete Jenkinsfiles

### ISSUE THREAD

**Issue by Hejado** [eclipse/xtext#1526]
Since the migration to JIRO is now complete, we don't need the old JIPP-Jenkinsfiles anymore; they can be removed.

In addition, we should rename the `CBI.Jenkinsfile`s to `Jenkinsfile` to indicate that those are the new default now.

Also, the jobs must be reconfigured to look for `Jenkinsfile` instead of `CBI.Jenkinsfile`.

Once we reconfigure the job, all branches that did not make the switch yet would then be executing the old JIPP pipeline, which would result in chaos. So we should make this switch in two steps:
1) Delete old Jenkinsfile, rename CBI.Jenkinsfile to Jenkinsfile and add a symlink CBI.Jenkinsfile->Jenkinsfile. Everything should continue to work normally.
2) If this change propagated to all branches, reconfigure the jobs and remove the symlink.

**Comment by Hejado** [comment]
Unfortunately, it seems like symlinking to Jenkinsfile is not supported: https://ci.eclipse.org/xtext/user/mail@nicoprediger.de/my-views/view/MyBranches/job/xtext-lib/job/np_issue1526/1/console

**Comment by Hejado** [comment]
One possibility would be to replace Jenkinsfile with a duplicate of CBI.Jenkinsfile and keep both files with the same content for a short while. We'd need to remember to change both until we can safely reconfigure the job and delete the duplicate one.

@cdietrich what do you think?

**Comment by cdietrich** [comment]
:+1: but i would keep that period short. e.g. removing CBI when 2.19.0.M2 is built

**Comment by Hejado** [comment]
Yes - we can remove CBI as soon as the duplicate Files are propagated to all (important) branches

**Comment by cdietrich** [comment]
@Hejado we should start working on this soon

**Comment by Hejado** [comment]
Switching the jobs is quick work - could do this now, if we assume that all important branches have the relevant master commits?

**Comment by cdietrich** [comment]
if people dont rebase ....
@szarnekow do you have any outdated branches in work?

**Comment by Hejado** [comment]
Reconfigured jobs to look for Jenkinsfile instead of CBI.Jenkinsfile. PRs will follow shortly.

**Comment by Hejado** [comment]
All done.
