### ISSUE TITLE
Problems to create a target platform with Xtext and Buildship

### ISSUE THREAD

**Issue by UdoW** [eclipse/xtext#1529]
I try to create a target platform for a runtime Eclipse RCP application where I want to use Xtext 2.18.0 and Buildship 3.1.1 based on Eclipse 2019-06.

Xtext needs Guava 21.0.0 and Buildship needs Guava 27.1.0.

In the Xtext Orbit p2 repository I can find the Guava 27.1.0 version but some Xtext bundles still require Guava 21.0.0.

How can I bundle both?

Is there a general plan which version of a "common" bundle to use for each platform release?

E.g. Guava 27.1.0 on Eclipse 2019-06, Guava 21.0.0 on Eclipse 2019-03 etc.

**Comment by cdietrich** [comment]
https://github.com/eclipse/buildship/issues/906

**Comment by cdietrich** [comment]
=> the buildship you use seems too new.
which buildship do you use consumed from where

**Comment by UdoW** [comment]
I consumed version 3.1.1 from this repository: 
https://download.eclipse.org/buildship/updates/e411/releases/3.x

As I thought that is is compatible with Eclipse 4.11 (2019-03) and Xtext 2.18.0 ist also compatible with Eclipse 4.11 both should match.

Do you know if there is an agreement of all feature contributors to an Eclipse Release version which external bundle version to use?

**Comment by cdietrich** [comment]
there is just a loose agreement.
my assumption is that with eclipse 2019-09 everybody will be at guava 27.1

**Comment by cdietrich** [comment]
(you may address this issue by writing your concerns to https://accounts.eclipse.org/mailing-list/cross-project-issues-dev

**Comment by UdoW** [comment]
ok, thank you.

**Comment by cdietrich** [comment]
@UdoW are you going to write to cross project issues dev or shall i do?

**Comment by UdoW** [comment]
I wrote some questions.

I also found out that Buildship 3.1.0 depends on Guava 21.0.0 but version 3.1.1 depends on 27.1.0. I think this is a regression.

**Comment by cdietrich** [comment]
no its a feature
xtext 2.18 and mwe 2.11 use guava 27.1 too.
the problem is that you try to use buildship 3.1.1 with old stuff

**Comment by UdoW** [comment]
But then I do not understand the concept of semantic versioning. 
I downgraded to Buildship 3.1.0 and now it works togehter with Xtext 2.18.0.

**Comment by cdietrich** [comment]
well the problem is: all using the same guava version is not part of the semantic versioning.
i dont think buildship has any public api so semantic versioning is irrelevant there

**Comment by UdoW** [comment]
Buildship has some public API since version 3.0.0, but nevermind.

**Comment by miklossy** [comment]
I observed a similar problem on the Eclipse GEF project, see [bug 549806](https://bugs.eclipse.org/bugs/show_bug.cgi?id=549806)
