### ISSUE TITLE
Discard old branch jobs using jenkins configuration

### ISSUE THREAD

**Issue by Hejado** [eclipse/xtext#1531]
I think we may retire this job here: https://ci.eclipse.org/xtext/job/releng/job/clean-stale-jobs/

and replace it with the 'discard old items' option provided by the multibranch job itself.

**Comment by cdietrich** [comment]
ping @kthoms @Hejado

**Comment by cdietrich** [comment]
moved to 2.20

**Comment by kthoms** [comment]
We have configured 'Orphaned Item Strategy' in the jobs. This does what we expect.

![screenshot 359](https://user-images.githubusercontent.com/265597/70441765-4cd99a80-1a95-11ea-8cb6-7f141fddf9cd.png)
