### ISSUE TITLE
Update Community Page

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#1541]
There is more stuff with Xtext (LSP and Web too) but not reflected on the community page. for the stuff that is open we should add entries to the table. we also might check the table for stuff that is in nirwana now. (maybe split table is active / historic projects)

below https://twitter.com/chrdietrich/status/1166341649955467264 you can find some stuff

- Yang https://github.com/theia-ide/yang-lsp
- Solidity IDE https://github.com/Yakindu/solidity-ide (maybe with demo url)
- Sprotty Example https://github.com/TypeFox/theia-xtext-sprotty-example
- itemis LSP Example https://github.com/itemis/xtext-languageserver-example
- Xtext Web Demo
- ELK stuff https://github.com/OpenKieler/elkgraph-web / https://t.co/LLozqpMxc6?amp=1
- Xtext Ide Extensions https://github.com/kuniss/xtext-ide-extensions
- N4JS

TODO research for others like SADL, ...

**Comment by miklossy** [comment]
I am aware of the following open-source Xtext-based projects that could also be listed there:

- Java Byte Code Editor: https://github.com/itemis/jbc
- e(fx)clipse: https://www.eclipse.org/efxclipse/index.html
- Eclipse EMF Parsley: https://www.eclipse.org/emf-parsley/documentation.html
- Eclipse Franca: https://projects.eclipse.org/projects/modeling.franca
- Xtendency: https://github.com/kbirken/xtendency
- Jnario: https://github.com/sebastianbenz/Jnario
- Natural: https://github.com/rlogiacco/Natural
- Softlang Megalib (University Koblenz-Landau): https://github.com/softlang/megalib/
- eMoflon (University Paderborn): https://github.com/eMoflon

**Comment by miklossy** [comment]
See also the [Xtext Community Web Site](https://bugs.eclipse.org/bugs/show_bug.cgi?id=328477) Bugzilla issue.

**Comment by Hugo-Bruneliere** [comment]
<tr>
	<td><a href="https://www.atlanmod.org/emfviews">EMF Views</a></td>
	<td>EMF Views is an Eclipse plugin that brings the concept of database views to the modeling world. Model views (focusing on parts of a model and/or combining several models) can be created and then navigated/queried/used as regular models for further model transformation, code generation, etc.</td>
	<td>EPL, GPL</td>
	<td>Language, Framework</td>
	<td>Florent Marchand de Kerchove, Hugo Bruneliere</td>
</tr>

**Comment by NielsLiisberg** [comment]
<tr>
	<td><a href="https://github.com/NielsLiisberg/RPG-lexer">RPG Lexer (IBM ILE RPG)</a></td>

	<td>This project is for tooling and better understanding of the ILE RPG language. Tooling like plug in for 100% free-RPG editors running in i.e. Eclipse with code completion etc. or even to build transpilers to create C, C# or JAVA code from RPG</td>

	<td>MIT License</td>

	<td>tools</td>

	<td>Niels Liisberg</td>

</tr>

**Comment by atb** [comment]
PlantUML DSL
<tr>
	<td><a href="https://github.com/atb/pt.isep.dsl.puml">PlantUML DSL</a></td>
	<td>An open-source and academic project which aim is to provide an xtext based DSL for PlantUML.</td>
	<td>EPL</td>
	<td>Language, Tool Suite</td>
	<td>Alexandre Bragança</td>
</tr>

**Comment by miklossy** [comment]
Thank you @atb !

**Comment by stefanocke** [comment]
```
<tr>
	<td><a href="https://github.com/japkit/japkit">japkit</a></td>
	<td>Japkit is an annotation processor that allows to develop Java code generators by using code templates written in Java with some annotations. There is no need to write any imperative code, which makes the code generators short and concise and so eases their maintenance.</td>
	<td>Apache 2 License</td>
	<td>Tool</td>
	<td>Stefan Ocke</td>
</tr>
```

**Comment by ArneDeutsch** [comment]
<tr>
	<td><a href="https://github.com/itemis/jbc">JBC</a></td>
	<td>JBC is an eclipse plugin that enables the developer to view and edit files containing java byte code (*.class) inside eclipse.</td>
	<td>EPL 1.0</td>
	<td>Developer Tool</td>
	<td>Arne Deutsch</td>
</tr>

**Comment by gerdleon** [comment]
<tr>
	<td><a href="https://github.com/dsldevkit/dsl-devkit">DSL Developer Kit and Runtime Library</a></td>
	<td>JDSL Developer Kit is an extension layer to Xtext built for active Xtext users. It extends Xtext runtime to handle more sophisticated cases in DSL design, to support scaling for larger models and better monitoring and recovery in headless frameworks based on Xtext. DDK comes with a few handy small DSLs helping to standardize implementatoins of tools for DSLs.</td>
	<td>EPL 1.0</td>
	<td>Framework</td>
	<td>Avaloq Solution Model Development and Compiler Framework team</td>
</tr>
<tr>
	<td><a href="https://docs.avaloq.com/tools/asmd/solution_model_development.htm">Avaloq Solution Model Development (ASMD)</a></td>
	<td>ASMD is a model driven client-server system providing customization tooling for the Avaloq Banking Platform. It supports customization experts managing more than 100k source artefacts in more than 60 DSLs that describe the aspects and behaviour of financial institutions.</td>
	<td>Commercial</td>
	<td>Eclipse IDE</td>
	<td>Avaloq Solution Model Development and Compiler Framework team</td>
</tr>
<tr>
	<td><a href="https://docs.avaloq.com/tools/compiler_framework.htm">Compiler Framework</a></td>
	<td>The Compiler Framework (CF) supports state of the art implementations of DSLs for the Avaloq Banking Platform with stand-alone generators for the target platform.</td>
	<td>Commercial</td>
	<td>Framework</td>
	<td>Avaloq Solution Model Development and Compiler Framework team</td>
</tr>

**Comment by miklossy** [comment]
Thank you @gerdleon !

**Comment by miklossy** [comment]
@tivervac : If you would like to add the `Sigasi Studio` project to the [Xtext community website](https://www.eclipse.org/Xtext/community.html), please provide the corresponding PR. I really find that `Sigasi Studio` deserves to be listed there, but I need your agreement to do that.

PS: I like the [recorded EclipseCon session](https://youtu.be/tBZVyYKgpcU) about your Sigasi Studio talk, I think we should also add a link to that in the description section.

**Comment by jperiodlangley** [comment]
<tr>
        <td><a href="https://github.com/CohesionForce/hla-toolkit">HLA Toolkit</a></td>
        <td>Toolkit for working with High Level Architecture (HLA) Federated Object Models and generating a logging federate</td>
        <td>EPL 2.0</td>
        <td>Framework</td>
        <td>CohesionForce, Inc</td>
</tr>

**Comment by drkstr101** [comment]
<tr>
        <td><a href="https://github.com/rlogiacco/Natural">Natural</a></td>
        <td>Natural is a collection of Eclipse plugins to enable rich smart editing of acceptance tests using natural language definition files. It currently supports Cucumber and JBehave syntax. </td>
        <td>Eclipse Public License 1.0</td>
        <td>BDD</td>
        <td>Roberto Lo Giacco</td>
    </tr>

Cheers and thank you!

**Comment by cdietrich** [comment]
@miklossy what is the state of this issue?

**Comment by miklossy** [comment]
I would suggest to close this issues as fixed.
