### ISSUE TITLE
update to Tycho 1.5.0

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#1553]
update to Tycho 1.5.0 (once the release is out)
- wizard
- all projects
- reference projects

**Comment by miklossy** [comment]
The [Pomless Build Feature](https://wiki.eclipse.org/Tycho/Release_Notes/1.5) of Tycho 1.5.0 looks very promising.

**Comment by cdietrich** [comment]
i dont think that will work for us

**Comment by cdietrich** [comment]
Fixed in 2.20
