### ISSUE TITLE
adapt gazillions of Jenkinsfiles to reflect changes in eclipse infrastructure

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#1554]
adapt gazillions of Jenkinsfiles to reflect changes in eclipse infrastructure
https://bugs.eclipse.org/bugs/show_bug.cgi?id=551584

**Comment by cdietrich** [comment]
TODO: check all in job Jenkinsfiles

**Comment by cdietrich** [comment]
Also Xtext-web does no longer work

https://bugs.eclipse.org/bugs/show_bug.cgi?id=551584

https://ci.eclipse.org/xtext/job/xtext-web/job/cd_xtext_issue1554/3/console

> Task :org.eclipse.xtext.web:npmInstall FAILED
npm ERR! path /home/jenkins/.npm
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall mkdir
npm ERR! Error: EACCES: permission denied, mkdir '/home/jenkins/.npm'
npm ERR!  { [Error: EACCES: permission denied, mkdir '/home/jenkins/.npm']
npm ERR!   stack:
npm ERR!    'Error: EACCES: permission denied, mkdir \'/home/jenkins/.npm\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/home/jenkins/.npm' }

**Comment by cdietrich** [comment]
running from local does not seem to work neither

> A problem occurred starting process 'command '/home/jenkins/agent/workspace/xtext-web_cd_xtext_issue1554/org.eclipse.xtext.web/.gradle/nodejs/node-v10.16.0-linux-x64/bin/npm''

**Comment by cdietrich** [comment]
TODO: 
- check if the fix for web is correct or if there is a better version
- check Jenkinsfiles for other Jobs
-check all in-job-Jenkinsfiles, check if something went missing

**Comment by cdietrich** [comment]
@kthoms would be nice if you or @Hejado could double check so that we can close

**Comment by cdietrich** [comment]
@kthoms @Hejado anything left

**Comment by cdietrich** [comment]
ping

**Comment by cdietrich** [comment]
anybody out there?

**Comment by Hejado** [comment]
So, regarding the m2-secret-dir you caught them all.

Regarding the npm thing, I think your work around works just as much as the proposed solution from the wiki. Unless we run into any further problems, I'd consider this fixed...

**Comment by cdietrich** [comment]
thx for checking @Hejado
