### ISSUE TITLE
clean-stale-jobs is broken

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#1555]
https://ci.eclipse.org/xtext/job/releng/job/clean-stale-jobs/

**Comment by cdietrich** [comment]
it does not go away. the job is red for days now

**Comment by kthoms** [comment]
Raised [Bug#551653](https://bugs.eclipse.org/bugs/show_bug.cgi?id=551653)

**Comment by kthoms** [comment]
Fixed by Mickael.
