### ISSUE TITLE
Adapt to ASM changes in orbit

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#1567]
Something about asm in orbit  has changed that breaks builds

**Comment by cdietrich** [comment]
https://download.eclipse.org/tools/orbit/downloads/drops/S20191025144108/

Has now asm 7.2

This breaks m2 builds on Monday / tuesday

**Comment by cdietrich** [comment]
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=21018

wont be able to do the doing
=> help wanted and needed

**Comment by szarnekow** [comment]
Done
