### ISSUE TITLE
Remove Buildship classpath container from launch configurations

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext#1568]
With a fresh oomphed workspace I see that Buildship's classpath container was automatically removed from the stored .launch files.

I see no error in the workspace, so I'll provide PRs for the removal of these entries.

Buildship version is: 3.1.2.v20190903-1802

<img width="1625" alt="screenshot 300" src="https://user-images.githubusercontent.com/265597/67671061-715e3500-f975-11e9-8fb1-9f80fe35b2ca.png">

**Comment by cdietrich** [comment]
@kthoms what is the state of this issue?

**Comment by cdietrich** [comment]
ping @kthoms

**Comment by cdietrich** [comment]
will close this for now. feel free to reopen if problem is left anywhere
