### ISSUE TITLE
Reduce usage of Xtend were it is not beneficial

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext#1569]
At ECE2019 we have decided to not use Xtend were it does not add much value over Java. With the evolution of Java many of Xtend's sweet spots are added to Java. This reduces the benefit of Xtend. We also want to improve the build speed.

As a consequence, we want to replace Xtend code by Java in the Xtext code base where it is not super useful. We should start with Xtend classes using deprecated API, as Xtend does not properly support suppression of the deprecation warnings.

Further candidates:
- Guice modules
- Xtend interfaces
- Small classes with limited Xtend logic

Since this is a potential long going task this issue collects the efforts for release 2.20 only.

**Comment by cdietrich** [comment]
move to 2.21 for further refactorings

**Comment by kthoms** [comment]
Should we create another issue? Otherwise this will stay open for a long time and the number of associated changes become confusing.

**Comment by cdietrich** [comment]
@kthoms feel free to do so

**Comment by kthoms** [comment]
Follow-up issue for 2.21: #1629
