### ISSUE TITLE
Escaping branch name in labels

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#1595]
It look like container labels are allowed for a specific character set only

https://ci.eclipse.org/xtext/job/xtext-core/job/jk%252Fgitpod/4/console

12:37:59  ERROR: Labels must follow required specs - https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set: xtext-core-jk/gitpod-4
12:37:59  Finished: FAILURE

thus i assume we need to do some escaping here

https://github.com/eclipse/xtext-core/blob/1e3374d0e3cfc3413dc10a32fb213d0ef2e87901/Jenkinsfile#L4

cc @Hejado @kthoms 

do you know any built in helpers for that?

**Comment by JanKoehnlein** [comment]
Tried the same with a branch name using `_` instead of the `/`. Doesn't work either.
https://github.com/eclipse/xtext-core/pull/1282

**Comment by cdietrich** [comment]
it actually does https://ci.eclipse.org/xtext/job/xtext-core/job/jk_gitpod/1/console

**Comment by JanKoehnlein** [comment]
But it shows a failing CI build on the PR

**Comment by cdietrich** [comment]
job is still running

**Comment by JanKoehnlein** [comment]
It shouldn't show as _failed_ when it's still running then.

**Comment by JanKoehnlein** [comment]
It shouldn't show as _failed_ when it's still running then.

**Comment by Hejado** [comment]
I don't know anything that's built-in. Writing a groovy function for that would be easy, but propagating it across all xtext repos would be a pain. Creating a global library just for that might be overkill. The easiest way would be to communicate a naming convention for branches or just to adopt the UUID-based labeling that's mentioned in JIRO's wiki somewhere...

**Comment by kthoms** [comment]
I suggest to replace / by underscore for the computed agent label in the Jenkinsfiles. Will prepare PRs for that.

**Comment by cdietrich** [comment]
@kthoms anything left?

**Comment by kthoms** [comment]
All changes are merged.
