### ISSUE TITLE
sign-and-deploy: Delete release branches

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext#1596]
With successful creation of release branches the sources are tagged. When the release branches were successfully build those branches can be safely deleted. I think this can be done as part of the [sign-and-deploy](https://ci.eclipse.org/xtext/job/releng/job/sign-and-deploy/).

Either clone all repositories as shallow as possible and call
```
git push --delete origin RELEASE_BRANCH_NAME
```
or use GitHub REST API to directly delete the branches. I think I'd prefer the latter.

**Comment by cdietrich** [comment]
are we sure this does not accidentially deletes something we dont want?

**Comment by kthoms** [comment]
The sources are tagged at that time, the branches could be restored. So this should be safe.

**Comment by Hejado** [comment]
Turns out, you don't need to clone or use any API:
`git push URL --delete RELEASE_BRANCH_NAME` will work as long as we are in *any* git repository.

**Comment by kthoms** [comment]
Ah, thought we would need to checkout all the repos, which I did not want to do in sign-and-deploy. Could you provide the PR?

**Comment by Hejado** [comment]
sure

**Comment by Hejado** [comment]
Should we keep this open until after 2.21.0.M1 to make sure it works as expected?

**Comment by cdietrich** [comment]
yes

**Comment by Hejado** [comment]
https://ci.eclipse.org/xtext/view/Xtext-release/job/releng/job/sign-and-deploy/383/console

```git push git@github.com:eclipse/xtext-lib.git --delete milestone_2.21.0.M1
 Failed to add the RSA host key for IP address '140.82.113.3' to the list of known hosts (/home/jenkins/.ssh/known_hosts).
 git@github.com: Permission denied (publickey).
 fatal: Could not read from remote repository.
 
 Please make sure you have the correct access rights
 and the repository exists.```

The 'Remove Release Branches' stage is missing the ssh agent :-(

I think I've seen the known_host warning somewhere without failing. I don't think this is fatal.

**Comment by Hejado** [comment]
PR should hopefully make this work. Guess, we'll find out at M2 :-)

**Comment by Hejado** [comment]
All release branches were removed automatically.

Fixed.
