### ISSUE TITLE
[2020-03] update oomph

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#1606]
update oomph to support 2019-12 final and new 2020-03
* new version
* I-builds change
* Orbit

Also document what needs to be done. see https://github.com/eclipse/xtext/issues/1565

**Comment by cdietrich** [comment]
https://github.com/eclipse/xtext/blob/master/dev-doc/MaintenanceTasks.md

**Comment by kthoms** [comment]
Updated MaintenanceTasks.md

PR https://github.com/eclipse/xtext-eclipse/pull/1288 prepared.

**Comment by cdietrich** [comment]
done
