### ISSUE TITLE
Xtext 2.21: Refactor Xtend to Java

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext#1629]
This is a follow-up issue for #1569 in order to continue reduction of Xtend usage in the Xtext code base. This issue tracks the efforts done for the 2.21 release.

**Comment by szarnekow** [comment]
I'll migrate the server.concurrent package.

**Comment by miklossy** [comment]
When creating a new Xtext MyDsl Project, the `org.xtext.example.mydsl.ide` Plug-in contains an empty `xtend-gen` folder.
![screenshot](https://user-images.githubusercontent.com/20393472/71835394-bc9d6e00-30b1-11ea-9622-a1144609e8b8.png)
I propose to remove this empty folder by default, since the `src` folder contains only `*.java` classes by default. The `xtend-gen` folder will be added automatically as soon as the user adds an `*.xtend` file.
@cdietrich What do you think about this suggestion?

**Comment by cdietrich** [comment]
who creates that folder?

**Comment by miklossy** [comment]
The folder is created by the Wizard, see [ProjectDescriptor.getSourceFolders()](https://github.com/eclipse/xtext-core/blob/master/org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/ProjectDescriptor.xtend#L43-L50). I suggest to override that method in the [IdeProjectDescriptor](https://github.com/eclipse/xtext-core/blob/master/org.eclipse.xtext.xtext.wizard/src/org/eclipse/xtext/xtext/wizard/IdeProjectDescriptor.xtend) class to exclude the `Outlet.MAIN_XTEND_GEN` `xtend-gen` folder from the super implementation.

**Comment by cdietrich** [comment]
i still have to think about that.
@szarnekow @kthoms what do you think?

**Comment by szarnekow** [comment]
In general we should only create the xtend-gen folder when at least a single xtend file is written for that project. Having an empty xtend-gen folder will otherwise likely confuse the gradle builder.

**Comment by szarnekow** [comment]
That being said, I'm not a fan of overriding something for the IdeProjectDescriptor. We should try to find a holistic solution instead.

**Comment by szarnekow** [comment]
Please create a separate ticket for this.

**Comment by miklossy** [comment]
Thanks for the feedback @szarnekow ! I created a separate ticket https://github.com/eclipse/xtext-core/issues/1341 for that issue.

**Comment by cdietrich** [comment]
having a look at the generateXbase workflow

**Comment by gyaltso** [comment]
I would like to migrate the Xtend code from the project `org.eclipse.xtext.ui`

**Comment by nbhusare** [comment]
I would like to migrate the Xtend code from the project `org.eclipse.xtext.ui`

**Comment by miklossy** [comment]
Thanks for offering your assistance @nbhusare ! I would suggest to do that work within a new issue: `Xtext 2.22: Refactor Xtend to Java`. Could you please create a new one?

**Comment by miklossy** [comment]
Fixed in 2.21
