### ISSUE TITLE
Marketplace entry validation failure

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext#1632]
The [Marketplace validation report](https://www.eclipse.org/setups/marketplace/?url=https://marketplace.eclipse.org/content/eclipse-xtext) shows issues with the Xtext SDK for platforms below 2019-12:

![screenshot 363](https://user-images.githubusercontent.com/265597/70624310-517e8a00-1c20-11ea-8d75-da08a75550fe.png)

Clicking on an error icon reveals problems with the dependency on MWE:
```
Contains: Missing requirement: Xtext Complete SDK 2.20.0.v20191202-1256 (org.eclipse.xtext.sdk.feature.group 2.20.0.v20191202-1256) requires 'org.eclipse.equinox.p2.iu; org.eclipse.emf.mwe2.language.sdk.feature.group 2.11.1' but it could not be found
```

MWE 2.11.1 can be found on the 2019-12 SimRel, but not on SimRel repositories of older releases.

**Comment by kthoms** [comment]
![screenshot 364](https://user-images.githubusercontent.com/265597/70625334-7c69dd80-1c22-11ea-84c4-4947127f7329.png)

**Comment by kthoms** [comment]
Should the MWE site be listed in the `category.xml` of Xtext's p2 repository?
xtext-eclipse/releng/org.eclipse.xtext.p2-repository/category.xml

![screenshot 365](https://user-images.githubusercontent.com/265597/70625614-0d40b900-1c23-11ea-8f16-1b524b9a358b.png)

**Comment by cdietrich** [comment]
am not sure isnt that what the xtext composite is for.

**Comment by cdietrich** [comment]
i wonder

- do we need a release specific composite including other stuff
- do we drop all version support in the marketplace?

**Comment by cdietrich** [comment]
this not only affects MWE but will also EMF if e.g. we require EMF 2.20

**Comment by kthoms** [comment]
Could reproduce the issue with the p2 director app on a fresh Oxygen installation.

Steps to reproduce:
- Start Eclipse Installer
- User product version Oxygen
- Use package Eclipse for Java Developers

Run director app with
```
director -r http://download.eclipse.org/modeling/tmf/xtext/updates/releases/2.20.0,http://download.eclipse.org/releases/oxygen -i org.eclipse.xtext.sdk.feature.group -d ~/temp/java-oxygen/
```

=> 
```

Installing org.eclipse.xtext.sdk.feature.group 2.20.0.v20191202-1256.
Installation failed.
Cannot complete the install because one or more required items could not be found.
 Software being installed: Xtext Complete SDK 2.20.0.v20191202-1256 (org.eclipse.xtext.sdk.feature.group 2.20.0.v20191202-1256)
 Missing requirement: Xtext Complete SDK 2.20.0.v20191202-1256 (org.eclipse.xtext.sdk.feature.group 2.20.0.v20191202-1256) requires 'org.eclipse.emf.mwe2.language.sdk.feature.group 2.11.1' but it could not be found
```

**Comment by kthoms** [comment]
Installing Xtext 2.20 on 2019-12 works
```
director -r http://download.eclipse.org/modeling/tmf/xtext/updates/releases/2.20.0,http://download.eclipse.org/releases/2019-12 -i org.eclipse.xtext.sdk.feature.group -d ~/temp/java-latest/
```

**Comment by kthoms** [comment]
Discussed with @Hejado and we came to the solution to provide an update site at location http://download.eclipse.org/modeling/tmf/xtext/updates/composite/marketplace

We'll add this composite to https://github.com/xtext/xtext-p2-orbit and revive the Jenkins job that copies the manually maintained composite descriptors to Xtext's project storage.

Also raised an [Bug#558359 for Marketplace Client](https://bugs.eclipse.org/bugs/show_bug.cgi?id=558359), since we can't specify multiple solution versions with the same set of supported Eclipse releases.

**Comment by kthoms** [comment]
Marketplace entry is valid again

![screenshot 374](https://user-images.githubusercontent.com/265597/70975254-d39c0200-20a9-11ea-9c1e-6b981cba0b22.png)
