### ISSUE TITLE
Make project settings consistent

### ISSUE THREAD

**Issue by szarnekow** [eclipse/xtext#1633]
The Tycho projects of the Xtext codebase use insonsistent output folders. Some compile to `bin` and `bin-test`, other compile to output folders beneath `target`. The projects that compile to `bin` will always have changes in the classpath files after updating the project config. This is error-prone and annoying.

We have to make a decision here:
- Either compile everything to the output folders that are configured by m2e: `target`
- Compile everything to `bin*` and use an m2e plugin to automate that and keep it automatically consistent.

**Comment by szarnekow** [comment]
Decision:
- We want to use different output folders for maven und the Eclipse build.
- Check if we can configure https://repo1.maven.org/maven2/.m2e/connectors/m2eclipse-tycho/0.9.0/N/LATEST somehow
- Plan B: Provide a custom m2e plugin that will configure bin and bin-test as output folders.

**Comment by szarnekow** [comment]
We had to opt for Plan B. See https://github.com/eclipse/xtext-eclipse/pull/1298

**Comment by cdietrich** [comment]
@szarnekow as tycho seems to be unresposive move to 2.22?

**Comment by szarnekow** [comment]
yes

**Comment by cdietrich** [comment]
move to 2.23

**Comment by cdietrich** [comment]
move to 2.24

**Comment by cdietrich** [comment]
it looks like. when m2e nature the junit launch expects classes to be in target/classes
e.g. /org.eclipse.xtext.builder.tests/xtext.standalone.builder.junit.launch

**Comment by szarnekow** [comment]
Closing as I don't expect a more holistic fix to be available soon.
