### ISSUE TITLE
Consider using platform/latest in target platforms

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#1636]
Consider using 
https://download.eclipse.org/releases/latest

in our latest platforms as proposed by @kthoms 

i have no idea what they are and contain

@kthoms do you have any additional information?

**Comment by kthoms** [comment]
To [facilitate IDE upgrades](https://wiki.eclipse.org/FAQ_How_do_I_upgrade_Eclipse_IDE%3F#Always_enable_major_upgrades) this repository always contains the latest official simrel release.

**Comment by cdietrich** [comment]
Release not milestone?

**Comment by kthoms** [comment]
No milestones. It is the latest recommended release. For our "latest" targets we should use this. This makes it obsolete to modify them after each release.
I'll provide PRs.

**Comment by cdietrich** [comment]
But latest is for milestones

**Comment by kthoms** [comment]
Recognized this also now. The "*latest.target" are using the I-Build repositories. This is latest integration state, not milestones.
We consume currently Xpand, m2e, buildship from the simrel repos, at least for the "latest" target in xtext-eclipse. For those features we may want the latest official release, or do we also want the latest integration build?

**Comment by cdietrich** [comment]
I don't understand the alias contains the simrel milestone s doesn't it

**Comment by cdietrich** [comment]
https://download.eclipse.org/releases/2020-03/ contains m1 as expected
the initial proposal was to replace
https://download.eclipse.org/releases/2020-03/
with 
https://download.eclipse.org/releases/latest/
which does not contain the milestones.
thus we should close

**Comment by kthoms** [comment]
Agreed.
