### ISSUE TITLE
StorageAwareResource.load(Map<?, ?>) throws NullPointerException

### ISSUE THREAD

**Issue by markdomeng** [eclipse/xtext#1651]
in the try-catch block:
` catch(IOException e) {
				// revert the resource into a clean state
				contents.clear
				eAdapters.clear
				unload
			}`
contents.clear is translated into this.contents.clear(); instead of this.getContents().clear();
the same goes for eAdapters.

**Comment by cdietrich** [comment]
hmmm emf lazy collections are always fascinating

**Comment by cdietrich** [comment]
@markdomeng  i wonder how you get this reproduced.

**Comment by cdietrich** [comment]
fixed in 2.21
