### ISSUE TITLE
Creating a .vsix file for my DSL

### ISSUE THREAD

**Issue by JesterOrNot** [eclipse/xtext#1659]
Hey, how can I make a vscode extension for my DSL?

**Comment by cdietrich** [comment]
have a look at https://github.com/itemis/xtext-languageserver-example/tree/master/vscode-extension-self-contained

**Comment by cdietrich** [comment]
@JesterOrNot do you need more information?

**Comment by JesterOrNot** [comment]
Yes is there a way to generate the vsix file like you would an eclipse extension?

**Comment by cdietrich** [comment]
no there is not.

**Comment by cdietrich** [comment]
as there was no further feedback will close for now
