### ISSUE TITLE
Xpand and EPL 2.0

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#1669]
If i read [this](https://www.eclipse.org/lists/cross-project-issues-dev/msg17428.html) thread on `cross-project-issues-dev/` correct then @waynebeaton wants to enforce all participants in 2020-06 to contribute EPL 2.0 licensed bits.

for us this would implicate

- drop the old generator and the xpand dependency
  - https://github.com/eclipse/xtext-core/issues/1384
  - remove from all targets
  - maybe remove from AbstractPluginCreator
- create and integrate a relicensed xpand package

cc @kthoms @szarnekow 

@waynebeaton did i read your message correct?

**Comment by waynebeaton** [comment]
I can't speak for the implications. 

But yes, we need to get these licenses updated.

**Comment by kthoms** [comment]
I would opt for dropping the old generator. I don't want to spent efforts on relicensing Xpand. Otherwise we would have to set up a new build infra just for this purpose. I would like to avoid the effort.

**Comment by cdietrich** [comment]
yes but it is a pity we have to drop still perfectr bits just cause the huge effort to do a license update.

**Comment by kthoms** [comment]
It is already deprecated and announced that it will be dropped in our [release notes](https://www.eclipse.org/Xtext/releasenotes.html#/releasenotes/2019/12/03/version-2-20-0). Now the time has come to make it real.

> As we want to stop using old Xpand in Xtext we will drop this support in a future Xtext release.

**Comment by cdietrich** [comment]
yes but with no time for feedback .....

**Comment by kthoms** [comment]
Anybody is free to stick with an old release or to do the necessary to migrate. It is possible to allocate resources for helping. I don't see a problem here, it is the natural consequence. If you plan to invest resources to keep Xpand as a dependency, do so. I would not recommend it. Can we stop moaning now and continue to do the necessary?

**Comment by cdietrich** [comment]
well this should happen with 2.22 / 2020-06.
but of course we can start dropping dependencies in places where it is not needed

**Comment by Guite** [comment]
> Anybody is free to stick with an old release or to do the necessary to migrate.

Agreed.

> just cause the huge effort to do a license update

I'd see this rather as an appropriate location.
The new generator is available for about five years now.
Time to cut off the old pigtails.

**Comment by cdietrich** [comment]
there is at least https://github.com/meysholdt/xtext_stateful_lexer which is used by https://github.com/eclipse/xpect which i dont know a replacement fragment for so this would kill Xpect long term

**Comment by kthoms** [comment]
Dead things can't be killed

**Comment by cdietrich** [comment]
well there are at least people using Xpect right now

**Comment by kthoms** [comment]
Raise an issue to those repos to claim need for action. It's up to the library's maintainers or users to do something. We should not wait for that. The need for action in Xtext is now. I won't invest a second into maintaining dead stuff for users of dead stuff that are not willing to invest into maintenance.

**Comment by cdietrich** [comment]
i brought up the problem in the forum and i linked to here. so here is the place for people to start thinking about implications. if we already know implications this is a valid place to discuss

**Comment by ewillink** [comment]
The rationale here seems completely misguided. Having migrated four projects to EPL 2.0, I can assure you it just involves a couple of judicious regex blasts at all files to change the 1.0 to 2.0. Not a big problem. It is totally unnecessary to go to the extra complexity id SPDXes etc.

OCL and QVTd have ten editors that continue to use the traditional workflow and so the old generator. This has no impact on the built distribution since all build dependencies are isolated in a build-time-only plugin. But it breaks the ability to rebuild the editors.

Therefore OCL and QVTd are faced with a problem. Stick with Xtext 2.21 for build-time purposes, or migrate many workflows for what appears to a misguided rationale.

Also, if you are unable to contact authors to move to 2.0, then continuing to supply 1.0 may be frowned upon, but is certainly not wrong.

**Comment by cdietrich** [comment]
yes and beeing able to rebuild is imho neccessary to be able to do changes to stuff Xtext generates in the future. in this case the author (@kthoms) does not want do the license change for xpand.

**Comment by ewillink** [comment]
OK, so at one level leave @kthoms and the EF to duke it out. Xtext continues as is until there is a compromise.

I do not actually see the relevance of Xpand since when I examine the flat dependencies of my builld-time-only plugin (org.eclipse.ocl.examples.build) it appears that Xpand is not required.

**Comment by cdietrich** [comment]
xpand is a hard dependency for `org.eclipse.xtext.generator` aka the "old workflow/generator"

**Comment by ewillink** [comment]
Oops. Yes. Sorry. I had deleted the org.eclipse.xtext.generator dependency to see where it was needed.

Let Xtext carry on as normal. There is no reason why EF cosmetics should needlessly break longstanding functionality.

**Comment by cdietrich** [comment]
yes but @waynebeaton confirmed https://github.com/eclipse/xtext/issues/1669#issuecomment-584704694 that epl 1 is now longer allowed

**Comment by ewillink** [comment]
If Xpand was a third party tool, subject to the XPAND license, the EF IP process would decide whether the XPAND license was compatible with EF policies. Let the EF review EPL 1.0 as the XPAND license and dare to come back with any killer critique.

**Comment by ewillink** [comment]
Ed Merks' comment on the cross-project-dev thread seems much more appropriate.

"Are you suggesting that SUA 2.0 is a new participation requirement?  It seems to me merely a very-nice-to-have.  At this point I would just be happy if there were no corrupted variants of SUA 1.0 and SUA 1.1"

Wayne's "need" 2.0 is somewhat weaker than a "must".

**Comment by cdietrich** [comment]
as wayne said

>  If your project is not planning any releases and is still using EPL-1.0, please plan a service release for 2020-06 with the license upgrade.

i see this diffrent until I am convinced otherwise

**Comment by ewillink** [comment]
You can happily convert all Xtext (and Xtend) sources to EPL 2.0, leaving Xpand as EPL 1.0; you will have done your best to comply with EF direction without damaging your project pointlessly.

**Comment by cdietrich** [comment]
Xtext & Xtend (& MWE) as they are (still) maintained have been updated last week. but we have a upstream dependency to Xpand and Xpand is only part of simrel cause we use it.

**Comment by ewillink** [comment]
Perhaps you can just repackage org.eclipse.xpand as org.eclipse.xtext.generator/lib/org.eclipse.xpand.jar.

Or you can treat the unmaintained Xpand as an Orbit-like library, dragging it in from an old SimRel.

**Comment by ewillink** [comment]
Another option if Xpand is 'dead'. You could terminate Xpand and clone the code as hidden internals of  the xtext generator plugin. No JIRO hassle.

**Comment by cdietrich** [comment]
move to 2.23

**Comment by cdietrich** [comment]
https://www.eclipse.org/forums/index.php?t=msg&th=1104548&goto=1830094&#msg_1830094

**Comment by cdietrich** [comment]
more sargnägel for xpand
https://github.com/eclipse-platform/eclipse.platform.releng/issues/69

**Comment by cdietrich** [comment]
with the removal of xpand as dependency this is obsolete
