### ISSUE TITLE
Error: Couldn't resolve reference to JvmIdentifiableElement 'Workflow'.

### ISSUE THREAD

**Issue by hanibhat** [eclipse/xtext#1678]
I get the following errors in my project's GenerateDSL.mwe2 file:

Couldn't resolve reference to JvmIdentifiableElement 'baseName'.
Couldn't resolve reference to JvmIdentifiableElement 'baseName'.
Couldn't resolve reference to JvmIdentifiableElement 'code'.
Couldn't resolve reference to JvmIdentifiableElement 'code'.
Couldn't resolve reference to JvmIdentifiableElement 'component'.
Couldn't resolve reference to JvmIdentifiableElement 'component'.
Couldn't resolve reference to JvmIdentifiableElement 'configuration'.
Couldn't resolve reference to JvmIdentifiableElement 'configuration'.
Couldn't resolve reference to JvmIdentifiableElement 'createEclipseMetaData'.
Couldn't resolve reference to JvmIdentifiableElement 'createEclipseMetaData'.
Couldn't resolve reference to JvmIdentifiableElement 'eclipsePlugin'.
Couldn't resolve reference to JvmIdentifiableElement 'eclipsePlugin'.
Couldn't resolve reference to JvmIdentifiableElement 'eclipsePluginTest'.
Couldn't resolve reference to JvmIdentifiableElement 'eclipsePluginTest'.
Couldn't resolve reference to JvmIdentifiableElement 'enabled'.
Couldn't resolve reference to JvmIdentifiableElement 'enabled'.
Couldn't resolve reference to JvmIdentifiableElement 'enabled'.
Couldn't resolve reference to JvmIdentifiableElement 'enabled'.
Couldn't resolve reference to JvmIdentifiableElement 'enabled'.
Couldn't resolve reference to JvmIdentifiableElement 'enabled'.
Couldn't resolve reference to JvmIdentifiableElement 'encoding'.
Couldn't resolve reference to JvmIdentifiableElement 'encoding'.
Couldn't resolve reference to JvmIdentifiableElement 'fileExtensions'.
Couldn't resolve reference to JvmIdentifiableElement 'fileExtensions'.
Couldn't resolve reference to JvmIdentifiableElement 'fileHeader'.
Couldn't resolve reference to JvmIdentifiableElement 'fileHeader'.
Couldn't resolve reference to JvmIdentifiableElement 'generate'.
Couldn't resolve reference to JvmIdentifiableElement 'generate'.
Couldn't resolve reference to JvmIdentifiableElement 'generateStub'.
Couldn't resolve reference to JvmIdentifiableElement 'generateStub'.
Couldn't resolve reference to JvmIdentifiableElement 'language'.
Couldn't resolve reference to JvmIdentifiableElement 'language'.
Couldn't resolve reference to JvmIdentifiableElement 'lineDelimiter'.
Couldn't resolve reference to JvmIdentifiableElement 'lineDelimiter'.
Couldn't resolve reference to JvmIdentifiableElement 'name'.
Couldn't resolve reference to JvmIdentifiableElement 'name'.
Couldn't resolve reference to JvmIdentifiableElement 'newProjectWizardForEclipse'.
Couldn't resolve reference to JvmIdentifiableElement 'newProjectWizardForEclipse'.
Couldn't resolve reference to JvmIdentifiableElement 'project'.
Couldn't resolve reference to JvmIdentifiableElement 'project'.
Couldn't resolve reference to JvmIdentifiableElement 'rootPath'.
Couldn't resolve reference to JvmIdentifiableElement 'rootPath'.
Couldn't resolve reference to JvmIdentifiableElement 'runtimeTest'.
Couldn't resolve reference to JvmIdentifiableElement 'runtimeTest'.
Couldn't resolve reference to JvmIdentifiableElement 'serializer'.
Couldn't resolve reference to JvmIdentifiableElement 'serializer'.
Couldn't resolve reference to JvmType 'StandardLanguage'.
Couldn't resolve reference to JvmType 'StandardLanguage'.
Couldn't resolve reference to JvmType 'StandardProjectConfig'.
Couldn't resolve reference to JvmType 'StandardProjectConfig'.
Couldn't resolve reference to JvmType 'Workflow'.
Couldn't resolve reference to JvmType 'Workflow'.
Couldn't resolve reference to JvmType 'XtextGenerator'.
Couldn't resolve reference to JvmType 'XtextGenerator'.

**Comment by cdietrich** [comment]
make sure XtextGenerator is on the buildpath and can be resolved

**Comment by hanibhat** [comment]
Can you please tell me how to do that? I'm new to xtext, and maven projects for that matter.

Thanks in advance.

**Comment by cdietrich** [comment]
- do you use pure maven or maven tycho/eclipse
- if you do a rightklick maven -> update, force update of snapshots/releases does that help.
- can you build the parent on command line or in eclipse with `clean install` goals?
- are you behind a firewall


=> there are many potential sources of failure

**Comment by cdietrich** [comment]
any update here?

**Comment by cdietrich** [comment]
as here is no feedback. i will close now. please feel free to reopen if you can provide more details
