### ISSUE TITLE
Xtext 2.22: Refactor Xtend to Java

### ISSUE THREAD

**Issue by miklossy** [eclipse/xtext#1679]
This is a follow-up issue for #1629 in order to continue reduction of Xtend usage in the Xtext code base. This issue tracks the efforts done for the 2.22 release.

**Comment by miklossy** [comment]
@nbhusare will take care of migrating the org.eclipse.xtext.ui package from Xtend to Java, see his comment https://github.com/eclipse/xtext/issues/1629#issuecomment-589253399  in the previous ticket.

**Comment by cdietrich** [comment]
TODO: Wizard & AbstractPluginProjectCreator

**Comment by cdietrich** [comment]
The Xtext 2.22 Part of this issue is done
