### ISSUE TITLE
Composite update site contains stuff that does not exist

### ISSUE THREAD

**Issue by kittaakos** [eclipse/xtext#1708]
Conversation: https://gitter.im/eclipse/xtext?at=5e665ebccc10be22a0760598

I had this entry in my TP:
```xml
<location includeAllPlatforms="false" includeConfigurePhase="false" includeMode="planner" includeSource="true" type="InstallableUnit">
  <unit id="org.eclipse.xtend.sdk.feature.group" version="2.14.0.v20180523-0937"/>
  <unit id="org.eclipse.xtext.sdk.feature.group" version="2.14.0.v20180523-0937"/>
  <unit id="org.objectweb.asm" version="6.1.1.v20180414-0329"/>
  <repository location="https://download.eclipse.org/modeling/tmf/xtext/updates/composite/releases/"/>
</location>
```

I blindly changed the repository `location` to https://download.eclipse.org/modeling/tmf/xtext/updates/composite/releases/.

The Maven build has failed with the `Artifact not found: http://download.eclipse.org/modeling/tmf/xtext/updates/releases/2.8.4/backup/content.jar. -> [Help 1]` error.

```
[ERROR] Failed to resolve target definition /path/to/my/target/target.target: Failed to load p2 metadata repository from location https://download.eclipse.org/modeling/tmf/xtext/updates/composite/releases/: Unable to read repository at https://download.eclipse.org/modeling/tmf/xtext/updates/composite/releases. Unable to read repository at http://download.eclipse.org/modeling/tmf/xtext/updates/releases. Artifact not found: http://download.eclipse.org/modeling/tmf/xtext/updates/releases/2.8.4/backup/content.jar. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MavenExecutionException
```

**Comment by cdietrich** [comment]
there is also other outdated stuff in the composite

**Comment by cdietrich** [comment]
isses should be fixed now.

**Comment by cdietrich** [comment]
problem is back. now we have

[INFO] Fetching content.jar from http://download.eclipse.org/modeling/tmf/xtext/updates/releases/maintenance/R201411190455/ (33,67kB)
[ERROR] Failed to resolve target definition /home/dietrich/git/xtext-reference-projects/greetings-tycho/2.21.0/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target: Failed to load p2 metadata repository from location https://download.eclipse.org/modeling/tmf/xtext/updates/composite/releases/: Unable to read repository at https://download.eclipse.org/modeling/tmf/xtext/updates/composite/releases. No repository found at http://download.eclipse.org/modeling/tmf/xtext/updates/releases/xpand. -> [Help 1]
[ERROR] 

dont know what has changes

@kthoms xtext-p2-orbit does no longer deploy?

**Comment by cdietrich** [comment]
we should remove xpand from there or add the real xpand releases update site there.
in the milestones we use
<child location="http://download.eclipse.org/modeling/m2t/xpand/updates/milestones"/>

**Comment by cdietrich** [comment]
created https://github.com/eclipse/xtext/issues/1725 to create a regression test

**Comment by ewillink** [comment]
It pays to review Ed Merks' excellent

https://download.eclipse.org/oomph/archive/p2-index/modeling.tmf.xtext.html

**Comment by cdietrich** [comment]
thx for the hint @ewillink didnt know that specific one

**Comment by Hejado** [comment]
The report no longer shows any errors. 👍
