### ISSUE TITLE
existence of xtext-2.22.0.M2 breaks maven build using xtext 2.21.0

### ISSUE THREAD

**Issue by richard-melvin** [eclipse/xtext#1771]
I have a pure maven (no tycho) build which references xtext-dev-bom 2.21.0. and uses the same version of the xtext-maven-plugin.

This produces a log:

```
[INFO] --- xtext-maven-plugin:2.21.0:generate (default) @ dsl.model ---
[INFO] Downloading from : https://repo.maven.apache.org/maven2/org/eclipse/xtext/org.eclipse.xtext/maven-metadata.xml
[INFO] Downloaded from : https://repo.maven.apache.org/maven2/org/eclipse/xtext/org.eclipse.xtext/maven-metadata.xml (2.6 kB at 12 kB/s)
[INFO] Downloading from : https://repo.maven.apache.org/maven2/org/eclipse/xtext/org.eclipse.xtext.util/maven-metadata.xml
[INFO] Downloaded from : https://repo.maven.apache.org/maven2/org/eclipse/xtext/org.eclipse.xtext.util/maven-metadata.xml (2.3 kB at 64 kB/s)

....

[INFO] Downloaded from : https://repo.maven.apache.org/maven2/org/eclipse/jdt/org.eclipse.jdt.debug/maven-metadata.xml (675 B at 19 kB/s)
[INFO] Encoding: UTF-8
[INFO] Compiler source level: 1.8
[INFO] Compiler target level: 1.8
[INFO] Using common types.
[INFO] Collecting source models.
[INFO] Installing type provider.
[WARNING] --- xtext.common.types ---------------------------------------------------
[WARNING] ASM library is too old. Falling back to java.lang.reflect API.
[WARNING] Please note that no information about compile time constants is available.
[WARNING] It's recommended to use org.objectweb.asm 7.0 or better (Maven group id: org.ow2.asm).
[WARNING] --------------------------------------------------------------------------

...

ERROR] Failed to execute goal org.eclipse.xtext:xtext-maven-plugin:2.21.0:generate (default) on project dsl.model: Execution default of goal org.eclipse.xtext:xtext-maven-plugin:2.21.0:generate failed: A required class was missing while executing org.eclipse.xtext:xtext-maven-plugin:2.21.0:generate: scisys/dsl/xcog/PrimaryType (wrong name: scisys/dsl/xcog/primaryType)
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.eclipse.xtext:xtext-maven-plugin:2.21.0
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/d:/maven/org/eclipse/xtext/xtext-maven-plugin/2.21.0/xtext-maven-plugin-2.21.0.jar
[ERROR] urls[1] = file:/d:/maven/org/eclipse/emf/org.eclipse.emf.ecore.xcore/1.13.0/org.eclipse.emf.ecore.xcore-1.13.0.jar
[ERROR] urls[2] = file:/d:/maven/org/eclipse/xtext/org.eclipse.xtext/2.22.0.M2/org.eclipse.xtext-2.22.0.M2.jar
[ERROR] urls[3] = file:/d:/maven/org/eclipse/xtend/org.eclipse.xtend.lib/2.22.0.M2/org.eclipse.xtend.lib-2.22.0.M2.jar
[ERROR] urls[4] = file:/d:/maven/org/eclipse/xtend/org.eclipse.xtend.lib.macro/2.22.0.M2/org.eclipse.xtend.lib.macro-2.22.0.M2.jar

```

This appear to be because:

- for some reason maven is using 2.22.0.M2 of xtext

- some part of that version of xtext explicitly checks the asm version, expecting 8.x

- the xtext-dev bom specifies 7.2

- the xtext code wrongly reports the minimum version as being 7.0

**Comment by cdietrich** [comment]
The m2 dev bom specifies asm 8 https://github.com/eclipse/xtext-lib/blob/28ab3541c04777773b72660713f92ea0e2907a8a/org.eclipse.xtext.dev-bom/build.gradle#L68

You need to find out why in your Codebase 2.21 and 2.22.M2 are mixed

**Comment by cdietrich** [comment]
I assume there is something in your config that brakes maven Resolution and Leads to maven pulling the milestone

**Comment by cdietrich** [comment]
created a fix for the error message

**Comment by richard-melvin** [comment]
Ok the underlying reason for picking up the new xtext is that I add as a plugin dependency org.eclipse.emf.ecore.xcore.lib v1.4.0.

```
[DEBUG] Dependency collection stats: {ConflictMarker.analyzeTime=1686200, ConflictMarker.markTime=721000, ConflictMarker.nodeCount=3191, ConflictIdSorter.graphTime=743300, ConflictIdSorter.topsortTime=27600, ConflictIdSorter.conflictIdCount=69, ConflictIdSorter.conflictIdCycleCount=0, ConflictResolver.totalTime=889200, ConflictResolver.conflictItemCount=465, DefaultDependencyCollector.collectTime=772334700, DefaultDependencyCollector.transformTime=4094700}
[DEBUG] org.eclipse.xtext:xtext-maven-plugin:jar:2.21.0
[DEBUG]    org.eclipse.emf:org.eclipse.emf.ecore.xcore:jar:1.13.0:runtime
[DEBUG]       org.eclipse.xtext:org.eclipse.xtext:jar:2.22.0.M2:compile
[DEBUG]          org.eclipse.xtend:org.eclipse.xtend.lib:jar:2.22.0.M2:compile
```


xcore.lib has a pom that specifies:

```
    <dependency>
      <groupId>org.eclipse.xtext</groupId>
      <artifactId>org.eclipse.xtext.xbase.lib</artifactId>
      <version>[2.13.0,3.0.0)</version>
    </dependency>
```

2.22.0.M2 is within that range, so it gets used. 

Not exactly clear why that overrides the explicitly stated version in the bom in dependency-management, but that's a maven issue. 

Workaround is to add an exclusion to that dependency.

**Comment by richard-melvin** [comment]
I guess the root cause here is that xcore is not using the xtext bom. instead expressing optimistic version ranges in a way that really doesn't work out in practice with maven. 

Is that fixable? It would be nice to have a stable build that didn't break when new milestones were released.

**Comment by kthoms** [comment]
This is still present in Xcore. If you want to have that fixed submit a bug and ideally patch to Xcore. This is out of scope of the Xtext project.

Usually you should be able to pin a certain version if you add this dependency explicitly before including the Xcore dependency.

**Comment by cdietrich** [comment]
We don’t have a sync release cycle with Xcore nor do we have a Xtext runtime bom thus I don’t think this is properly fixable in Xcore besides having a Xcore maven plug-in which will never happen

**Comment by kthoms** [comment]
I'm closing this now. I assume the question has been answered, and a solution is out of our scope here. It would be great if you could help the Xcore project fixing the issue by providing a patch for them.
