### ISSUE TITLE
Update org.eclipse.platform/org.eclipse.jdt maven/gradle dependencies in bom

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#1802]
- Update org.eclipse.platform/org.eclipse.jdt maven/gradle dependencies in bom in xtext-lib
- create and run/test downstream branches

https://ci.eclipse.org/xtext/job/releng/job/check-versions/lastCompletedBuild/testReport/

**Comment by ArneDeutsch** [comment]
https://ci.eclipse.org/xtext/job/releng/job/check-versions/422/
