### ISSUE TITLE
Move to Java 11 with 2022-12

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#1804]
As Platform and JDT move to Java 11 with 2020-09 / 4.17 we have to follow up (at least once we want to consume newer versions from Maven/Gradle and the dances needed for #1717  become too cumbersome).

What do you think?

Known obstacles

- There is no warning free Java 11 version of Guice available yet (https://github.com/google/guice/issues/1133)

**Comment by ewillink** [comment]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=565368 hopefully stops the platform rush to Java 11 in its tracks.

https://en.wikipedia.org/wiki/Java_version_history shows that Java 8, unlike its predecessors, is nowhere nearly an imminent End of Life.

For OCL, QVTd I'm sticking with Java 8, although checking an occasional build with Java latest. I found that my autogenerated code is nearly three times slower with Java 11. Yet to investigate. Might just be a magic --modules stupidity that I don't have time / skill to understand.

**Comment by ewillink** [comment]
> nearly three times slower with Java 11. Yet to investigate. Might just be a magic

https://bugs.eclipse.org/bugs/show_bug.cgi?id=565563 raised to investigate OCL's 'slowness' on Java 11.

**Comment by cdietrich** [comment]
moved to 2.25 / 2021-03

**Comment by cdietrich** [comment]
Greeting example needs java 11 too now.

**Comment by ewillink** [comment]
Are you commenting on an improvement made by the Xtext team, or an observation of a problem caused by the platform? If the former, why has Xtext changed to require Java 11? If the latter what is the reference to the platform Bugzilla reporting the issue?

**Comment by cdietrich** [comment]
we are using platform and so we have to use java 11 if they force us to do so.
and in this case Java 11 is more in the heart of platform now so with 2020-12 running against jabva 8 no longer works
whilst in 2020-09 it did

**Comment by ewillink** [comment]
Yes, but for 2012-06 I got one BREE 11 reverted and Dani Megert commented [1] that just because Jetty needs BREE 11 it is not an excuse for everything else to rush to BREE 11. I have yet to investigate why a week after the reversion my 2012-09 builds started to fail again, so OCL builds have been red for 3 months now. We have to fight back against Java 11.

[1] https://bugs.eclipse.org/bugs/show_bug.cgi?id=565368#c18

**Comment by cdietrich** [comment]
https://travis-ci.org/github/itemis/xtext-reference-projects/jobs/736709958
looks hopeless

```
       Unresolved requirement: Require-Bundle: org.eclipse.equinox.p2.engine; bundle-version="[2.0.0,3.0.0)"

           -> Bundle-SymbolicName: org.eclipse.equinox.p2.engine; bundle-version="2.6.700.v20200511-1530"; singleton:="true"

              org.eclipse.equinox.p2.engine [99]

                Unresolved requirement: Import-Package: org.eclipse.equinox.internal.p2.metadata.repository.io

                  -> Export-Package: org.eclipse.equinox.internal.p2.metadata.repository.io; bundle-symbolic-name="org.eclipse.equinox.p2.metadata.repository"; bundle-version="1.3.400.v20191211-1528"; version="0.0.0"; x-friends:="org.eclipse.equinox.p2.engine"

                     org.eclipse.equinox.p2.metadata.repository [101]

                       Unresolved requirement: Import-Package: org.eclipse.equinox.internal.p2.persistence

                         -> Export-Package: org.eclipse.equinox.internal.p2.persistence; bundle-symbolic-name="org.eclipse.equinox.p2.repository"; bundle-version="2.5.0.v20200917-0634"; version="0.0.0"; x-friends:="org.eclipse.equinox.p2.artifact.repository,  org.eclipse.equinox.p2.engine,  org.eclipse.equinox.p2.metadata.repository,  org.eclipse.equinox.p2.ui.importexport,  org.eclipse.equinox.p2.repository.tools"

                            org.eclipse.equinox.p2.repository [102]

                              Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=11))"

                       Unresolved requirement: Import-Package: org.eclipse.equinox.internal.p2.repository
```

+ others

**Comment by cdietrich** [comment]
should we change the stupid wizard to select 2020-09 (or 2020-06) when < Java 11 is selected?

**Comment by kthoms** [comment]
Bundles from JDT, PDE, p2 and some more are already BREE-11. We are free to leave BREE-1.8 as long Xtext would run on Java 8, but for new projects created with the wizard I would not encourage that. This includes the example projects, i.e. they should target J11.
For the case that we would require a bundle in a version that is already BREE-11 then we should make this a hard requirement. ATM this is not the case yet if I see this correctly.

**Comment by cdietrich** [comment]
@kthoms this is about users on 2020-06 and older selecting java 8 in the wizard. would you skip java 8,9,10 from the dropdown in the wizard. it works perfectly fine if user does not build with maven tycho.

**Comment by kthoms** [comment]
Right, for users on older platforms it is valid to choose different Java versions. Do you think we should filter the provided list depending on the used platform version? Of course we could query the bundle version of some core platform bundle and relate this to the used platform version.

**Comment by cdietrich** [comment]
yes but this is all too compilated in my opinion.
what i dont understand is why platform does this lousy strategy and does not update everywhere

**Comment by cdietrich** [comment]
also this is not about the running platform but about the .target file we generate

**Comment by kthoms** [comment]
> what i dont understand is why platform does this lousy strategy and does not update everywhere
Bundles or whole projects upgrade when they decide to have a reason. Usually once a first bundle is bumped for one part project, then the others follow. You may raise this question on platform-dev.

> also this is not about the running platform but about the .target file we generate
This makes it a bit more complicated. Suppose you decide to choose "Java 8", but are on a 2020-12 platform, why should you generate a target for 2020-06 then?
On the other side: When you are on 2020-06 platform and Java 8 when executing the wizard, why should you generate a target for latest when you chose Java 8?
To make this smarter, the running platform may need to be considered.
To make this dumber and less maintenance effort, remove support for Java <11 in the wizard.

**Comment by cdietrich** [comment]
there are also gradle and pure maven people. the can use java 8 with no issue ...

**Comment by kthoms** [comment]
Right. So the issue is about the wizard and project generator.

**Comment by cdietrich** [comment]
yes and again the problem that you select java version on the first page and the rest on the second
(see my last PR that got rejected cause of that)

**Comment by kthoms** [comment]
We may have to rethink what is configured on which page.

**Comment by cdietrich** [comment]
there is still no no-java11-warning guice available

**Comment by cdietrich** [comment]
move to 2.26 / 2021-06

**Comment by cdietrich** [comment]
Java 17 Supported moved to 2.28
