### ISSUE TITLE
Remove ModuleCoreNature

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext#1806]
This popup appeared during a fresh Oomph setup. The nature should be removed, the project should not need WST. I guess this was for WST's XML editor.

<img width="455" alt="Anmerkung 2020-06-22 221825" src="https://user-images.githubusercontent.com/265597/85331668-d3f0dc00-b4d6-11ea-8f22-18e3156e8a49.png">

**Comment by cdietrich** [comment]
I don’t know how to unteach gradle that nature

**Comment by kthoms** [comment]
So this is added automatically by Gradle?

**Comment by cdietrich** [comment]
Yes. I did not find the time to digg how to remove it from gradle eclipse

**Comment by cdietrich** [comment]
@szarnekow didnt we do some gradle eclipse fiddling at other places ?

**Comment by szarnekow** [comment]
Yes, we tweaked the build commands and source / bin folders at a few places. Should be possible to remove natures, too.

**Comment by kthoms** [comment]
For reference: https://docs.gradle.org/current/dsl/org.gradle.plugins.ide.eclipse.model.EclipseProject.html

**Comment by cdietrich** [comment]
fixed

**Comment by kthoms** [comment]
Thanks Christian!

**Comment by kthoms** [comment]
I have set up a fresh workspace now, the popup appeared again. There must be some other location.

**Comment by kthoms** [comment]
Fixed
