### ISSUE TITLE
Use CBI pod template 'centos-7' and make JDK version configurable

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext#1812]
This is a sub task of #1804.

We need builds to use both Java 8, Java 11 and potentially other JDK versions to be prepared for building the latest target against JDK 11. Currently we use a custom container with a fixed Java version in the build. At the time of introduction the CBI images did not satisfy our needs, especially we had problems with the execution of UI tests.

Things have moved on and CBI provides different pod templates. The most suitable one was `migration`, which is [now renamed to `centos-7`](https://www.eclipse.org/lists/cross-project-issues-dev/msg17752.html).

Testing with xtext-lib and xtext-eclipse showed that the pod template is usable, and using it does simplify the Jenkinsfiles and allows Xtext to build in a more standardized way.

Additionally the JDK version should be configurable as a parameter. Eclipse CBI provides all latest JDK versions, see https://wiki.eclipse.org/Jenkins#Tools_.28and_locations_on_the_default_JNLP_agent_container.29 . With the use of a parametrized schedule we could build against the `latest` target with JDK 11.

The selected JDK version should be visible in the build's display name.

The JDK version has to be propagated to downstream builds TRIGGER_DOWNSTREAM_BUILD is set.

**Comment by kthoms** [comment]
I observe significantly better build times with using `centos-7`.

xtext-lib: 4:58 -> 3:03
xtext-core: 11 min -> 5:24
xtext-extras: 21 min -> 13 min
xtext-eclipse: 28 min -> 17 min
xtext-xtend: 46 min
xtext-maven: 25 min -> 4:40
xtext-web: 4:12 -> 1:50

**Comment by kthoms** [comment]
- Available JDK should be: adoptopenjdk hotspot "latest", "8", "11"
- Artifacts are only archived for build with JDK 8
- JDK 11 builds only for xtext-eclipse and xtext-xtend
- Examine parallel building of master with JDK 8 and 11

**Comment by Hejado** [comment]
Posting here instead of one of the PRs, but this is important. We probably need to pass the JDK parameter to downstream builds, so that the entire chain is built with the same JDK. Downstream builds that consume upstream artifacts might also need to try to download artifacts from upstream builds first, before falling back to lastStable or master branch. There might even be further implications...

**Comment by kthoms** [comment]
This is a good point. I'll update the PRs accordingly.

**Comment by kthoms** [comment]
Added parameter propagation for xtext-lib and xtext-core, works.

xtext-core got triggered by xtext-lib with JDK 11
https://ci.eclipse.org/xtext/job/xtext-core/job/kt_issue1812_parametrized_jdk/5/

```
13:59:55  Java version: 11.0.2, vendor: AdoptOpenJDK, runtime: /opt/tools/java/adoptopenjdk/hotspot-jdk-11/11.0.2
``` 

Will add the param propagation now to the other Jenkinsfiles

**Comment by kthoms** [comment]
Additional requirement: The selected JDK version should be visible in the build's display name.

**Comment by kthoms** [comment]
Done
