### ISSUE TITLE
First time user of xtext to write my spec file 

### ISSUE THREAD

**Issue by JeffGaly** [eclipse/xtext#1813]
Hello Team,

Can yo guide on xtext installation url for eclipse IDE 2020 version. Im using it for the very first time .

Thanks
Ashwini K

**Comment by cdietrich** [comment]
Hi

https://www.eclipse.org/downloads/packages/release/2020-06/r/eclipse-ide-java-and-dsl-developers

Should contain all you need

**Comment by JeffGaly** [comment]
@cdietrich  thanks a lot for prompt reply .Im getting the below error 
Unable to read repository at https://www.eclipse.org/downloads/packages/release/2020-06/r/eclipse-ide-java-and-dsl-developers.
https://www.eclipse.org/downloads/packages/release/2020-06/r/eclipse-ide-java-and-dsl-developers is not a valid repository location.

**Comment by cdietrich** [comment]
no. there you can download a complere eclipse with everything preinstalled.
you can find all xtext releases on https://download.eclipse.org/modeling/tmf/xtext/updates/composite/releases/
respectively on subsites like
https://download.eclipse.org/modeling/tmf/xtext/updates/releases/
or more specific
https://download.eclipse.org/modeling/tmf/xtext/updates/releases/2.22.0/

you can also find it on the preconfigured e.g. 2020-06 update site in your eclipse

**Comment by JeffGaly** [comment]
@cdietrich  sure i will give a try on this .Thanks a ton.

**Comment by cdietrich** [comment]
@JeffGaly did it work?

**Comment by JeffGaly** [comment]
@cdietrich Im getting this error 
An error occurred while collecting items to be installed
session context was:(profile=epp.package.java, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
No repository found containing: osgi.bundle,org.eclipse.pde.build,3.10.800.v20200410-1419
No repository found containing: osgi.bundle,org.eclipse.pde.core,3.13.400.v20200415-0531
No repository found containing: osgi.bundle,org.eclipse.pde.launching,3.8.200.v20200512-0948

**Comment by cdietrich** [comment]
what eclipse do you install to?
and did you deselect conctact all repos in the install dialog?
ususally there is the eclipse repo preconfigured in ecliupse to pull such things from e.g.
http://download.eclipse.org/releases/2020-06

**Comment by JeffGaly** [comment]
@cdietrich 
IDE version: 2020-03 (4.15.0)
yes i deselected that and selected only xtext .

**Comment by cdietrich** [comment]
nope 
you need to make sure 
http://download.eclipse.org/releases/2020-03 is enabled to pull upstream dependencies
also contact all update site must be enabeld

**Comment by cdietrich** [comment]
@JeffGaly  any update?

**Comment by kthoms** [comment]
@JeffGaly I'm closing this ticket now. Please feel free to reopen when there more issues.

**Comment by JeffGaly** [comment]
@cdietrich I still have an issue .I will try to fix it .If not i can reopen this .

**Comment by cdietrich** [comment]
If so please provide exact steps of what you are doing
