### ISSUE TITLE
Upgrade JUnit 4 to 4.13

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext#1838]
Bump [junit](https://github.com/junit-team/junit4) from 4.12 to 4.13.
- [Release notes](https://github.com/junit-team/junit4/releases)
- [Changelog](https://github.com/junit-team/junit4/blob/main/doc/ReleaseNotes4.12.md)
- [Commits](junit-team/junit4@r4.12...r4.13)

JUnit 4 4.13 is available on [current Orbit](https://download.eclipse.org/tools/orbit/downloads/drops/R20200529191137/).

* Update dependency in BOM
* Update target definitions
* Update wizard

**Comment by cdietrich** [comment]
in https://github.com/eclipse/xtext/issues/1645 we decided to do nothing

**Comment by kthoms** [comment]
Duplicates #1645
