### ISSUE TITLE
Follow up Foundation  docker.io changes

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#1842]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=566581

**Comment by cdietrich** [comment]
The bugzilla is fixed now.
i dont know if we have anything todo

cc @kthoms @Hejado

**Comment by kthoms** [comment]
I think we can consider this as no-op. The regular builds are working. Those who use a custom image are run very infrequently and thus are not affected by any pull limits. And if I understand correctly won't face pull limits now.
