### ISSUE TITLE
Avoid NPE in XTextBuildConsole

### ISSUE THREAD

**Issue by frankbenoit** [eclipse/xtext#1843]
Hi XText,

In here:
https://github.com/eclipse/xtext-eclipse/blob/master/org.eclipse.xtext.builder/src/org/eclipse/xtext/builder/debug/XtextBuildConsole.java#L50

In a unit test run, i see an exception at the end for this line.
I suspect the ConsolePlugin to be shutdown already while a logging is about to be done.
Hence a null check for `ConsolePlugin.getDefault()` could avoid the NPE.

Frank

**Comment by frankbenoit** [comment]
https://github.com/eclipse/xtext-eclipse/pull/1531

**Comment by kthoms** [comment]
Thanks, Frank!
