### ISSUE TITLE
Orbit Update Automation does not work

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#1845]
Orbit Update Automation does not work

- regex looks bad with escaping ```"```
- there seems no diff and or commit + PRs

**Comment by cdietrich** [comment]
@kthoms i give up here. i dont get https://ci.eclipse.org/xtext/job/releng/job/bot-updates/61/replay/ doing the right thing

**Comment by kthoms** [comment]
Fixed via https://github.com/eclipse/xtext-umbrella/pull/226
