### ISSUE TITLE
GitHub password authentication deprecation

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext#1856]
See https://www.eclipse.org/lists/cross-project-issues-dev/msg17920.html:

GitHub is deprecating password authentication. We need to make sure that our builds are not affected, or be fixed.

It might be necessary to use new token credentials. Also we have to check cases where we use curl to access the GitHub API, e.g. in the bot-updates job.

**Comment by cdietrich** [comment]
@kthoms @Hejado is there anything left? do we know anything failing after failover date?

**Comment by kthoms** [comment]
I don't assume so, but we did not push anything yet by jobs. Let's wait until M3 build.

**Comment by cdietrich** [comment]
@NicoPrediger @kthoms any update here?

**Comment by cdietrich** [comment]
move to 2.25

**Comment by NicoPrediger** [comment]
Well, we just released 2.24 without any authentication problems. Also, the foundation replaced all credentials, we replaced the credential ids in another issue.

I'd consider this done.
