### ISSUE TITLE
Stop building SimRel aggregation

### ISSUE THREAD

**Issue by Hejado** [eclipse/xtext#1858]
When building a release, https://ci.eclipse.org/xtext/job/releng/job/release-simrel-update/ now fails.

Apparently the maven build now requires java 11. Instead of fixing this, I'd propose to stop validating our simrel contribution altogether, since it will be validated by CBI's gerrit/jenkins anyway. Why validate twice?

In addition, our own test result may even be obsolete, if multiple gerrit changes arrive around the same time.

@kthoms @cdietrich 

WDYT?

**Comment by cdietrich** [comment]
otherwise we would need to call the simrel build with java 11 as it uses tycho 2.0

**Comment by Hejado** [comment]
https://ci.eclipse.org/xtext/job/releng/job/release-simrel-update/32/console

**Comment by Hejado** [comment]
Build failed again. Should we disable it for future releases?

**Comment by cdietrich** [comment]
ping @kthoms

**Comment by kthoms** [comment]
We should just make sure to run with Java 11. I prefer to detect problems before pushing to SimRel. I have provided an update for the job.

**Comment by kthoms** [comment]
https://ci.eclipse.org/xtext/job/releng/job/release-simrel-update/42/console demonstrates the new behavior. But the values entered had to be faked. Without any changes committed the build would fail, and with these artificial changes the simrel build would not succeed.
But you can see that Java 11 runtime is used and the simrel aggregation is built.

**Comment by Hejado** [comment]
Thanks, @kthoms
