### ISSUE TITLE
Xtext-bot creates non-normalized emf-parsley.aggrcon 

### ISSUE THREAD

**Issue by jonahgraham** [eclipse/xtext#1859]
On each new release of XText, xtext-bot needs to disable emf-parsley.aggrcon, but each time it does so it leaves the file in a non-normalized state. Can the bot be updated please? See https://git.eclipse.org/r/c/simrel/org.eclipse.simrel.build/+/170657/1/emf-parsley.aggrcon

**Comment by cdietrich** [comment]
if simrel ditches CBI this will be obsolete https://github.com/eclipse/xtext/issues/1904

**Comment by LorenzoBettini** [comment]
In any case, I removed the upper limit on Xtext, so this won't be a problem in the future anymore.

**Comment by NicoPrediger** [comment]
We removed the deactivation in 2.25.0.M1, so this shouldn't be a problem anymore.
