### ISSUE TITLE
Xtext-bot contribution message incorrect for 2020-12 M1

### ISSUE THREAD

**Issue by jonahgraham** [eclipse/xtext#1860]
The xtext-bot created a commit with the wrong subject for simrel:

https://git.eclipse.org/r/c/simrel/org.eclipse.simrel.build/+/170642

It said Xtext 2.24.0.M1 contribution to SimRel 2020-**09** when it should have been 2020-12

**Comment by cdietrich** [comment]
@jonahgraham we do this right now

```
 SIMREL_LABEL=$(grep -m 1 -o 'label="[^"]*' simrel.aggr |sed -e 's/label="//')
```

looks like simrel.aggr was not adopted yet

**Comment by cdietrich** [comment]
https://git.eclipse.org/r/c/simrel/org.eclipse.simrel.build/+/170670

**Comment by jonahgraham** [comment]
Thanks @cdietrich

**Comment by Hejado** [comment]
A hint to double check was added to our release check list.
