### ISSUE TITLE
Jenkins: release-prepare-branches should set display name

### ISSUE THREAD

**Issue by NicoPrediger** [eclipse/xtext#1869]
https://ci.eclipse.org/xtext/job/releng/job/release-prepare-branches/ should set a more speaking display name and/or description, so that one can easily see which release was prepared for every build. Some builds were already renamed manually to show how this might look.

**Comment by cdietrich** [comment]
move to 2.25

**Comment by cdietrich** [comment]
@NicoPrediger any update here?

**Comment by cdietrich** [comment]
move to 2.26

**Comment by kthoms** [comment]
Solved via https://github.com/eclipse/xtext-umbrella/pull/252
