### ISSUE TITLE
Invalid link on the Microsoft LSP website

### ISSUE THREAD

**Issue by miklossy** [eclipse/xtext#1878]
The [Microsoft LSP website](https://microsoft.github.io/language-server-protocol/implementors/servers/) refers to https://github.com/eclipse/xtext-core/blob/master/org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/LanguageServerImpl.xtend . Due to the Xtend to Java refactorings, the link should refer to https://github.com/eclipse/xtext-core/blob/master/org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/LanguageServerImpl.java

**Comment by kthoms** [comment]
Opened a PR at their repo: https://github.com/microsoft/language-server-protocol/pull/1135

**Comment by miklossy** [comment]
The PR https://github.com/microsoft/language-server-protocol/pull/1135 has been merged, now the link points to the right location.

Thanks for the fix @kthoms !

Fixed in 2.24.
