### ISSUE TITLE
why dont support array grammar?

### ISSUE THREAD

**Issue by duzhaoxi** [eclipse/xtext#1895]
I hope use a[1] to map a.get() , or a.get(offset, skip), but hard to work, confused~

**Comment by cdietrich** [comment]
hi, can you please give more context. if this is about xbase: please note that `[]` is closure syntax.

**Comment by cdietrich** [comment]
besides that you may want to check out this grammar and all customizations in the project
https://github.com/LorenzoBettini/jbase/blob/master/jbase/src/jbase/Jbase.xtext

**Comment by kthoms** [comment]
Please elaborate more about your context.

**Comment by glandon** [comment]
Thanks, i

> besides that you may want to check out this grammar and all customizations in the project
> https://github.com/LorenzoBettini/jbase/blob/master/jbase/src/jbase/Jbase.xtext

Thank you!  I implemented these functions now，including import...as and array slice.
That's great, I think should somebody maintence the jbase.

**Comment by LorenzoBettini** [comment]
> That's great, I think should somebody maintence the jbase.

I didn't have enough time to keep up Jbase with new versions of Xtext, but I hope I'll be able to keep on working on that soon. Glad it helped.
