### ISSUE TITLE
Extend IFileSystemAccess with method to write non UTF8 Files

### ISSUE THREAD

**Issue by maxweissboeck** [eclipse/xtext#1905]
The methode
	public void generateFile(String fileName, CharSequence contents);
gives us a hard time, as we need to generate non UTF8 Output.
Which is, as long as you have to use String or Char not possible at all in Java, as these are always UTF8.

So far we found no solution but to do an extra conversion from UTF8 to ANSI-1252 of the generated file after it has been written. 

Solution could be much simpler, if we had an additional method
	public void generateFile(String fileName, **ByteSequence** contents);

So please can the IFileSystemAccess Interface be extended to allow ByteSequence, Thanks.

If someone can give me a hint where to start, I will try to provide a solution for this.

Max

**Comment by cdietrich** [comment]
@maxweissboeck any reason not to use

org.eclipse.xtext.generator.IFileSystemAccessExtension3.generateFile(String, InputStream)

**Comment by maxweissboeck** [comment]
Thanks, did not see this, solved my problem!
