### ISSUE TITLE
release-prepare-branches does not fail when pushing to git fails

### ISSUE THREAD

**Issue by NicoPrediger** [eclipse/xtext#1922]
See: https://ci.eclipse.org/xtext/job/releng/job/release-prepare-branches/115/console

>  + git push --force --tags origin milestone_2.25.0.Beta
> ERROR: You must verify your email address.
> See https://github.com/settings/emails.
> 
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.

Yet:

> Finished: SUCCESS

Expected Results: Build should fail

**Comment by cdietrich** [comment]
move to 2.26

**Comment by kthoms** [comment]
I think we can close the issue.
1) release-prepare-branches now uses the current logged in user's name and email, there is no way of mistyping it
2) the job fails when push is failing. For testing I removed the "-force" on the push and tried to push the same branch (milestone_2.26.0.Beta) again. This failed with:
```
08:50:18  + git push --tags origin milestone_2.26.0.Beta
08:50:18  To git@github.com:eclipse/xtext-lib.git
08:50:18   ! [rejected]        milestone_2.26.0.Beta -> milestone_2.26.0.Beta (fetch first)
08:50:18   ! [rejected]        v2.26.0.Beta -> v2.26.0.Beta (already exists)
08:50:18  error: failed to push some refs to 'git@github.com:eclipse/xtext-lib.git'
08:50:18  hint: Updates were rejected because the tag already exists in the remote.
08:50:19  [Pipeline] }
08:50:19  [Pipeline] // dir
08:50:19  [Pipeline] }
08:50:19  $ ssh-agent -k
08:50:19  unset SSH_AUTH_SOCK;
08:50:19  unset SSH_AGENT_PID;
08:50:19  echo Agent pid 697 killed;
08:50:19  [ssh-agent] Stopped.
08:50:20  [Pipeline] // sshagent
08:50:20  [Pipeline] }
08:50:20  [Pipeline] // script
08:50:21  [Pipeline] }
08:50:21  [Pipeline] // stage
08:50:22  [Pipeline] }
08:50:22  [Pipeline] // timestamps
08:50:22  [Pipeline] }
08:50:23  [Pipeline] // timeout
08:50:23  [Pipeline] }
08:50:23  [Pipeline] // withEnv
08:50:24  [Pipeline] }
08:50:24  [Pipeline] // withEnv
08:50:25  [Pipeline] }
08:50:25  [Pipeline] // node
08:50:25  [Pipeline] }
08:50:26  [Pipeline] // podTemplate
08:50:26  [Pipeline] End of Pipeline
08:50:26  ERROR: script returned exit code 1
08:50:26  Finished: FAILURE
```
https://ci.eclipse.org/xtext/job/experimental/job/release-prepare-branches-issue1922/2/console

So this behaves as expected.

@NicoPrediger Close this issue when you agree and delete the [experimental job](https://ci.eclipse.org/xtext/job/experimental/job/release-prepare-branches-issue1922).

**Comment by NicoPrediger** [comment]
Okay, fine for me. Job is gone.
