### ISSUE TITLE
Visibility of org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.ReturnValue

### ISSUE THREAD

**Issue by grafandreas** [eclipse/xtext#1923]
The visibility of the field org.eclipse.xtext.xbase.interpreter.impl.XbaseInterpreter.ReturnValue is currently package-private (default). That makes it difficult to override some of the functionality in custom derived implementations of the interpreter (e.g. de.xx.ar.interpreter.ModelCheckerInterpreter._doEvaluate(XTryCatchFinallyExpression, IEvaluationContext, CancelIndicator) ), because  this class cannot be accessed from without the package.

Please change the visibility to add more flexibility for the creation of custom implementations.

**Comment by cdietrich** [comment]
@szarnekow looks ok. what do you think?
@miklossy could you provide a PR?

**Comment by miklossy** [comment]
I will provide a PR soon.

**Comment by miklossy** [comment]
Fixed in 2.25.
