### ISSUE TITLE
org.eclipse.xtext.ui.wizard.template is not api (yet)

### ISSUE THREAD

**Issue by vwegert** [eclipse/xtext#1962]
The generated template provider classes contain references to various interfaces in org.eclipse.xtext.ui.wizard.template - namely

```
import org.eclipse.xtext.ui.wizard.template.FileTemplate
import org.eclipse.xtext.ui.wizard.template.IFileGenerator
import org.eclipse.xtext.ui.wizard.template.IFileTemplateProvider
import org.eclipse.xtext.ui.wizard.template.IProjectGenerator
import org.eclipse.xtext.ui.wizard.template.IProjectTemplateProvider
import org.eclipse.xtext.ui.wizard.template.ProjectTemplate
```

This causes a number of "Discouraged access" warnings in the IDE because the package is not among those exported by org.eclipse.xtext.ui. All of the interfaces above are marked as `@Beta`.

**Comment by cdietrich** [comment]
i have no idea if the apis are advanced enhough to remove the internal clause from the export and the beta annotation

**Comment by vwegert** [comment]
I understand that - and I would not know either, being familiar with my rather narrow use case. I can work with the build path editing proposed by @miklossy in https://www.eclipse.org/forums/index.php?t=msg&th=1107528&goto=1839888&#msg_1839888 for the time being.

**Comment by cdietrich** [comment]
@ArneDeutsch @szarnekow what do you think?

**Comment by szarnekow** [comment]
Fine by me if we make this API.

**Comment by ArneDeutsch** [comment]
Yes, we do not plan to modify it. We can make it API.
