### ISSUE TITLE
[WARNING] label option is deprecated. To use a static pod template, use the 'inheritFrom' option.

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#1987]
[WARNING] label option is deprecated. To use a static pod template, use the 'inheritFrom' option.

https://ci.eclipse.org/xtext/job/xtext-web/job/cd_gradle6CrapExperiments/11/console

**Comment by cdietrich** [comment]
@nprediger  any idea on how to fix this?

**Comment by nprediger** [comment]
As long as the CBI team configured the podnames to equal the label, we should be able to simply replace it, see: https://ci.eclipse.org/xtext/job/xtext-web/job/cd_gradle6CrapExperiments/14/console (aborted by me after starting worked)

```
pipeline {
  agent {
    kubernetes {
      inheritFrom 'centos-7'
    }
  }
```

**Comment by cdietrich** [comment]
@nprediger  how would the solution look like for https://github.com/eclipse/xtext-umbrella/blob/master/releng/jenkins/sign-and-deploy/Jenkinsfile or similar?

**Comment by cdietrich** [comment]
TODO care about leftovers

releng/jenkins/cleanup-project-storage/Jenkinsfile
releng/jenkins/sign-and-deploy/Jenkinsfile

+ maybe others.

**Comment by cdietrich** [comment]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=575400

**Comment by cdietrich** [comment]
@nprediger any updates here?

**Comment by cdietrich** [comment]
@nprediger any updates here?

**Comment by cdietrich** [comment]
move to 2.27.0

**Comment by cdietrich** [comment]
have problems with sign and deploy
https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/1226

**Comment by cdietrich** [comment]
centos8 is still ot working for all the sign and deploy crap

**Comment by cdietrich** [comment]
TODO: mwe

**Comment by cdietrich** [comment]
done
