### ISSUE TITLE
hide Comments not working

### ISSUE THREAD

**Issue by Babwenbiber** [eclipse/xtext#1989]
I am trying to parse some content within /* */ comments.
Unfortunately, something is wrong.
Here is a mini example:

```
grammar org.xtext.example.mydsl.MyDsl with org.eclipse.xtext.common.Terminals hidden(WS, SL_COMMENT)

generate myDsl "http://www.xtext.org/example/mydsl/MyDsl"

Model:
	(numbers+=INT | comments+=MyComment)+
;

MyComment:
	'/*'( ID
	) '*/'
;
```
(Also tried `'/*' (ID) -> '/*'`)
With a content:

```
5
/*foo*/
6
```

**Expected Behavior**
Compilation succeeds and I can parse foo in the comments EList.

**Actual Behavior**
Eclipse throws an (inlined) error even before compiling:
```
Multiple markers at this line
- The word 'foo' is not correctly spelled
- missing EOF at '/*foo*/'
```

I use Xtext 2.25 and Java 16.

Let me know if you need more Infos.

**Comment by cdietrich** [comment]
you should get rid of the ML comment rule in supergrammar
e.g. by overriding it or by not inherting from
terminals and inline the terminals contents to your grammar.

**Comment by dhuebner** [comment]
Don‘t know if it is your original grammar, probably a typo, but the last terminal in mycomment rule should be '*/' not '/*'

**Comment by Babwenbiber** [comment]
> Don‘t know if it is your original grammar, probably a typo, but the last terminal in mycomment rule should be `'*/'`not `'/*'`

Yes, was a typo in the question.
The Problem remains the same.

> you should get rid of the ML comment rule in supergrammar
e.g. by overriding it or by not inherting from
terminals and inline the terminals contents to your grammar.

I believe I tried what you suggested: 
```
@Override
terminal SL_COMMENT:
	"MyVeryOwnComment!"
;
```
This comes to the very same result.

**Comment by cdietrich** [comment]
not SL_COMMENT
ML_COMMENT

**Comment by Babwenbiber** [comment]
> not SL_COMMENT
> ML_COMMENT

Thanks a lot, that did the trick!
