### ISSUE TITLE
What to do about new s****d foundation download rules

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#2012]
What to do about new s****d foundation download rules
https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/78
when we basically remove everything from our composite update sites
and also invalidate 10s of old download urls,
users will be very happy :(

**Comment by cdietrich** [comment]
see also https://github.com/eclipse/xtext/issues/1436

**Comment by cdietrich** [comment]
gonna move some downloads first. for update site, e.g. composite we have to discuss
cc @szarnekow @kthoms

**Comment by cdietrich** [comment]
https://www.eclipse.org/modeling/tmf/downloads/index.php?project=xtext&showAll=1&showMax=5&sortBy=
does not seem to see all.

@nprediger @kthoms any idea how to get source code of index.php

**Comment by nprediger** [comment]
You could use a job to ssh on projects and run `cat index.php` in the respective directory, though I hardly think the EF would like that. Not knowing if it contains credentials, I'd advice to be careful :)

**Comment by cdietrich** [comment]
did not work. now i am looking here
https://git.eclipse.org/r/c/www.eclipse.org/modeling/tmf/+/187331/2/downloads/extras-xtext.php
where i have no write access

**Comment by cdietrich** [comment]
we have updated the page now.
sebastian and dennis should have rights to merge changes in future

**Comment by cdietrich** [comment]
consider this "fixed" for now. fdn will complain if space is pressious again
