### ISSUE TITLE
Place to put @Inject extension IQualifiedNameProvider is unclear

### ISSUE THREAD

**Issue by dellerDLR** [eclipse/xtext#2022]
The docs in the extended tutorial say that:

The qualified name itself has to be obtained from a special service that is available for each language. Fortunately, Xtend allows to reuse that one easily. We simply inject the IQualifiedNameProvider into the generator.
```
      @Inject extension IQualifiedNameProvider
```
      

But it does not say, where to put the Inject. I thought it belongs above the class name, but it has to be on "member-level". If you put if above the class declaration (like a regular Java inject) you get no hints from eclipse, that the place is wrong.

I was only able to solve the problem, because someone on stackoverflow hat the same problem. There someone mentioned, that a issue on github should be created, but it seems like noone did it, so I'm posting this here.

**Comment by szarnekow** [comment]
Can you please share the stackoverflow link here?

**Comment by dellerDLR** [comment]
Sure: https://stackoverflow.com/questions/51431409/using-inject-in-an-xtend-based-xtext-code-generator
This person ran into the same problem I did.

**Comment by cdietrich** [comment]
@dellerDLR @szarnekow  what do you think of the pr

**Comment by cdietrich** [comment]
Fixed

**Comment by dellerDLR** [comment]
@cdietrich I think it does the job 👍
