### ISSUE TITLE
Switch to Reload4j

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#2028]
Observe Reload4j situation
https://github.com/qos-ch/reload4j
https://reload4j.qos.ch/

https://www.eclipse.org/lists/cross-project-issues-dev/msg18876.html

- should we use it in maven/gradle?
- what about p2/orbit?

**Comment by cdietrich** [comment]
TODO: why do `org.eclipse.xtext.ui.testing,org.eclipse.xtext.junit4,org.eclipse.xtend.standalone,xtend-annotation-examples,org.eclipse.xtext.xbase.tests` have a require bundle and not an import package.

also todo what about the fragment xtext.logging?

**Comment by szarnekow** [comment]
> require bundle 

This is certainly an oversight.

> xtext.logging

If reload4j is a drop-in replacement, we can likely change the host bundle for xtext.logging if we make a version increment.

**Comment by cdietrich** [comment]
we will fix the require bundle in 2.26 and see for the rest later

**Comment by cdietrich** [comment]
@szarnekow  do you know/remember why this https://github.com/eclipse/xtext-eclipse/blob/ffa3cf77753ebc29687768731a5d45416d2b50f1/org.eclipse.xtext.logging/META-INF/MANIFEST.MF#L5 version range is so restrictive.

**Comment by cdietrich** [comment]
org.eclipse.emf.mwe2.launcher-feature/feature.xml also directly points to org.apache.log4j

**Comment by cdietrich** [comment]
also removed direct inclusion in features. will do imports instead

**Comment by cdietrich** [comment]
reload4j is now on orbit master

**Comment by cdietrich** [comment]
looks like simrel wants to enforce to switch to new reload 4j
problem 1: https://bugs.eclipse.org/bugs/show_bug.cgi?id=578941
problem 1b: https://github.com/eclipse/xtext/issues/2042
problem 1c: https://github.com/eclipse/xtext/issues/1669
problem 1d: https://github.com/eclipse/Xpect/issues/249

**Comment by cdietrich** [comment]
@szarnekow @kthoms it would be nice if you could checkout the reload4j branches and check what i have overlooked

**Comment by cdietrich** [comment]
should we bump minimum versions in manifests too?
or skip it for now?

**Comment by szarnekow** [comment]
> should we bump minimum versions in manifests too?

I'd be strongly in favor of that, yes.

**Comment by cdietrich** [comment]
@oehme any idea why log4j still shows up here
https://scans.gradle.com/s/x2romo5ade3qu/dependencies?dependencies=log4j&expandAll&toggled=W1swLDBdLFswLDBdXQ

**Comment by oehme** [comment]
> @oehme any idea why log4j still shows up here https://scans.gradle.com/s/x2romo5ade3qu/dependencies?dependencies=log4j&expandAll&toggled=W1swLDBdLFswLDBdXQ is this the bootstrapping version at https://github.com/eclipse/xtext-web/blob/577dea708a7f60fd6c00e46ec29fd8d813f450c6/gradle/versions.gradle#L9

Yes, you can open the details of a dependency to see where it comes from:

https://scans.gradle.com/s/x2romo5ade3qu/dependencies?dependencies=log4j&expandAll&focusedDependency=WzAsMCwxMDYsWzAsMCxbMF1dXQ&focusedDependencyView=versions&toggled=W1swLDBdLFswLDBdXQ

**Comment by cdietrich** [comment]
TODO: wait for feedback
MWE + bootstrapping

**Comment by cdietrich** [comment]
consider this done
