### ISSUE TITLE
Mylyn is dead?!? remove it from Oomph

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#2052]
If i understand the messages from cross-project-issues-dev correct, mylyn is dead.
so we should drop it from oomph

**Comment by LorenzoBettini** [comment]
From what I understand, it's not dead; it's out from simrel. I'm still using it from its update site.

**Comment by szarnekow** [comment]
That's true. Given the flexibility of Oomph with user-specific configuration, I'd still prefer Mylyn to be dropped from the Oomph setup.
