### ISSUE TITLE
Switch Jenkinsfiles to Centos 8

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#2057]
we should check if we can switch Jenkinsfiles to Centos 8

**Comment by cdietrich** [comment]
https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/1163

**Comment by cdietrich** [comment]
sign and deploy still makes problem with the signing
https://github.com/eclipse/xtext/issues/1987#issuecomment-1111156813

**Comment by cdietrich** [comment]
experiment at https://github.com/xtext/gradle-sign-test https://ci.eclipse.org/xtext/job/releng/job/gradle-sign-test/

**Comment by cdietrich** [comment]
see also https://github.com/eclipse/xtext/issues/2065

**Comment by cdietrich** [comment]
it looks like centos will also be deprecated, but they dont have decided for a successor yet
https://github.com/eclipse-cbi/jiro-agents/issues/2#issuecomment-1128854297

**Comment by cdietrich** [comment]
sign & deploy is switched now too

@nprediger can we find out which jobs with no checked in jenkinsfile still use centos-7

**Comment by nprediger** [comment]
Not sure about the state of #1875 or how many of those jobs even still exist

**Comment by cdietrich** [comment]
there are no more centos7 job \o/
