### ISSUE TITLE
Create Documentation about IntelliJ+Xtext LSP

### ISSUE THREAD

**Issue by miklossy** [eclipse/xtext#2078]
The [LSP Support chapter](http://www.eclipse.org/Xtext/documentation/340_lsp_support.html) of the Xtext documentation currently describes how to use Xtext LSP in Eclipse.

I think this documentation should be extended to describe how to use Xtext LSP in IntelliJ.

I can take care of creating such a documentation if you also think that it makes sense.

**Comment by cdietrich** [comment]
so add a pointer to the documentations of the plugins or a screenshot of the config?

**Comment by miklossy** [comment]
Yes.

**Comment by cdietrich** [comment]
you might write an additional paragraph on that, yes

**Comment by miklossy** [comment]
https://github.com/eclipse/xtext/pull/2100
