### ISSUE TITLE
adapt minimum deps for platform/jdt/mwe/junit in manifests

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#2125]
adapt minimum deps for 
- [x] platform
- [x] jdt
- [x] mwe
- [x] junit 
- [x] and others in manifests

(to the version from 2022-03)

**Comment by cdietrich** [comment]
@szarnekow is there anything that speaks against bumping junit version in manifests?

**Comment by szarnekow** [comment]
> @szarnekow is there anything that speaks against bumping junit version in manifests?

No, not that I'm aware of. I think it's a good idea.

**Comment by cdietrich** [comment]
consider this done for now
