### ISSUE TITLE
jdt.compiler.(apt|tool) gone

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#2134]
jdt.compiler.(apt|tool) gone seems to be removed from jdt
@iloveeclipse @szarnekow do you know if this is intentional?
what is the replacement?

https://github.com/eclipse-jdt/eclipse.jdt.core/commit/457e2221c44b49b6f38fcdfe6d1d59467a04bf75
of course it will be painful to make this work with backwards compatibility

**Comment by cdietrich** [comment]
cc @LorenzoBettini this breaks the changes with https://github.com/eclipse/xtext-maven/issues/146

**Comment by cdietrich** [comment]
the new bundle also seems not to be a fragment anymore

**Comment by cdietrich** [comment]
only explicit usage in maven and wizard,
the question is if there is any eclipse code that relys on the fragments present,
@szarnekow do you know?

**Comment by LorenzoBettini** [comment]
IIRC, It was announced in the cross project dev mailing list as the result of refactoring of ecj. Probably for backward compatibility we could add jdt.feature to the tp? Or maybe those fragments are not needed anymore also for order tp now that we have pinned versions?

**Comment by iloveeclipse** [comment]
https://www.eclipse.org/eclipse/news/4.27/jdt.php#ecj-separated-from-core

**Comment by cdietrich** [comment]
so to be on the safe side we need to add a dependency to
org.eclipse.jdt.core.compiler.batch
where we have a dependency to jdt.core

**Comment by cdietrich** [comment]
```
find . -name "MANIFEST.MF"| xargs grep org.eclipse.jdt.core | grep -v /build/ | grep -v /target/
./xtext-eclipse/org.eclipse.xtext.ui.shared/META-INF/MANIFEST.MF: org.eclipse.jdt.core;bundle-version="3.29.0";resolution:=optional;x-installation:=greedy,
./xtext-eclipse/org.eclipse.xtext.ui/META-INF/MANIFEST.MF: org.eclipse.jdt.core;bundle-version="3.29.0";resolution:=optional;x-installation:=greedy,
./xtext-eclipse/org.eclipse.xtext.ui.tests/META-INF/MANIFEST.MF: org.eclipse.jdt.core;bundle-version="3.29.0",
./xtext-eclipse/org.eclipse.xtext.purexbase.ui/META-INF/MANIFEST.MF: org.eclipse.jdt.core;bundle-version="3.29.0",
./xtext-eclipse/org.eclipse.xtext.xbase.ui.testing/META-INF/MANIFEST.MF: org.eclipse.jdt.core;bundle-version="3.29.0";resolution:=optional;x-installation:=greedy,
./xtext-eclipse/org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.ui.tests/META-INF/MANIFEST.MF: org.eclipse.jdt.core;bundle-version="3.29.0",
./xtext-eclipse/org.eclipse.xtext.xtext.ui.examples/projects/fowlerdsl/org.eclipse.xtext.example.fowlerdsl.ui/META-INF/MANIFEST.MF: org.eclipse.jdt.core,
./xtext-eclipse/org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ui/META-INF/MANIFEST.MF: org.eclipse.jdt.core;bundle-version="3.29.0";resolution:=optional;x-installation:=greedy,
./xtext-eclipse/org.eclipse.xtext.xtext.ui.examples/projects/domainmodel/org.eclipse.xtext.example.domainmodel.ui.tests/META-INF/MANIFEST.MF: org.eclipse.jdt.core;bundle-version="3.29.0",
./xtext-eclipse/org.eclipse.xtext.xtext.ui.examples/projects/homeautomation/org.eclipse.xtext.example.homeautomation.ui.tests/META-INF/MANIFEST.MF: org.eclipse.jdt.core;bundle-version="3.29.0",
./xtext-eclipse/org.eclipse.xtext.xbase.ui.tests/META-INF/MANIFEST.MF: org.eclipse.jdt.core;bundle-version="3.29.0",
./xtext-eclipse/org.eclipse.xtext.ui.testing/META-INF/MANIFEST.MF: org.eclipse.jdt.core;bundle-version="3.29.0";resolution:=optional;x-installation:=greedy,
./xtext-eclipse/org.eclipse.xtext.common.types.shared/META-INF/MANIFEST.MF: org.eclipse.jdt.core;bundle-version="3.29.0",
./xtext-eclipse/org.eclipse.xtext.xbase.junit/META-INF/MANIFEST.MF: org.eclipse.jdt.core;bundle-version="3.29.0";resolution:=optional;x-installation:=greedy,
./xtext-eclipse/org.eclipse.xtext.xtext.ui.tests/META-INF/MANIFEST.MF: org.eclipse.jdt.core;bundle-version="3.29.0",
./xtext-eclipse/org.eclipse.xtext.purexbase.eclipse.tests/META-INF/MANIFEST.MF: org.eclipse.jdt.core;bundle-version="3.29.0",
./xtext-eclipse/org.eclipse.xtext.m2e/META-INF/MANIFEST.MF: org.eclipse.jdt.core;resolution:=optional
./xtext-eclipse/org.eclipse.xtext.xbase.ui/META-INF/MANIFEST.MF: org.eclipse.jdt.core;bundle-version="3.29.0";resolution:=optional;x-installation:=greedy,
./xtext-eclipse/org.eclipse.xtext.xbase.ui/META-INF/MANIFEST.MF: org.eclipse.jdt.core.manipulation;bundle-version="1.16.0";resolution:=optional;x-installation:=greedy,
./xtext-eclipse/org.eclipse.xtext.common.types.ui/META-INF/MANIFEST.MF: org.eclipse.jdt.core;bundle-version="3.29.0",
./xtext-eclipse/org.eclipse.xtext.common.types.ui/META-INF/MANIFEST.MF: org.eclipse.jdt.core.manipulation;bundle-version="1.16.0",
./xtext-eclipse/org.eclipse.xtext.builder.tests/META-INF/MANIFEST.MF: org.eclipse.jdt.core;bundle-version="3.29.0";resolution:=optional,
./xtext-eclipse/org.eclipse.xtext.builder/META-INF/MANIFEST.MF: org.eclipse.jdt.core;bundle-version="3.29.0";resolution:=optional;x-installation:=greedy,
./xtext-eclipse/org.eclipse.xtext.xtext.ui/META-INF/MANIFEST.MF: org.eclipse.jdt.core;bundle-version="3.29.0",
./xtext-eclipse/org.eclipse.xtext.junit4/META-INF/MANIFEST.MF: org.eclipse.jdt.core;bundle-version="3.29.0";resolution:=optional;x-installation:=greedy,
./xtext-eclipse/org.eclipse.xtext.common.types.eclipse.tests/META-INF/MANIFEST.MF: org.eclipse.jdt.core;bundle-version="3.29.0",
./xtext-xtend/org.eclipse.xtend.ide/META-INF/MANIFEST.MF: org.eclipse.jdt.core;bundle-version="3.29.0",
./xtext-xtend/org.eclipse.xtend.ide/META-INF/MANIFEST.MF: org.eclipse.jdt.core.manipulation;bundle-version="1.16.0";resolution:=optional,
./xtext-xtend/org.eclipse.xtend.ide.tests/META-INF/MANIFEST.MF: org.eclipse.jdt.core;bundle-version="3.29.0",
./xtext-xtend/org.eclipse.xtend.ide.tests/META-INF/MANIFEST.MF: org.eclipse.jdt.core.manipulation;bundle-version="1.16.0",
./xtext-xtend/org.eclipse.xtend.core/META-INF/MANIFEST.MF: org.eclipse.jdt.core;bundle-version="3.29.0";resolution:=optional;x-installation:=greedy,
./xtext-xtend/org.eclipse.xtend.standalone/META-INF/MANIFEST.MF: org.eclipse.jdt.core;bundle-version="3.29.0";visibility:=reexport,
./xtext-xtend/org.eclipse.xtend.core.tests/META-INF/MANIFEST.MF: org.eclipse.jdt.core;bundle-version="3.29.0",
./xtext-xtend/org.eclipse.xtend.examples/projects/xtend-annotation-examples/META-INF/MANIFEST.MF: org.eclipse.jdt.core,
./xtext-xtend/org.eclipse.xtend.performance.tests/META-INF/MANIFEST.MF: org.eclipse.jdt.core;bundle-version="3.29.0",
./xtext-extras/org.eclipse.xtext.xbase.testing/META-INF/MANIFEST.MF: org.eclipse.jdt.core;bundle-version="3.29.0";visibility:=reexport,
./xtext-extras/org.eclipse.xtext.common.types.tests/META-INF/MANIFEST.MF: org.eclipse.jdt.core;bundle-version="3.29.0",
./xtext-extras/org.eclipse.xtext.java/META-INF/MANIFEST.MF: org.eclipse.jdt.core;bundle-version="3.29.0",
./xtext-extras/org.eclipse.xtext.builder.standalone/META-INF/MANIFEST.MF: org.eclipse.jdt.core;bundle-version="3.29.0";resolution:=optional,
./xtext-extras/org.eclipse.xtext.generator/META-INF/MANIFEST.MF: org.eclipse.jdt.core;bundle-version="3.29.0";resolution:=optional
./xtext-extras/org.eclipse.xtext.purexbase.tests/META-INF/MANIFEST.MF: org.eclipse.jdt.core;bundle-version="3.29.0",
./xtext-core/org.eclipse.xtext.xtext.generator/META-INF/MANIFEST.MF: org.eclipse.jdt.core;bundle-version="3.29.0";resolution:=optional
```

**Comment by cdietrich** [comment]
i checked, jdt.compiler.core has a dependency to jdt.compiler.batch
thus is assume we can simply remove the tool and apt stuff and would be fine
<img width="546" alt="Bildschirmfoto 2023-01-14 um 09 15 00" src="https://user-images.githubusercontent.com/238736/212463004-a6c3d003-83e8-4bd5-8029-85a8fcc00b3a.png">

**Comment by cdietrich** [comment]
@LorenzoBettini could you try that with your usecase for https://github.com/eclipse/xtext-maven/issues/146

**Comment by iloveeclipse** [comment]
> i checked, jdt.compiler.core has a dependency to jdt.compiler.batch thus is assume we can simply remove the tool and apt stuff and would be fine

Have you actually read the notes?

> All of ECJ packages are re-exported by org.eclipse.jdt.core, therefore from OSGI point of view, all 3rd party code that used some compiler related API from org.eclipse.jdt.core doesn't require any change.

> So if some target definition, launch configuration or build file referenced the two fragments, these references can and should be removed now.

**Comment by cdietrich** [comment]
i was confused the second apt that point do "ant" like environments

**Comment by iloveeclipse** [comment]
Do you have **non OSGI based** use case where Xtext used in a plain Java application (means, no dependencies resolving via manifests through OSGI container)? In that case you need to add batch compiler bundle to the classpath.

**Comment by cdietrich** [comment]
only if users do not use maven or gradle or tycho to provide the classpath
like calling xtend compiler from ant as your company does @iloveeclipse

**Comment by cdietrich** [comment]
@iloveeclipse @merks can you tell / do you know if there are is a maven snapshot repo available for jdt and platform meanwhile?

**Comment by iloveeclipse** [comment]
We **do** use xtext from OSGI context, and that's is a different problem (too much of context)  :) 
There was only one place we had where we used **jdt core** for Java parsing from ant - and that was the only place where extra batch compiler needed now.

**Comment by merks** [comment]
This job should be doing that

https://ci.eclipse.org/releng/view/Publish%20to%20Maven/

With results published here:

https://repo.eclipse.org/content/repositories/eclipse-snapshots/

This JDT stuff indeed looks very new:

https://repo.eclipse.org/content/repositories/eclipse-snapshots/org/eclipse/jdt/

**Comment by iloveeclipse** [comment]
> This JDT stuff indeed looks very new:

Note, it still has ecj and doesn't have compiler batch. Also note, ecj **is** the compiler batch bundle.

**Comment by merks** [comment]
What is there is as expected and is correct...

There is this mapping rule:

![image](https://user-images.githubusercontent.com/208716/212466781-b27e93ad-6cdc-451c-9c8e-7c7d752aae85.png)

That produces the expected ecj artifact name:

![image](https://user-images.githubusercontent.com/208716/212466728-853c594e-e88d-4984-89b7-7d39c4e6817a.png)

That artifact has the expected symbolic name:

![image](https://user-images.githubusercontent.com/208716/212466842-cb62a520-3c6a-4fa6-8c52-efbc210fd280.png)

And eventually, when release, it will end up here as before:

https://repo1.maven.org/maven2/org/eclipse/jdt/ecj/

So what we see in this snapshot repository is what we will see after it's published to Maven central...

**Comment by cdietrich** [comment]
=> we should do a branch where we update to latest platform
and also adds 

```
<dependency>
<groupId>org.eclipse.jdt</groupId>
<artifactId>ecj</artifactId>
<version>3.33.0-SNAPSHOT</version>
</dependency>
```

to the dev bom.
+ remove all maven/gradle refs to compiler tool+apt

**Comment by cdietrich** [comment]
testing blocked by https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/811
