### ISSUE TITLE
prepare r202303target platforms and update latest to 202306/4.28 I-builds

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#2141]
prepare r202303 (target platforms and update latest to 202306/4.28 I-builds (done)

- wizard 
- xtext-eclipse 
- xtext-xtend 
- oomph

**Comment by cdietrich** [comment]
TODO: wizard and oomph are still outstanding

**Comment by LorenzoBettini** [comment]
> TODO: wizard and oomph are still outstanding

what do you mean?

Oomph has been updated to consume the nightly repo.

The wizard should not require any change, or am I missing something?

**Comment by cdietrich** [comment]
@LorenzoBettini  oomoh misses a 2023-06 target platform with 4.28 I-builds

**Comment by cdietrich** [comment]
TODO: unclear if we can keep running builds with j11 or need a switch in TargetPlatformProject

**Comment by cdietrich** [comment]
last outstanding: oomph

**Comment by cdietrich** [comment]
Oomph is done too
Todo: change default once m1 is out
