### ISSUE TITLE
Update Oomph to this new repo

### ISSUE THREAD

**Issue by LorenzoBettini** [eclipse/xtext#2148]
- [x] point to this git repository
- [x] Also update working sets
- [x] Ask the redirection for Oomph to this new setup

**Comment by LorenzoBettini** [comment]
For the time being, I created new working sets https://github.com/eclipse/xtext/commit/4386dfc10927fc8a54fbf87c973f520f14acf149

Features
Tests
Examples
Releng
Main Projects

We can change them in the future. For sure, the current ones did not apply anymore ;)

**Comment by LorenzoBettini** [comment]
@merks we'd like to change the reference to the Xtext setup to this new location now that we merged all repos into this one

https://raw.githubusercontent.com/eclipse/xtext/main/releng/org.eclipse.xtext.contributor/Xtext.setup

should I open a bug in bugzilla or somewhere else?

thanks in advance

**Comment by merks** [comment]
This build made the changes available in the setups.zip:

https://ci.eclipse.org/oomph/job/setup-archiver/46681/

So that should be visible very shortly.

**Comment by LorenzoBettini** [comment]
Thank you @merks ! :)
