### ISSUE TITLE
Nightly & Daily Jobs

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#2149]
- change the nightly / milestone / release build to run with java 11  and r202203 platform
- introduce daily builds (without deploy) to run with java 17 / latest platform and also tycho 3.x and 4.0.0-SNAPSHOT

**Comment by cdietrich** [comment]
have deactivated daily xtext-eclipse/xtext-xtend and xtext-umbrella and the gradle based nightly deploy jobs

**Comment by cdietrich** [comment]
the default for the main branch is also Java 11 and r202203 now

**Comment by LorenzoBettini** [comment]
@cdietrich I need some help here: what is a job I can use as a starting point for the daily build with latest? Or, if you know already what to do, could you please take care of that?

**Comment by cdietrich** [comment]
Please check xtext-eclipse before my last commit

**Comment by LorenzoBettini** [comment]
@cdietrich let's see whether it works tomorrow and then we can close it

**Comment by cdietrich** [comment]
also added a branch for tycho 4.0.0-SNAPSHOT. with that this is finally done
