### ISSUE TITLE
Cleanup Maven plugins ITs

### ISSUE THREAD

**Issue by LorenzoBettini** [eclipse/xtext#2158]
@cdietrich @szarnekow this line https://github.com/eclipse/xtext/blob/main/org.eclipse.xtend.maven.plugin/src/test/resources/it/pom.xml#L13 scares me a lot!

It means that we run the IT projects using the currently released version of Xtext, NOT the currently developed version. We might release a new version of xtend-maven-plugin that does not work with the same released version of Xtext.

I'd apply the same strategy as in https://github.com/xtext/xtext-monorepo/pull/17 so that the integration tests are using the same artifacts of the current sources, OK?

**Comment by cdietrich** [comment]
@LorenzoBettini this is new to me in xtext-xtend. we do all the "local repo foo"
to run the tests against the plugin we build right before,
picking up the stuff built by the gradle plugin.

```
		<profile>
			<id>useJenkinsSnapshots</id>
			<repositories>
				<repository>
					<id>local-repo</id>
					<url>${gradleMavenRepo}</url>
				</repository>
```

```
<plugin>
				<artifactId>maven-antrun-plugin</artifactId>
				<executions>
					<execution>
						<id>create-jar</id>
						<phase>pre-integration-test</phase>
						<configuration>
							<skip>${maven.test.skip}</skip>
							<target>
								<property name="src.jar"
									value="${project.build.directory}/${project.build.finalName}.jar" />
								<property name="it.jar.name" value="${project.build.finalName}-it" />
								<property name="it.jar.directory"
									value="${project.build.directory}/${it.jar.name}" />
								<unzip src="${src.jar}" dest="${it.jar.directory}" />
								<replaceregexp file="${it.jar.directory}/META-INF/maven/plugin.xml"
									match="&lt;version&gt;(.*)&lt;/version&gt;" replace="&lt;version&gt;IT-SNAPSHOT&lt;/version&gt;"
									byline="false" />
								<jar destfile="${project.build.directory}/${it.jar.name}.jar"
									basedir="${it.jar.directory}" />
							</target>
						</configuration>
						<goals>
							<goal>run</goal>
						</goals>
					</execution>
					<execution>
						<id>touch-jar</id>
						<phase>pre-integration-test</phase>
						<configuration>
							<target>
								<property name="it.jar.name" value="${project.build.finalName}-it" />
								<touch file="${project.build.directory}/${it.jar.name}.jar" />
							</target>
						</configuration>
						<goals>
							<goal>run</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
```

**Comment by LorenzoBettini** [comment]
@cdietrich I had already removed the gradle foo (maybe there are some properties left that are not used anymore). The problem is still the version of the BOM, which should NOT be a version different from the current one.

**Comment by LorenzoBettini** [comment]
This also looks wrong to me https://github.com/eclipse/xtext/blob/main/org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/pom.xml#L15

we should not use a fixed version here: if we bump our versions we should remember to update that as well.
Instead, we should rely on resource filtering to automatically keep that up-to-date.
This would allow us also to get rid of that preprocessing of our plugin version with IT-SNAPSHOT https://github.com/eclipse/xtext/blob/main/org.eclipse.xtext.maven.plugin/pom.xml#L150

**Comment by cdietrich** [comment]
might also fix problems like this
https://ci.eclipse.org/xtext/job/xtext/job/main/48/testReport/junit/org.eclipse.xtend.maven/XtendCompilerMojoIT/simpleProjectXtend2Tests/

**Comment by LorenzoBettini** [comment]
Indeed! It also happened on GitHub actions
