### ISSUE TITLE
Some test bundles are published in the p2 site

### ISSUE THREAD

**Issue by LorenzoBettini** [eclipse/xtext#2159]
Due to the merging of all the split repos' p2 repositories.
I'll fix that ASAP.

**Comment by LorenzoBettini** [comment]
Also this project doesn't seem to be needed anymore `org.eclipse.xtend.p2repository`

**Comment by cdietrich** [comment]
yes all temp p2 repos from lib,core,extras,eclipse and xtend should no longer be needed
