### ISSUE TITLE
Get rid of the mwe2 dummy feature?

### ISSUE THREAD

**Issue by LorenzoBettini** [eclipse/xtext#2160]
I think this project and feature https://github.com/eclipse/xtext/blob/main/org.eclipse.emf.mwe2.language.sdk.dummy/feature.xml can be removed.

@cdietrich do you remember why it was there besides the comment in the feature?

**Comment by LorenzoBettini** [comment]
I try to remove it and see what happens

**Comment by LorenzoBettini** [comment]
@cdietrich It is still required:

```
Error:  Cannot resolve project dependencies:
Error:    Software being installed: org.eclipse.xtext.generator.feature.group 2.31.0.qualifier
Error:    Missing requirement: org.eclipse.xtext.sdk.feature.group 2.31.0.qualifier requires 'org.eclipse.equinox.p2.iu; org.eclipse.emf.mwe2.language.sdk.feature.group 2.14.0' but it could not be found
Error:    Cannot satisfy dependency: org.eclipse.xtext.generator.feature.group 2.31.0.qualifier depends on: org.eclipse.equinox.p2.iu; org.eclipse.xtext.sdk.feature.group 0.0.0
```

I'll close this one

**Comment by LorenzoBettini** [comment]
On second thought: it should be enough to put the `org.eclipse.emf.mwe2.language.sdk.feature.group` in the target platform. I'll try later.

**Comment by cdietrich** [comment]
@LorenzoBettini  yes i assume it is needed for
`      <import feature="org.eclipse.emf.mwe2.language.sdk" version="2.14.0" match="greaterOrEqual"/>`
but i am not sure how the bootstrap/bump cycle can be done when we consume from mwe update site
that might be the reason why we do it like that.

- we create a new mwe that needs a newer xtext
- we add this to the target in xtext (as a nightly) + the previous xtext nightly?
- or do we have to first build a milestone xtext version. then use that one in mwe
- then use the milestone xtext and the mwe milestone in the target.
- then build next xtext milestone

**Comment by LorenzoBettini** [comment]
@cdietrich if you already heavily rely on this dummy feature for easy bootstrapping new versions of mwe and/or Xtext, then it's better to leave things as they are :)
