### ISSUE TITLE
Refactor the contents of Xtend SDK

### ISSUE THREAD

**Issue by LorenzoBettini** [eclipse/xtext#2169]
Currently, the `xtend.sdk.feature` has

```xml
   <requires>
      <import feature="org.eclipse.xtext.ui" version="2.31.0" match="equivalent"/>
      <import feature="org.eclipse.xtext.xbase.lib" version="2.31.0" match="equivalent"/>
      <import plugin="org.eclipse.xtend.lib" version="2.31.0" match="equivalent"/>
      <import plugin="org.eclipse.xtend.lib.macro" version="2.31.0" match="equivalent"/>
      <import plugin="org.eclipse.xtend.lib.source" version="2.31.0" match="equivalent"/>
      <import plugin="org.eclipse.xtend.lib.macro.source" version="2.31.0" match="equivalent"/>
      <import plugin="com.google.guava" version="30.1.0" match="compatible"/>
      <import plugin="io.github.classgraph" version="4.8.149" match="compatible"/>
      <import plugin="org.apache.log4j" version="1.2.24" match="equivalent"/>
   </requires>
```

The version 2.31.0 match=equivalent means that 2.31.1 is acceptable, but 2.32.0 is NOT. We rarely publish versions of the shape 2.31.1. Having that version range doesn't make much sense. The version range on the source bundles is even worse: it breaks the version bump scripts I'm working on, which are based on the standard Maven/Tycho plugin for bumping versions. The plugins can detect that the version of required bundles has to be increased but since the source bundles do not exist (they are produced later during the build) it cannot increment them.

In any case, it doesn't make sense to "require" things that we implement and are in our update site: we should include them. That's what we do in other features. I guess it is like that because of the split repo?

Not to mention that `xtend.lib.macro` and `xtend.lib` are in our `xtend.lib.feature`, so we could simply include the feature. By the way, we don't publish `xtend.lib.feature` but we should.

Summarizing, I propose to publish `xtend.lib.feature`, include that in `xtend.sdk.feature`.
Concerning the required `xtext.ui` and `org.eclipse.xtext.xbase.lib`, we could also leave them like that, though I'd guess we could simply include them instead of require them.

@cdietrich @szarnekow what do you think?

**Comment by cdietrich** [comment]
The question is. How can we avoid a wild mix is used

**Comment by LorenzoBettini** [comment]
What do you mean by "wild mix"? If you mean using different versions of Xtext bundles and features then the solution is once again "including" instead of "requiring": when you include a bundle or feature in your feature the build will automatically set the exact version match as exact, corresponding to the published included feature/bundle.
That is why our stuff should always be **included**, NOT **required**, in our features.

For example, this is how an included plugin looks like in a published feature:

```xml
   <plugin
         id="org.eclipse.xtend.core"
         download-size="1386"
         install-size="3807"
         version="2.31.0.v20230331-0150"
         unpack="false"/>
```

This corresponds to the original source

```xml
   <plugin
         id="org.eclipse.xtend.core"
         download-size="0"
         install-size="0"
         version="0.0.0"
         unpack="false"/>
```

On the contrary, requirements stay the same in the published feature.

**Comment by cdietrich** [comment]
The problem is I can say zero on the history of features. Maybe Sebastian can

**Comment by LorenzoBettini** [comment]
OK, let's see what @szarnekow says.

What I propose is safe and the recommended way ;)
