### ISSUE TITLE
Phase old repos out

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#2173]
fix orbit inconsistency
- [x] add hint to readme
- [x] decide on which prs and issues to move?!?
- [x] Check if we still need a 2.28.1 release
- [x] make them readonly / archive

**Comment by cdietrich** [comment]
@szarnekow @LorenzoBettini i propose this text. what do you think:

```
## Notice

The content of this repository (`xtext-...`) has been moved/merged into the [Xtext Monorepo](https://github.com/eclipse/xtext/). Please refer to that repository to find the code, create issues or file pull requests.
```

**Comment by szarnekow** [comment]
I agree.

**Comment by LorenzoBettini** [comment]
Me too!

**Comment by cdietrich** [comment]
@LorenzoBettini @szarnekow the issue transfer seems to work.
the question is: do we want to do it for all, or just selectively

**Comment by LorenzoBettini** [comment]
@cdietrich I wouldn't know... if there are some issues/PRs that are really interesting we might leave them open, though with the message that the repository has moved.

**Comment by cdietrich** [comment]
i have closed almost all prs already.
this is more about issues

**Comment by cdietrich** [comment]
- unfortunately it does not seem possible to make issues readonly besides archiving the complete project
- archiving the projects also will make it impossible to push stuff, so e.g. testing xtext-xtend to test the gradle stuff also wont work. guess i would need a private fork then.

**Comment by HannesWell** [comment]
I would suggest to move all issues to this repo, this might be many but that's better than having them lost (somewhere else is also some kind of lost to me).

**Comment by HannesWell** [comment]
Btw. in platform we made a final commit where we deleted the content of the repo (the history is of course preserved) to have a 'lightweight' archiving. This way one will definitely notice the move when fetching the repo.

**Comment by cdietrich** [comment]
2.28.1 release was done yesterday.

**Comment by cdietrich** [comment]
@szarnekow @LorenzoBettini should we start archiving the repos?

**Comment by szarnekow** [comment]
Yes, I think it's time.

**Comment by cdietrich** [comment]
repos archied. https://projects.eclipse.org/projects/modeling.tmf.xtext/developer still shows it.
never managed this so there might be a sync job on fdn side. asked back
