### ISSUE TITLE
Update to 2023-03 platform in maven/bom

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#2174]
Update to 2023-03 platform in maven/bom
see also https://github.com/eclipse/xtext/issues/2134

to my knowledge this is the last Java 11 version

**Comment by cdietrich** [comment]
move to 2023-09

**Comment by LorenzoBettini** [comment]
Hadn't this already been approved for merging?

**Comment by cdietrich** [comment]
yes but i did not find enhough time to test with all my maven and gradle test project in time for m3
