### ISSUE TITLE
LSP: replace SymbolInformation with Document/Workspace symbol

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#2179]
SymbolInformation is deprecated, we should replace them with Document/Workspace symbol
(in DocumentSymbolService)

- new are range and selection
- hierarchical

see also HierarchicalDocumentSymbolService/WorkspaceSymbolService

also the interface impl usage DocumentSymbolService/IDocumentSymbolService seems inconsitent

**Comment by shashwatanand** [comment]
Hi @cdietrich,

I was looking into this issue to get more knowledge regarding the process.
To fix this issue below is an approach that I thinking to take.
Modify `org.eclipse.xtext.ide.server.symbol.IDocumentSymbolService` and the update other impacted classes and tests


```
diff --git a/org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/symbol/IDocumentSymbolService.java b/org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/symbol/IDocumentSymbolService.java
index 67aac2e6f2..e211e4ce71 100644
--- a/org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/symbol/IDocumentSymbolService.java
+++ b/org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/symbol/IDocumentSymbolService.java
@@ -15,6 +15,7 @@ import java.util.List;
 import org.eclipse.lsp4j.DocumentSymbol;
 import org.eclipse.lsp4j.DocumentSymbolParams;
 import org.eclipse.lsp4j.SymbolInformation;
+import org.eclipse.lsp4j.WorkspaceSymbol;
 import org.eclipse.lsp4j.jsonrpc.messages.Either;
 import org.eclipse.xtext.ide.server.Document;
 import org.eclipse.xtext.ide.server.symbol.IDocumentSymbolService.Noop;
@@ -40,13 +41,13 @@ import com.google.inject.ImplementedBy;
 @ImplementedBy(Noop.class)
 public interface IDocumentSymbolService {
 
-       List<Either<SymbolInformation, DocumentSymbol>> getSymbols(Document document, XtextResource resource,
+       List<Either<DocumentSymbol, WorkspaceSymbol>> getSymbols(Document document, XtextResource resource,
                        DocumentSymbolParams params, CancelIndicator cancelIndicator);
 
        public static class Noop implements IDocumentSymbolService {
 
                @Override
-               public List<Either<SymbolInformation, DocumentSymbol>> getSymbols(Document document, XtextResource resource,
+               public List<Either<DocumentSymbol, WorkspaceSymbol>> getSymbols(Document document, XtextResource resource,
                                DocumentSymbolParams params, CancelIndicator cancelIndicator) {
 
                        return emptyList();
```


As `SymbolInformation` is still needed in `org.eclipse.lsp4j.services.TextDocumentService.documentSymbol(DocumentSymbolParams)}` so in `org.eclipse.xtext.ide.server.LanguageServerImpl.documentSymbol(DocumentSymbolParams)`, we can convert DocumentSymbol to SymbolInformation.

Please let me know if this approach is Okay or if there is some other expectation.

Thanks
Shashwat

**Comment by cdietrich** [comment]
Hi @shashwatanand , i did  not look into that yet.
but if i understand it correct

- SymbolInformation is deprecated, we should not use it besides in signatures as it will be removed one day.
- TextDocumentService.documentSymbol should return Either with DocumentSymbols
- WorkspaceService.symbol should return Either with WorkspaceSymbols

=> unclear where SymbolInformatioan is still needed outside signatures?

@tivervac @szarnekow  any comments from your side as users of xtext lsp?

**Comment by shashwatanand** [comment]
The current signature of `TextDocumentService.documentSymbol` should return `CompletableFuture<List<Either<SymbolInformation, DocumentSymbol>>>`. 

This is a reason why lsp4j is not annotated SymbolInformation with Deprecated annotation till now.

**Comment by cdietrich** [comment]
i assume yes. but as said it should be used in signatures only, not in actual instances with this change

**Comment by tivervac** [comment]
@cdietrich We're fine with no backwards compatibility. We prefer to have no deprecations at all. To allow this I would suggest just tagging any LSP class as `@Beta` as they do not guarantee backwards compatibility

**Comment by shashwatanand** [comment]
Hi @cdietrich 

I went through your review comments. I don't think `org.eclipse.xtext.ide.server.LanguageServerImpl.documentSymbol(DocumentSymbolParams` can return only `DocumentSymbol`.

When the document service is of type `HierarchicalDocumentSymbolService` type then we need to return `DocumentSymbol` in `Either` (in right) and when the service is of `DocumentSymbolService` then we need to return `SymbolInformation` in `Either` (in left).
Sample model:
```
"type Foo {\n" +
"	int bar\n" +
"}\n" +
"type Bar {\n" +
"	Foo foo\n" +
"}\n";
```
Expected symbols -- in the case of DocumentSymbolService - it finds the symbols using DFS
```
"symbol \"Foo\" {\n" +
"	kind: 7\n" +
"	location: MyModel.testlang [[0, 5] .. [0, 8]]\n" +
"}\n" +
"symbol \"Foo.bar\" {\n" +
"	kind: 7\n" +
"	location: MyModel.testlang [[1, 5] .. [1, 8]]\n" +
"	container: \"Foo\"\n" +
"}\n" +
"symbol \"Foo.bar.int\" {\n" +
"	kind: 7\n" +
"	location: MyModel.testlang [[1, 1] .. [1, 4]]\n" +
"	container: \"Foo.bar\"\n" +
"}\n" +
"symbol \"Bar\" {\n" +
"	kind: 7\n" +
"	location: MyModel.testlang [[3, 5] .. [3, 8]]\n" +
"}\n" +
"symbol \"Bar.foo\" {\n" +
"	kind: 7\n" +
"	location: MyModel.testlang [[4, 5] .. [4, 8]]\n" +
"	container: \"Bar\"\n" +
"}\n";
```
Expected symbol-- in the case of HierarchicalDocumentSymbolService
```
"symbol \"Foo\" {\n" +
"    kind: 7\n" +
"    range: [[0, 0] .. [2, 1]]\n" +
"    selectionRange: [[0, 5] .. [0, 8]]\n" +
"    details: \n" +
"    deprecated: false\n" +
"    children: [\n" +
"        symbol \"Foo.bar\" {\n" +
"            kind: 7\n" +
"            range: [[1, 1] .. [1, 8]]\n" +
"            selectionRange: [[1, 5] .. [1, 8]]\n" +
"            details: \n" +
"            deprecated: false\n" +
"            children: [\n" +
"                symbol \"Foo.bar.int\" {\n" +
"                    kind: 7\n" +
"                    range: [[1, 1] .. [1, 4]]\n" +
"                    selectionRange: [[1, 1] .. [1, 4]]\n" +
"                    details: \n" +
"                    deprecated: false\n" +
"                }\n" +
"            ]\n" +
"        }\n" +
"    ]\n" +
"}\n" +
"symbol \"Bar\" {\n" +
"    kind: 7\n" +
"    range: [[3, 0] .. [5, 1]]\n" +
"    selectionRange: [[3, 5] .. [3, 8]]\n" +
"    details: \n" +
"    deprecated: false\n" +
"    children: [\n" +
"        symbol \"Bar.foo\" {\n" +
"            kind: 7\n" +
"            range: [[4, 1] .. [4, 8]]\n" +
"            selectionRange: [[4, 5] .. [4, 8]]\n" +
"            details: \n" +
"            deprecated: false\n" +
"        }\n" +
"    ]\n" +
"}\n";```
```
Please let me know how I should proceed
1) Both `HierarchicalDocumentSymbolService` and `DocumentSymbolService` should return `DocumentSymbol` then I will go ahead and adapt the test and then we may not need `org.eclipse.xtext.testing.AbstractLanguageServerTest.hierarchicalDocumentSymbolSupport` and `org.eclipse.xtext.ide.server.symbol.DocumentSymbolService.createSymbol(String, DocumentSymbol, Function1<? super DocumentSymbol, ? extends String>)` too.

2) Or keep returning `WorkspaceSymbol` and `DocumetSymbol` - then where I should convert `WorkspaceSymbol` to `SymbolInformation`

Thanks
Shashwat

**Comment by cdietrich** [comment]
Can’t the left right be done in language Server impl and in the service just a plain list ???

**Comment by cdietrich** [comment]
And you should never convert to the deprecated class

**Comment by shashwatanand** [comment]
If we don't convert to SymbolInformation
org.eclipse.xtext.ide.server.LanguageServerImpl.documentSymbol(DocumentSymbolParams) should return DocumentSymbol (in right)

then I need to adapt the test `org.eclipse.xtext.ide.tests.server.DocumentSymbolTest.testDocumentSymbol_01()` so it should except DocumentSymbol which doesn't have `container` and `location` information

then only difference between `HierarchicalDocumentSymbolService` and `DocumentSymbolService` will DocumentSymbolService will find symbol using DFS.

**Comment by cdietrich** [comment]
Yes tests may need adaptation

**Comment by cdietrich** [comment]
Thx for the fix @shashwatanand
