### ISSUE TITLE
packages o.c.x.generator.trace.node can be API?

### ISSUE THREAD

**Issue by frankbenoit** [eclipse/xtext#2188]
At the moment the packages

org.eclipse.xtext.generator.trace.node
org.eclipse.xtext.generator.trace

Are both having discouraged access, because they are marked to be accessible only by x-friends.
But they are documented in public examples to be used. Should they then also be just accessible without the warning?

**Comment by cdietrich** [comment]
i am not sure if the code is robust enhough to be public api
