### ISSUE TITLE
Wizard: Update to Junit 5.9.2

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#2197]
Wizard: Update to Junit 5.9.2

**Comment by laeubi** [comment]
You are probably using a JUnit5 classpath container in your project, then the import is superfluous and might lead to some confusion here when you mix older tycho versions with newer eclipse releases.

**Comment by cdietrich** [comment]
thx that seems to help

**Comment by LorenzoBettini** [comment]
IIRC, the JUnit5 classpath container is required to run tests from Eclipse.
I also seem to remember that also the import package was needed... at least some time ago, maybe things have changed now.

**Comment by cdietrich** [comment]
meh. asusme we have to add vintage enginge for eclipse :(

**Comment by cdietrich** [comment]
runnings works anyway but you have tlo select junit 4 for junit 4 tests without viontage engine

**Comment by laeubi** [comment]
As said, if you mix old stuff with new stuff then there is some chance that something gets mixed up.
We now have a page describing all setups and a demos, if anything is missing it would be good to add an example and/or test: https://tycho.eclipseprojects.io/doc/master/TestingBundles.html

**Comment by cdietrich** [comment]
possible workaround for testing project: create a separate testing.tests project instead of having tests in the bundle

**Comment by LorenzoBettini** [comment]
> possible workaround for testing project: create a separate testing.tests project instead of having tests in the bundle

but here I read: https://tycho.eclipseprojects.io/doc/master/TestingBundles.html

> You use the eclipse-test-plugin packaging, and with those your plugin must only contain test-classes and they will be executed automatically as part of the integration-test phase of your build. This aproach is not recommended for new designs.

However, is it working now?
Did you keep the JUnit5 classpath container and removed the imported bundles?

**Comment by cdietrich** [comment]
i have to remove the container to get tyhco work
i need to select junit4 in the run as dialog as i had to do in gradle without vintage enging
junit5 tests seems to work ootb without container

**Comment by LorenzoBettini** [comment]
> i have to remove the container to get tyhco work i need to select junit4 in the run as dialog as i had to do in gradle without vintage enging junit5 tests seems to work ootb without container
> 
> removing the import package is not an option as it wont work in shipped code

mh... sad to hear that... which project are we talking about?
Could you please save two launch configurations in the project? One for running JUnit4 tests and one for JUnit5 tests. Otherwise, it might not be clear how to run tests from Eclipse.

**Comment by laeubi** [comment]
> but here I read

As far as I know this is using tests executed not with an extra plugin but with the same project as the code (not 100% sure) also I'm not sure what Tycho version is used (the documentation is mostly for Tycho 3+) nor what Eclipse release is targeted.

All this can / will influence what features can be used / combined :-)

**Comment by LorenzoBettini** [comment]
> @laeubi
> 
> tycho reports
> 
> ```
> [INFO] {osgi.os=macosx, osgi.ws=cocoa, org.eclipse.update.install.features=true, osgi.arch=x86_64}
> [ERROR] Cannot resolve project dependencies:
> [ERROR]   You requested to install 'org.eclipse.equinox.p2.iu; org.junit.jupiter.api [5.0.0,6.0.0)' but it could not be found
> [ERROR]
> ```
> 
> although there is a import package only and not a require bundle. any idea where this could be coming from or how to debug
> 
> https://github.com/eclipse/xtext/actions/runs/4628190858/jobs/8186980457#step:6:50

What looks strange to me is that we don't have that version range `[5.0.0,6.0.0)` in that project. We have `[5.1.0,6.0.0)`; so I don't understand where that installation requirement comes from.

**Comment by cdietrich** [comment]
caause we started junit 5 with junit 5.1

**Comment by cdietrich** [comment]
https://github.com/eclipse-jdt/eclipse.jdt.ui/commit/dc19a3bca7474410f9bb86adbb8b262eaa30d77b
=> might need to use old for 202203 and 202206

**Comment by cdietrich** [comment]
am experimenting on cd_junit592intarget_anothertry branch

**Comment by cdietrich** [comment]
yes but i am still unsure about toolchains and java 11.
the problem is i have zero experience in that area

**Comment by cdietrich** [comment]
yes but this would open the tycho problem again if we use newer junit5 in java 11 / r202203 tp

**Comment by LorenzoBettini** [comment]
I thought you had proposed to use the new junit5 only in the latest target platform

**Comment by cdietrich** [comment]
yes but this does not work with tycho 2.7.5.
tycho 2.7.5 wants old bundles for junit5 container

=> we cannot have use tycho 3 with new maven junit5 stuff everywhere.
=> maybe i get your proposal wrong

**Comment by cdietrich** [comment]
yes but i still dont understand why.

**Comment by cdietrich** [comment]
=> use tycho 3.x as default.
adapt java 11 build to use older tycho.
keep old target for 202203 and 202206

**Comment by cdietrich** [comment]
if we go this route and use tycho 2.7 for 202203 and 202206 then it should work both modes
but i assume we then need a tycho version via profile or via param in jenkinsfile

**Comment by cdietrich** [comment]
@szarnekow what do you think? extra harm with add. tests bundles?

**Comment by szarnekow** [comment]
I think it's a fair cleanup.

**Comment by cdietrich** [comment]
https://github.com/eclipse/xtext/pull/2218

**Comment by laeubi** [comment]
I'm not sure what are the concerns / problems with toolchains, but technically you only need a toolchain if you want to compile /run with an "real" java 11 JVM.
Beside that setting up a toolchain is quite trivial (github action set one up by default already).

**Comment by cdietrich** [comment]
@laeubi  the point is:
we want the same build to run (especially tests) with java 11 and with java 17

**Comment by LorenzoBettini** [comment]
But in different jobs

**Comment by cdietrich** [comment]
yes but easy to use like: mvn doitwithj11 and mvn doitwithj17

**Comment by LorenzoBettini** [comment]
From what I know, once everything is configured, it's just a matter of passing a property, or, better, enabling a profile

**Comment by cdietrich** [comment]
yes. my qustion is: how does this work with tycho 3 and maven toolchains. as said i have zero experience with them.

**Comment by laeubi** [comment]
> yes. my qustion is: how does this work with tycho 3 and maven toolchains. as said i have zero experience with them.

See https://tycho.eclipseprojects.io/doc/latest/tycho-surefire-plugin/test-mojo.html#useJDK

**Comment by cdietrich** [comment]
should be done now. tycho updates / toolchain will be handled on different issues
