### ISSUE TITLE
Flaky mac tests on Github Actions

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#2199]
we should check what we can do about the very flaky mac tests on Github Actions

**Comment by LorenzoBettini** [comment]
As I was proposing in another issue, I'd try with this one:

https://tycho.eclipseprojects.io/doc/latest/tycho-surefire-plugin/integration-test-mojo.html#rerunFailingTestsCount

it should be enough to pass `-Dsurefire.rerunFailingTestsCount=2`

**Comment by LorenzoBettini** [comment]
I created https://github.com/eclipse/xtext/tree/lb_2199_flaky_tests
let's see if that helps
