### ISSUE TITLE
macOS failure in GitHub Actions

### ISSUE THREAD

**Issue by LorenzoBettini** [eclipse/xtext#2229]
the build on GitHub Actions in macOS started to fail like that consistently:

```
Downloaded from central: https://repo.maven.apache.org/maven2/org/eclipse/emf/org.eclipse.emf.mwe2.launch/2.14.0/org.eclipse.emf.mwe2.launch-2.14.0.pom
...
Error:  Failed to execute goal on project org.eclipse.xtext.common.types.tests: Could not resolve dependencies for project org.eclipse.xtext:org.eclipse.xtext.common.types.tests:jar:2.31.0-SNAPSHOT: Failed to collect dependencies at org.eclipse.emf:org.eclipse.emf.mwe2.language:jar:2.14.0: Failed to read artifact descriptor for org.eclipse.emf:org.eclipse.emf.mwe2.language:jar:2.14.0: The following artifacts could not be resolved: org.eclipse.emf:org.eclipse.emf.mwe2.language:pom:2.14.0 (absent): Could not transfer artifact org.eclipse.emf:org.eclipse.emf.mwe2.language:pom:2.14.0 from/to central (https://repo.maven.apache.org/maven2): Connection reset -> [Help 1]
```

These are my suspects:

- macOS uses Maven 3.9.1, which might have introduced some breakage
- The really strict version in mwe2.launch https://github.com/eclipse/mwe/blob/master/plugins/org.eclipse.emf.mwe2.launch/pom.xml#L21 "[version]" is even stricter than "version"

Concerning the second point, https://books.sonatype.com/mvnref-book/reference/pom-relationships-sect-project-dependencies.html#pom-relationships-sect-version-ranges seems to discourage that syntax:

> When declaring a "normal" version such as 3.8.2 for Junit, internally this is represented as "allow anything, but prefer 3.8.2." This means that when a conflict is detected, Maven is allowed to use the conflict algorithms to choose the best version. If you specify [3.8.2], it means that only 3.8.2 will be used and nothing else. If somewhere else there is a dependency that specifies [3.8.1], you would get a build failure telling you of the conflict. We point this out to make you aware of the option, but use it sparingly and only when really needed. The preferred way to resolve this is via dependencyManagement.

**Comment by cdietrich** [comment]
@LorenzoBettini wasnt this just a network issue? maybe github actions has some problems in their mac networking

**Comment by LorenzoBettini** [comment]
@cdietrich No, it fails consistently at the same point.

Using `-U` makes it work (https://github.com/LorenzoBettini/xtext/commit/85b690d4406da716e17cecfa273a9c1189abc64b) but that sounds wrong to me, since that is NOT a SNAPSHOT version.

**Comment by LorenzoBettini** [comment]
@cdietrich as an alternative to update snapshots, listing all the transitive dependencies also works: https://github.com/LorenzoBettini/xtext/commit/e16eec3307f06c55ca4d1db71d6b98f34cee3b14

I'd prefer this second solution, what do you think?

I still think that the versions in mwe2 should not be "[...]" but "..."

**Comment by cdietrich** [comment]
problem still happens. 
of course i cannot reproduce locally. also not with maven 3.9.1

**Comment by cdietrich** [comment]
@LorenzoBettini i guess we can give it a try withn that. can you open a pr

**Comment by cdietrich** [comment]
other stuff to look at
https://github.com/GoogleContainerTools/skaffold/issues/5248
https://github.com/actions/runner-images/issues/1499

**Comment by LorenzoBettini** [comment]
I pushed (force) this branch using the Maven wrapper in GitHub Actions: https://github.com/eclipse/xtext/tree/lb_2229_GH_macOS_failure

on my fork it works, let's see here...

**Comment by LorenzoBettini** [comment]
@cdietrich as I suspected, the wagon properties as you did in your commit https://github.com/eclipse/xtext/commit/d7f15b0459bd860b2708b18a2e5df5d2fb7b5748 don't help with Maven 3.9.1

**Comment by cdietrich** [comment]
can we have a custom settings xml with longer timeouts https://maven.apache.org/guides/mini/guide-resolver-transport.html

**Comment by LorenzoBettini** [comment]
> can we have a custom settings xml with longer timeouts https://maven.apache.org/guides/mini/guide-resolver-transport.html

Or these are the corresponding properties for the new resolver (https://maven.apache.org/resolver/configuration.html), I think they correspond to the ones in settings

**Comment by LorenzoBettini** [comment]
@cdietrich The Maven wrapper works.
Should I create a PR and also update the Jenkins build accordingly?
Or do you want to experiment further with properties for the transport?

**Comment by szarnekow** [comment]
I'm in favor of working with the wrapper in any case. This should also help locally.

My gut tells me, the properties for the transport are kind of orthogonal to this.

**Comment by cdietrich** [comment]
which wrapper version doi we use?
i assume one day we want to use a newer one
keep using the old version only will postpone the issue

**Comment by LorenzoBettini** [comment]
Currently, I'm using the same version we use in Jenkins 3.8.6.

Of course, yes, it postpones the issue; but please remember that some versions of Maven are buggy ;)
For example, Maven 3.9.0 was unusable, IIRC from the cross-dev mailing list.

I don't know how it works for Gradle, but for the Maven wrapper, it's just a matter of changing the version of Maven, not of the wrapper, in `maven-wrapper.properties`.

By the way, the build on `main` works on GitHub Actions macOS because of the cache: as soon as a job does not use the cache, you get the problem.

**Comment by cdietrich** [comment]
so we can go with maven wrapper for now  but need to continue if setting some timeout or retry properties helps with newer maven version

**Comment by LorenzoBettini** [comment]
I created the PR #2663 but now the build fails for

```
Error:  Failed to resolve target definition file:/home/runner/work/xtext/xtext/org.eclipse.xtext.xbase.lib/../xtext-latest.target: Failed to load p2 metadata repository from location https://download.eclipse.org/modeling/emf/emf/builds/nightly/latest: Unable to read repository at https://download.eclipse.org/modeling/emf/emf/builds/nightly/latest. Server returned HTTP response code: 502 for URL: https://download.eclipse.org/modeling/emf/emf/builds/nightly/latest/content.jar
```

**Comment by cdietrich** [comment]
see https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3130
