### ISSUE TITLE
Update to Jetty 11

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#2235]
Update to Jetty 11 or 10 (is there a lts ?!?)

 - switch to jakarta (base)classes
 - fix jetty configuration and logging (`new WebAppConfiguration()`) seems to be missing, WebInfConfiguration seems to miss constants etc)
 - adapt jetty sample project
 - adapt wizard

**Comment by florianpirchner** [comment]
Hi Christian,

i been working on this issue and it seems, that i finished properly. xtext-web now uses jetty 11.x and jakarta.servlets api.

[https://github.com/florianpirchner/xtext branch issue_2235](https://github.com/florianpirchner/xtext/tree/issue_2235)

Will renew my contributor agreement tomorrow and then create a pull request.

Best, Flo

**Comment by cdietrich** [comment]
fixed in 2.32. thx for the contribution @florianpirchner
