### ISSUE TITLE
Refresh on Access does not work for Xtext editors

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#2385]
Refresh on Access does not work for Xtext editors

(2) configure workspace for refresh on access
(1) open a Xtext based dsl file
(2) modify on disk
(3) click into the editor

Expected behaviour:
Editor refreshes (e.g. as `.java` or `.txt`)
Actual behaviour:
Editor does not refresh

This is caused by the customization in

`org.eclipse.xtext.ui.editor.model.XtextDocumentProvider.isSynchronized(Object)`

i have no idea why the code there is like it is and what doing some copy&paste from superclass would break

Question: can the `XtextDocumentProvider` be fixed without breaking something else

**Comment by iloveeclipse** [comment]
> This is caused by the customization in
> `org.eclipse.xtext.ui.editor.model.XtextDocumentProvider.isSynchronized(Object)`
> i have no idea why the code there is like it is and what doing some copy&paste from superclass would break
> Question: can the `XtextDocumentProvider` be fixed without breaking something else

That is what we've also just found. We plan to provide a PR that should fix that, current state is just not acceptable from the user point of view.

**Comment by mehmet-karaman** [comment]
Removing the isSynchronized implementation and make use of its super implementation works. But for the case if the editor was dirty and the file was edited outside of eclipse, the user gets a dialog in which he can choose loading of the new content or ignore the change. If the user selects to ignore the changes, the dirty editor can't save it anymore, because the file is out of sync. So I am going to investigate this problem too.

**Comment by mehmet-karaman** [comment]
@szarnekow 
@cdietrich 

Does this PR has any issues? Do I have to do something?

**Comment by mehmet-karaman** [comment]
@szarnekow 
I guess this ticket can be closed now?

**Comment by szarnekow** [comment]
Indeed. Thank you for the heads-up.

**Comment by LorenzoBettini** [comment]
@mehmet-karaman one of the added tests seems to be flaky (especially in macOS):

```
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertFalse(Assert.java:65)
	at org.junit.Assert.assertFalse(Assert.java:75)
	at org.eclipse.xtext.ui.tests.editor.DirtyStateEditorSupportIntegrationTest.testModifyFileInExternEditor(DirtyStateEditorSupportIntegrationTest.java:148)
```

maybe some refresh should be explicitly executed before the assertion?

**Comment by mehmet-karaman** [comment]
I am going to check this.

**Comment by LorenzoBettini** [comment]
@mehmet-karaman sorry to go back to this, but `org.eclipse.xtext.ui.tests.editor.DirtyStateEditorSupportIntegrationTest.testModifyFileInExternEditor()` is still very flaky on GitHub Actions in macOS. There's still something wrong with that test (there's some missed synchronization...).

```
expected:<[stuff foo]> but was:<[]>
org.junit.ComparisonFailure: expected:<[stuff foo]> but was:<[]>
	at org.junit.Assert.assertEquals(Assert.java:117)
	at org.junit.Assert.assertEquals(Assert.java:146)
	at org.eclipse.xtext.ui.tests.editor.DirtyStateEditorSupportIntegrationTest.testModifyFileInExternEditor(DirtyStateEditorSupportIntegrationTest.java:155)
```

I guess that the `assertEquals` is using wrong arguments:

```java
assertEquals(document.get(), "");
```

should be

```java
assertEquals("", document.get());
```

shouldn't it?

**Comment by LorenzoBettini** [comment]
Shouldn't `syncUtil.waitForReconciler(editor);` be executed before checking document's contents?
