### ISSUE TITLE
Avoid generating maven-clean-plugin configuration for cleaning src-gen

### ISSUE THREAD

**Issue by LorenzoBettini** [eclipse/xtext#2520]
I'd like to propose a change in the generated POM of the DSL project: avoid generating the `maven-clean-plugin` configuration for cleaning `src-gen` folders.

Personally, it's the first thing I remove from the generated POM each time I create a new Xtext project.

The reasons for such a removal are the following:

- `src-gen` folders are already cleaned when running the MWE2 workflow, so it's quite useless to remove them in advance
- while cleaning `xtend-gen` (before running the `xtend-maven-plugin`) makes sense in general because of the missing incremental building mechanisms in Maven, on the contrary, as said in the previous point, the MWE2 already does that in any case, and regenerating `src-gen` takes some time, so removing `src-gen` during a `mvn clean` is not much useful
- the current configuration of `maven-clean-plugin` for cleaning src-gen wipes everything, including possible `.gitignore` files in those folders, while MWE2 avoids that when cleaning such folders
- you have to keep in sync the configuration of `maven-clean-plugin` with the one in MWE2 in case you add/remove/change the folders where you generate something during the workflow

Summarizing, I only see drawback with the current approach, without any real benefit...

Before the PR I'd like to have some feedback though ;)

**Comment by LorenzoBettini** [comment]
@cdietrich @szarnekow I'd like to revive this one :)

**Comment by tripleo1** [comment]
`./.eclipse/config/org.eclipse.xtext.conf`['make-@LoenzoBettini-happy = true;]'?

**Comment by LorenzoBettini** [comment]
I think we can close this and live with what we have now.
