### ISSUE TITLE
Set mirror and stats in p2 site's artifacts

### ISSUE THREAD

**Issue by LorenzoBettini** [eclipse/xtext#2617]
See https://github.com/xtext/xtext-monorepo/issues/13

maybe for the next milestone M1

**Comment by LorenzoBettini** [comment]
Mirror has been configured in https://github.com/eclipse/xtext/commit/2e9ada1bb66c760ef6388ae1fd6fc76ce86c62fe

**Comment by cdietrich** [comment]
@LorenzoBettini what is left for this issue?

**Comment by LorenzoBettini** [comment]
@cdietrich the download stats haven't been implemented. I don't know whether those stats still have to be configured explicitly: I can already access Xtext download statistics anyway. The mirror part is complete. I think we can close this as complete.

**Comment by LorenzoBettini** [comment]
Just an additional note: mirroring for 2.31 works as expected: while Oomphing one of my Xtext installations I see

```
Mirrored 46 artifacts from https://eclipse.mirror.garr.it/modeling/tmf/xtext/updates/releases/2.31.0/ at 2,508kb/s
Mirrored 44 artifacts from https://mirror.dogado.de/eclipse/modeling/tmf/xtext/updates/releases/2.31.0/ at 1,832kb/s
Mirrored 20 artifacts from https://ftp.fau.de/eclipse/modeling/tmf/xtext/updates/releases/2.31.0/ at 1,319kb/s
```

:)
