### ISSUE TITLE
Building 2.31.0.M2

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#2624]
M2 week is the first week of may.
@LorenzoBettini what is your availability next week monday/tuesday?

as we dont have built a m1 yet we can also do a training run this week.
i at least want to try to build one milestone myself.

also the current full-deploy log seems to be broken.
it refers to 1-maven-build.sh
which seems to be gone

i also wonder if profiles can be done in a way that i can run a test build locally where rsync is not available

**Comment by LorenzoBettini** [comment]
@cdietrich I still don't see the reference to the old script in the logs of the two jobs I mentioned above... could you please point me to the log you're referring to?

OK for Wed: we'll schedule a Google meet so you can start the milestone release job while we're on the meet.

I usually do tagging manually. In the past, you were doing tagging in Jenkins? In general, I prefer not to do such things in the CI. If you already have some existing jobs, we might try adapting them, as long as it's easily feasible.

**Comment by cdietrich** [comment]
@LorenzoBettini yes tagging was done by jenkins in the past.
i am referring to this log
https://github.com/eclipse/xtext/blob/7f2031bcb8ec46c1ee3d75064d622d581a1d8a55/full-deploy.sh#L16

**Comment by LorenzoBettini** [comment]
> @LorenzoBettini yes tagging was done by jenkins in the past. i am referring to this log

OK, as I said, if it can be done easily we can try to adapt that.

> 
> https://github.com/eclipse/xtext/blob/7f2031bcb8ec46c1ee3d75064d622d581a1d8a55/full-deploy.sh#L16

OK, that is printed only in case of `-h`, but for sure it must be changed accordingly :)

**Comment by cdietrich** [comment]
> OK for Wed: we'll schedule a Google meet so you can start the milestone release job while we're on the meet.

will you or shall i?

**Comment by LorenzoBettini** [comment]
I created https://github.com/eclipse/xtext/tree/lb_2624_M1 where I cleaned up a few things for the tomorrow M1 release

**Comment by LorenzoBettini** [comment]
@cdietrich since I rebased https://github.com/eclipse/xtext/pull/2629 on main instead of merging, the tag you had created is still there but "This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository."

Sorry, my bad, I should have merged this time instead of rebasing.

Will you please create the tag again?

**Comment by cdietrich** [comment]
i created the tag from your branch. so no issue

**Comment by cdietrich** [comment]
ok i have force pushed a new tag

**Comment by cdietrich** [comment]
M2 is done
