### ISSUE TITLE
Prepare Job / Scripts for release

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#2625]
Prepare Job / Scripts for release
- milestone script knows GA but still deploys to milestones
- script that does version adjustment needs to be tested

**Comment by cdietrich** [comment]
@LorenzoBettini a starting point can be found on cd_issue2625_relScripts branch

**Comment by LorenzoBettini** [comment]
I have already a script for setting the versions and then it's just a matter of another jenkinsfile and a Maven profile

**Comment by LorenzoBettini** [comment]
Oh, I see you already prepared that :) . I'll have a look in the next few days

**Comment by cdietrich** [comment]
alternative solution would be to reuse the normal jenkinsfile for milestones and if/else on the GA parameter

**Comment by LorenzoBettini** [comment]
I'd like to avoid that :)
I prefer to have a dedicated one
