### ISSUE TITLE
New Build: Xtend Classpath container in Runtime eclipse

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#2627]
If i start a a runtime eclipse
and create a java project
and then add the xtend classpath container
(e.g. create xtend file and use quickfix or use the java buildpath config)
then the xtend classpath container is not working

(there seems to be inconsistency with class dirs, build properties, whatever)

@LorenzoBettini  @szarnekow do you see this problem too
any idea what could be the problem

**Comment by cdietrich** [comment]
i assume the bin/bin guessing in 
org.eclipse.xtend.ide.buildpath.XtendClasspathContainer
will need adaptation

**Comment by LorenzoBettini** [comment]
I hadn't thought about such a use case and I thought we had a test even for such situations ;)

**Comment by cdietrich** [comment]
have no clue how this could be tested automatically

**Comment by LorenzoBettini** [comment]
I don't think we can because I think we use workarounds instead of using general solutions based on the classloader. But I wouldn't know how to do that.
