### ISSUE TITLE
Oomph: latest jdt not visible when selecting latest

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#2634]
latest jdt ([org.eclipse.jdt.core_3.34.0.v20230425-1003.jar](https://www.eclipse.org/downloads/download.php?file=/eclipse/updates/4.28-I-builds/I20230425-1800/plugins/org.eclipse.jdt.core_3.34.0.v20230425-1003.jar)) not visible when selecting latest (2023-06) as target platform
instead i am still seeing /Users/cdietrich/xtext-main/ws/.metadata/.plugins/org.eclipse.pde.core/.bundle_pool/plugins/org.eclipse.jdt.core_3.34.0.v20230410-1351.jar

@merks any idea how to investigate this or what could cause this

**Comment by merks** [comment]
What URLs are being used?  

When I update my Oomph IDE targlet-based target platform I see this in the log:

> Performing Targlets Modular Target (Eclipse Platform + Oomph), activate
> Repository https://download.eclipse.org/eclipse/updates/4.28-I-builds
> Repository https://download.eclipse.org/usssdk/updates/latest
> Repository https://download.eclipse.org/egit/updates-stable-nightly
> Repository https://download.eclipse.org/tools/orbit/downloads/latest-R
> Repository https://download.eclipse.org/tools/orbit/downloads/drops/R20221123021534/repository
> Repository https://download.eclipse.org/modeling/emf/emf/builds/milestone/latest
> Repository https://download.eclipse.org/mylyn/snapshots/weekly
> Repository https://download.eclipse.org/tools/orbit/downloads/drops2/R20190602212107/repository
> Repository https://download.eclipse.org/technology/m2e/snapshots/latest
> Repository https://download.eclipse.org/nebula/snapshot
> Repository https://download.eclipse.org/technology/swtbot/snapshots
> Repository https://download.eclipse.org/webtools/downloads/drops/R3.29.0/R-3.29.0-20230303230236/repository
> Repository https://download.eclipse.org/justj/jres/17/updates/milestone/latest
> ...
> Fetching org.eclipse.jdt.core_3.34.0.v20230425-1003.jar from https://download.eclipse.org/eclipse/updates/4.28-I-builds/I20230425-1800/plugins/ (4,01MB)

You might try Preferences -> Oomph -> Bundle Pools -> Clear Cache... if perhaps because of network problem (which there seem to be today), cached repo metadata is being used.

**Comment by cdietrich** [comment]
hmmm i see this one

```
Mirrors = true
Include All Platforms = false
Include All Requirements = true
Include Binary Equivalents = true
Include Sources = true
Adding metadata repository https://download.itemis.com/updates/releases/2.1.1
Fetching content.jar from https://download.itemis.com/updates/releases/2.1.1/ (5,47kB)
Fetching p2.index from https://download.eclipse.org/eclipse/updates/4.28-I-builds/ (128B)
Adding metadata repository https://download.eclipse.org/eclipse/updates/4.28-I-builds
Fetching p2.index from https://download.eclipse.org/cbi/updates/analyzers/4.7/ (122B)
Adding metadata repository https://download.eclipse.org/cbi/updates/analyzers/4.7
Fetching compositeContent.jar from https://download.eclipse.org/eclipse/updates/4.28-I-builds/ (447B)
Fetching compositeContent.xml from https://download.eclipse.org/cbi/updates/analyzers/4.7/
Fetching p2.index from https://download.eclipse.org/cbi/updates/analyzers/4.7/I20180525-1502/ (172B)
Fetching content.jar from https://download.eclipse.org/eclipse/updates/4.28-I-builds/categories/ (1,25kB)
Fetching p2.index from https://download.eclipse.org/eclipse/updates/4.28-I-builds/I20230424-1800/ (172B)
Fetching content.xml.xz from https://download.eclipse.org/cbi/updates/analyzers/4.7/I20180525-1502/ (6,45kB)
Fetching p2.index from https://download.eclipse.org/cbi/updates/analyzers/4.7/I20180523-1323/ (172B)
Fetching content.xml.xz from https://download.eclipse.org/cbi/updates/analyzers/4.7/I20180523-1323/ (6,46kB)
Fetching p2.index from https://download.eclipse.org/cbi/updates/analyzers/4.7/I20180423-1938/ (172B)
Fetching content.xml from https://download.eclipse.org/eclipse/updates/4.28-I-builds/I20230424-1800/
Fetching content.xml.xz from https://download.eclipse.org/cbi/updates/analyzers/4.7/I20180423-1938/ (6,47kB)
Fetching p2.index from https://download.eclipse.org/eclipse/updates/4.28-I-builds/I20230425-1800/ (172B)
Fetching content.xml from https://download.eclipse.org/eclipse/updates/4.28-I-builds/I20230425-1800/
Calculating requirements and dependencies.
```

but pde still uses the old jdt. will try a different machine in the evening

**Comment by LorenzoBettini** [comment]
@cdietrich try to open the target file with the target editor and let it resolve it (but don't set it as the target platform). Then, try to run oomph again.

**Comment by cdietrich** [comment]
the funny thing is that in a separate eclipse and open and set target platform it works perfectly fine
willt try to delete
/Users/cdietrich/xtext-main/ws/.metadata/.plugins/org.eclipse.pde.core/.bundle_pool/
next

**Comment by merks** [comment]
Yes, my sense is that something is cached with respect to the *.target resolution.  We call org.eclipse.pde.core.target.ITargetDefinition.resolve(IProgressMonitor) on such a target, but I don't see anything (API) to "force" it to resolve from scratch.  I think that call is supposed to do that.

**Comment by cdietrich** [comment]
yes force load seems to have worked. as i have removed the pool before dont know which part exactly helped here

**Comment by LorenzoBettini** [comment]
> Yes, my sense is that something is cached with respect to the *.target resolution. We call org.eclipse.pde.core.target.ITargetDefinition.resolve(IProgressMonitor) on such a target, but I don't see anything (API) to "force" it to resolve from scratch. I think that call is supposed to do that.

As far as I know, we should increment sequenceNumber in the target file to force PDE not to use the cache. That number should be incremented each time we change the target file, though almost no one does that ;)

**Comment by merks** [comment]
When Oomph’s target generates it it does that. 👿

**Comment by cdietrich** [comment]
ok i will try to remember that
