### ISSUE TITLE
Dont build on Github Actions for tags

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#2644]
Dont build on Github Actions for tags

@LorenzoBettini  @HannesWell  any idea how to prevent the actions to run on tags?

**Comment by HannesWell** [comment]
According to the docs, the push event is fired when a branch or tag is pushed:
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#push

We can probably use the `tags-ignore` filter to not run on tags at all.
I'll try it out and provide a PR if it works.
