### ISSUE TITLE
Building 2.31.0 Release

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#2649]

**Comment by cdietrich** [comment]
@LorenzoBettini what is your availibility early next week in case i need your help?

**Comment by LorenzoBettini** [comment]
Approximately, Monday, Tuesday afternoon or Wednesday early or late morning.

**Comment by cdietrich** [comment]
ok, i will start on monday and ping you if i face any problems

**Comment by cdietrich** [comment]
done
