### ISSUE TITLE
Consider Adapting new Timeout api to avoid leaked browsers by Hovers

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#2653]
Consider Adapting new Timeout api to avoid leaked browsers by Hovers
https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/528
https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/548
https://github.com/eclipse-platform/eclipse.platform.text/issues/191
https://github.com/eclipse-platform/eclipse.platform.text/pull/193

- XtextBrowserInformationControl (reflectively call setDisposeTimeout)
- XbaseInformationControl (port fix over from BrowserInformationContro, also check if c&p the complete class is still needed)

unclear: use of preference
https://github.com/eclipse-platform/eclipse.platform.ui/pull/743
https://github.com/eclipse-platform/eclipse.platform.ui/issues/742

**Comment by iloveeclipse** [comment]
@cdietrich : platform changes are on master now.

**Comment by cdietrich** [comment]
of course supporting this via compatible api will no be easy

@szarnekow do you know a way to call a super method via reflection?

**Comment by cdietrich** [comment]
maybe using a default method in our interface will work

**Comment by szarnekow** [comment]
> maybe using a default method in our interface will work

No, it would not work. Well need a method handle for this to work.

**Comment by iloveeclipse** [comment]
@cdietrich : I don't know what is missing here, but if you need some change in the platform (API or non API), just propose it.

**Comment by szarnekow** [comment]
> @szarnekow do you know a way to call a super method via reflection?

A MethodHandle allows that

> A non-virtual method handle to a specific virtual method implementation can also be created. These do not perform virtual lookup based on receiver type. Such a method handle simulates the effect of an invokespecial instruction to the same method. A non-virtual method handle can also be created to simulate the effect of an invokevirtual or invokeinterface instruction on a private method (as applicable).

**Comment by cdietrich** [comment]
@szarnekow in my debugging experiments the default method thing worked.
u´sing that i see the default method in interface called id superclasss has no method and method in superclass is called otherwise

**Comment by cdietrich** [comment]
done
