### ISSUE TITLE
Investigate Maven Wrapper

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#2656]
Investigate if using maven Wrapper can make the build more consistent over mutiple OSes/BuildServers/Environments

**Comment by HannesWell** [comment]
As an alternative you could just use the [setup-maven](https://github.com/marketplace/actions/setup-maven).
It has the advantage that you don't have to commit binaries to the repo and there is much less ceremony required.

**Comment by szarnekow** [comment]
We believe that a local build should need no additional setup, too. A GitHub action would not help with that.

**Comment by HannesWell** [comment]
> We believe that a local build should need no additional setup, too. A GitHub action would not help with that.

Understand.

Just in case you have not heard about it, but there already have already been cases where malicious code was added to projects through the jar for the Maven-Wrapper. Therefore I recommend to only accept updates for the Maven wrappers from developers you trust, unless you introspect the updated jar and verify it is not modified.
