### ISSUE TITLE
Investigate solution for maven 3.9.1+ problem

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#2664]
Investigate solution for maven 3.9.1 problem we see in github actions

cc @LorenzoBettini

**Comment by cdietrich** [comment]
of course (tm) cannot reproduce with maven 3.9.1 locally on mac nor on ci.eclipse.org/xtext on linux

**Comment by cdietrich** [comment]
tycho 4.0 will need maven 3.9.1

**Comment by LorenzoBettini** [comment]
@cdietrich will you try with the MWE2 milestone?

**Comment by cdietrich** [comment]
dont know if i will find the time.
seems not to be propagated yet

**Comment by cdietrich** [comment]
Please do so
