### ISSUE TITLE
Add option `includePluginDependencies` to `xtext-maven-plugin`

### ISSUE THREAD

**Issue by SimonCockx** [eclipse/xtext#2665]
It's sometimes useful to include the classpath of plugin dependencies when generating code using the `xtext-maven-plugin`.

See use case here: https://www.eclipse.org/forums/index.php/m/1859085/#msg_1859085.

The `xtext-maven-plugin` could add an option such as `includePluginDependencies`, much like how the `maven-exec-plugin` does it (see [this method](https://github.com/mojohaus/exec-maven-plugin/blob/master/src/main/java/org/codehaus/mojo/exec/ExecJavaMojo.java#LL690C39-L690C39), which accesses the plugin dependencies via the maven variable `${plugin.artifacts}`).

**Comment by LorenzoBettini** [comment]
@SimonCockx how do you scan the classpath in your DSL?

@cdietrich @szarnekow I'd like to try to implement this, but do you know if any of our testing language could be used to test this?

**Comment by cdietrich** [comment]
@LorenzoBettini i understand this is about model files in jars.
so using the normal [nojdt](https://github.com/eclipse/xtext/blob/main/org.eclipse.xtext.maven.plugin/src/test/resources/it/generate/simple-lang/src/main/java/RefModel.nojdt) should do it

**Comment by LorenzoBettini** [comment]
mh... then I got it wrong from the start...

@SimonCockx I need a detailed use case

of course, I could mimic what the exec plugin does, but I'd like to be able to test it.

**Comment by SimonCockx** [comment]
My use case is having a simple way of including my DSL standard library while running the `xtext-maven-plugin`, without cluttering the dependencies of my consuming project by adding an unnecessary project dependency on the DSL.

DSL project: contains a standard library of `.mydsl` files that should be included when parsing any `.mydsl` resource.

Consuming project: a plain Maven project that contains `.mydsl` files. It relies on the generated code, so as part of its build process, it runs the `generate` goal of the `xtext-maven-plugin`. Other than that, it doesn't have any dependency on the DSL.

Ideally, it should not be necessary to add a dependency on the DSL project to the consuming project. Only the plugin needs it, so the DSL can be defined as a plugin dependency. However, the `xtext-maven-plugin` only scans the classpath of project dependencies for `.mydsl` files, so using the DSL as a plugin dependency results in the standard library not being available.

I.e., the `xtext-maven-plugin` looks at `${project.compileClasspathElements}` (see [here](https://github.com/eclipse/xtext/blob/18216f46e9113841336beb3df238bd34c31d3a44/org.eclipse.xtext.maven.plugin/src/main/java/org/eclipse/xtext/maven/XtextGenerateMojo.java#L34)). I imagine having an option to look at `${plugin.artifacts}` as well would solve this issue.

**Comment by cdietrich** [comment]
so you have some stdlib.mydsl files in a jar/other project and want to put this not to the dependency of the project with the clients.mydsl files but just pass it to the xtext-maven-plugin as extraDependency

**Comment by LorenzoBettini** [comment]
So, if I understand correctly, an integration test could be like the one I created here: https://github.com/LorenzoBettini/xtext/commit/0ae715b199446014e94da832431199383972b0b6

The IT test succeeds because in `simple-lang-ref-model` there's a project dependency on `simple-lang-model` (which contains the referred DSL element). If I move that dependency in the dependencies of the xtext-maven-plugin the test fails, because the referred DSL element cannot be resolved.
