### ISSUE TITLE
Problem with malformed bundles during build or opening DSL files

### ISSUE THREAD

**Issue by rosczja** [eclipse/xtext#2677]
When opening a DSL file or building a project that contains DSL files an IllegalArgumentException is thrown whenever a jar archive is on the classpath of the project, claiming to be an OSGi bundle, but it has an empty BundleSymbolicName.

This happens in the class org.eclipse.xtext.ui.resource.JavaProjectResourceSetInitializer on line 86 where the prefix of an URL gets replaced. The issue can be traced back to the class  org.eclipse.xtext.ui.resource.Storage2UriMapperJavaImpl line 347 where the uriPrefix is set to the symbolic name of the bundle if it is not null.

**Comment by cdietrich** [comment]
am not sure if i can follow you.
you mean there is a symbolic name (!= null) but it is empty?

**Comment by rosczja** [comment]
Yes exactly. In the Manifest you will find "BundleSymbolicName=" which seems to translate to an empty string.

**Comment by cdietrich** [comment]
can you provide a pr?

**Comment by rosczja** [comment]
Sure. Already working on it.

**Comment by rosczja** [comment]
Cannot create an account on Eclipse Foundation to sign CLA.

**Comment by rosczja** [comment]
Because they disabled web account registration due to spam. At least that is what the website says.

**Comment by cdietrich** [comment]
can you give me a link?

**Comment by cdietrich** [comment]
@rosczja there is already an account with the id
jrosczak
is this you?

**Comment by rosczja** [comment]
I finally managed to get it to work, my email was not public, so Eclipse Foundation could not match my account. Sorry for the chaos.
