### ISSUE TITLE
Java 20 support

### ISSUE THREAD

**Issue by nils-christian** [eclipse/xtext#2680]
Hi,

Is there a plan on supporting Java 20? Currently our build crashes, but it also writes a warning on the console beforehand:

`[WARNING] source level should be in '1.1'...'1.8','9'...'18' (or '5.0'..'18.0'): 20`

Thank you and best regards

  Nils

**Comment by cdietrich** [comment]
Xtext does support 11 and 17 only.
this message comes from JDT (used under the hood).
once Java 21 is out we will drop 11 and support 21.
timeline is not clear yet. as all upstream depenendencies need to support Java 21

**Comment by nils-christian** [comment]
Thank you very much for the information, @cdietrich.

**Comment by cdietrich** [comment]
see also https://github.com/eclipse/xtext/issues/2686
