### ISSUE TITLE
Incomplete check whether to use WorkspaceFolders or not?

### ISSUE THREAD

**Issue by jnt0r** [eclipse/xtext#2699]
I think there is an incomplete check whether WorkspaceFolders should be used or not. The used method always returns true, independent of the capabilities the client sent to the server. Shouldn't there be an additional check whether the client supports WorkspaceFolders?

https://github.com/eclipse/xtext/blob/2e3970b20dd9dd40c21fc0c79c61b99cffbc7a8e/org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/LanguageServerImpl.java#L234-L242

https://github.com/eclipse/xtext/blob/2e3970b20dd9dd40c21fc0c79c61b99cffbc7a8e/org.eclipse.xtext.ide/src/org/eclipse/xtext/ide/server/WorkspaceManager.java#L180-L182

**Comment by jnt0r** [comment]
Should I prepare an PR to implement this check?

**Comment by cdietrich** [comment]
am not sure @szarnekow what do you think?

**Comment by szarnekow** [comment]
@jnt0r The initiative is greatly appreciated and we welcome a PR with the necessary changes to adhere to the LSP protocol. Please also add tests for both scenarios - a client capable of using workspace folders and a client using the other approach.

If you feel like the necessary work is getting out of hand, please don't hesitate to ask questions or discuss ideas.

**Comment by cdietrich** [comment]
assume existing tests need to be changed as well depending on the default

**Comment by szarnekow** [comment]
I would prefer if we find a solution that would not require different init params to be sent to retain the status quo.

**Comment by jnt0r** [comment]
@szarnekow The status quo is not correct based on the specification, I would say. The server should only use WorkspaceFolders if the client explicitly sets the WorkspaceFolders capability to true, and not if he only sets the WorkspaceFolders array. So if a client currently sends an initialize request without WorkspaceFolders capability enabled but with an empty WorkspaceFolders array and the rootPath set, the server would use an empty list of WorkspaceFolders and therefore would not recognize my files correctly. There is already a check for the WorkspaceFolders capability in creation of the ServerCapabilities. So this check here was just not complete at the moment...
