### ISSUE TITLE
Xtend website removal

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#2706]
looks like the xtend website removal issue get more pressing 

https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/1936

@szarnekow @LorenzoBettini  what shall we do

**Comment by LorenzoBettini** [comment]
I seem to understand that one of the old proposals, which also seems the easiest one to apply, is to generate the Xtend website as a subfolder and then have a redirect.

**Comment by cdietrich** [comment]
yes but this need to be done and tested

**Comment by cdietrich** [comment]
see https://github.com/eclipse/xtext-website/compare/cd_issue2706

**Comment by cdietrich** [comment]
is now deployed under /Xtext/xtend

for post cleanup

https://github.com/eclipse/xtext-website/issues/13

now: waiting for redirect to be installed

**Comment by cdietrich** [comment]
done
