### ISSUE TITLE
XBase interpreter example in doc out of date

### ISSUE THREAD

**Issue by steve-hickman-epistimis** [eclipse/xtext#2710]
In the [doc for XBase](https://www.eclipse.org/Xtext/documentation/305_xbase.html#xbase-expressions), in the section titled `Using the Xbase Interpreter`, there is a code snippet that refers to `XbaseScopeProvider`, which has been deprecated since XText 2.4.  Can that be updated to show the preferred approach?

**Comment by cdietrich** [comment]
Pull request is welcome

**Comment by steve-hickman-epistimis** [comment]
https://github.com/eclipse/xtext/pull/2711

**Comment by sxhickman** [comment]
How about https://github.com/eclipse/xtext-website/pull/14 ?

**Comment by cdietrich** [comment]
Need to check if there is another constant that can be used once I am at pc and can grep

**Comment by stevehickman** [comment]
How about https://github.com/eclipse/xtext-website/pull/16 ?

**Comment by cdietrich** [comment]
With the latest patch it is fixed. Thx for your help
