### ISSUE TITLE
Update to Guava 32.1

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#2726]
Update to Guava 32.1

**Comment by cdietrich** [comment]
@merks where is org.apiguardian gone?

**Comment by merks** [comment]
This?

https://download.eclipse.org/oomph/simrel-orbit/nightly/N202306301409/archive/download.eclipse.org/oomph/simrel-orbit/nightly/N202306301409/index/org.apiguardian.api_1.1.2.html

**Comment by cdietrich** [comment]
no

<unit id="org.apiguardian" version="0.0.0"/>

**Comment by merks** [comment]
Where was it before? Not that Orbit itself has been actively deleting things.

**Comment by cdietrich** [comment]
:(
