### ISSUE TITLE
 Need API access org.eclipse.xtext.common.types.access.jdt.JdtTypeProvider.workingCopyOwner

### ISSUE THREAD

**Issue by shashwatanand** [eclipse/xtext#2756]
We have customized the build process for our project.

Currently, we are accessing `org.eclipse.xtext.common.types.access.jdt.JdtTypeProvider.workingCopyOwner` and `org.eclipse.xtext.builder.impl.XtextBuilder.toBeBuiltComputer` using reflection via `java.security.AccessController` which will be deprecated from JDK 17

**Comment by cdietrich** [comment]
thx for the patch @shashwatanand
