### ISSUE TITLE
Switch build notifications from Slack to Matrix

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#2765]
Switch build notifications from Slack to Matrix

see https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3473

**Comment by cdietrich** [comment]
First version is Live for Xtext
follow up  helpdesk issue created for MWE and Xpect
https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3523

**Comment by cdietrich** [comment]
MWE also done. Xpect needs PL approval

**Comment by cdietrich** [comment]
@kthoms @miklossy can you please start the steps to tear down the slack channel

**Comment by cdietrich** [comment]
@miklossy @kthoms any update here?

**Comment by cdietrich** [comment]
ping @miklossy @kthoms

**Comment by miklossy** [comment]
Actually, currently I do not need any Xtext build notification. So from my point of view, you can tear down the slack channel.

**Comment by cdietrich** [comment]
@miklossy i am pinging you can Karsten because i am no longer with itemis so I CANT tear it down

**Comment by miklossy** [comment]
ok, I understand. I have just sent them a message via the xtext-builds itemis slack-channel so that this channel will be archived. Let's see if they have any objections.

**Comment by cdietrich** [comment]
there is no they. its just karsten and you

**Comment by miklossy** [comment]
OK

**Comment by miklossy** [comment]
I have just archived the xtext-build channel on the itemis Slack.
![Screenshot 2023-10-03 103909](https://github.com/eclipse/xtext/assets/20393472/a27daba3-d4a1-4aa4-9756-0fe05fbe3baa)
