### ISSUE TITLE
Proposal to add a new method `addParameter`  with position in `MutableExecutableDeclaration`

### ISSUE THREAD

**Issue by dvojtise** [eclipse/xtext#2777]
Somehow related to #2318 I have another similar regression since xtend 2.27

In our project, we have an active annotation that inserts a method parameter to an existing method in first position.

Since the active annotation current API `MutableExecutableDeclaration` only has a `MutableParameterDeclaration addParameter(String name, TypeReference type)` method that add the parameter at the end of the list, we  used to workaround by clearing the parameters list, then add our new updated list.

With a code similar to the one below
```xtend
override doTransform(MutableClassDeclaration annotatedClass, extension TransformationContext context) {
  for( m : annotatedClass.declaredMethods) {
      // save original list of parameters in l
      val l = new ArrayList<Pair<String, TypeReference>>
      for (p1 : m.parameters)
	      l.add(new Pair(p1.simpleName, p1.type))
      
      m.parameters.toList.clear
      // reset parameters and add _self as first parameter
      m.addParameter("_selfName", newTypeReference(String))
      
      for (param : l)
	      m.addParameter(param.key, param.value)
  }
}
```

Unfortunately, the line  `m.parameters.toList.clear` raises BatchLinkableResourceStorageWritable messages like in #2318

As I suspect that manipulating the parameter list like this isn't actually a good way, I propose to contribute a new API method in `MutableExecutableDeclaration`  and `JvmExecutableDeclarationImpl` such as 
`MutableParameterDeclaration addParameter(Integer position, String name, TypeReference type);`  that would allow inserting the new parameter at a given position.

**Comment by cdietrich** [comment]
@szarnekow  any comments?

**Comment by szarnekow** [comment]
It might make sense to have that API, yes. It needs thorough unit tests, though.

**Comment by dvojtise** [comment]
Ok, thanks, I'll prepare it (including tests ;-) )
