### ISSUE TITLE
Adapt to latest orbit changes

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#2779]
Adapt to latest orbit changes e.g. guava
(currently the build is no longer working)

- adapt
   - targets
   - bom
   - manifests
   - features
   - categegeory.xml
   - ....

@szarnekow @LorenzoBettini @tjeske do you have any capacity to look at it

also check reference projects, xpect and mwe

**Comment by cdietrich** [comment]
also

- hamcrest
- javax.inject
- junit 4.13
- org.slf4j.binding.simple 
seem to make problems

**Comment by cdietrich** [comment]
@LorenzoBettini  do you remember why you added org.slf4j.binding.simple

**Comment by cdietrich** [comment]
In reference project

log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.511 s <<< FAILURE! - in org.eclipse.xtext.swtbot.tests.XtendExamplesTest
org.eclipse.xtext.swtbot.tests.XtendExamplesTest  Time elapsed: 1.51 s  <<< ERROR!
java.lang.LinkageError: loader constraint violation: loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @6765d4ee wants to load interface org.hamcrest.Matcher. A different interface with the same name was previously loaded by org.eclipse.osgi.internal.loader.EquinoxClassLoader @78f5ec2d. (org.hamcrest.Matcher is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @78f5ec2d, parent loader 'platform')


Maybe something todo with the hamcrest discussion in platform the last weekend

**Comment by tjeske** [comment]
@cdietrich I can have a look end of this week.

**Comment by LorenzoBettini** [comment]
@cdietrich I think I added binding.simple to have some code compile or not complain at runtime.

I don't think I can have a look at that this week; however, if the failure is due to required versions not being available anymore, as I suggested in the past, I'd go with "0.0.0" for the version in the target files. I seem to understand that Orbit will not change often, and it might become too much work to manually update the versions so often.

**Comment by cdietrich** [comment]
the problem is there is also bundle name changes.
i can do a search and replace but no extensive testing, looking if anything is overlooked

**Comment by merks** [comment]
When looking for javax things that seem to be missing, look for jakarta replacements:

![image](https://github.com/eclipse/xtext/assets/208716/308c370d-6abd-4fa4-ae9b-3625b329fade)

You'll need to use the latest org.junit 4.13.2.v20230809-1000, org.hamcrest.core 2.2.0.v20230809-1000, and org.hamcrest 2.2.0.

**Comment by cdietrich** [comment]
problem is i dont know how we use hamcrest and how they do semantic vesioning.
what is the difference between 1 and 2

**Comment by merks** [comment]
The 2.x version is a drop-in replacement for the 1.x version so no code needs to change, but maybe some upper bound needs to change.    Basically they combined org.hamcrest.core and org.hamcrest.library into a single new bundle called org.hamcrest and that bundle comes complete as an OSGI bundle.  The org.hamcrest.core 2.x bundle (as well as the org.hamcrest.libary 2.x bundle)  simply required the org.hamcrest 2.x bundle and re-exports it.    The org.junit bundle requires org.hamcrest.core 1.x or higher and re-exports it, which is the only reason that org.hamcrest.core is still needed.

These are the dependencies on the actual javax.inject bundle name:

![image](https://github.com/eclipse/xtext/assets/208716/9ac500b9-8c9e-49b4-8284-b8a5616ad42e)

Re-exporting a bundle just lets downstream consumers use the packages of that bundle but doesn't make them dependent on the name of the bundle.

**Comment by merks** [comment]
FYI, all these versions of slf4j are available:

![image](https://github.com/eclipse/xtext/assets/208716/f3b3e87d-bbd5-4198-a1ca-c1533300a70e)

**Comment by cdietrich** [comment]
wip pr at
https://github.com/eclipse/xtext/pull/2780

left out the why of slf4j
left out hamcrest 2.0
left out removal of javax from api

todo check for completness

**Comment by cdietrich** [comment]
merged the pr.

**Comment by merks** [comment]
FYI, the latest version of the platform no longer includes org.hamcrest.core 1.3.0 and there are places it's not supported:

https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/705

**Comment by cdietrich** [comment]
yes i saw the discussion, but i dont know why we do the ecplicit stuff
and i have zero time to digg
=> in doubt will live with somethign that explodes or pull xtext from simrel

**Comment by cdietrich** [comment]
also the question would be:
what does older eclipses do with newer hamcrest

**Comment by merks** [comment]
@cdietrich 

I just expected that everywhere normal MANIFEST.MF dependencies would be used and that's mostly true, but there were/are hard-code places that I did not expect such as JUNIT container thing.  I didn't even know there was such a thing!

Note that if you specify org.hamcrest.core 2.2.0, then org.hamcrest 2.2.0 **must also be available** so org.hamcrest.core 1.3.0 should generally be replaced with a **pair of things**.

**Comment by cdietrich** [comment]
Meh

**Comment by cdietrich** [comment]
Any idea why https://github.com/xtext/xtext-reference-projects/blob/4edb2b5443ea364d3f3d3f54be9589feef813910/greetings-tycho/2.32.0/org.xtext.example.mydsl.target/org.xtext.example.mydsl.target.target#L31 works then

**Comment by merks** [comment]
Yes, you are using `includeMode="planner"` and org.hamcrest.core 2.2.0 requires org.hamcrest 2.2.0.  This is why I mentioned "must be available".   If all the places specify planner then you don't have to explicitly specify org.hamcrest; you'll just generally get the newest available version of it.

**Comment by cdietrich** [comment]
updated to hamcrest 2

**Comment by cdietrich** [comment]
created #2787 for the javax.inject problem
