### ISSUE TITLE
ProblemsView location is not sorted properly

### ISSUE THREAD

**Issue by frankbenoit** [eclipse/xtext#2792]
Xtext based problems do have location like: "line 12: path/myResouce.dsl"

https://github.com/eclipse/xtext/blob/bc5f99eb3546507066c760f0361b66dcab6e675b/org.eclipse.xtext.ui/src/org/eclipse/xtext/ui/editor/validation/MarkerCreator.java#L49

In ProblemsView, when sorting on the location column, the content is sorted alphabetically, hence line 4 is between 12 and 65.

In JDT this works properly and the location does only contain a text like "line 4". Those markers of JDT do not have the location attribute of the marker be set at all.

My understanding is:
If there is a line number, then the location shall not be set. This creates a default text "line 4" and sorting is done based on the line number, not the text.
If there is no line number, then the location attribute shall be set with whatever is needed to find the location.

To fix this, in my application i bind the MarkerCreator to a FixedXtextMarkerCreator
````
public class FixedXtextMarkerCreator extends MarkerCreator {
    @Override
    protected void setMarkerAttributes(final Issue issue, final IResource resource, final IMarker marker)
            throws CoreException {

        super.setMarkerAttributes(issue, resource, marker);

        // if a line number exists, the location shall not be set
        // 1. the location will get a default text "line <linenumber>"
        // 2. if the location is set with a text, it will be sorted alphabetically, not by line number
        if (marker.getAttribute(IMarker.LINE_NUMBER) != null) {
            marker.setAttribute(IMarker.LOCATION, null);
        }
    }
}
````
Now sorting of the location column works as expected.

**Comment by cdietrich** [comment]
@LorenzoBettini can you please label issues you close with milestone label

**Comment by LorenzoBettini** [comment]
@cdietrich I thought we were labelling PRs. Should I always label issues instead?

**Comment by cdietrich** [comment]
Both
