### ISSUE TITLE
Should we remove the cbi tests

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#2796]
is the cbi test stuff still maintained? do we make use of it?
we also dont seem to execute them on Jenkins/GH actions

**Comment by szarnekow** [comment]
What are the cbi tests?

**Comment by cdietrich** [comment]
They seem to check some simrel requirements @kthoms do you have more details

**Comment by szarnekow** [comment]
Did these ever fail since we use tycho?

**Comment by cdietrich** [comment]
They were never executed

**Comment by szarnekow** [comment]
`rm -rf`
