### ISSUE TITLE
Say goodbye to Xpand

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#2811]
Now that Xpect is finally Xpand free, we will start the removal of the Xpand dependency in Xtext

- [x] Postprocessor
- [x] Old generator
- [x] targets

see also
- https://github.com/eclipse/xtext/issues/2788
- https://github.com/eclipse/xtext/issues/2729
- https://github.com/eclipse/xtext/issues/2676
- https://github.com/eclipse/xtext/issues/1669

**Comment by cdietrich** [comment]
@ewillink

looks like ocl still depends on the old org.eclipse.xtext.generator

```
16:14:23  Build failed! Exception was org.eclipse.core.runtime.CoreException: Cannot complete the install because one or more required items could not be found. Software being installed: validationSet_main 1.0.0 Missing requirement: org.eclipse.ocl.examples.xtext.build 1.18.0.v20221201-0557 requires 'osgi.bundle; org.eclipse.xtext.generator [2.9.0,3.0.0)' but it could not be found Cannot satisfy dependency: mappedRepo_download.eclipse.org_modeling_mdt_ocl_updates_releases_6.18.0 1.0.0 depends on: org.eclipse.equinox.p2.iu; org.eclipse.ocl.build.feature.group [6.18.0,6.19.0) Cannot satisfy dependency: org.eclipse.ocl.build.feature.group 6.18.0.v20221201-0557 depends on: org.eclipse.equinox.p2.iu; org.eclipse.ocl.examples.xtext.build [1.18.0.v20221201-0557,1.18.0.v20221201-0557] Cannot satisfy dependency: validationSet_main 1.0.0 depends on: org.eclipse.equinox.p2.iu; mappedRepo_download.eclipse.org_modeling_mdt_ocl_updates_releases_6.18.0 [1.0.0,1.0.0]
16:14:23  Cannot complete the install because one or more required items could not be found. Software being installed: validationSet_main 1.0.0 Missing requirement: org.eclipse.ocl.examples.xtext.build 1.18.0.v20221201-0557 requires 'osgi.bundle; org.eclipse.xtext.generator [2.9.0,3.0.0)' but it could not be found Cannot satisfy dependency: mappedRepo_download.eclipse.org_modeling_mdt_ocl_updates_releases_6.18.0 1.0.0 depends on: org.eclipse.equinox.p2.iu; org.eclipse.ocl.build.feature.group [6.18.0,6.19.0) Cannot satisfy dependency: org.eclipse.ocl.build.feature.group 6.18.0.v20221201-0557 depends on: org.eclipse.equinox.p2.iu; org.eclipse.ocl.examples.xtext.build [1.18.0.v20221201-0557,1.18.0.v20221201-0557] Cannot satisfy dependency: validationSet_main 1.0.0 depends on: org.eclipse.equinox.p2.iu; mappedRepo_download.eclipse.org_modeling_mdt_ocl_updates_releases_6.18.0 [1.0.0,1.0.0]
16:14:23  [0]Missing requirement: OCL build support for the Xtext Declarative Serializer 1.18.0.v20221201-0557 (org.eclipse.ocl.examples.xtext.build 1.18.0.v20221201-0557) requires 'osgi.bundle; org.eclipse.xtext.generator [2.9.0,3.0.0)' but it could not be found
16:14:23  
16:14:23  Bundle(org.eclipse.xtext.generator [2.9.0,3.0.0)) is required by:
16:14:23    ValidationSet(main)
16:14:23      Contribution(OCL for 2023-09)
16:14:23        MappedRepository(https://download.eclipse.org/modeling/mdt/ocl/updates/releases/6.18.0)
16:14:23          Feature(org.eclipse.ocl.build.feature.group [6.18.0,6.19.0))
16:14:23            InstallableUnit(org.eclipse.ocl.examples.xtext.build 1.18.0.v20221201-0557)
```

**Comment by ewillink** [comment]
See https://bugs.eclipse.org/bugs/show_bug.cgi?id=563046

I sort of got the migration going but found the 'new' formatter absolutely dreadful particularly once de-Xtend-ed.

This prompted me to develop the Declarative Formatter. Ouch! a year later it sort of worked but assumed a lossless mapping between node model and EMF model, which sadly Xtext in particular does not satisfy. So after pretty much wasting a year, I moved on to the next distressingly time consuming problem.

**Comment by cdietrich** [comment]
you still can use the old formatter.

**Comment by cdietrich** [comment]
i dont even know how to clone from old git.eclipse.org anymore :(

**Comment by ewillink** [comment]
The problem dependency is from the Releng aspect of OCL which most users should not install. This could be dropped from SimRel and users redirected to the project install, provided a similar redirect to the Xtext project install finds the old generator.

**Comment by cdietrich** [comment]
i have doubts old generator would work with new xtext.

**Comment by cdietrich** [comment]
disabling indeed seems to work

**Comment by ewillink** [comment]
I'm just about to do OCL 2023-12 M1, but see no disable in ocl.aggrcon. Are you waiting for me, or waiting for M2 or ...

I'll try to phase out the old generator (again) for M2.

**Comment by cdietrich** [comment]
@ewillink I have disabled it here https://github.com/eclipse-simrel/simrel.build/commit/c7ddc34e48eebcde1160a4fbc7ec9ede7fe79bf9

**Comment by ewillink** [comment]
oops. I'm still set up for the old 'Gerrit' approach. Amazing how long the Gerrit approach didn't last.

**Comment by ewillink** [comment]
2023-12M3: OCL and QVTd editors have moved to the new generator framework, albeit using the idiom-based DeclarativeFormatter/Serializer. (generator usage re-enabled on SimRel.)

**Comment by ewillink** [comment]
> This prompted me to develop the Declarative Formatter. Ouch! a year later it sort of worked but assumed a lossless mapping between node model and EMF model, which sadly Xtext in particular does not satisfy. So after pretty much wasting a year, I moved on to the next distressingly time consuming problem.

I think the real reason I reverted was that it was M3 and a depressing number of bugs were still appearing, so I had to put the migration on hold. This time. restarting after M1 there was enough time to finish development.
