### ISSUE TITLE
Adapt to latest orbit changes

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#2819]
Unable to locate installable unit com.google.guava 32.1.2.jre (new version)
Unable to locate installable unit io.github.classgraph 4.8.149.v20220915-0556 (new version)
Unable to locate installable unit org.antlr.runtime 3.2.0.v20220404-1927 (changed timestamp)
Unable to locate installable unit org.apache.log4j 1.2.24.v20221221-2012 (new version)

maybe more

bom needs adaption too log4j=reload4j

**Comment by cdietrich** [comment]
mwe and xpect likely need adaptions as well
reference projects too

**Comment by cdietrich** [comment]
@merks in the new name io.github.classgraph.classgraph intentional?

**Comment by merks** [comment]
Yes, that's it's bundle symbolic name direct from Maven:

 - [io.github.classgraph](https://repo1.maven.org/maven2/io/github/classgraph/)
    - [classgraph](https://repo1.maven.org/maven2/io/github/classgraph/classgraph/) **[4.8.162](https://repo1.maven.org/maven2/io/github/classgraph/classgraph/4.8.162)**

- https://repo1.maven.org/maven2/io/github/classgraph/classgraph/4.8.162/classgraph-4.8.162.jar

Generally if I have to wrap it, I matched the BSN to what it had before.  If it comes directly from Maven as an OSGi bundle then it is what it is...
