### ISSUE TITLE
Consider migrating away from guava library (or make its use internal)

### ISSUE THREAD

**Issue by laeubi** [eclipse/xtext#2838]
Google Guava is a collection of useful things but there also lies its weakness as this results in big size, and heavy dependencies on specific versions even if not all parts are affected. Also with today modern java many things can be archived with plain java as well.

As it is know to create dependency-hell problems, I'd like to suggest to:

-  replace all usages where possible with standard java
-  embeds the code that can't be replaced easily in an internal package

See

- https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1476

for a discussion where the usage of guava currently prevents usage of LSP4J in eclipse-platform while it seems a technology that should be used even more there and currently requires several plugins to ship their own what can then create even more problems of competing versions.

See also

- https://github.com/eclipse-lsp4j/lsp4j/issues/771

where the use of guava in xtend affect lsp4j

**Comment by cdietrich** [comment]
lol with 0 contributions this will happen in 2033

**Comment by laeubi** [comment]
I see some recent (open) contributions here so it is not completely hopeless:
- https://github.com/eclipse/xtext/pulls

:-)

**Comment by cdietrich** [comment]
Bug fixes and small features are happening
The keep with simrel I do in my spare time 
But ditching guava is a gigantic thing also breaking clients

**Comment by laeubi** [comment]
> But ditching guava is a gigantic thing also breaking clients

Client can still include guava for their own convenience and every giant thing starts with small steps (making this visible by an issue is the first one).

**Comment by cdietrich** [comment]
The breaking is us using guava in api methods

**Comment by szarnekow** [comment]
I’ll close as won’t fix. We won’t break existing clients. Backwards compatibility is an asset I’m not willing to give up.

**Comment by laeubi** [comment]
> I’ll close as won’t fix.

You closed it as completed ;-)

> The breaking is us using guava in api methods

This does not mean you have to require Guava... as mentioned above

>> embeds the code that can't be replaced easily in an internal package

you could also embed API interfaces and use substitution packages, that way uses that use guava will get them from guava (and xtext as well) but users without guava will get them from the embedded classes from xtext directly.

So I kindly ask to reopen the issue again...

**Comment by laeubi** [comment]
By the way the 

> We won’t break existing clients. Backwards compatibility is an asset I’m not willing to give up.

is already intrinsic in xtext/xtend if you rely on external API on your own API the breakage of guava APIs (and that's what people often claim, they break API all the time) will immediately result in breaking your API for all older clients as well.

**Comment by szarnekow** [comment]
People claim many things. Decisions should be based on facts. Neither does Xtext rely on unstable parts of Guava nor does the Guava team lighthearted changes. Nowadays I’m more confident with Guava types being used in Xtext API then with Eclipse platform usages.
