### ISSUE TITLE
Possibility to configure the encoding in the IResourcesSetupUtil.createTempFile

### ISSUE THREAD

**Issue by miklossy** [eclipse/xtext#2844]
The [IResourcesSetupUtil.createTempFile](
https://github.com/eclipse/xtext/blob/5769c8d021cc9019b5a6065a79ce3a1514dafd67/org.eclipse.xtext.ui.testing/src/org/eclipse/xtext/ui/testing/util/IResourcesSetupUtil.java#L252-L259) should be overloaded with a signature that accepts not only the fileName, the suffix and the content, but the encoding as well.

This could help to overcome encoding problem within the test cases @hannesN just encountered in a customer project.

**Comment by cdietrich** [comment]
What about the other createFile methods

**Comment by miklossy** [comment]
We can also extend the [IResourcesSetupUtil.createFile](https://github.com/eclipse/xtext/blob/5769c8d021cc9019b5a6065a79ce3a1514dafd67/org.eclipse.xtext.ui.testing/src/org/eclipse/xtext/ui/testing/util/IResourcesSetupUtil.java#L229-L250) method with an additional encoding parameter.

**Comment by cdietrich** [comment]
Change or add additional? The first would break compatibility

**Comment by hannesN** [comment]
Add!

**Comment by hannesN** [comment]
I can implement this on friday, if you agree.

**Comment by miklossy** [comment]
Thanks you @hannesN !

**Comment by miklossy** [comment]
Fixed by https://github.com/eclipse/xtext/pull/3101
