### ISSUE TITLE
ValidatorTester and AssertableDiagnostics deprecated

### ISSUE THREAD

**Issue by LorenzoBettini** [eclipse/xtext#2860]
https://github.com/eclipse/xtext/blob/652c2c41499387ab87737143d12939a8bdab41ab/org.eclipse.xtext.junit4/src/org/eclipse/xtext/junit4/validation/AssertableDiagnostics.java and https://github.com/eclipse/xtext/blob/652c2c41499387ab87737143d12939a8bdab41ab/org.eclipse.xtext.junit4/src/org/eclipse/xtext/junit4/validation/ValidatorTester.java were deprecated in 2.30 as part as the old `org.eclipse.xtext.junit4` bundle.

In `org.eclipse.xtext.testing` we now have
https://github.com/eclipse/xtext/blob/652c2c41499387ab87737143d12939a8bdab41ab/org.eclipse.xtext.testing/src/org/eclipse/xtext/testing/validation/AssertableDiagnostics.java but no corresponding `ValidatorTester`, which was the only one creating objects of AssertableDiagnostics.

We still use `ValidatorTester` in our own tests (we copied it there): https://github.com/eclipse/xtext/blob/652c2c41499387ab87737143d12939a8bdab41ab/org.eclipse.xtext.tests/src/org/eclipse/xtext/validation/ValidatorTester.java#L29

Why don't we put the latter in `org.eclipse.xtext.testing`?

It is not straightforward to port existing tests using ValidatorTester to `ValidationTestHelper`.

**Comment by szarnekow** [comment]
Please add a convenient substitute for the deprecated ValidationTester.

**Comment by LorenzoBettini** [comment]
I was suggesting to use the one we already use in our tests https://github.com/eclipse/xtext/blob/652c2c41499387ab87737143d12939a8bdab41ab/org.eclipse.xtext.tests/src/org/eclipse/xtext/validation/ValidatorTester.java#L29

I mean: put that one in the `org.eclipse.xtext.testing`. I seem to understand that it is exactly the same as the deprecated one.

**Comment by szarnekow** [comment]
Yes, please.
