### ISSUE TITLE
`IEObjectDescription#getUserData` does not allow non-`String` fields

### ISSUE THREAD

**Issue by SimonCockx** [eclipse/xtext#2870]
The default change detection strategy of Xtext relies on resource descriptions/`IEObjectDescription`s. An easy way to customize when a change should be propagated is by adding "user data" to an object's description, e.g.,
```
@Singleton
public class MyDSLResourceDescriptionStrategy extends DefaultResourceDescriptionStrategy {

	@Inject
	private IQualifiedNameProvider qualifiedNameProvider;

	@Override
	public boolean createEObjectDescriptions(EObject eObject, IAcceptor<IEObjectDescription> acceptor) {
		if (eObject instanceof Attribute) {
			QualifiedName qualifiedName = qualifiedNameProvider.getFullyQualifiedName(eObject);
			acceptor.accept(EObjectDescription.create(qualifiedName, eObject, Map.of("TYPE", ((Attribute)eObject).getType().getName()))); // Make sure that changes to the type of an attribute trigger Xtext's change detection
		}
		return super.createEObjectDescriptions(eObject, acceptor);
	}
}
```

Although the fact that I have to convert the type of the attribute to a `String` seems smelly, I think this should work fine. (except if there are multiple types of the same name defined in a different namespace, in which case I should actually use the fully qualified name)

However, now I've encountered a situation where conversion to a suitable `String` is not straight forward, and I was wondering whether there is a better way.

Quick sketch: our language features integer types with a custom precision, e.g.,
```
class A {
  int(bits: 32) attr1; // an integer attribute of 32 bits
  int(bits: 20) attr2; // an integer attribute of 20 bits
}
```
If the type (or any of its arguments) of an attribute changes, then resources containing references to this attribute should be considered "affected" as well.

If the user data of an `EObjectDescription` would allow non-`String` values, then this would be an easy feature to have:
```
@Inject
private MyDSLTypeProvider typeProvider;

@Override
public boolean createEObjectDescriptions(EObject eObject, IAcceptor<IEObjectDescription> acceptor) {
	if (eObject instanceof Attribute) {
		QualifiedName qualifiedName = qualifiedNameProvider.getFullyQualifiedName(eObject);
		MyDSLType attributeType = typeProvider.getType((Attribute)eObject);
		acceptor.accept(EObjectDescription.create(qualifiedName, eObject, Map.of("TYPE", attributeType)); // Make sure that changes to the type of an attribute trigger Xtext's change detection
	}
	return super.createEObjectDescriptions(eObject, acceptor);
}
```

So... is there a good reason why user data values can only be of type `String`? Is there a better way to achieve the same?

**Comment by SimonCockx** [comment]
I could do that, although that's not entirely fool-proof. Suppose I have multiple types with the same name defined in different namespaces, e.g.,
```
namespace foo

class A {}
```
```
namespace bar

class A {}
```
```
namespace test

import foo.A

class B {
  A attribute; // Attribute of type foo.A
}
```

Change the type of `attribute` by changing `import foo.A` to `import bar.A` and the node model won't see a difference in `attribute`'s type.

**Comment by cdietrich** [comment]
xtext first indexes all stuff. and then resolves => no chance.
you may write all combination of possible imports and names to the index entry
and later try to find out the correct one.

**Comment by cdietrich** [comment]
what is the actual problem you try to solve? when and how do you exactly use the index data

**Comment by SimonCockx** [comment]
> xtext first indexes all stuff. and then resolves => no chance.

Hm, that's what I feared.

The issue I'm trying to resolve is concisely described here: [Change in one file sometimes does not trigger model validation in other file with cross-reference](https://github.com/REGnosys/rosetta-dsl/issues/582)

> File 1:
> ```
> type A:
>    attribute int (1..1)
> ```
> 
> File 2:
> ```
> func Foo:
>   inputs: input A (1..1)
>   output: result int (1..1)
>   
>   set result: input -> attribute
> ```
> 
> The type checker passes at this point, as it should.
> 
> Now change the type of `attribute` to `string` in File 1:
> ```
> type A:
>    attribute string (1..1)
> ```
> 
> Type checking in File 2 is not triggered again until I make a change there, so it looks like there is no type error, although there should be.
> 
> Note that other changes _do_ trigger type checking again, like removing or renaming `attribute`.

**Comment by cdietrich** [comment]
then i assume collecting all possible names and rebuilt in doubt would be an option

**Comment by LorenzoBettini** [comment]
@SimonCockx , I guess it would be really helpful if you could share your solution (the interesting code bits) once it's working fine :)

**Comment by SimonCockx** [comment]
@LorenzoBettini Sure! The full change can be found here: https://github.com/REGnosys/rosetta-dsl/pull/708

For any named object in my language that has features other than its name important for validation checks, I've added those features to their descriptions.

One example. For `Attribute`s, this meant including their type and their cardinality constraint: (snippet in the `createEObjectDescriptions` method of `RosettaResourceDescriptionStrategy`) 
```
if (eObject instanceof Attribute) {
	Attribute attr = (Attribute)eObject;

	QualifiedName qualifiedName = getQualifiedNameProvider().getFullyQualifiedName(attr);
	String typeCall = serialize(attr.getTypeCall());
	String cardinality = serialize(attr.getCard());
	acceptor.accept(new AttributeDescription(qualifiedName, attr, typeCall, cardinality));

	return false;
}
```
Definition of `AttributeDescription`: (this could actually also be inlined in the `RosettaResourceDescriptionStrategy` - I found it a bit more clean to separate)
```
public class AttributeDescription extends EObjectDescription {
	public static final String TYPE_CALL = "TYPE_CALL";
	public static final String CARDINALITY = "CARDINALITY";

	public AttributeDescription(QualifiedName qualifiedName, Attribute attribute, String typeCall, String cardinality) {
		super(qualifiedName, attribute, createUserData(typeCall, cardinality));
	}

	private static Map<String, String> createUserData(String typeCall, String cardinality) {
		Map<String, String> userData = new HashMap<>();
		if (typeCall != null) {
			userData.put(TYPE_CALL, typeCall);
		}
		if (cardinality != null) {
			userData.put(CARDINALITY, cardinality);
		}
		return userData;
	}
}
```
Note that it's important to handle `null` values - the model can be incomplete while typing!

In the code above, I used a `serialise` method to convert the type and the cardinality of the attribute to a string:
```
private String serialize(EObject eObject) {
	if (eObject == null) {
		return null; // for partial models
	}
	INode node = NodeModelUtils.getNode(eObject);
	if (node != null) {
		return node.getText();
	}
	return null; // for programmatically created objects
}
```

The PR I linked also contains some nice unit tests, if you're interested. :)
