### ISSUE TITLE
Java 17 in Oomph

### ISSUE THREAD

**Issue by LorenzoBettini** [eclipse/xtext#2874]
Currently, the Oomph setup requires Java 11, but without Java 17 many launches and in particular any test involving the Eclipse platform fail because they require Java 17.
Shouldn't we require Java 17 in the Oomph setup directly?

**Comment by cdietrich** [comment]
depends on if you select 202203 tp

**Comment by LorenzoBettini** [comment]
Would Java 17 break 202203? That would be a corner case anyway, wouldn't it?

**Comment by cdietrich** [comment]
Depending on when we start with java 21 anyway

**Comment by szarnekow** [comment]
@merks Can Oomph derive the JRE information from a target platform file? That would help with the problem of Java11 not being compatible for Xtext's latest platform and Java17 not being of a lot of value for its oldest target platform.

**Comment by merks** [comment]
No.

**Comment by LorenzoBettini** [comment]
Then, I would completely remove the Java version property from the Oomph setup.
Specifying Java 11 is misleading and wrong in many respects. For sure, you cannot run tests or workbench for the latest platforms. I know about the problem and always specify a Java 17 VM. But if one does not know about that, they could have an unusable workspace. Alternatively, I would specify Java 17: it might be useless for older platforms but is required for newer ones, so it should be sound to specify a requirement that works in all situations.

**Comment by merks** [comment]
You could make the version a choice, but I don't totally understand what problem one is trying to solve here....

**Comment by LorenzoBettini** [comment]
@merks Currently, our Oomph setup requires Java 11 because that's the Java version of our bundles and because older platforms are fine with that. However, when using the latest platform, from the workspace we cannot run any test (that refers to an Eclipse class compiled with Java 17) or run any workbench from the development workspace. (Unless you know about the problem and you provide a Java 17 VM when the setup asks you for a Java 11).

I suggested requiring Java 17 for good; even if older platforms, Java 11 would be OK.

My understanding of that Oomph property is clarifying what Java version you need to have a usable workspace.

**Comment by merks** [comment]
Yes, I would just require Java 17 and if someone wants to work with an older target platform they can always add a JRE manually and make it the default.  But that seems a corner case.  Also, I current know of no case where something that works with Java 11 doesn't also work with Java 17.
