### ISSUE TITLE
Update to Guava 33

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#2876]
Orbit 2024-03 now ships with Guava 33
so we need to update

**Comment by cdietrich** [comment]
MWE needs an update too. So will Xpect i guess

**Comment by szarnekow** [comment]
Might be ok to just raise the upper bound. I’ll have a look.

**Comment by cdietrich** [comment]
i have some untested search and replace available
did it on the train so could not oomph yet

**Comment by cdietrich** [comment]
puhsed to https://github.com/eclipse/xtext/pull/new/cd_guava33

**Comment by LorenzoBettini** [comment]
@cdietrich I don't see your PR as created...

**Comment by cdietrich** [comment]
i did not create.
i have no idea if it builds is complete etc

**Comment by cdietrich** [comment]
mwe search and replace: 
https://github.com/eclipse/mwe/pull/new/cd_guava33

**Comment by LorenzoBettini** [comment]
There are failures on Xtend and task:

```
Failures: 
org.eclipse.xtend.ide.tests.compiler.batch.XtendCompilerAntTaskTest.testSrcdirAsAttr
  Run 1: XtendCompilerAntTaskTest.testSrcdirAsAttr:60 Gen folder created
  Run 2: XtendCompilerAntTaskTest.testSrcdirAsAttr:60 Gen folder created
  Run 3: XtendCompilerAntTaskTest.testSrcdirAsAttr:60 Gen folder created
  Run 4: XtendCompilerAntTaskTest.testSrcdirAsAttr:60 Gen folder created

org.eclipse.xtend.ide.tests.compiler.batch.XtendCompilerAntTaskTest.testSrcdirAsNestedPath
  Run 1: XtendCompilerAntTaskTest.testSrcdirAsNestedPath:80 Gen folder created
  Run 2: XtendCompilerAntTaskTest.testSrcdirAsNestedPath:80 Gen folder created
  Run 3: XtendCompilerAntTaskTest.testSrcdirAsNestedPath:80 Gen folder created
  Run 4: XtendCompilerAntTaskTest.testSrcdirAsNestedPath:80 Gen folder created
```

**Comment by cdietrich** [comment]
i assume there are some wiredo regexes in some ant files

**Comment by cdietrich** [comment]
pushed

**Comment by cdietrich** [comment]
Do we track mwe and bootstrap somewhere else

**Comment by szarnekow** [comment]
Reopening to make sure the bootstrapping is not forgotten

**Comment by cdietrich** [comment]
published a Xtext 2.33.0.M0 so we can use it in mwe

**Comment by cdietrich** [comment]
https://github.com/eclipse/mwe/pull/282 
TODO double check i did not miss anything

**Comment by cdietrich** [comment]
done for now. TODO release Xtext M1
