### ISSUE TITLE
Importing MWE sources into xtext workspace no longer works

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#2896]
```
One or more cycles were detected in the build path of project 'org.eclipse.xtend.core'. The paths towards the cycle and cycle are:
org.eclipse.xtend.core->{org.eclipse.emf.mwe2.language, org.eclipse.xtext.common.types, org.eclipse.emf.mwe2.launch}
```

```
One or more cycles were detected in the build path of project 'org.eclipse.emf.mwe2.language'. The paths towards the cycle and cycle are:
->{org.eclipse.emf.mwe2.language, org.eclipse.xtext.common.types, org.eclipse.emf.mwe2.launch}
org.eclipse.emf.mwe2.language->{org.eclipse.xtext.common.types, org.eclipse.emf.mwe2.launch}
->{org.eclipse.emf.mwe2.language, org.eclipse.xtext.common.types}
```

am not sure if this is due to platform changes or your change @LorenzoBettini 
cc @szarnekow 

maybe we need a bootstrap project for common types gen project too

**Comment by cdietrich** [comment]
i think this is due to run as mwe workflow needs this dependency

**Comment by LorenzoBettini** [comment]
But common types has a java file for the generation, so launch should not be required

**Comment by cdietrich** [comment]
so it can be removed i guess

**Comment by LorenzoBettini** [comment]
Yes. You might try to run the java file without that dependency.

And yes, my PR was the culprit https://github.com/eclipse/xtext/pull/2882/files#diff-2fea07bb0aeeeb3bdff8c638542a1f06ada285094518b8a07f0d2b0357d84c50R13

I had added that dep when I created the mwe2 file. I then removed the mwe2 file going back to the Java file. Unfortunately, I forgot to remove the dep.
