### ISSUE TITLE
Xtext does not build with tycho 5 anymore

### ISSUE THREAD

**Issue by LorenzoBettini** [eclipse/xtext#2914]
Xtext does not build with tycho 5 anymore

https://ci.eclipse.org/xtext/job/xtext/job/cd_tycho50/

```
[INFO] --- bundle:5.1.8:manifest (bundle-manifest) @ org.eclipse.xtext.web
...
[ERROR] Failed to execute goal org.apache.felix:maven-bundle-plugin:5.1.8:manifest (bundle-manifest) on project org.eclipse.xtext.web: Execution bundle-manifest of goal org.apache.felix:maven-bundle-plugin:5.1.8:manifest failed: An API incompatibility was encountered while executing org.apache.felix:maven-bundle-plugin:5.1.8:manifest: java.lang.NoSuchMethodError: 'void aQute.bnd.osgi.Jar.setReproducible(boolean)'
```

We use maven-bundle-plugin:5.1.8, but the latest one is 5.1.9.

Or maybe related:

https://github.com/bndtools/bnd/issues/3146

https://github.com/bndtools/bnd/issues/2242

Originally posted here: https://github.com/xtext/xtext-reference-projects/issues/402

**Comment by LorenzoBettini** [comment]
Some more information: Tycho 5 switched to `biz.aQute.bnd` version 7 https://github.com/eclipse-tycho/tycho/blob/e5463f53aa5a24a0fe75a981d75ddb6c38b87a2c/pom.xml#L73.

Version 7 of aQute removed the old deprecated method aQute.bnd.osgi.Jar.setReproducible(boolean) relying only on aQute.bnd.osgi.Jar.setReproducible(String).

maven-bundle-plugin still uses `biz.aQute.bnd` 6.3.1 and it uses the old deprecated method aQute.bnd.osgi.Jar.setReproducible(boolean)

**Comment by LorenzoBettini** [comment]
@cdietrich I create a PR against your branch that should fix it for good!

I should have read the documentation better when I introduced the plugin O:)
https://felix.apache.org/documentation/subprojects/apache-felix-maven-bundle-plugin-bnd.html

It's probably worthwhile to backport it to `main`

**Comment by cdietrich** [comment]
I rebase the tycho branch on main
=> can you please pr against main

**Comment by LorenzoBettini** [comment]
@cdietrich I changed the PR so that it is against main
