### ISSUE TITLE
Inconsistent handling of files in an output folder - full vs. incremental build

### ISSUE THREAD

**Issue by stephan-herrmann** [eclipse/xtext#2920]
Observed in Xtext 2.28.0:

I was debugging an issue where a search using resource descriptions produced unexpected results, because we encountered a mix of descriptions from `src` and `bin` folders.

Disclaimer: against prior advice we indeed use index search during building, after taking appropriate steps to ensure a complete index at the point of usage.

I found that the problem does not occur during **full builds**, because `ToBeBuiltComputer.updateProject()` rejects any `IFolder` that is an output folder (using `isHandled(IFolder)` etc.).

During **incremental build**, however, `XtextBuilder.createDeltaVisitor()` creates a visitor that does not have a branch for `IFolder` and hence we fall through to `return true;` causing all files in output folders to be visited, too.

This looks inconsistent to me.

We are currently fixing this by rolling a custom XtextBuilder, but I wonder if perhaps there is some reasoning behind this difference between full & incremental builds? If not, adding a corresponding branch in said delta visitor might actually bring a performance benefit for everybody, no? :)

I should add, that I don't see an easy way to extract our situation into a sharable test...

Browsing previous issues, that closest I could find is #2512 which looks inconclusive to me.

**Comment by LorenzoBettini** [comment]
Just in case, have you tried using more recent versions of Xtext? The current release is 2.33.0

**Comment by stephan-herrmann** [comment]
>...  Do you plan to create a PR?

Coming shortly, some observations while local tests are still running:

I was pleasantly surprised how oomph created a fresh workspace which was immediately usable - without any hiccups. Nice!
 (My previous workspace was still on https://github.com/eclipse/xtext-core/ where my [previous PR](https://github.com/eclipse/xtext-core/pull/1560) fades into eternal oblivion :) ...)

Then during a local maven build I saw consistent failure in org.eclipse.xtext.xbase.tests.typesystem.ResolvedFeaturesTest.testUnmodifiableIterator(), which, however, could not be reproduced when running the same in the IDE. Is that perhaps a known issue that needs extra care during local maven builds?

**Comment by stephan-herrmann** [comment]
> Just in case, have you tried using more recent versions of Xtext? The current release is 2.33.0

Thanks for the hint. In fact we recently finished migration to a newer version. When we started the migration 2.28 was the newest version available :)

Positively speaking, I would invest the effort to try testing on newer Xtext _if_ there were specific hints that this particular behavior may have recently changed, but based on @szarnekow 's comment this doesn't look the case.

**Comment by cdietrich** [comment]
@stephan-herrmann what do you mean with the problem around
ResolvedFeaturesTest?

**Comment by LorenzoBettini** [comment]
@cdietrich yes: some tests need a saved launch configuration to be first run to execute a few needed Maven phases to produce some artifacts needed by tests when run from Eclipse, but only in a few projects. For sure this is the case for Xtext and Xtend Maven plugin projects, and maybe in another case I don't remember (maybe the Xtend Ant task test?) Instead, when run from Maven everything is taken care of automatically. 
However, @stephan-herrmann reports the opposite: it succeeds in Eclipse but fails in Maven.

@stephan-herrmann what is the failure message for that test? 

IIRC, that test relies on the number of methods provided by `com.google.common.collect.UnmodifiableIterator`; if that class changes in a Guava version, that test must be adapted accordingly, is that right @cdietrich ? Maybe, you're using a different version of Guava in Maven and Eclipse?

> Positively speaking, I would invest the effort to try testing on newer Xtext _if_ there were specific hints that this particular behavior may have recently changed, but based on @szarnekow 's comment this doesn't look the case.

I probably remembered something similar but different: resources in output folders were considered in validation leading to wrong errors about types already defined; that was fixed some time ago. However, your use case is different.

> I was pleasantly surprised how oomph created a fresh workspace which was immediately usable - without any hiccups. Nice!

Thank you for the positive feedback and kind words about the Oomph setup! :)

**Comment by stephan-herrmann** [comment]
> @stephan-herrmann what is the failure message for that test?

something like "expected 7 but got 8" :)

> IIRC, that test relies on the number of methods provided by `com.google.common.collect.UnmodifiableIterator`; if that class changes in a Guava version, that test must be adapted accordingly, is that right @cdietrich ? Maybe, you're using a different version of Guava in Maven and Eclipse?

As you mention versions, I checked what versions are used on jenkins and re-ran local tests with maven 3.8.6 (before: 3.8.5) and JDK 17 (before: 20). ResolvedFeaturesTest was successful this time (not sure how those diffs could influence the guava version, but smth of that kind seems to be happening). I'm hoping for a green local build this time (still running).

**Comment by LorenzoBettini** [comment]
@stephan-herrmann IIRC, Maven 3.8.5 had severe dependency management problems, primarily when used with Tycho and target platforms, fixed in 3.8.6.

That's why we use the Maven wrapper to improve reproducibility in the CI and the local environment ;)

**Comment by stephan-herrmann** [comment]
> That's why we use the Maven wrapper to improve reproducibility in the CI and the local environment ;)

I used `full-build.sh`. Are you saying, that one should not be used for local builds? Perhaps `CONTRIBUTING.md` should explain the proper maven invocation?

**Comment by LorenzoBettini** [comment]
It's probably a mistake from our side O:)

@cdietrich is that OK if we use the maven wrapper `mvnw` also in `full-build.sh`, i.e., also on Jenkins?
In GitHub Actions, we manually call `mvnw` instead of the script.

**Comment by cdietrich** [comment]
I am ok with it.

**Comment by cdietrich** [comment]
Can we also set min maven version with enforcer ?

**Comment by LorenzoBettini** [comment]
@cdietrich I'll try to enforce it. Which version? The one we use in the wrapper, right?

**Comment by LorenzoBettini** [comment]
I've already created the PR, see above

**Comment by stephan-herrmann** [comment]
Actually, when I first saw the file mvnw I thought it would relate to mvn the same way as javaw relates to java ;-P
