### ISSUE TITLE
[Xtend] No check for duplicate interface specification

### ISSUE THREAD

**Issue by LorenzoBettini** [eclipse/xtext#2928]
While working on https://github.com/eclipse/xtext/issues/2349 I discovered that Xtend does not check for duplicate interface specification:

![image](https://github.com/eclipse/xtext/assets/1202254/a19cc9e1-6379-4307-9dba-9f74c54ff236)

This leads to a wrong Java class generation:

![image](https://github.com/eclipse/xtext/assets/1202254/d70fdf09-9764-4c7c-9df6-9e6a97bf2b6b)

And then the Java error is reported on the Xtend file

![Screenshot-20240205134759-2560x1440](https://github.com/eclipse/xtext/assets/1202254/0d039bf6-3551-46a4-9086-231872f22998)

But maybe we could catch it before getting to the code generation.

@szarnekow I can fix it upstream and then port it to https://github.com/eclipse/xtext/issues/2349 , what do you think?

**Comment by szarnekow** [comment]
@LorenzoBettini Yes, please add a validation.
