### ISSUE TITLE
Investigate commons logging problem

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#2936]
https://github.com/eclipse/xtext/actions/runs/7948480602/job/21698724151

Sometimes commons logging cannot be found on latest. No idea why

**Comment by cdietrich** [comment]
am not sure if this is a simrel orbit problem 
with commons.commons-logging vs commons.logging.
am also not sure where we pull it from
as we dont seem to explicitely mention it

**Comment by LorenzoBettini** [comment]
That's the first time I see that. have you seen that before?

**Comment by cdietrich** [comment]
yes i have seen this one before but after a restart it works.
am not sure if this is a race in tycho or something like that
so that the package import sometimes works and sometimes not

**Comment by LorenzoBettini** [comment]
We're also still use Tycho 3: we should move to 4..

**Comment by LorenzoBettini** [comment]
@cdietrich @szarnekow looks like it now fails constantly. Maybe they changed the bundle name in orbit?

**Comment by cdietrich** [comment]
Yes they did. But we use import page.
What I don’t understand why does it work here 
https://ci.eclipse.org/xtext/job/xtext/job/main/902/

**Comment by LorenzoBettini** [comment]
Indeed I noticed that too: it works on Jenkins.
I now cleared the GitHub actions caches, let's see whether it works now (I'm relaunching the failed jobs)

**Comment by cdietrich** [comment]
In sebastians pr it worked on gh actions too

**Comment by LorenzoBettini** [comment]
No, it didn't: it failed on the last Sebastian's PR as well.

![20240218_19h17m57s_grim](https://github.com/eclipse/xtext/assets/1202254/f8b659c9-08e0-4f94-99fb-4f944326d157)

However, after clearing all the caches, the original job mentioned here seems to build (it passed the unresolvable project already). Now, I'm relaunching Sebastian's PR https://github.com/eclipse/xtext/pull/2937 jobs as well.

**Comment by LorenzoBettini** [comment]
Sebastian's PR still fails...

**Comment by LorenzoBettini** [comment]
While https://github.com/eclipse/xtext/actions/runs/7948480602 seems to work now...
maybe @szarnekow PR should be first rebased on top of master

**Comment by cdietrich** [comment]
Now it shows up there
Will rebase too 
https://ci.eclipse.org/xtext/job/xtext/job/cd_tycho40/367/console

**Comment by cdietrich** [comment]
Will also check if Tacho 4.0.6 is any better
I assume commons logging might also be removed from an upstream dependency like platform

**Comment by cdietrich** [comment]
Maybe the problem is also we sometimes use import package and sometimes require bundle

**Comment by LorenzoBettini** [comment]
Tycho 4.0.5 fails in Jenkins but not in GH. (Was that already rebased?).
Tycho 4.0.6 seems to work in both.

**Comment by cdietrich** [comment]
No tycho 4 was not rebased

**Comment by cdietrich** [comment]
What I still don’t understand which repo provides the bundle
We don’t seem to have an explicit dependency in any target

**Comment by LorenzoBettini** [comment]
Orbit 2024-03 provides that.

**Comment by szarnekow** [comment]
It’s sometimes an additional bundle requirement in the build.properties and sometimes in the manifest. 

Did I understand it right, that the bundle’s symbolic name was changed recently?

**Comment by cdietrich** [comment]
I don’t know when
But I see it named

commons.commons-logging now

**Comment by cdietrich** [comment]
But what about old platforms ?

**Comment by cdietrich** [comment]
Why not import ecerywhere and explicit mention in tp?

**Comment by cdietrich** [comment]
Also: is this a Xtext dep or a transitive eg mwe

**Comment by LorenzoBettini** [comment]
In all the target platforms we always use "https://download.eclipse.org/tools/orbit/simrel/orbit-aggregation/2024-03" if I'm not wrong.
That's why I was suggesting an explicit mention in all the target platforms.
I still haven't checked the local workspace, so I don't know where that dep comes from.

**Comment by cdietrich** [comment]
The question in what else in older tps uses Xtext and commons logging on their own

**Comment by cdietrich** [comment]
I assume we should package it to mwe update site

**Comment by LorenzoBettini** [comment]
So it's mwe that brings that dep?

**Comment by szarnekow** [comment]
Yes, it is necessary to run the workflow
