### ISSUE TITLE
Copy-paste error in `UriExtensions#cleanupEncodedCharacters` for URIs with escaped sequences

### ISSUE THREAD

**Issue by EhabY** [eclipse/xtext#2963]
The culprit here seems to be the follow line: https://github.com/eclipse/xtext/blob/1e42c1b22f58ebc86c0bc08bd331bfc3d2311e35/org.eclipse.xtext.util/src/org/eclipse/xtext/util/UriExtensions.java#L104

Where the query is assigned to the fragment (thus the actual query is discarded), this only happens if the URI contains an escape sequence (`%`).

**Comment by szarnekow** [comment]
Fixed.
