### ISSUE TITLE
Provide an abstract base class to be able to test the formatter.

### ISSUE THREAD

**Issue by miklossy** [eclipse/xtext#2965]

**Comment by LorenzoBettini** [comment]
I reopen this because there are some Xtend generated classes that were not committed see https://github.com/eclipse/xtext/pull/2966#discussion_r1573273331

**Comment by miklossy** [comment]
It can happen that I did not checked in all the Xtend generated classes. I have a lots of "dirty" classes in my worskpace, so it can easily happen that I missed some. Thanks for correcting this, @LorenzoBettini !

**Comment by LorenzoBettini** [comment]
> It can happen that I did not checked in all the Xtend generated classes. I have a lots of "dirty" classes in my worskpace, so it can easily happen that I missed some. Thanks for correcting this, @LorenzoBettini !

@miklossy may I ask you why you have so many "dirty" classes? Are you using Windows?

**Comment by miklossy** [comment]
Yes. I am using Windows.

**Comment by LorenzoBettini** [comment]
@miklossy OK, then you're also hit by https://github.com/eclipse/xtext/issues/2293

**Comment by miklossy** [comment]
Yes. Exactly.
