### ISSUE TITLE
Update Minimal MWE(2) version to 1.12 / 2.18

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#2974]
Update Minimal MWE(2) version to 1.12 / 2.18

(currently on 1.11/2.17 or even older)

**Comment by LorenzoBettini** [comment]
Isn't this solved?

**Comment by cdietrich** [comment]
so see e.g manifests that refer the old 2.17 or even older 1.10

**Comment by LorenzoBettini** [comment]
OK, I can work on that
