### ISSUE TITLE
Problems with the new `getLast` method in Java 21 and the extension method `last`

### ISSUE THREAD

**Issue by LorenzoBettini** [eclipse/xtext#2981]
Java 21 introduces the `getLast` method in a few collection classes.
Xbase will prefer `getLast` to our extension method `last` to generate Java code when the runtime is Java 21 when the `last` extension method is used in the DSL code, e.g., Xtend.
Such a strategy has been implemented in the past for example to use the Java 8 `forEach` instead of the extension method `forEach`. And that never generated problems.

The problem now is that our extension method `last` returns null when the collection is empty, while the `getLast` method in Java 21 throws a 

```
java.util.NoSuchElementException
 	at java.base/java.util.List.getLast(List.java:843)
``` 

https://github.com/openjdk/jdk/blob/d771ec6296bd3bb17ac2dd79671fdb6f154b4ea5/src/java.base/share/classes/java/util/List.java#L839

I'm already changing a few occurrences in our code base, mainly in XbaseFormatter and XtendFormatter while working on https://github.com/eclipse/xtext/issues/2686: instead of doing `list.last` I'm changing it into `IterableExtensions.last(list)`, thus forcing the use of our method.

but I think we should take counter measures in the Xbase compiler now to avoid generating code with different and breaking semantics when the runtime is Java 21.

@szarnekow do you think we could add a kind of exception rule when resolving methods in Xbase. I mean, when the method `last` is an extension method we should not look for possibly matching methods from the Java API, and force the use of our `last` method?

**Comment by szarnekow** [comment]
What do you think about deprecating `last` and introducing `lastOrNull` on IterableExtensions?
Having a special treatment for types from xbase.lib sounds like wormhole to me, in which we don't want to be trapped.

**Comment by LorenzoBettini** [comment]
@szarnekow your proposal sounds good and much more manageable! O:)

**Comment by LorenzoBettini** [comment]
@szarnekow I re-open this because the deprecation does not work as I expected:

With Java 17, you get the expected deprecation warnings:

<img width="356" alt="image" src="https://github.com/eclipse/xtext/assets/1202254/99c110e6-85f0-4c19-a742-eff8639eda40">

With Java 21, the deprecation warnings are only when `last` is bound to the extension method, which would be safe anyway; on the contrary, for types where the `getLast` was introduced, it is bound to `getLast`, so no deprecation and the problem goes unnoticed:

<img width="356" alt="image" src="https://github.com/eclipse/xtext/assets/1202254/f7e87fc5-6aa9-4582-a0c0-7cfdf6e63478">

In that respect, the deprecation and the new `lastOrNull` are useless.
At least, I hadn't thought about that.
How about you?

**Comment by szarnekow** [comment]
Yes, I was aware of it and had the hope that some people would see the deprecation already before migrating to Java 21.

**Comment by LorenzoBettini** [comment]
@szarnekow OK, let's write it in the N&N: a possible recommendation is to first remove the deprecated calls and THEN move to Java 21
