### ISSUE TITLE
io.github.classgraph.classgraph version change in Orbit

### ISSUE THREAD

**Issue by LorenzoBettini** [eclipse/xtext#3012]
Our builds currently failed because of this:

```
Error:  Failed to resolve target definition file:/home/runner/work/xtext/xtext/org.eclipse.xtext.xbase.lib/../xtext-latest.target: Could not find "io.github.classgraph.classgraph/4.8.168" in the repositories of the current location
```

In fact, in https://download.eclipse.org/tools/orbit/simrel/orbit-aggregation/2024-06/ there's a new version ` 4.8.172`.

Is that OK, if I remove the strict version from the target platforms? Note that this version is available only in the latest Orbit.

@cdietrich ?

**Comment by LorenzoBettini** [comment]
Otherwise, maintaining all the target platforms becomes complex...

**Comment by cdietrich** [comment]
i am not sure.
we still have manifests and the boms

how would you deal with them

**Comment by LorenzoBettini** [comment]
The MANIFESTs mention the minimal required (old) version so they would be fine.
The BOM could be updated to the new version.

If you still prefer to have strict versions, older platforms should take only that dependency from the new Orbit.

In general, I prefer not to have many strict versions in the target.

We already have unbounded versions for some dependencies:

```xml
			<unit id="junit-jupiter-api" version="0.0.0"/>
			<unit id="junit-jupiter-engine" version="0.0.0"/>
			<unit id="junit-jupiter-migrationsupport" version="0.0.0"/>
			<unit id="junit-jupiter-params" version="0.0.0"/>
			<unit id="junit-platform-commons" version="0.0.0"/>
			<unit id="junit-platform-engine" version="0.0.0"/>
			<unit id="junit-platform-launcher" version="0.0.0"/>
			<unit id="junit-platform-runner" version="0.0.0"/>
			<unit id="junit-platform-suite-api" version="0.0.0"/>
			<unit id="junit-platform-suite-commons" version="0.0.0"/>
			<unit id="junit-vintage-engine" version="0.0.0"/>
```

**Comment by cdietrich** [comment]
i mean more critical ones e.g. asm

**Comment by LorenzoBettini** [comment]
For ASM we update the manifests accordingly, but we also have a strict range for asm

For Classgraph we don't have a strict range, the manifests can be kept like that and in the latest platform they will take the newer version. I don't know how critical Classgraph is.

The only manifest mentioning it is common.types and it has

```
Import-Package: io.github.classgraph;version="4.8.168",
```

so it's an open range.

**Comment by cdietrich** [comment]
but we ususally bump the minimum version there.
the question is what is the explosion risk

**Comment by cdietrich** [comment]
the problem is my brain cappa for xtext is zero.
:(
atm

wit just stupidly search and replace i was fine in the past as it can be done without thinking

**Comment by cdietrich** [comment]
=> yes this is what i did in the past, just search and replace everyting

**Comment by LorenzoBettini** [comment]
> => yes this is what i did in the past, just search and replace everyting

No problem; as I said, it's just a problem in target platforms, where it's not just search/replace but I can do that.

**Comment by cdietrich** [comment]
there is also the wizard

**Comment by LorenzoBettini** [comment]
Yes I noted. That's why I wanted to keep it minimal, but let's do that (I'll open a PR). The global quick search functionality helps here.

I think in the future we should try to avoid such maintenance burden and be less strict for some dependencies ;)
