### ISSUE TITLE
Remove of deprecated `.xtext.junit4` and `.xbase.junit`

### ISSUE THREAD

**Issue by LorenzoBettini** [eclipse/xtext#3026]
I propose to ditch for good those deprecated projects, whose mechanisms are provided by the corresponding split projects `.testing` and `.ui.testing`.

The only thing to address is the `AbstractXtextTests` and `ResourceLoadHelper`, which don't have a counterpart in the new projects. We still use them a lot, by duplicating them, in several test projects in Xtext. We could re-introduce them in the new testing projects before the proposed removal of the deprecated ones. This can be achieved in a separate PR.

The removal will allow us to also get rid of the corresponding `.tests` projects.

**Comment by cdietrich** [comment]
should we add another reminder to release notes?
is all marked forRemoval?

**Comment by cdietrich** [comment]
isnt ResourceLoadHelper unused ?

**Comment by LorenzoBettini** [comment]
@cdietrich I'll check for the `forRemoval` later.
`ResourceLoadHelper` seems to be just an interface...

What I still have to understand is whether the `AbstractXtextTests` copied in most of our test projects is always the same.

**Comment by cdietrich** [comment]
i assume yes

**Comment by LorenzoBettini** [comment]
@cdietrich indeed `forRemoval` seems everywhere on those older projects

**Comment by LorenzoBettini** [comment]
By the way, we already have `org.eclipse.xtext.ui.testing.util.ResourceLoadHelper` in `ui.testing`, so probably that's the right place to be. In any case, we can't remove that one: it's in the new project and it's used in some of content assist base test classes.

In the new `AbstractXtextTests` base class, I won't make it implement that interface, though, since it's not used in that context

**Comment by LorenzoBettini** [comment]
@cdietrich With https://github.com/eclipse/xtext/pull/3038 merged, should we go on removing the old projects for 2.35?

**Comment by cdietrich** [comment]
I would Annonce in rel notes and remove in 236

**Comment by szarnekow** [comment]
> I would Annonce in rel notes and remove in 2.36

I'd do the same.

**Comment by LorenzoBettini** [comment]
I'm about to start working on that

**Comment by cdietrich** [comment]
Fallout in Xpect fixed.
Fix for fallout in MWE is WIP

**Comment by cdietrich** [comment]
mwe fixed too

**Comment by cdietrich** [comment]
@LorenzoBettini i still see `org.eclipse.xtext.junit4.tests` floating around. is this intentional?

**Comment by LorenzoBettini** [comment]
No, it isn't :(
Maybe occurrences in xfriend

**Comment by cdietrich** [comment]
@LorenzoBettini no i mean org.eclipse.xtext.junit4.tests is a project

**Comment by LorenzoBettini** [comment]
That's definitely a mistake. And I wonder why the build doesn't fail: it shouldn't be able to resolve the required bundle ".xtext.junit4"..

**Comment by cdietrich** [comment]
Maybe the project is not part of the reactor

**Comment by LorenzoBettini** [comment]
Right! And maybe when I removed it from the workspace I forgot to remove it physically.
