### ISSUE TITLE
Regression in AbstractContentAssistTest breaking customizations

### ISSUE THREAD

**Issue by LorenzoBettini** [eclipse/xtext#3051]
I haven't noted before but https://github.com/eclipse/xtext/pull/3024/ by @miklossy breaks my content assist tests, and maybe others, where you need to customize the project, e.g., by turning it into a plugin project: `javaProject` is private in the base class and there's no way to customize that project but overriding `getJavaProject()`. Such method should be called consistently instead of accessing `javaProject` directly. However, this new line https://github.com/eclipse/xtext/pull/3024/files#diff-b9c6713383f0749744a3be5dc32c91a592d966c5332bff947b8c8ad6a1a4b184R87 doesn't do that.

I'll create a PR right away so that it calls `getJavaProject()` and maybe leave a comment on the private field, just in case for the future.

**Comment by LorenzoBettini** [comment]
Actually, in other places `javaProject` is now used directly. I'll check all the occurrences.

**Comment by LorenzoBettini** [comment]
@cdietrich @szarnekow of course, the alternative could be to make `javaProject` protected in the base class, though I'm not a big fan of this solution

**Comment by szarnekow** [comment]
All code should use the getter if it's overridable. I wouldn't mind making javaProject accessible *additionally*

**Comment by LorenzoBettini** [comment]
> All code should use the getter if it's overridable. I wouldn't mind making javaProject accessible _additionally_

@szarnekow I double-checked: unfortunately, the overridable `getJavaProject` does not help: the method takes a `ResourceSet` as parameter, so it could not be called in the new/modified methods of https://github.com/eclipse/xtext/pull/3024. I guess that's why @miklossy did not call that.

I'd go with making `javaProject` accessible.

By the way, I didn't remember that but in a subclass if you call a `BeforeClass` static method the same as in the superclass, JUnit will only call the one of the derived class: that's how I hooked in the project creation and created a custom project returned by the overridden `getJavaProject`; but of course, that doesn't work anymore.

**Comment by miklossy** [comment]
Thank you @LorenzoBettini !
