### ISSUE TITLE
Fragments are disallowed in unordered groups

### ISSUE THREAD

**Issue by tfonda-fbk** [eclipse/xtext#3068]
This issue matches [this old bug report on Bugzilla](https://bugs.eclipse.org/bugs/show_bug.cgi?id=501118); it was also initially briefly discussed [in the forum](https://www.eclipse.org/forums/index.php/t/1075202/).

Fragments are always rejected in unordered groups, but it looks like at least fragments consisting of an (multiple?) assignment(s?) exclusively should be allowed (please correct me if I'm wrong, I'm quite new to grammars, parsers and Xtext).

**Comment by LorenzoBettini** [comment]
cc @szarnekow

**Comment by szarnekow** [comment]
Fragments should generally speaking be allowed as unordered elements since they don't defer the object instantiation to the called rule. There's no need to inspect the body of the called fragment.

See org.eclipse.xtext.GrammarUtil.isEObjectFragmentRuleCall(EObject)
