### ISSUE TITLE
Fix api breakage with newest jdt

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#3089]
05:09:28  [ERROR] The method read(byte[], String) in the type ClassFileReader is not applicable for the arguments (InputStream, String)

Cc @iloveeclipse is this an intentional change upstream

**Comment by cdietrich** [comment]
https://ci.eclipse.org/xtext/job/xtext/job/main/1231/

**Comment by iloveeclipse** [comment]
See https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2555
May be the old method could be added back (redirecting to new one with inputStrean.readAllBytes()) to make Xtext happy.

**Comment by jukzi** [comment]
can you update xtext to use IFile.readAllChars() an not use jdt internals, please?

**Comment by cdietrich** [comment]
We need to check what is available in which version and of course we are using internal api at 100 s if other places too as for many there is no api. I assume the code here also runs outside workspace no so I file available

**Comment by jukzi** [comment]
> outside workspace no so I file available

You could then use inputStrean.readAllBytes()) or faster: java.nio.Files.readAllBytes(file.toPath())

**Comment by szarnekow** [comment]
This change breaks existing installations that use Xtext. Why wasn’t it possible to do a backwards compatible modification instead?

**Comment by LorenzoBettini** [comment]
> See [eclipse-jdt/eclipse.jdt.core#2555](https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2555) May be the old method could be added back (redirecting to new one with inputStrean.readAllBytes()) to make Xtext happy.

@iloveeclipse that would be great

**Comment by cdietrich** [comment]
reflection workaround is in place. would still be better to have a compiled solution

**Comment by iloveeclipse** [comment]
> This change breaks existing installations that use Xtext. Why wasn’t it possible to do a backwards compatible modification instead?

I wonder if only xbase **tests* are affected?

**If not**, could you please provide a PR doing that? I agree that if this affects all existing Xtext releases it would be a big pain for everyone who can't update to latest Xtext but updates the platform.

**Comment by cdietrich** [comment]
it affects xbase tests and everything that uses xtext.java.
(e.g. xtend + gradle) but that one likely uses a hard coded older jdt

**Comment by LorenzoBettini** [comment]
@iloveeclipse indeed it would be great and helpful if the involved change in JDT could be reverted :)

**Comment by iloveeclipse** [comment]
> indeed it would be great and helpful if the involved change in JDT could be reverted :)

I'm not talking about revert, but about adding the only "missing" method back that would use the new one.

**Comment by LorenzoBettini** [comment]
@iloveeclipse yes, of course that'd be great as well.

**Comment by iloveeclipse** [comment]
So could any of interested parties here provide such PR?

**Comment by jukzi** [comment]
> but about adding the only "missing" method back that would use the new one.

Could you then please add a hint that the Method is used (provisional API?) - possibly with a dull junit test i jdt that just just refers to it. If you use other internals you could please also refer them.

**Comment by LorenzoBettini** [comment]
@iloveeclipse I'll try to do that now

@jukzi just a JUnit test calling this method and nothing else? any suggestion on where to place it?
Moreover:

> Could you then please add a hint that the Method is used (provisional API?)

that the Method is used? Did you mean something else?

**Comment by jukzi** [comment]
> just a JUnit test calling this method and nothing else?

yes, even without any assert and does not need to be executed. just to get some indication it should not be removed without good reason.

>any suggestion on where to place it?

no - depends on all the methods you need. Only that the Filename clear indicate the usecase - maybe "XtextDependencies.java"

> that the Method is used? Did you mean something else?

sorry, i do not understand that question. please see https://github.com/eclipse-platform/eclipse.platform/blob/master/docs/Provisional_API_Guidelines.md#javadoc

**Comment by szarnekow** [comment]
> possibly with a dull junit test in jdt

The method was used from tests and yet the tests were changed along with the breaking change. Curious why another newly added would prevent that from happening in the future …

**Comment by LorenzoBettini** [comment]
@jukzi created this https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2578

**Comment by jukzi** [comment]
> The method was used from tests and yet the tests were changed along with the breaking change. Curious why another newly added would prevent that from happening in the future …

The difference would be that it is not a functional test but only a test for keeping signature.
