### ISSUE TITLE
Multiline comment expectations

### ISSUE THREAD

**Issue by mehmet-karaman** [eclipse/xtext#3125]
Hi, 

recently I've stumbled on a problem in editing strategies and multi line comments. It occurs when the user starts his comment block with /*** and closes it with */ ..

But after debugging I couldn't tell if its a bug or a feature. These terminals are configured in org.eclipse.xtext.ui.editor.autoedit.DefaultAutoEditStrategyProvider.configureMultilineComments(IEditStrategyAcceptor). So xtext expects if the user starts his block comment with `/***` he has to close that also with `***/` .. Might be I am wrong but why is it necessary to have these terminals. Wouldn't be enough to have `/*` and `*/` unnecessary if he uses `/*****` or `/**` and closes with `*/` ?

Best regards
Mehmet

**Comment by mehmet-karaman** [comment]
Forgot to mention the xtext version. The version which we are currently using is 2.33

**Comment by cdietrich** [comment]
i cant really tell but these juse seem to be some defaults
the tripe things were introduced for the copyright headers
see https://github.com/eclipse/xtext-xtend/issues/163

**Comment by mehmet-karaman** [comment]
Thanks for the clarification.
