### ISSUE TITLE
`casesPerSpecialStateSwitch` option does not work for the `InternalParser`

### ISSUE THREAD

**Issue by SimonCockx** [eclipse/xtext#3126]
The generated parser `InternalRosettaParser` of the [Rosetta DSL](https://github.com/finos/rune-dsl) currently contains a compilation error due to the size of the `specialStateTransition` method:

```
The code of method specialStateTransition(int, IntStream) is exceeding the 65535 bytes limit
```

Following the suggestions in https://github.com/eclipse/xtext/issues/3114, I tried enabling splitting of this method by setting `casesPerSpecialStateSwitch` to 20 in the `XtextAntlrGeneratorFragment2`:
```
			parserGenerator = XtextAntlrGeneratorFragment2 {
				options = {
					classSplitting = true
					casesPerSpecialStateSwitch= "20"
					fieldsPerClass = "200"
					methodsPerClass = "200"
					stripAllComments = true
				}
			}
```

However, this did not change the generated method at all. Upon further investigation, it seems splitting is only applied to the lexer, not to the parser which has the issue. (I found some issues with the lexer splitting logic as well - but that's another issue which doesn't cause me harm at the moment)

Is there a way of splitting the `specialStateTransition` method in the `InternalParser` as well? Or is this currently missing from Xtext?

**Comment by cdietrich** [comment]
no currently not. that would need to be added.
you may check out org.eclipse.xtext.xtext.generator.parser.antlr.splitting package

**Comment by szarnekow** [comment]
Simon, at a first glance the language grammar doesn't look as if it *should* trigger such a large generated method.
Can you confirm that all the manually inserted predicates are necessary?

**Comment by SimonCockx** [comment]
@szarnekow I'll give them a review.

**Comment by SimonCockx** [comment]
Upon reviewing all of our syntactic predicates, I managed to remove six of them. This brings us under the limit again, but still with little margin. I'll have a look to see whether it's doable to create a fragment which can reduce the size of the `specialStateTransition` method as a longer term solution.

**Comment by SimonCockx** [comment]
I managed to write a fragment that extracts code inside `case`s into separate methods if there are many cases.

See https://github.com/finos/rune-dsl/pull/805/files#diff-d952fbfc4000e8db62eb8cf802fae491dd82159fe0762c41acb726e21529e3ae

**Comment by szarnekow** [comment]
Do you intent to contribute this fragment? We could run it against all test languages in the Xtext repo.

**Comment by SimonCockx** [comment]
With a holiday around the corner, I'm currently a bit hasty, but I suppose it can't hurt to contribute this. I'll add a reminder for once I'm back.

I suppose the same can be said about the `ParserCompressorFragment2`?
