### ISSUE TITLE
Even more problems with latest jdt

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#3188]
/home/jenkins/agent/workspace/xtext_main/org.eclipse.xtext.xbase.testing/src/org/eclipse/xtext/xbase/testing/InMemoryJavaCompiler.java:[207] 
05:21:12  [ERROR] 	this.compilerOptions.inlineJsrBytecode = true;
05:21:12  [ERROR] 	                     ^^^^^^^^^^^^^^^^^
05:21:12  [ERROR] inlineJsrBytecode cannot be resolved or is not a field
05:21:12  [ERROR] 1 problem (1

**Comment by cdietrich** [comment]
@iloveeclipse what is the proper replacement?

**Comment by iloveeclipse** [comment]
Simply remove it, the option is enabled by default.

**Comment by cdietrich** [comment]
of course now i see a ton of test errors i cannot reproduce locally.

**Comment by cdietrich** [comment]
Caused by: java.lang.Error: Unresolved compilation problem: 
	SANITY CHECK: Invalid opcode -88 at pc 162 for stackmap table attribute for method foo()

	at foo.Test.foo(Test.java:7)
	... 59 more

**Comment by cdietrich** [comment]
=> i assume we need to use another ton of reflection :(

**Comment by cdietrich** [comment]
xtext java 11 uses jdt 3.33

**Comment by iloveeclipse** [comment]
> xtext java 11 uses jdt 3.33

You mean 4.33? The option there is **always true** independently what is set. In 4.34 the option is gone.

**Comment by cdietrich** [comment]
jdt core 3.33

**Comment by iloveeclipse** [comment]
OMG
