### ISSUE TITLE
Bundle org.apache.commons.commons-logging cannot be resolved

### ISSUE THREAD

**Issue by hummeling** [eclipse/xtext#3192]
Running Eclipse 2024-09 (4.33.0)
Eclipse Xtext 2.36.0.v20240825-0714 org.eclipse.xtext.sdk
on Linux Mint 21.3 Cinnamon

Just following the 15 mins tutorial (domainmodel) gives this error:
Bundle org.apache.commons.commons-logging cannot be resolved

**Comment by cdietrich** [comment]
Where do you exactly get this error?

**Comment by hummeling** [comment]
Thank you for your swift reply!

The error is reported in the Problems tab.

I'm not sure exactly how I installed Eclipse (about half a year ago), and now it's auto-updating per my os settings. I think I installed Eclipse with the Xtext bundle. I certainly didn't install mwe (nor mwe2) manually.

**Comment by cdietrich** [comment]
Hmmm 2024-09 just released 
Same for Xtext 2.36

Can you try if adding / installing mwe2 explicit helps

**Comment by cdietrich** [comment]
Hmmmm

https://github.com/eclipse/xtext/blob/a189bea4cf97327ef221fa70d115ba8119e1b275/org.eclipse.xtext.sdk.feature/feature.xml#L74

shouuld also pull a up to date mwe
And that some should pull the commons logging

do you have an idea @LorenzoBettini

**Comment by cdietrich** [comment]
maybe we should add an explicit dependency to commons-logging to xtext sdk
or increase the minimal version in mwe.
the one used seems to be the 1.2.0 with the different bundle name ...

**Comment by cdietrich** [comment]
workaround in this case

<img width="915" alt="image" src="https://github.com/user-attachments/assets/6d9b64a3-5208-497d-8fa7-9101abcde7cf">

**Comment by cdietrich** [comment]
its also on the update site. i asume its already installed.
but as its currently accepts the old commons.logging
it did not install the newer commons-logging.
the wizard is created for.

**Comment by LorenzoBettini** [comment]
> maybe we should add an explicit dependency to commons-logging to xtext sdk or increase the minimal version in mwe. the one used seems to be the 1.2.0 with the different bundle name ...

Indeed I think that's required to deal with the change in the name of commons logging. I mean the explicit dep in our sdk.

Removing that from the build.properties is just a temporary workaround that will break once the new commons logging is installed.

**Comment by cdietrich** [comment]
@merks do you still have the dependency reports? why is the old commons.logging still present?

**Comment by hummeling** [comment]
Just for more context, the MWE2 in my setup came with the Xtext Complete SDK:
MWE2 Language SDK	2.19.0.v20240823-1107	org.eclipse.emf.mwe2.language.sdk.feature.group	Eclipse Xtext

**Comment by merks** [comment]
The old one is present because, most importantly because this httpclient thing requires the packages it provides in a very restricted version range:

![image](https://github.com/user-attachments/assets/6c9ee263-f1f3-4582-9ba9-cd4409aa65dc)

And **many** things depend on that bundle:

![image](https://github.com/user-attachments/assets/47167222-d8c4-42bc-a7f5-296898e356d3)
