### ISSUE TITLE
Classgraph version bump

### ISSUE THREAD

**Issue by LorenzoBettini** [eclipse/xtext#3199]
4.8.175 is not available anymore in Orbit, which now provides 4.8.176.

Since in the generated projects from the wizard we got rid of the pinned version, can I do the same in our target platforms?
cc @cdietrich

**Comment by cdietrich** [comment]
i am undecided. should we also remove from manifests? or add a range there?

**Comment by cdietrich** [comment]
i also wonder if we can configure dependabot to just bump classgraph then?

**Comment by LorenzoBettini** [comment]
Maybe adding a version range in the MANIFEST could be safer, something like [4.8.176,4.9.0)? Or something more brave like [4.8.176,5.0.0)?

I don't know Classgraph and how stable is nowadays.

For the POM, using dependabot would be great.

**Comment by cdietrich** [comment]
I guess up to 49 would be ok
@szarnekow wdyt

**Comment by szarnekow** [comment]
`[4.8.176,4.9.0)` please. It looks like they are using proper semantic versioning, but it better be safe than sorry.

**Comment by LorenzoBettini** [comment]
Ok, I'll update the PR accordingly and remove the pinned version from the target files.

@cdietrich concerning dependabot will it work automatically or should it be configured?

**Comment by cdietrich** [comment]
i was asking if it can be configured to just bump classgraph and e.g. not jdt.core

**Comment by LorenzoBettini** [comment]
I didn't know dependabot. Cc @HannesWell
