### ISSUE TITLE
Guava and junit.org need updates

### ISSUE THREAD

**Issue by LorenzoBettini** [eclipse/xtext#3213]
Orbit added new versions for guava (3.33.1) and org.junit (4.13.2.v20240929-1000) so our builds fail since the TP cannot be resolved anymore.

I'd like to propose the same strategy we adopted for classgraph: remove the strict version in our target files and rely on dependabot for updating our BOM.

@cdietrich @szarnekow wdyt?

**Comment by cdietrich** [comment]
Feiertag in germany. Problem Ranges / Manifests.

with guava I have concerns doing this.
But I assume other simrel projects just don’t care / pay attention

**Comment by LorenzoBettini** [comment]
So? Would it be OK if I adapted the manifest ranges as well?
Note that guava incremented the patch version, not even the minor.

**Comment by cdietrich** [comment]
Don’t have brain capacity can we discuss it in next call

**Comment by LorenzoBettini** [comment]
Yes, sure.
In the meantime, I'll bring the build to green by removing the strict version of junit and update the version of Guava everywhere.
