### ISSUE TITLE
Remove project p2.releng

### ISSUE THREAD

**Issue by LorenzoBettini** [eclipse/xtext#3219]
If I understand correctly, that's not used anymore but from old scripts that should be removed as well.

**Comment by cdietrich** [comment]
do we have a list?

**Comment by cdietrich** [comment]
e.g. tycho-sign.sh seems to be used in jenkins

**Comment by LorenzoBettini** [comment]
p2.releng is used by the scripts tycho-test.sh and tycho-sign.sh which we don't use anymore. These were used in some experiments of Jenkinsfile.
Did you refer to that?

**Comment by cdietrich** [comment]
so the real deploy jenkins dont use it?

**Comment by LorenzoBettini** [comment]
No: in fact those Jenkinsfiles are in "other-experiments" folder.
We use only full-build.sh and full-deploy.sh

**Comment by cdietrich** [comment]
ok. i guess then we dont need it.
see also https://github.com/eclipse/xtext/issues/1875
