### ISSUE TITLE
Objectweb.asm needs to be updated to 9.7.1

### ISSUE THREAD

**Issue by LorenzoBettini** [eclipse/xtext#3224]
Here we are again: Orbit provides 9.7.1, while we have a strict version on 9.7.0.

@cdietrich @szarnekow can I do the same thing done recently and remove the strict version from our target platforms? The dev BOM can be analyzed by dependabot.

**Comment by cdietrich** [comment]
have no cappa to check asm breakages in the constant classes in the past.
and in which versions they were done

**Comment by LorenzoBettini** [comment]
So should I just increase the version to make the build green again?

**Comment by cdietrich** [comment]
yes. maybe sebastian or you can do an assesment.
we might also check how often in the past there ever was a .. release
