### ISSUE TITLE
org.eclipse.m2e.core requires Java 21

### ISSUE THREAD

**Issue by LorenzoBettini** [eclipse/xtext#3253]
Our builds started to fail because of this:

```
Error:  org.eclipse.m2e.core 2.7.0.20241001-1350 requires Execution Environment that matches (&(osgi.ee=JavaSE)(version=21)) but the current resolution context uses [a.jre.javase 17.0.0]
Error:  Cannot resolve target definition:
Error:    Software being installed: org.eclipse.m2e.feature.feature.group 2.7.0.20241011-1559
Error:    Missing requirement: org.eclipse.m2e.core 2.7.0.20241001-1350 requires 'osgi.ee; (&(osgi.ee=JavaSE)(version=21))' but it could not be found
Error:    Cannot satisfy dependency: org.eclipse.m2e.feature.feature.group 2.7.0.20241011-1559 depends on: org.eclipse.equinox.p2.iu; org.eclipse.m2e.core [2.7.0.20241001-1350,2.7.0.20241001-1350]
```

**Comment by LorenzoBettini** [comment]
@HannesWell can you please confirm this?

**Comment by HannesWell** [comment]
Yes the latest version of M2 e requires Java-21 because the editor dependencies require it too.

**Comment by LorenzoBettini** [comment]
@cdietrich @szarnekow This means that we must use Java 21 for building against the latest platform.

On GitHub Actions, where we always build using the latest platform, it means always using Java 21.

On Jenkins, when https://github.com/eclipse/xtext/pull/3233 is merged, it means that with the minimal tp, 2024-03, we'll use Java 17, while for the latest tp we'll use Java 21.

**Comment by cdietrich** [comment]
Yes and the r202412 that I did not create yet as am waiting for the j17 pr
